= La Diffusione del Dhamma

[.voice]
`Seconda Voce.` Avvenne questo. C’era un uomo di nobile stirpe, chiamato
Yasa. Era il figlio di un ricco mercante, allevato tra gli agi.
Possedeva tre palazzi, uno per la stagione fredda, uno per la stagione
calda e un altro per quella delle piogge. Nel palazzo per la stagione
delle piogge era intrattenuto da menestrelli, tra i quali non c’era
alcun uomo. Per i quattro mesi della stagione delle piogge non si recava
mai nel piano inferiore del palazzo.

Ora, mentre Yasa si dilettava, godendo dei cinque tipi di piaceri
sensoriali a sua disposizione, benché fosse ancora presto si addormentò,
e si addormentarono pure le sue inservienti. Però, una lampada notturna
era accesa, e quando Yasa si svegliò, vide le sue inservienti che
dormivano. Una aveva il liuto sotto il braccio, un’altra aveva il
tamburello sotto il mento, un’altra ancora il tamburo sotto il braccio.
I capelli di una s’erano slegati, dalla bocca di un’altra usciva bava,
un’altra ancora stava bofonchiando. Sembrava un carnaio. Allorché vide
tutto questo, quando fu direttamente colpito da un tale squallore, il
suo cuore si sentì male ed egli esclamò: «È spaventoso, è
orribile!».footnote:[Nel _Tipiṭaka_ il racconto dei menestrelli che dormono è
narrato solo in relazione a Yasa, ma versioni successive lo legano anche
al Bodhisatta quale ragione diretta per la sua rinuncia.]

Allora calzò le sue pantofole d’oro e andò alla porta della casa, e
degli esseri non-umani aprirono la porta, così che nessuno potesse
impedirgli di abbandonare la sua casa e la vita famigliare per la vita
religiosa. Egli si recò poi al cancello della città, e degli esseri
non-umani aprirono il cancello, così che nessuno potesse impedirgli di
abbandonare la casa e la vita famigliare per la vita religiosa.

Camminò fino al Parco delle Gazzelle di Isipatana. Quella notte il Beato
si era alzato presto, verso l’alba, e stava facendo la meditazione
camminata all’aperto. Quando vide in lontananza che Yasa stava
arrivando, smise di camminare e si mise a sedere nel posto preparatogli.
Quando Yasa non fu lontano dal Beato, esclamò: «È spaventoso, è
orribile!».

Allora il Beato disse: «Non è spaventoso, non è orribile. Vieni, Yasa,
siediti. Ti insegnerò il Dhamma».

Yasa pensò: «Non è spaventoso, non è orribile». Fu felice e pieno di
speranza. Si tolse le sue pantofole d’oro e si recò dove si trovava il
Beato. Dopo avergli prestato omaggio, si mise a sedere da un lato.
Quando l’ebbe fatto, il Beato gli impartì un insegnamento progressivo,
ossia gli parlò della genorosità, della virtù e dei paradisi. Gli spiegò
i pericoli, la vanità e la contaminazione dei piaceri sensoriali e le
benedizioni della rinuncia. Quando vide che la mente di Yasa era pronta,
recettiva, libera da impedimenti, ardente e fiduciosa, gli espose
l’insegnamento peculiare dei Buddha:footnote:[Questa traduzione di
_sāmukkaṃsika_ è basata sul Commentario a A.7:12. Non c’è dubbio che
il P.T.S. Dictionary sia qui in errore.] la sofferenza, la
sua origine, la sua cessazione e il sentiero per la sua cessazione.
Proprio come una stoffa pulita, dalla quale sono state rimosse tutte le
macchie, può essere tinta in modo uniforme, così, mentre Yasa stava lì
seduto, sorse in lui la pura, immacolata visione del Dhamma: tutto quel
che sorge deve cessare.

La madre di Yasa salì al palazzo di Yasa. Non vedendolo, andò dal
mercante e disse: «Non riesco a trovare tuo figlio, Yasa».

Egli allorà inviò messaggeri in tutte e quattro le direzioni, ed egli
stesso si recò al Parco delle Gazzelle di Isipatana. Vide le orme delle
pantofole d’oro, e le seguì. Il Beato vide che stava arrivando. Pensò:
«E se usassi il mio potere sovrannaturale per far sì che il mercante,
mentre sta seduto qui, non veda che pure Yasa è seduto qui?». Così fece.
Allora il mercante giunse dal Beato e gli chiese: «Signore, il Beato ha
forse visto Yasa?».

«Ora mettiti a sedere, e mentre sei seduto qui forse potrai vedere che
pure Yasa è seduto qui».

Quando il mercante udì queste parole fu felice, prestò omaggio al Beato
e si mise a sedere da un lato. Quando l’ebbe fatto, il Beato gli parlò
come aveva fatto con Yasa. Allora il mercante vide, raggiunse, trovò e
penetrò il Dhamma. Si lasciò alle spalle ogni incertezza, e i suoi dubbi
svanirono, ottenne una perfetta fiducia e divenne indipendente dagli
altri nella Dispensazione del Maestro. Disse: «Magnifico, Signore,
magnifico, Signore! Il Dhamma è stato chiarito in molti modi dal Beato,
come se egli avesse raddrizzato quel che era capovolto, rivelato quel
che era nascosto, indicato la via a chi è smarrito, alzato una lampada
nel buio per chi ha occhi per vedere forme visibili. Prendo rifugio nel
Beato, nel Dhamma e nel Saṅgha dei bhikkhu. Da oggi, Signore, il Beato
mi accolga come suo seguace che si è recato da lui per prendere rifugio
finché durerà il mio respiro». Ed egli fu il primo al mondo a prendere
il Triplice Rifugio.

Mentre il Dhamma era insegnato al padre, Yasa passò in rassegna il
livello di conoscenza che aveva visto e sperimentato, e per mezzo del
non-attaccamento il suo cuore fu liberato dalle contaminazioni. Allora
il Beato pensò: «Dopo questo conseguimento Yasa non è più in grado di
tornare a ciò che si è lasciato alle spalle e di godere dei piaceri
sensoriali nella casa famigliare come era solito fare. E se io smettessi
di usare il mio potere sovrannaturale?».

Così fece. Il mercante vide suo figlio che stava lì seduto. Gli disse:
«Yasa, figlio mio, tua madre è addolorata e afflitta. Rendi la vita a
tua madre».

Yasa guardò il Beato. Il Beato disse al mercante: «Che cosa ne pensi? Se
Yasa avesse visto il Dhamma con la conoscenza del
discentefootnote:[Questo termine si riferisce a “Chi è Entrato nella
Corrente” (_sotāpanna_) (Nyp.).] e con gli occhi del discente, come anche tu
hai fatto, e se egli avesse poi passato in rassegna il livello di
conoscenza che ha visto e sperimentato, e se per mezzo del
non-attaccamento il suo cuore si fosse liberato dalle contaminazioni,
sarebbe egli in grado di tornare a ciò che si è lasciato alle spalle e
di godere dei piaceri sensoriali nella casa famigliare come era solito
fare?».

«No, Signore».

«Però, è quel che Yasa ha fatto. Egli non è ora più in grado di tornare
a ciò che si è lasciato alle spalle e di godere dei piaceri sensoriali
nella casa famigliare come era solito fare».

«È un guadagno, Signore, è un grande guadagno per Yasa, che per mezzo
del non-attaccamento il suo cuore si sia liberato dalle contaminazioni.
Signore, che il Beato, con Yasa e il suo monaco attendente, accettino da
me il pasto di oggi». Il Beato accettò in silenzio. Quando il mercante
seppe che il Beato aveva accettato, si alzò dal posto in cui sedeva e,
dopo aver prestato omaggio al Beato, se ne andò girandogli a destra.

Appena se ne fu andato, Yasa disse al Beato: «Signore, desidero
abbracciare la vita religiosa e ricevere la piena ammissione dal Beato».

«Vieni bhikkhu», disse il Beato. E aggiunse: «Il Dhamma è ben
proclamato. Vivi la santa vita per completare la fine della sofferenza».
E questa fu la piena ammissione del venerabile Yasa.

E allora ci furono sette Arahant nel mondo.

Poiché s’era fatto mattino, il Beato si vestì, prese la ciotola e la
veste superiore, si recò con il venerabile Yasa e il suo monaco
attendente nella casa del mercante, e si mise a sedere sul seggio
preparatogli.

Allora la madre del venerabile Yasa assieme a colei che in precedenza
era stata sua moglie si recarono dal Beato e, dopo avergli prestato
omaggio, si misero a sedere da un lato. Egli parlò a loro come aveva
fatto con Yasa e con suo padre. La pura, immacolata visione del Dhamma
sorse anche nelle due donne: tutto quel che sorge deve cessare. Videro
il Dhamma come aveva fatto il mercante, e presero il Triplice Rifugio:
«A partire da oggi, Signore, il Beato ci accolga come sue seguaci che si
sono recate da lui per prendere rifugio finché durerà il nostro
respiro». E loro furono le prime donne al mondo a prendere il Triplice
Rifugio.

Allora la madre, il padre e colei che in precedenza era stata la moglie
del venerabile Yasa servirono il Beato e il venerabile Yasa con le loro
stesse mani, e li soddisfecero con differenti tipi di buon cibo. Quando
il Beato aveva finito di mangiare e non teneva più la ciotola in mano,
loro si misero a sedere da un lato. Poi il Beato, dopo averli istruiti,
esortati, risvegliati e incoraggiati con un discorso di Dhamma, si alzò
dal posto in cui sedeva e andò via.

Ora, quattro amici del venerabile Yasa che appartenevano alle principali
famiglie di mercanti di Benares, i cui nomi erano Vimala, Sabāhu,
Puṇṇaji e Gavampati, sentirono dire: «Pare che Yasa, uomo di rango, si
sia rasato i capelli e la barba, abbia indossato l’abito ocra e lasciato
la casa e la vita famigliare per la vita religiosa». Quando sentirono
queste cose, pensarono: «Se Yasa si è comportato così, deve trattarsi di
un Dhamma e di una Disciplina non usuali, non può trattarsi dell’usuale
andar via da casa e dalla vita famigliare».

Si recarono dal venerabile Yasa, e dopo avergli prestato omaggio, si
misero in piedi da un lato. Il venerabile Yasa li condusse allora dal
Beato. Dopo averli presentati al Beato, disse: «Signore, che il Beato li
consigli e li istruisca». Allora il Beato parlò a loro come già aveva
fatto, e anche loro divennero indipendenti dagli altri nella
Dispensazione del Maestro. Dissero: «Signore, desideriamo abbracciare la
vita religiosa e ricevere la piena ammissione dal Beato».

«Venite bhikkhu», disse il Beato. E aggiunse: «Il Dhamma è ben
proclamato. Vivete la santa vita per completare la fine della
sofferenza». E questa fu l’ammissione di questi venerabili. Allora il
Beato consigliò e istruì questi bhikkhu nel Dhamma, e mentre erano così
consigliati e istruiti, i loro cuori per mezzo del non-attaccamento
furono liberati dalle contaminazioni.

E allora ci furono undici Arahant nel mondo.

Ora, cinquanta amici del venerabile Yasa, figli delle famiglie
principali e secondarie della campagna, allo stesso modo sentirono dire
che egli aveva lasciato la casa e la vita famigliare per la vita
religiosa. Si recarono dal venerabile Yasa, che li condusse dal Beato. E
quando il Beato ebbe parlato a costoro, anche loro chiesero di
abbracciare la vita religiosa e ricevere la piena ammissione. Dopo che
furono consigliati e istruiti dal Beato, i loro cuori per mezzo del
non-attaccamento furono liberati dalle contaminazioni. E allora ci
furono sessantuno Arahant nel mondo.

Il Beato si rivolse allora ai bhikkhu: «Bhikkhu, io sono libero da tutte
le catene, sia umane sia divine. Andate ora errando per il benessere e
per la felicità di molti, per compassione nei riguardi del mondo, per il
beneficio, il benessere e la felicità di déi e uomini. Insegnate il
Dhamma che è salutare al principio, salutare nel mezzo e salutare alla
fine, con il significato e il senso letterale. Spiegate la santa vita
che è assolutamente perfetta e pura. Ci sono esseri che hanno solo poca
polvere negli occhi, i quali saranno perduti se non ascoltano il Dhamma.
Alcuni di loro comprenderanno il Dhamma. Io andrò a Uruvelā, a
Senānigāma, per insegnare il Dhamma».

Allora Māra il Malvagio si recò dal Beato e si parlarono con queste
strofe:

[verse]
____
Tu sei legato da tutte le catene +
sia umane sia divine, +
i legami che ti vincolano sono forti, +
e tu non mi sfuggirai, monaco.

Io sono libero da tutte le catene +
sia umane sia divine, +
libero dai vincoli più forti, e tu +
sei ora sconfitto, Sterminatore.

Quella catena che sta nell’aria, +
essa sta sulla mente, con essa +
ti terrò legato per sempre, +
e tu non mi sfuggirai, monaco.

Sono privo di desiderio per immagini, +
suoni, sapori, e odori, e cose da toccare, +
per quanto essi buoni paiano, +
e tu sei ora sconfitto, Sterminatore.
____

Allora Māra il Malvagio seppe: «Il Beato mi conosce, il Sublime mi
conosce». Triste e deluso, subito sparì.

I bhikkhu che erano andati errando per la diffusione del Dhamma da varie
direzioni e regioni stavano ormai portando uomini che volevano
abbracciare la vita religiosa e ricevere la piena ammissione, affinché
la ricevessero dal Beato. Ciò era problematico sia per i bhikkhu sia per
chi voleva abbracciare la vita religiosa e ricevere la piena ammissione.
Il Beato considerò tale questione e, quando fu sera, chiamò a raccolta
il Saṅgha dei bhikkhu per questa ragione. Dopo aver tenuto un discorso
di Dhamma, si rivolse a loro in questo modo:

«Bhikkhu, quando ero in ritiro da solo questo pensiero sorse nella mia
mente: “I bhikkhu da varie direzioni e regioni stanno portando uomini
che vogliono abbracciare la vita religiosa e ricevere la piena
ammissione, affinché la ricevano da me. Ciò è problematico sia per i
bhikkhu sia per chi vuole abbracciare la vita religiosa e ricevere la
piena ammissione. Perché non dovrei autorizzare i bhikkhu a dar il
consenso per far abbracciare la vita religiosa e ricevere la piena
ammissione, in qualsiasi direzione, in qualsiasi regione dovessero
trovarsi?”. Nei fatti è questo che vi autorizzo a fare. E ciò deve
essere fatto in questo modo: prima devono essere rasati i capelli e la
barba. Poi, indossata la veste ocra, la veste superiore deve essere
ripiegata su una spalla e deve essere prestato omaggio ai piedi del
bhikkhu. Poi, inginocchiati e con le palme delle mani giunte, si deve
dire questo: “Prendo rifugio nel Buddha, prendo rifugio nel Dhamma,
prendo rifugio nel Saṅgha. Per la seconda volta ... Per la terza volta
...”. Autorizzo i bhikkhu a dar il consenso per far abbracciare la vita
religiosa e ricevere la piena ammissione mediante il Triplice Rifugio».

Ora, quando il Beato aveva trascorso la stagione delle piogge a Benares,
egli si rivolse ai bhikkhu in questo modo:

«Bhikkhu, è con attenzione metodica, con sforzo metodico, che io ho
raggiunto e realizzato la Liberazione suprema. È con attenzione
metodica, con sforzo metodico, che anche voi, bhikkhu, avete raggiunto e
realizzato la Liberazione suprema».

Allora Māra il Malvagio si recò dal Beato e gli parlò con queste strofe:

[verse]
____
Tu sei legato dalle catene di Māra +
sia umane sia divine. +
Tu sei legato dai vincoli di Māra, +
e tu non mi sfuggirai, monaco.

Io sono libero dalle catene di Māra +
sia umane sia divine. +
Libero dai vincoli di Māra, +
e tu sei ora sconfitto, Sterminatore.
____

Allora Māra il Malvagio seppe: «Il Beato mi conosce, il Sublime mi
conosce». Triste e deluso, subito sparì.

Allorché il Beato aveva soggiornato a Benares per tutto il tempo che
volle, si mise in viaggio per tappe verso Uruvelā. Quando era in
cammino, lasciò la strada per recarsi in una foresta, e lì si mise a
sedere ai piedi di un albero. In quel momento trenta amici con le loro
mogli tenevano un festa speciale, si divertivano insieme nella foresta.
Uno di loro non aveva moglie, e per lui era stata portata una
prostituta. Mentre si stavano divertendo sconsideratamente, la
prostituta lo derubò dei suoi beni e scappò via. Così, al fine di
aiutarlo, i suoi amici andarono alla ricerca della donna. Mentre se ne
andavano in giro per la foresta, videro il Beato che sedeva ai piedi di
un albero. Andarono da lui e gli chiesero: «Signore, il Beato ha visto
una donna?». «Ragazzi, perché cercate quella donna?». Loro gli
raccontarono l’accaduto.

«Che cosa ne pensate? Che cosa è meglio per voi? Dovreste cercare una
donna oppure dovreste cercare voi stessi?».footnote:[Non pare si debba
leggere nelle parole _attānaṃ
gaveseyyātha_ (“dovreste cercare voi stessi”) più di quel che è
contenuto nell’oracolo delfico “conosci te stesso”. Nella lingua pāli la
parola _attā_ (sé) non è usata al plurale, e non c’è nulla di strano se
tale forma singolare è applicata a un gruppo (gli alfabeti indiani non
hanno maiuscole).]

«Signore, per noi è meglio cercare noi stessi».

«Sedete, allora, e vi insegnerò il Dhamma».

«Nonostante tutto, così sia, Signore», risposero. Dopo avergli prestato
omaggio, si misero a sedere da un lato.

Il Beato impartì loro un insegnamento progressivo. A tempo debito sorse
in loro la pura, immacolata visione del Dhamma. E infine divennero
indipendenti dagli altri nella Dispensazione del Maestro. Allora
dissero: «Desideriamo abbracciare la vita religiosa e ricevere la piena
ammissione dal Beato».

«Venite bhikkhu», disse il Beato. E aggiunse: «Il Dhamma è ben
proclamato. Vivete la santa vita per completare la fine della
sofferenza». E questa fu l’ammissione di questi venerabili.

Il Beato viaggiò per tappe finché giunse finalmente a Uruvelā. In quel
tempo a Uruvelā vivevano tre asceti dai capelli intrecciati, di nome
Kassapa di Uruvelā, Kassapa del fiume, e Kassapa di Gayā. Kassapa di
Uruvelā era il caposcuola, il capofila, il capo, la guida e il
principale di cinquecento asceti dai capelli intrecciati, Kassapa del
fiume di trecento, e Kassapa di Gayā di duecento.

Il Beato si recò al romitorio di Kassapa di Uruvelā, e disse: «Kassapa,
se non hai nulla da obiettare, vorrei trascorrere una notte nella tua
camera del fuoco».

«Non ho nulla da obiettare, Grande Monaco. Lì c’è però un serpente
_nagā_ reale e selvaggio. Ha poteri sovrannaturali. È velenoso,
terribilmente velenoso, in grado di ucciderti».

Il Beato chiese una seconda e una terza volta e ricevette la stessa
risposta. Egli disse: «Forse non mi annienterà, Kassapa. Concedimi la
camera del fuoco».

«Allora restaci per tutto il tempo che vuoi, Grande Monaco».

Così, il Beato andò nella camera del fuoco.

Stese una stuoia a terra e si mise a sedere, incrociò le gambe e, con il
corpo eretto, fissò la consapevolezza di fronte a lui. Quando il _nagā_
vide il Beato entrare si infuriò, e produsse del fumo. Allora il Beato
pensò: «E se io neutralizzassi il suo fuoco con del fuoco, senza
danneggiare la sua pelle esterna o la sua pelle interna, o le sue carni
o i suoi tendini o le sue ossa o il suo midollo?». Così fece, e produsse
del fumo. Allora il _nagā_, senza contenere più la sua furia, produsse
delle fiamme. Il Beato entrò nell’elemento fuoco e produsse anch’egli
delle fiamme. La camera del fuoco parve bruciare, divampare e ardere per
le loro fiamme. Gli asceti dai capelli intrecciati si riunirono lì
attorno, e dissero: «Il Grande Monaco, così bello, è stato annientato
dal _nagā_».

Quando la notte fu terminata e il Beato ebbe neutralizzato con il fuoco
il fuoco del _nagā_ senza danneggiarlo, lo mise nella sua ciotola e lo
mostrò a Uruvelā Kassapa: «Questo è il tuo _nagā_, Kassapa. Il suo fuoco
è stato neutralizzato con il fuoco». Allora Uruvelā Kassapa pensò: «Il
Grande Monaco è davvero poderoso e possente, giacché è in grado di
neutralizzare con il fuoco il fuoco del serpente _nagā_ reale e
selvaggio con poteri sovrannaturali che è velenoso, terribilmente
velenoso. Lui però non è un Arahant come me».

Il Beato andò a vivere in una foresta non distante dal romitorio di
Kassapa. Quando era notte inoltrata, i Quattro Divini Sovrani, che erano
meravigliosi a vedersi e illuminavano l’intera foresta, si recarono dal
Beato e, dopo avergli prestato omaggio, si misero in piedi ai quattro
punti cardinali, come pilastri fiammeggianti. Quando la notte fu
trascorsa, l’asceta dai capelli intrecciati Uruvelā Kassapa andò dal
Beato e disse: «È ora, Grande Monaco, il pasto è pronto. Chi è venuto da
te questa notte?».

«Erano i Divini Sovrani dei Quattro Punti Cardinali, Kassapa. Sono
venuti da me per ascoltare il Dhamma».

Allora Kassapa pensò: «Il Grande Monaco è davvero poderoso e possente,
giacché i Quattro Sovrani sono andati da lui per ascoltare il Dhamma.
Lui però non è un Arahant come me».

Durante le notti successive, Sakka, Sovrano degli Déi, e Brahmā
Sahampati andarono dal Beato. Furono visti da Kassapa, e le cose
andarono nella stessa maniera.

In quel mentre doveva essere celebrata la grande cerimonia sacrificale
di Uruvelā Kassapa, e la gente giunse entusiasta da tutto l’Anga e il
Magadha portando grandi quantità di vari generi di cibo. Allora Kassapa
pensò: «Ora la mia grande cerimonia sacrificale deve essere celebrata, e
la gente sta giungendo entusiasta da tutto l’Anga e il Magadha e sta
portando grandi quantità di vari generi di cibo. Se il Grande Monaco
operasse un miracolo al cospetto di tutta questa gente, la sua fama e
rinomanza crescerebbe e la mia diminuirebbe. Se solo il Grande Monaco
domani non venisse!».

Il Beato fu consapevole nella sua mente del pensiero sorto nella mente
di Kassapa. Così, si recò nella regione occidentale di Uttarakuru e lì
elemosinò del cibo. Allora portò il cibo elemosinato al lago di Anotatta
nell’Himalaya e lì mangiò e passò l’intera giornata. Quando la notte fu
trascorsa, Kassapa andò dal Beato e disse: «È ora, Grande Monaco, il
pasto è pronto. Perché il Grande Monaco non è venuto ieri? Ci siamo
chiesti perché non sia venuto. La sua porzione di cibo era stata
preparata». Il Beato glielo disse. Allora Kassapa pensò: «Il Grande
Monaco è davvero poderoso e possente, giacché è consapevole nella sua
mente del pensiero sorto nella mia mente. Lui però non è un Arahant come
me».

Quando il Beato ebbe finito di mangiare il pasto di Uruvelā Kassapa,
tornò a vivere nella stessa foresta. In quel mentre un panno scartato
giunse in possesso del Beato. Egli pensò: «Dove laverò questo panno
scartato?». Allora Sakka, Sovrano degli Déi, fu consapevole nella sua
mente del pensiero sorto nella mente del Beato. Con la sua mano scavò
uno stagno, e disse al Beato: «Signore, che il Beato lavi qui il panno
scartato».

Poi il Beato pensò: «Su che cosa batterò questo panno scartato?». Allora
Sakka, Sovrano degli Déi, consapevole nella sua mente del pensiero sorto
nella mente del Beato, pose sul terreno una grande pietra: «Signore, che
il Beato batta qui il panno scartato».

Poi il Beato pensò: «Dove stenderò questo panno scartato?». Allora una
divinità che viveva in un albero _kakudha_ piegò un ramo: «Signore, che
il Beato stenda qui il panno scartato».

Quando la notte fu trascorsa, Kassapa andò dal Beato e disse: «È ora,
Grande Monaco, il pasto è pronto. Però, Grande Monaco, come mai qui c’è
uno stagno che prima non c’era? Chi ha messo qui questa pietra che prima
non c’era? Come mai questo ramo kakudha s’è piegato, mentre prima non lo
era?».

Il Beato gli disse quel che era avvenuto. Allora Kassapa pensò: «Il
Grande Monaco è davvero poderoso e possente, giacché Sakka, Sovrano
degli Déi, si prende cura di lui. Lui però non è un Arahant come me».

Di nuovo, quando la notte fu trascorsa, Kassapa andò dal Beato e disse:
«È ora, Grande Monaco, il pasto è pronto». Il Beato lo congedò, dicendo:
«Vai Kassapa, ti seguirò». Andò all’albero di melarosa, dal quale ha
preso il nome la regione indiana di Melarosa, e prese un frutto. Poi
arrivò per primo e si mise a sedere nella camera del fuoco. Kassapa lo
vide lì seduto e gli chiese: «Grande Monaco, quale strada hai percorso?
Io sono partito prima di te, ma tu sei arrivato prima di me e sei qui,
seduto nella camera del fuoco». Il Beato gli disse dove era stato, e
aggiunse: «Qui c’è una melarosa. È colorita, profumata e saporita.
Mangiala tu, se vuoi».

«No, Grande Monaco, sei stato tu a portarla. Dovresti mangiarla tu».

Allora Kassapa pensò: «Il Grande Monaco è davvero poderoso e possente,
giacché mi ha fatto andar via per primo e poi è andato all’albero di
melarosa, ha preso un frutto, è arrivato prima di me ed è qui, seduto
nella camera del fuoco. Lui però non è un Arahant come me». Più tardi il
Beato tornò nella foresta.

Di nuovo, in circostanze simili, il Beato andò all’albero di melarosa e
da un albero lì vicino prese un mango ... da un albero lì vicino prese
una noce di galla ... da un albero lì vicino prese una gialla noce di
galla ... andò nel paradiso delle Trentatré Divinità e colse un fiore
dall’albero _pāricchattaka_. Ogni volta Kassapa ebbe gli stessi pensieri
di prima.

In quel mentre gli asceti dai capelli intrecciati, che volevano
alimentare i loro fuochi, non furono in grado di spaccare i tronchi di
legno. Pensarono: «Deve essere a causa dei poteri sovrannaturali del
Grande Monaco che non riusciamo a spaccare i tronchi di legno».

Il Beato chiese a Kassapa: «I tronchi di legno dovrebbero spaccarsi,
Kassapa?». «Dovrebbero spaccarsi, Grande Monaco».

Subito i cinquecento tronchi si spaccarono. Allora Kassapa pensò: «Il
Grande Monaco è davvero poderoso e possente, giacché i tronchi di legno
non potevano essere spaccati. Lui però non è un Arahant come me».

E di nuovo, in circostanze simili, gli asceti dai capelli intrecciati,
volendo alimentare i loro fuochi, non riuscivano ad accendere i loro
fuochi ... non riuscivano a spegnere i loro fuochi. E ogni volta Kassapa
ebbe gli stessi pensieri di prima.

In quelle fredde notti invernali, durante gli “otto giorni di ghiaccio”
gli asceti dai capelli intrecciati s’immergevano nel fiume Nerañjarā e
ne emergevano, s’immergevano e ne emergevano in continuazione. Allora il
Beato creò cinquecento bracieri per riscaldare gli asceti dai capelli
intrecciati quando uscivano dall’acqua. Essi pensarono: «Questi bracieri
devono essere stati creati dai poteri sovrannaturali del Grande Monaco».
Allora Kassapa pensò: «Il Grande Monaco è davvero poderoso e possente,
giacché ha creato così tanti bracieri. Lui però non è un Arahant come
me».

Sempre in quei giorni scoppiò fuori stagione un gran temporale e si
verificò un’enorme inondazione. Il posto nel quale il Beato viveva era
del tutto sommerso. Allora egli pensò: «E se io facessi in modo che
l’acqua restasse bloccata indietro tutt’intorno, così da poter camminare
sul terreno asciutto?». Così egli fece.

Kassapa pensò: «Spero che il Grande Monaco non sia stato trascinato via
dall’acqua». Così, accompagnato un certo numero di asceti dai capelli
intrecciati si recò con una barca nel posto in cui il Beato viveva. Vide
che il Beato aveva fatto restare l’acqua bloccata indietro tutt’intorno
e stava camminando sul terreno asciutto. Quando vide, disse:

«Sei tu, Grande Monaco?».

«Sì, Kassapa».

Il Beato si librò nell’aria e andò a posarsi sulla barca. Allora Kassapa
pensò: «Il Grande Monaco è davvero poderoso e possente, giacché neanche
l’acqua è riuscita a sopraffarlo. Lui però non è un Arahant come me».

Allora il Beato pensò: «Questo fuorviato continuerà per sempre a pensare
“Lui però non è un Arahant come me”. E se io gli dessi uno scossone?».
Disse a Kassapa: «Kassapa tu non sei né un Arahant né sei sulla strada
per diventarlo. In quel che tu fai non c’è nulla che ti possa far
diventare un Arahant o far entrare nella via per diventarlo».

A quel punto l’asceta dai capelli intrecciati prostrò il capo ai piedi
del Beato e gli disse: «Signore, desidero abbracciare la vita religiosa
e ricevere l’ammissione dal Beato».

«Kassapa, tu sei però il caposcuola, il capofila, il capo, la guida e il
principale di cinquecento asceti dai capelli intrecciati. Prima devi
consultarli, in modo che loro facciano quel che ritengono giusto».

Così, Uruvelā Kassapa andò dagli altri asceti e disse loro: «Voglio
vivere la santa vita sotto il Grande Monaco. Fate quel che ritenete
giusto».

«Da tempo abbiamo fede nel Grande Monaco. Se tu vuoi vivere la santa
vita sotto di lui, tutti noi faremo lo stesso».

Allora gli asceti dai capelli intrecciati presero i loro capelli, le
loro ciocche intrecciate, i loro beni, gli arredi del fuoco sacrificale
e li gettarono in acqua, affinché fossero portati via da essa. Poi
andarono dal Beato, prostrarono il capo ai suoi piedi e dissero:
«Signore, desideriamo abbracciare la vita religiosa e ricevere
l’ammissione dal Beato».

«Venite bhikkhu», disse il Beato. E aggiunse: «Il Dhamma è ben
proclamato. Vivete la santa vita per completare la fine della
sofferenza». E questa fu la piena ammissione di quei venerabili.

L’asceta dai capelli intrecciati Kassapa del fiume vide i capelli, le
ciocche intrecciate, i beni e gli arredi del fuoco sacrificale portati
via dall’acqua. Pensò: «Spero che mio fratello non sia stato vittima di
un disastro». Inviò degli asceti dai capelli intrecciati: «Andate a
vedere che cosa è successo a mio fratello». Poi andò egli stesso con i
suoi trecento asceti dai capelli intrecciati dal venerabile Uruvelā
Kassapa, e gli chiese: «Questo è meglio, Kassapa?».

«Sì, amico, questo è meglio».

Allora quegli asceti dai capelli intrecciati presero i loro capelli, le
loro ciocche intrecciate, i loro beni, gli arredi del fuoco sacrificale
e li gettarono in acqua, affinché fossero portati via da essa. Poi
andarono dal Beato, prostrarono il capo ai suoi piedi e chiesero di
abbracciare la vita religiosa, e di ricevere l’ammissione. E l’asceta
dai capelli intrecciati Kassapa di Gayā con i suoi duecento asceti dai
capelli intrecciati fece quel che aveva fatto Kassapa del fiume.

[.suttaref]
_Vin. Mv. 1:7-20_

[.voice]
`Prima Voce.` Così ho udito. Una volta il Beato soggiornava a Uruvelā nei
pressi dell’albero _ajapāla nigrodha_ sulla riva del fiume Nerañjarā.
Māra il Malvagio stava seguendo il Beato da sette anni alla ricerca di
un’opportunità, ma senza riuscire a trovarne nessuna. Allora si recò dal
Beato e si rivolse a lui con queste strofe:

[verse]
____
Sogni di boschi, immerso nel dolore? +
Hai perso la ricchezza, o ti stai struggendo per essa? +
Hai commesso qualche crimine in città? +
Perché non hai amici tra la gente? +
E non c’è nessuno che tu possa chiamare amico?

La radice del dolore è sradicata da me. +
Senza dolermi, medito nell’innocenza +
e libero dalle contaminazioni, o Cugino della Distrazione, +
come chi ha vinto ogni brama per l’esistenza.

Le cose per cui gli uomini dicono “è mio” +
e pronunciano la parola “mio”: +
se tu hai pensieri apparentati a queste cose, +
non puoi allora sfuggirmi, monaco.

Le cose che chiamano “mie” non così io le chiamo, +
non sono uno che parla in questo modo. +
Ascolta questo, allora, Malvagio, il Sentiero che +
io conosco tu neanche a vederlo riesci.

Se hai trovato davvero un Sentiero +
che conduce in tutta sicurezza a Ciò Che Non Muore, +
percorrilo. Ma fallo da solo. +
Che bisogno c’è che lo conoscano altri?

Le persone che cercano di andare al di là +
mi chiedono dov’è che la morte non prevale. +
Interrogato in questo modo, racconto la Fine di Tutto, +
laddove non c’è sostanza per rinascite.
____

«Supponi, Signore, che non lontano da una città o da un villaggio ci sia
uno stagno nel quale vive un granchio, e che un gruppo di ragazzi o di
ragazze esca dalla città o dal villaggio per recarsi allo stagno, che si
rechino allo stagno e mettano il granchio fuori dall’acqua, e lo poggino
sulla terraferma. E tutte le volte che il granchio allunga una zampa
gliela taglino, gliela rompano e la schiaccino con bastoni e pietre, di
modo che il granchio, con tutte le zampe tagliate, rotte e schiacciate,
non sia in grado di tornare nello stagno. Così, anche le deformazioni,
le parodie e i travestimenti di Māra sono stati tagliati, rotti e
schiacciati dal Beato, e ora non posso più avvicinarmi al Beato alla
ricerca di un’opportunità».

Allora Māra pronunciò queste strofe di delusione alla presenza del
beato:

[.suttaref]
_S. 4:24_

[verse, Sn. 3:2]
____
Passo passo per sette anni +
seguii il Beato. +
L’Essere Completamente Illuminato, in possesso della +
Consapevolezza, non mi diede occasione alcuna.
____

[verse]
____
C’era un corvo che camminava intorno a +
una pietra che sembrava un grumo di grasso: +
“Ci sarà qualcosa di morbido qui dentro? +
Ci sarà qualcosa di saporito qui?”. +
Egli, non trovando nulla di saporito, +
fuggì via. Anche noi da Gotama +
andiamo via, delusi, +
come il corvo che provò con la pietra.
____

Pieno di tristezza l’infelice demone si lasciò scivolare il suo liuto da
sotto il braccio, e poi svanì.

[.suttaref]
_Sn. 3:2; S. 4:24_

Ora, Māra il Malvagio, dopo aver pronunciato queste strofe di delusione
alla presenza del Beato, abbandonò quel posto e si mise a sedere in
terra a gambe incrociate non lontano dal Beato, grattando il terreno con
un bastoncino, in silenzio, costernato, con le spalle cadenti e a testa
bassa, abbattuto e senza aver nulla da dire.

Allora le tre figlie di Māra, Taṇhā, Aratī e Ragā – Brama, Noia e
Lussuria – andarono dal padre e gli parlarono in strofe:

[verse]
____
O Padre, perché sei sconsolato? +
Su chi stai rimuginando? +
Lo possiamo catturare, +
preparando una trappola con la lussuria, lo legheremo, +
proprio come si cattura un elefante della foresta, +
per ricondurlo di nuovo in tuo potere.

C’è al mondo un sublime Arahant, +
e quando un uomo sfugge dalla sfera di Māra +
non ci sono astuzie per adescarlo di nuovo +
con la lussuria, ed è per questo che sono così addolorato.
____

Allora le tre figlie di Māra, Taṇhā, Aratī e Ragā andarono dal Beato e
gli dissero: «O Monaco, ci prostriamo ai tuoi piedi». Il Beato, però,
non se ne curò, poiché era libero per la fine definitiva degli
essenziali dell’esistenza.

Loro si ritirarono da una parte e si consultarono: «I gusti degli uomini
sono vari. E se ognuna di noi creasse le forme di un centinaio di
ragazze?». Così fecero, e andarono dal Beato e dissero: «O Monaco, ci
prostriamo ai tuoi piedi». Di nuovo, per la stessa ragione, il Beato non
se ne curò.

Allora si ritirarono da una parte e si consultarono: «I gusti degli
uomini sono vari. E se ognuna di noi creasse le forme di un centinaio di
vergini ... di donne che hanno partorito una volta ... di donne che
hanno partorito due volte ... di donne mature ... di donne anziane?».
Fecero tutto questo e poi andarono dal beato e dissero: «O Monaco, ci
prostriamo ai tuoi piedi». E di nuovo, per la stessa ragione, il Beato
non se ne curò.

Allora si ritirarono da una parte e dissero: «Pare che nostro padre
abbia ragione, perché se avessimo tentato in questo modo un qualsiasi
monaco o brāhmaṇa non libero dalla lussuria, il suo cuore si sarebbe
infiammato, oppure del sangue bollente sarebbe sgorgato dalla sua bocca,
oppure sarebbe diventato folle o matto, oppure si sarebbe avvizzito,
disseccato e appassito come un filo d’erba tagliato». Andarono dal Beato
e si misero in piedi da un lato. Taṇhā gli parlò in strofe:

[verse]
____
Sogni di boschi, immerso nel dolore? +
Hai perso la ricchezza, o ti stai struggendo per essa? +
Hai commesso qualche crimine in città? +
Perché non hai amici tra la gente? +
E non c’è nessuno che tu possa chiamare amico?

Ho sconfitto tutte le compatte schiere +
delle allettanti e piacevoli forme. Ho trovato la beatitudine +
meditando da solo e ho ottenuto la beatitudine del traguardo, +
quella beatitudine che si trova nella quiete del cuore. +
Per questo non cerco amici tra la gente, +
perché non c’è nessuno con cui ho bisogno di fare amicizia.
____

Allora Aratī gli parlò in strofe:

[verse]
____
Quale dimorare pratica qui un bhikkhu +
che dopo aver attraversato le cinque mareefootnote:[I Commentari
affermano che le «cinque maree» sono «quelle
della brama, ecc., connesse con le cinque porte sensoriali», mentre la
«sesta» è «la marea delle contaminazioni connesse con la porta della
mente».] +
può attraversare anche la sesta? Quale pratica +
meditativa impedisce ai piaceri sensoriali di raggiungerlo?

Tranquillo nel corpo, con la mente liberata, +
senza escogitare nulla, consapevole e distaccato, +
conoscendo il Dhamma, concentrato e privo di pensieri vaganti, +
di rabbia e di ansia, di perplessità. +
Questo è il dimorare che qui pratica un bhikkhu, +
che dopo aver attraversato le cinque maree +
può attraversare anche la sesta. Questa è la pratica +
meditativa che impedisce ai piaceri sensoriali di raggiungerlo.
____

Allora Ragā pronunciò queste strofe alla presenza del Beato:

[verse]
____
Va accompagnato della recisa bramosia, +
numerosi esseri lo seguiranno, ahimè! +
E ci sono moltitudini che il Distaccato +
strapperà dal regno della Morte e condurrà a riva. +
I Grandi Eroi, gli Esseri Perfetti, +
porteranno gli uomini lontano per mezzo del Buon Dhamma. +
Quale geloso nostro livore può essere utile +
contro il potere di guida del Buon Dhamma?
____

Allora Taṇhā, Aratī e Ragā, le figlie di Māra, andarono da Māra il
Malvagio. Vedendole arrivare, egli pronunciò queste strofe:

[verse]
____
Stolte! Avete cercato di spaccare una roccia +
colpendola con steli di giglio, +
di cavare una collina con le vostre unghie, +
di masticare del ferro con i vostri denti, +
di trovare un appoggio su una scogliera +
con una grande pietra sulla vostra testa, +
di abbattere un albero con il vostro petto. +
E così siete state disilluse da Gotama.
____

[.suttaref]
_S. 4:24-25_

[.voice]
`Seconda Voce.` Ora, dopo essere rimasto a Uruvelā per tutto il tempo che
volle, il Beato si avviò verso Gayāsīsa con un gran seguito di bhikkhu,
con un migliaio di bhikkhu, con tutti quelli che prima erano stati
asceti dai capelli intrecciati. Il Beato si fermò a Gayāsīsa, nei pressi
di Gayā, con i mille bhikkhu. Lì si rivolse ai bhikkhu in questo modo:

(_Il Sermone del Fuoco_)

«Bhikkhu, tutto brucia. E che cos’è che brucia?».

«L’occhio brucia. Le forme visibili bruciano. La coscienza visiva
brucia. Il contatto visivo brucia. Anche la sensazione, piacevole o
dolorosa o né-dolorosa-né piacevole, che sorge con il contatto visivo
quale sua condizione, anch’essa brucia. Con che cosa brucia? Brucia con
il fuoco della brama, con il fuoco dell’avversione, con il fuoco
dell’illusione. Brucia con la nascita, l’invecchiamento e la morte, e
anche con l’afflizione, il lamento, il dolore, il dispiacere e la
disperazione, questo vi dico».

«L’orecchio brucia. I suoni bruciano ...».

«Il naso brucia. Gli odori bruciano ...».

«La lingua brucia. I sapori bruciano ...».

«Il corpo brucia. Gli oggetti tangibili bruciano ...».

«La mente brucia. Gli oggetti mentali bruciano. La coscienza mentale
brucia. Anche la sensazione, piacevole o dolorosa o né-dolorosa-né
piacevole, che sorge con il contatto mentale quale sua condizione,
anch’essa brucia. Con che cosa brucia? Brucia con il fuoco della brama,
con il fuoco dell’avversione, con il fuoco dell’illusione. Brucia con la
nascita, l’invecchiamento e la morte, e anche con l’afflizione, il
lamento, il dolore, il dispiacere e la disperazione, questo vi dico».

«Con questa comprensione, bhikkhu, un saggio nobile discepolo diventa
disincantato nei riguardi dell’occhio, nei riguardi delle forme
visibili, nei riguardi della coscienza visiva, nei riguardi del contatto
visivo. Diventa disincantato anche nei riguardi della sensazione,
piacevole o dolorosa o né-dolorosa-né-piacevole, che sorge con il
contatto visivo quale sua condizione».

«Diventa disincantato nei riguardi dell’orecchio, nei riguardi dei suoni
...».

«Diventa disincantato nei riguardi del naso, nei riguardi degli odori
...».

«Diventa disincantato nei riguardi della lingua, nei riguardi dei sapori
...».

«Diventa disincantato nei riguardi del corpo, nei riguardi degli oggetti
tangibili ...».

«Diventa disincantato nei riguardi della mente, nei riguardi degli
oggetti mentali, nei riguardi della coscienza mentale, nei riguardi del
contatto mentale. Diventa disincantato anche nei riguardi della
sensazione, piacevole o dolorosa o né-dolorosa-né piacevole, che sorge
con il contatto mentale quale sua condizione».

«Diventando disincantato, la sua brama svanisce, con lo svanire della
brama, il suo cuore è liberato. Quando il suo cuore è liberato, giunge
la conoscenza: “È liberato”. Egli comprende: “La nascita è distrutta, la
santa vita è stata vissuta, quel che doveva essere fatto è stato fatto,
non ci sarà altra rinascita”».

E mentre questo discorso era tenuto, i cuori dei mille bhikkhu furono
liberati dalle contaminazioni mediante il non-attaccamento.

[.suttaref]
_Vin. Mv. 1:21; S. 35:28_

Allorché il Beato aveva vissuto a Gayāsīsa per tutto il tempo che volle,
si mise in viaggio per tappe verso Rājagaha con un gran seguito di
bhikkhu, con un migliaio di bhikkhu, con tutti quelli che prima erano
stati asceti dai capelli intrecciati. Viaggiando per tappe egli giunse
infine a Rājagaha, e lì soggiornò nel Boschetto degli Alberelli, nel
Sacrario di Supaṭṭhita.

Seniya Bimbisāra, re di Magadha, udì: «Sembra che il monaco Gotama, il
figlio dei Sakya, che abbandonò un clan dei Sakya e la vita famigliare
per la vita religiosa, è giunto a Rājagaha e soggiorna nel Boschetto
degli Alberelli del Sacrario di Supaṭṭhita». La rinomanza del Maestro
Gotama si era diffusa in questo modo: «Quel Beato è tale poiché è
realizzato, completamente illuminato, perfetto nella conoscenza e nella
condotta, sublime, conoscitore dei mondi, incomparabile guida degli
uomini che devono essere addestrati, insegnante di déi e uomini,
illuminato, beato. Ha rivelato questo mondo con i suoi deva, con i suoi
Māra e con le sue divinità, in questa generazione con i suoi monaci e
brāhmaṇa, con i suoi principi e uomini, che lui stesso ha compreso per
mezzo di una conoscenza diretta. Insegna il Dhamma che è salutare al
principio, salutare nel mezzo e salutare alla fine, con il significato e
il senso letterale, e spiega la santa vita che è assolutamente perfetta
e pura». «È bene andare a incontrare un tale essere realizzato».

Allora Seniya Bimbisāra, re di Magadha, accompagnato da dodici schiere
di centoventimila capifamiglia brāhmaṇa di Magadha, andò dal Beato, e
dopo avergli prestato omaggio, si mise a sedere da un lato. Tra le
dodici schiere di capifamiglia brāhmaṇa, alcuni prestarono omaggio al
Beato e si misero a sedere da un lato. Altri scambiarono con lui dei
saluti e, quando furono terminati i formali doveri di reciproca
cortesia, si misero a sedere da un lato. Altri levarono le palme giunte
delle loro mani in saluto del Beato e si misero a sedere da un lato.
Altri pronunciarono il nome loro e quello della loro stirpe alla
presenza del beato, e si misero a sedere da un lato. Altri ancora
restarono in silenzio e si misero a sedere da un lato.

Si chiedevano: «È il Grande Monaco a condurre la santa vita sotto
Uruvelā Kassapa o è Uruvelā Kassapa a condurre la santa vita sotto il
Grande Monaco?». Però, il Beato nella sua mente fu consapevole del
pensiero sorto nella loro mente, e si rivolse al venerabile Uruvelā
Kassapa in strofe:

[verse]
____
Che cosa vide, lo scarno insegnante che dimora +
a Uruvelā, da fargli lasciare i fuochi? +
Ti faccio questa domanda, Kassapa: +
per quale ragione hai smesso di adorare il fuoco?

Immagini e suoni e sapori e concubine +
sono le ricompense promesse per il sacrificio. +
Delle cose mondane ho visto che erano una contaminazione. +
Allora non ho più gioito della venerazione e del sacrificio.

Se però il tuo cuore non si delizia più per queste cose, +
Kassapa, disse il Beato, +
per immagini e suoni, come anche per i sapori, +
che cosa allora delizia il tuo cuore, qui, in questo mondo +
di déi e uomini, Kassapa? Dimmelo.

Ho visto la condizione di pace, non di questo mondo, +
dove non ci sono possessi, e neanche esseri sensoriali, +
né alterità, né esseri guidati da altri. +
Allora non ho più gioito della venerazione e del sacrificio.
____

Poi il venerabile Uruvelā Kassapa si alzò dal posto in cui sedeva,
sistemò la veste [superiore] su una spalla, e prostrò il capo ai piedi
del Beato, dicendo: «Signore, il Beato è la mia guida, io sono un
discepolo. Il Beato è la mia guida, io sono un discepolo».

Allora le dodici schiere di capifamiglia brāhmaṇa di Magadha pensarono:
«Uruvelā Kassapa conduce la santa vita sotto il Beato». Il Beato,
consapevole nella sua mente del pensiero sorto nella loro mente, impartì
loro un insegnamento progressivo. Infine la pura, immacolata visione del
Dhamma sorse lì e allora in undici delle dodici schiere di capifamiglia
brāhmaṇa di Magadha: tutto quel che sorge deve cessare. E i componenti
di una schiera divennero dei seguaci.

Allora Seniya Bimbisāra, re di Magadha, vide, raggiunse, trovò e penetrò
il Dhamma. Si lasciò alle spalle ogni incertezza e i suoi dubbi
svanirono, ottenne una perfetta fiducia e divenne indipendente dagli
altri nella Dispensazione del Maestro.

Egli disse al Beato: «Signore, quando ero ragazzo avevo cinque
aspirazioni. Ora sono realizzate. Una volta, quando ero ragazzo, pensai:
“Se solo fossi consacrato su un trono”. Questa fu la mia prima
aspirazione, ed è stata realizzata. La seconda fu: “Se solo incontrassi
un Arahant completamente illuminato durante la mia vita”. Ed essa è
stata realizzata. La terza fu: “Se solo fossi in grado di onorare quel
Beato”. Ed essa è stata realizzata. La quarta fu: “Se solo il Beato
m’insegnasse il Dhamma”. Ed essa è stata realizzata. La quinta fu: “Se
solo fossi in grado di comprendere il Dhamma del Beato”. E anch’essa è
stata realizzata».

«Magnifico, Signore, magnifico, Signore! Il Dhamma è stato chiarito in
molti modi ... Signore, il Beato mi accolga come suo seguace che si è
recato da lui per prendere rifugio finché durerà il mio respiro. Ora,
Signore, che il Beato con il Saṅgha dei bhikkhu accetti da me il pasto
di domani». 

Il Beato accettò in silenzio. Quando il re vide che il Beato aveva
accettato, si alzò dal posto in cui sedeva e, dopo avergli prestato
omaggio, se ne andò girandogli a destra.

Quando la notte fu trascorsa, egli aveva preparato buon cibo di vario
genere e annunciò: «È ora, Grande Monaco, il pasto è pronto».

Poiché era mattino, il Beato si vestì, prese la ciotola e la veste
superiore, andò a Rājagaha con un gran seguito di bhikkhu, con un
migliaio di bhikkhu, con tutti quelli che prima erano stati asceti dai
capelli intrecciati. Quando andarono, Sakka, Sovrano degli Déi, assunse
la forma di un giovane brāhmaṇa e si mise in piedi dinanzi al Beato, e
levò le palme giunte delle sue mani di fronte al Saṅgha guidato dal
Beato, cantando queste strofe:

____
Venne a Rājagaha, controllato e libero, +
e con lui quelli che prima erano stati asceti dai capelli intrecciati. +
Controllato e libero, luminoso come un aureo gioiello +
il Beato entrò a Rājagaha.

Venne a Rājagaha, acquietato e libero ... +
Venne a Rājagaha, affrancato e libero ... +
Venne a Rājagaha, realizzato e libero ...

Egli con dieci modi di vita e con dieci poteri, +
vedendo dieci cose, possessore di dieci fattori,footnote[I «dieci modi
di vita» sono i dieci modi di vita degli
Esseri Nobili (D. 33). Per i dieci poteri, si veda il cap. 11, p. 206.
Le «dieci cose» sono i dieci tipi di azioni, salutari e non salutari (si
veda ad esempio M. 9). I «dieci fattori» sono i dieci stati dell’adepto.
Si veda anche il Commentario.] +
e forte di un seguito di mille, +
il Beato entrò a Rājagaha.
____

Quando la folla vide Sakka, Sovrano degli Déi, disse: «Il giovane
brāhmaṇa è attraente, bello e pieno di grazia. Chi è?». Quando ciò fu
detto, egli si rivolse a essa in strofe:

[verse]
____
Egli è un santo, sempre controllato +
e purificato, senza pari +
in tutto il mondo, sublime, realizzato, +
e io sono un suo seguace.
____

Allora il Beato andò nella dimora del re Bimbisāra, si mise a sedere nel
posto preparatogli, circondato dal Saṅgha dei bhikkhu. Con le sue stesse
mani il re servì e soddisfece il Saṅgha guidato dal Beato. Quando il
Beato aveva finito di mangiare e non teneva più la ciotola in mano, il
re si mise a sedere in terra da un lato. Quando lo ebbe fatto, egli
pensò: «Dove potrebbe vivere il Beato? In un posto che non sia né troppo
lontano dalla città né troppo vicino, con una via d’ingresso e una via
d’uscita, accessibile per la gente che lo cerca, non frequentato di
giorno e tranquillo di notte, senza voci che lo disturbino, con
un’atmosfera di separatezza, dove si può rimanere nascosti dalla gente,
favorevole al ritiro?». Poi pensò: «Questo nostro parco, il Boschetto di
Bambù, ha tutte queste qualità. E se io donassi il Boschetto di Bambù al
Saṅgha guidato dal Buddha?».

Allora egli prese una caraffa d’oro e dedicò il Boschetto di Bambù al
Beato mediante il lavacro delle mani, dicendo: «Signore, dono questo
Boschetto di Bambù al Saṅgha dei bhikkhu guidato dal Buddha».

Il Beato accettò il parco. Poi, quando ebbe istruito, esortato,
risvegliato e incoraggiato con un discorso di Dhamma Seniya Bimbisāra,
re di Magadha, si alzò dal posto in cui sedeva e se ne andò.

[.suttaref]
_Vin. Mv. 1:22_
