= I due discepoli eminenti
:chapter-number: 5

[.voice]
*Seconda voce.* Avvenne questo. L’asceta itinerante Sañjaya si trovava a
Rājagaha con un gran seguito di asceti itineranti, con duecentocinquanta
asceti itineranti. E Sāriputta e Moggallāna stavano vivendo la vita
religiosa sotto l’asceta itinerante Sañjaya. Avevano fatto questo patto:
chi di loro avesse per primo raggiunto Ciò Che Non Muore avrebbe
informato l’altro. Ora, essendo mattino, il venerabile Assaji si vestì,
prese la ciotola e la veste superiore, e si recò a Rājagaha per la
questua. Il suo portamento ispirava fiducia e, se andava avanti o
indietro, se guardava davanti o di lato, se si piegava o si distendeva,
teneva gli occhi bassi e si muoveva con grazia. L’asceta itinerante
Sāriputta lo vide mentre faceva la questua a Rājagaha, e pensò: «Nel
mondo ci sono degli Arahant, quelli che posseggono il sentiero degli
Arahant, e questo bhikkhu è uno di loro. E se io mi avvicinassi a lui e
chiedessi sotto chi conduce la vita religiosa, chi è il suo maestro,
quale Dhamma professa?». Poi pensò: «Non è questo il momento di fare
domande a questo bhikkhu, mentre fa la questua camminando fra le case. E
se io lo seguissi per risalire a quel che hanno scoperto i cercatori?».

Quando il venerabile Assaji ebbe terminato il giro per la questua,
lasciò Rājagaha con il cibo ottenuto in elemosina. Allora l’asceta
itinerante Sāriputta si avvicinò a lui e lo salutò. Terminati i formali
doveri di cortesia, si mise in piedi da un lato e gli disse: «Amico, le
tue facoltà sono rasserenate, il colore della tua pelle è chiaro e
luminoso. Sotto chi hai praticato la vita religiosa? Chi è il tuo
maestro? Quale Dhamma professi?».

«C’è il Grande Monaco, amico, il figlio dei Sakya, che ha abbandonato un
clan dei Sakya per la vita religiosa. Ho abbracciato la vita religiosa
sotto il Beato. Egli è il mio maestro. È il Dhamma di quel Beato che io
professo».

«Che cosa dice il venerabile maestro, che cosa insegna?».

«Ho abbracciato la vita religiosa solo da poco, amico, sono appena
giunto a questo Dhamma e a questa Disciplina, non posso insegnarti il
Dhamma nei dettagli. Ti dirò, però, il suo significato in breve».

Allora Sāriputta disse: «E sia, amico».

[quote]
____
Di' pure molto o poco, come ti sembra giusto, +
ma dimmi ora il significato. +
Perché ho bisogno solo del significato, +
non mi faccio alcun pensiero dei dettagli, ora.
____

Il venerabile Assaji offrì all’asceta itinerante Sāriputta tale schema:

[quote]
____
Il Perfetto ha detto la causa +
del sorgere condizionato delle cose, +
e anche quel che conduce alla loro cessazione: +
questa è la dottrina predicata dal Grande Monaco.
____

Quando l’asceta itinerante Sāriputta ascoltò quest’esposizione di
Dhamma, la pura, immacolata visione del Dhamma sorse in lui: tutto quel
che sorge deve cessare.

[quote]
____
Questa è la verità: anche se questo fosse tutto, +
tu hai raggiunto la condizione in cui non c’è dolore +
che noi per molte volte diecimila ere +
abbiamo lasciato passare inosservata.
____

L’asceta itinerante Sāriputta andò dall’asceta itinerante Moggallāna.
L’asceta itinerante Moggallāna lo vide arrivare. Gli disse: «Le tue
facoltà sono rasserenate, il colore della tua pelle è chiaro e luminoso.
Hai forse trovato Ciò Che Non Muore?». «Sì, amico, ho trovato Ciò Che
Non Muore». «Come hai fatto a trovarlo, amico?».

L’asceta itinerante Sāriputta raccontò quello che era avvenuto. Quando
l’asceta itinerante Moggallāna ascoltò quell’esposizione di Dhamma:

[quote]
____
Il Perfetto ha detto la causa +
del sorgere condizionato delle cose, +
e anche quel che conduce alla loro cessazione: +
questa è la dottrina predicata dal Grande Monaco.
____

La pura, immacolata visione del Dhamma sorse in lui: tutto quel che
sorge deve cessare.

[quote]
____
Questa è la verità: anche se questo fosse tutto, +
tu hai raggiunto la condizione in cui non c’è dolore +
che noi abbiamo lasciato passare inosservata +
per molte volte diecimila ere.
____

Allora Moggallāna disse: «Amico, andiamo dal Beato. Il Beato è il nostro
maestro».

«Però, amico, questi duecentocinquanta asceti itineranti che vivono qui
dipendono da noi, noi siamo il loro punto di riferimento. Prima devono
essere consultati. Loro faranno quello che ritengono giusto».

Insieme si recarono dagli asceti itineranti e dissero loro: «Amici, noi
stiamo andando dal Beato. Il Beato è il nostro maestro».

«Noi viviamo in dipendenza dai venerabili, sono loro il nostro punto di
riferimento. Se loro vanno a vivere la santa vita sotto il Grande
Monaco, anche noi faremo lo stesso».

Così, Sāriputta e Moggallāna andarono da Sañjaya l’asceta itinerante e
gli dissero quello che stavano per fare.

«Va bene così, amici, non andate. Guidiamo tutti e tre insieme questa
comunità».

Una seconda e una terza volta loro dissero la stessa cosa e ricevettero
la stessa risposta.

Allora Sāriputta e Moggallāna andarono con i duecentocinquanta asceti
itineranti al Boschetto di Bambù. Sangue bollente sgorgò dalla bocca
dell’asceta itinerante Sañjaya.

Il Beato vide da lontano che arrivavano Sāriputta e Moggallāna. Quando
li vide, disse ai bhikkhu: «Stanno arrivando questi due amici, Kolita e
Upatissa. Questi due saranno i miei discepoli eminenti, una coppia di
buon auspicio».

[quote]
____
Fu allora che il Maestro li annunciò – +
loro, che erano già liberati +
nel campo della profonda conoscenza, +
nella suprema distruzione della materia dell’esistenza, +
già prima che raggiungessero il Boschetto di Bambù – +
dicendo: «Stanno arrivando questi due amici, +
Kolita e Upatissa. +
Questi due saranno i miei discepoli eminenti, +
una coppia di buon auspicio».
____

Sāriputta e Moggallāna si avvicinarono al Beato e si prostrarono ai suoi
piedi. Gli dissero: «Signore, desideriamo abbracciare la vita religiosa
sotto il Beato, e l’ammissione».

«Venite bhikkhu», disse il Beato. E aggiunse: «Il Dhamma è ben
proclamato. Vivete la santa vita per completare la fine della
sofferenza». E quella fu l’ammissione di quei venerabili.

Ora, in quel tempo, un certo numero di ben noti uomini di rango di
Magadha stavano conducendo la vita santa sotto il Beato. La gente
disapprovava, mormorava e protestava: «Il monaco Gotama sta causando
assenza di prole e vedovanza, sta distruggendo le stirpi. Già un
migliaio di asceti dai capelli intrecciati ha abbracciato la vita
religiosa, come pure questi duecentocinquanta asceti itineranti, e ora
anche questi ben noti uomini delle stirpi di Magadha sono andati a
condurre la santa vita sotto il monaco Gotama!». Quando la gente vedeva
i bhikkhu, li sbeffeggiava con queste strofe:

[quote]
____
Gotama il monaco è arrivato +
alla Fortezza di Magadha, +
ha portato via tutto il gruppo di Sañjaya. +
Chi porterà via oggi?
____

I bhikkhu udirono queste parole, andarono dal Beato e gliele riferirono.
Egli disse: «È una cosa che non durerà a lungo. Durerà solo sette
giorni. Al termine di sette giorni cesserà. Così, quando la gente vi
sbeffeggia con quelle strofe, potete rispondere rimproverandola con
queste strofe:

[quote]
____
Sono portati dal Dhamma, loro che sono anche +
Grandi Eroi ed Esseri Perfetti. +
E perciò, giacché sono portati dal Dhamma, +
per quale ragione essere gelosi?
____

Così, quando la gente li sbeffeggiava, loro rispondevano
rimproverandoli. Allora la gente cominciò a pensare: «I monaci figli del
Sakya sono portati dal Dhamma, sembra, non vanno contro il Dhamma». E la
cosa durò sette giorni, e al termine di sette giorni cessò.

[.suttaref]
_Vin. Mv. 1:23-24_

[.narrator]
*Secondo narratore.* L’Anziano Moggallāna ottenne la condizione di
Arahant sette giorni dopo essersi recato dal Buddha. L’Anziano Sāriputta
trascorse invece due settimane a passare in rassegna e ad analizzare con
la visione profonda tutti i livelli della coscienza. Come divenne un
Arahant è narrato nel modo seguente.

[.voice]
*Prima voce.* Così ho udito. Mentre il Beato soggiornava a Rājagaha, nella
Caverna Sūkarakhatā, l’asceta itinerante Dīghanakha andò da lui e
scambiò i saluti. Poi disse: «La mia teoria e il mio punto di vista è
questo, Maestro Gotama: “Niente mi piace”».

«Questo è il tuo punto di vista, Aggivessana, “Niente mi piace”: nemmeno
questo punto di vista ti piace?».

«Anche se questo mio punto di vista mi piacesse, tutto sarebbe uguale,
Maestro Gotama, tutto sarebbe uguale».

«Al mondo sono in molti a dire “tutto sarebbe uguale”, e non solo non
riescono ad abbandonare questo punto di vista, ma si attaccano pure ad
altri punti di vista. E al mondo sono pochi a dire “tutto sarebbe
uguale”, e abbandonano questo punto di vista senza attaccarsi ad altri
punti di vista».

«Alcuni monaci e brāhmaṇa hanno questa teoria e punto di vista “Tutto mi
piace”, altri “Niente mi piace”, e altri ancora “Qualcosa mi piace” e
“Qualcosa non mi piace”. Ora, il punto di vista di quelli la cui teoria
e punto di vista è “Tutto mi piace” è prossimo alla brama, alla
schiavitù, all’assaporare, all’adesione, all’attaccamento. Il punto di
vista di quelli la cui teoria e punto di vista è, però, “Niente mi
piace” è prossimo alla non-brama, alla non-schiavitù, al non-assaporare,
alla non-adesione, al non-attaccamento».

L’asceta itinerante Dīghanakha osservò: «Il Maestro Gotama loda il mio
punto di vista, il Maestro Gotama loda il mio punto di vista».

«E il punto di vista di quelli la cui teoria e punto di vista è
“Qualcosa mi piace” e “Qualcosa non mi piace” è, in ciò che a loro
piace, prossimo alla brama, alla schiavitù, all’assaporare,
all’adesione, all’attaccamento, mentre, in ciò che a loro non piace, è
prossimo alla non-brama, alla non-schiavitù, al non-assaporare, alla
non-adesione, al non-attaccamento».

«Un uomo saggio che, tra questi monaci e brāhmaṇa la cui teoria e punto
di vista è “Tutto mi piace”, farebbe questa considerazione: “Il mio
punto di vista è che tutto mi piace”. Se però lo fraintendessi e
insistessi dicendo: “Solo questo è vero, qualsiasi altra cosa è
sbagliata”, allora mi scontrerei con entrambi gli altri gruppi: con i
monaci e brāhmaṇa la cui teoria e punto di vista è “Niente mi piace” e
con i monaci e brāhmaṇa la cui teoria e punto di vista è “Qualcosa mi
piace” e “Qualcosa non mi piace”. Mi scontrerei con questi due gruppi. E
quando c’è scontro, ci sono dispute, ci sono discussioni. E quando ci
sono discussioni, c’è danno».

«Quando presagisce questo, egli abbandona quel punto di vista senza
attaccarsi a qualche altro punto di vista. È in questo modo che tali
punti di vista vengono abbandonati, lasciati».

[.narrator]
*Secondo narratore.* Lo stesso è ripetuto per l’“uomo saggio” il cui
punto di vista è “Niente mi piace”, “Qualcosa mi piace” e “Qualcosa non
mi piace”.

[.voice]
*Prima voce.* Ora, Aggivessana, questo corpo che ha una forma materiale
consiste di quattro grandi entità: terra, acqua, fuoco e aria. È
procreato da madre e padre, e cresciuto con riso e pane. Esso è soggetto
all’impermanenza, a essere unto e sfregato, alla dissoluzione e alla
disintegrazione. Deve essere considerato impermanente, come una
sofferenza, come una piaga, come una freccia, come una calamità, come
un’afflizione, come un estraneo, come in via di disintegrazione, come
vuoto, come non-sé. Quando è considerato in questo modo, si abbandona
ogni desiderio e amore per esso e l’abitudine di trattarlo come base
necessaria di tutte le sue inferenze».footnote:[«Abitudine di trattarlo
(il corpo fisico) come base di tutte
le sue inferenze» (_kāyanvayatā_) rinvia al modo di pensare secondo il
quale il corpo fisico è una realtà basilare, una verità empirica, per
poi costruire su tale assunto un sistema (il materialismo, nei fatti, la
visione fisiologica della mente, o la visione della coscienza come un
“epifenomeno” della materia). Sia questo punto di vista sia il suo
opposto, che considera la materia come subordinata alla mente, sono
discusse all’inizio di M. 36.]

«Ci sono tre generi di sensazioni: sensazione piacevole, sensazione
dolorosa e sensazione-né-dolorosa-né-piacevole. Quando un uomo prova una
di queste tre, non prova le altre due. La sensazione piacevole è
impermanente, formata, originata in dipendenza di qualcos’altro,
soggetta a esaurirsi, dimuinuire, svanire e cessare. E così è pure per
la sensazione dolorosa e per la sensazione neutra».

«Quando un ben istruito nobile discepolo vede questo, diventa
disincantato nei riguardi della sensazione piacevole e della sensazione
dolorosa e della sensazione neutra. Diventando disincantato, la sua
brama svanisce. Con lo svanire della brama, il suo cuore è liberato.
Quando il suo cuore è liberato, giunge la conoscenza: “È liberato”. Egli
comprende: “La nascita è distrutta, la santa vita è stata vissuta, quel
che doveva essere fatto è stato fatto, non ci sarà altra rinascita”. Un
bhikkhu con il cuore così liberato non parteggia per nessuno, non
disputa con nessuno e utilizza, ma senza fraintendimenti, il linguaggio
corrente del mondo».

Per tutto il tempo, il venerabile Sāriputta era stato in piedi dietro il
Beato per fargli aria con un ventaglio. Allora pensò: «Il Beato, il
Sublime, sembra che parli per diretta conoscenza dell’abbandono e della
rinuncia a queste cose». E quando pensò in questo modo il suo cuore fu
liberato dalle contaminazioni mediante il non-attaccamento.

Nel frattempo la pura, immacolata visione del Dhamma sorse nell’asceta
itinerante Dīghanakha ... Egli disse: «... Prendo rifugio nel Maestro
Gotama, e nel Dhamma e nel Saṅgha».

[.suttaref]
_M. 74_

[.narrator]
*Secondo narratore.* In questo tempo il re Suddhodana mandò Kāludāyī, il
figlio di uno dei suoi ministri, a Rājagaha al fine di persuadere suo
figlio, il Buddha, a visitare Kapilavatthu. Prima di comunicare la sua
missione, Kāludāyī divenne un bhikkhu. Alla fine della stagione fredda –
era la prima dopo l’Illuminazione – egli comunicò tuttavia la sua
missione con questi versi, miranti a persuadere il Buddha a mettersi in
viaggio.

[quote, role=cantor]
____
*Cantore*

Signore, ci sono alberi che ora ardono come brace, +
sperando nei frutti, hanno lasciato cadere i loro verdi veli +
e bruciano audacemente con una fiamma scarlatta: +
è l’ora, Grande Eroe, Degustatore della Verità. +
Alberi pienamente in fiore che sono una delizia per la mente, +
effondono profumi ai quattro venti, +
le loro foglie hanno lasciato cadere, in attesa dei frutti: +
è l’ora, o Eroe, di partire da qui. +
Per i viaggi ora, Signore, la stagione è piacevole +
perché non è troppo freddo né troppo caldo. +
Consentite ai Sakya e ai Koliya di vedervi +
rivolto a occidente, mentre attraversate il fiume
Rohiṇī.footnote:[Secondo il Commentario
alle _Theragāthā_, il fiume Rohiṇī
scorre verso sud e separa, a ovest, il territorio dei Sakya da quello
dei Koliya, che è a est. Rājagaha si trova molto più a sud, oltre il
Gange, così che chi avesse viaggiato da questa città attraversando il
Vajji e poi il territorio dei Koliya, avrebbe attraversato il fiume
guardando verso occidente.]

I campi sono arati con speranza, +
i semi sono piantati con speranza, +
i commercianti salpano con speranza +
attraverso il mare per la ricchezza: +
possa la speranza che nutro +
avere successo!

Ancora e poi ancora si piantano i semi, +
ancora e poi ancora il Divino Sovrano invia la pioggia, +
ancora e poi ancora i contadini arano i campi, +
ancora e poi ancora il regno miete il grano, +
ancora e poi ancora i mendicanti chiedono l’elemosina, +
ancora e poi ancora i generosi offrono i loro doni, +
ancora e poi ancora l’offerta dei loro doni +
ancora e poi ancora fa trovare loro un posto in paradiso.

Quale che sia il lignaggio nel quale è nato, +
un Eroe, detentore della vera comprensione, +
nobilita le sette precedenti generazioni – +
Tu, più grande degli dèi, lo sento, puoi fare ben di più, +
perché la parola “Perfetto” si è fatta vera in te.
____

[.suttaref]
_Thag. 527-33_

[.voice]
*Seconda voce.* Allorché il Beato era rimasto a Rājagaha per tutto il
tempo che volle, si mise in viaggio per Kapilavatthu. Viaggiando per
tappe, alla fine vi arrivò, e rimase nel Parco di Nigrodha. Ora, quando
fu mattino, il Beato si vestì, prese la ciotola e la veste superiore, si
recò alla residenza di Suddhodana il Sakya, e si mise a sedere nel posto
preparatogli.

[.suttaref]
_Vin. Mv. 1:54_

[.narrator]
*Primo narratore.* Il racconto di questa visita offerto dal Canone è
breve, perfino lapidario. Perciò, prima di continuare con tale racconto,
alcuni dettagli tratti dal Commentario renderanno più chiara la
situazione.

[.narrator]
*Secondo narratore.* Quando il Buddha arrivò a Kapilavatthu, gli uomini
del lignaggio Sakya, ben noti per il loro orgoglio, non erano inclini a
prestargli omaggio. A quel punto egli compì il miracolo doppio, causando
il simultaneo comparire di getti di fuoco e di acqua da tutte le sue
membra. A ciò seguì la predicazione della Storia della Nascita di
Vessantara. Dopo il primo pasto cerimoniale offertogli nel palazzo di
suo padre, egli predicò la Storia della Nascita di Dhammapāla, e il re
ottenne il terzo, o penultimo, livello di realizzazione. Egli morì come
Arahant circa quattro anni dopo. Nel contempo la regina, Mahāpajāpati,
madre del principe Nanda e zia del Buddha, ottenne il primo livello di
realizzazione. Quello stesso giorno era stato scelto per la celebrazione
dell’imminente matrimonio del principe Nanda, unico figlio della regina
Mahāpajāpati. Ora, quando il Buddha si alzò per andar via, diede al
principe Nanda la sua ciotola e si avviò. Non sapendo che cosa fare, il
principe Nanda lo seguì con la ciotola, e quando si incamminò, la sua
futura sposa gli disse: «Torna presto, principe». Quando arrivarono nel
luogo in cui il Buddha dimorava, il Buddha gli chiese se volesse
lasciare la casa famigliare. Più per venerazione che per propensione,
egli accettò. Al settimo giorno il Buddha consumò di nuovo il suo pasto
nel palazzo del padre.

[.narrator]
*Primo narratore.* Ora continua il racconto canonico.

[.voice]
*Seconda voce.* La madre del principe Rāhula disse al principe Rāhula:
«Questo è tuo padre, Rāhula. Vai a chiedergli la tua eredità». Allora il
principe Rāhula andò dal Beato e si mise in piedi di fronte a lui: «Il
tuo aspetto è gradevole, monaco».

Allora il Beato si alzò dal posto in cui sedeva e se ne andò. Il
principe Rāhula andò dietro al Beato, dicendo: «Dammi la mia eredità,
monaco, dammi la mia eredità, monaco».

Allora il Beato disse al venerabile Sāriputta: «Sāriputta, ammettilo
alla vita religiosa».footnote:[_Pabbajjā_: l’ordinazione di un novizio (Nyp.).]

«Come faccio ad ammetterlo alla vita religiosa, Signore?». Il Beato,
allora, per questo motivo e per questa occasione offrì un discorso di
Dhamma e si rivolse ai bhikkhu in questo modo: «Consento che
l’ammissione alla vita religiosa sia impartita mediante i Tre Rifugi.
L’ammissione deve però avvenire in questo modo. Prima devono essere
rasati i capelli e la barba, e indossata la veste ocra. Poi, chi sta per
essere ammesso deve ripiegare la veste superiore su una spalla, deve
prestare omaggio ai piedi del bhikkhu, si deve inginocchiare e, con le
palme delle mani giunte, deve dire: “Prendo rifugio nel Buddha, prendo
rifugio nel Dhamma, prendo rifugio nel Saṅgha. Per la seconda volta ...
Per la terza volta ...”».

Allora il venerabile Sāriputta impartì l’ammissione alla vita religiosa
al principe Rāhula. Suddhodana il Sakya andò dal Beato e, dopo avergli
prestato omaggio, si mise a sedere da un lato. Egli disse: «Chiedo un
favore al Beato».

«Gli Esseri Perfetti hanno lasciato dietro di loro i favori, Gotama».

«Si tratta di una cosa possibile e non riprovevole, Signore».

«Chiedi, allora, Gotama».

«Signore, ho provato non poco dolore quando il Beato se ne andò di casa
per abbracciare la vita religiosa. Poi fu la volta di Nanda. Rāhula è
troppo. L’amore per i nostri figli taglia la pelle esterna. Dopo aver
tagliato la pelle esterna, taglia la pelle interna. Dopo aver tagliato
la pelle interna, taglia le carni. Dopo aver tagliato le carni, taglia i
tendini. Dopo aver tagliato i tendini, taglia le ossa. Dopo aver
tagliato le ossa, raggiunge il midollo e là resta. Signore, sarebbe bene
che i venerabili non impartissero l’ammissione alla vita religiosa senza
il consenso dei genitori».

Il Beato istruì, esortò, risvegliò e incoraggiò Suddodhana il Sakya con
un discorso di Dhamma. Allora Suddhodana il Sakya si alzò dal suo
seggio, e dopo aver prestato omaggio al Beato, se ne andò girandogli a
destra.

Il Beato, allora, per questo motivo e per questa occasione offrì un
discorso di Dhamma, e si rivolse ai bhikkhu in questo modo: «Bhikkhu,
non dovete ammettere dei bambini alla vita religiosa senza il consenso
dei genitori. Se qualcuno lo fa, commette un’infrazione per atto errato.

[.suttaref]
_Vin. Mv. Kh. 1:54_

[.narrator]
*Primo narratore.* Secondo la tradizione, la decisione del cugino del
Buddha, Ānanda, e di altri di lasciare la casa famigliare per la vita
religiosa avvenne al tempo di questa visita. Il Buddha era già andato
via da Kapilavatthu, ma si trovava ancora nei territori a nord di
Kosala. Essa dovette verificarsi in corrispondenza dei due seguenti
episodi, benché non vi siano precise indicazioni per collocarla.

[.voice]
*Prima voce.* Così ho udito. Una volta il Beato stava viaggiando
attraverso la regione di Kosala con il venerabile Nāgasamāla, il suo
monaco attendente. Il venerabile Nāgasamāla vide che la strada si
biforcava. Egli disse al Beato: «Signore, questa è la direzione, andiamo
in quella direzione».

Quando ciò fu detto, il Beato replicò: «Questa è la direzione,
Nāgasamāla. Andiamo in questa direzione».

Una seconda e una terza volta il venerabile Nāgasamāla disse la stessa
cosa e ricevette la stessa risposta. Poi poggiò la ciotola e la veste
superiore del Beato in terra e se ne andò. Quando percorse quella strada
comparvero dei ladroni che lo percossero con calci e pugni, gli ruppero
la ciotola e strapparono la veste superiore fatta di toppe. In seguito
tornò dal Beato con la ciotola rotta e la veste superiore fatta di toppe
strappata, e gli raccontò quello che era avvenuto. Conoscendo il
significato di quest’avvenimento, il Beato esclamò queste parole:

[quote]
____
Un saggio e un folle +
camminavano e vivevano in compagnia. +
Per bere il latte le gru lasciano le acque paludose: +
i saggi abbandonano quel che sanno essere male.
____

[.suttaref]
_Ud. 8:7_

Ora, quando il Beato risiedeva nella regione di Kosala, ad Araññakuṭika,
alle pendici dell’Himalaya, mentre era in ritiro da solo sorse in lui
questo pensiero: «È possibile governare senza uccidere e ordinare
esecuzioni capitali, senza confiscare e sequestrare, senza addolorarsi e
causare dolori, in altre parole, governare rettamente?». Allora Māra il
Malvagio nella sua mente fu consapevole del pensiero sorto nella mente
del Beato, e andò da lui e disse: «Che il Beato governi, che il Sublime
governi senza uccidere e ordinare esecuzioni capitali, senza confiscare
e sequestrare, senza addolorarsi e causare dolori, in altre parole,
governi rettamente».

«Malvagio, qual è il fine per cui ti rivolgi a me in questo modo?».
«Signore le quattro basi del successo [spirituale]footnote:[Le “quattro
basi per il successo” (o vie per il potere) sono
descritte come «la base per il successo che ha concentrazione fondata sul
desiderio-di-agire e risolutezza motivata dallo sforzo-controllato» (M. 16).
Questa è la prima. Per le altre tre, sostituire, rispettivamente, “energia”,
“(naturale purezza della) mente”, e “investigazione” al “desiderio-di-agire”.
Esse rappresentano i quattro tipi di approccio dello sviluppo, da regolare sulla
base delle avversioni individuali.] sono state costantemente mantenute
in essere e praticate dal Beato, rese
veicolo e base, sono state fondate, consolidate e propriamente
intraprese. E così, Signore, se il Beato decidesse: “Che l’Himalaya, re
delle montagne, diventi d’oro” esso diventerebbe una montagna d’oro».

[quote]
____
E se tutta quella montagna fosse di oro giallo, +
il doppio non basterebbe a soddisfare i desideri di un uomo. +
Sapere questo è agire di conseguenza. +
Un uomo che ha visto la sofferenza e la sua fonte +
come potrebbe volgersi verso i desideri sensoriali? +
Sapendo che è questa sostanza della rinascita +
a legarlo al mondo, un uomo +
non può far altro che addestrarsi per liberarsene.
____

Allora Māra il Malvagio seppe: «Il Beato mi conosce, il Sublime mi
conosce». Triste e deluso, subito sparì.

[.suttaref]
_S. 4:20_

[.voice]
*Seconda voce.* Avvenne questo. Mentre il Beato soggiornava a Anupiyā –
una città dei Malla è chiamata Anupiyā – molti ben noti principi Sakya
abbracciarono la vita religiosa sotto il Beato. C’erano due fratelli,
Mahānāma il Sakya e Anuruddha il Sakya. Anuruddha era stato allevato tra
gli agi. Possedeva tre palazzi, uno per la stagione fredda, uno per la
stagione calda e un altro per quella delle piogge. Per quattro mesi era
intrattenuto nel palazzo per la stagione delle piogge da menestrelli,
tra i quali non c’era alcun uomo e non si recava mai nel piano inferiore
del palazzo.

Mahānāma pensò: «Molti ben noti principi Sakya hanno abbracciato la vita
religiosa sotto il Beato. Nella nostra famiglia, però, nessuno ha
lasciato la propria casa per abbracciare la vita religiosa. E se fossi
io a farlo, o Anuruddha?».

Andò allora da Anuruddha e gli disse quel che aveva pensato. Anuruddha
disse: «Io sono stato allevato tra gli agi. Non posso lasciare la nostra
casa per abbracciare la vita religiosa. Sarai tu a farlo».

«Vieni allora Anuruddha, ti istruirò nella vita famigliare. Un campo
deve essere prima arato, poi deve essere seminato, poi in esso si deve
condurre l’acqua, poi l’acqua deve essere drenata, poi bisogna estirpare
l’erba, poi deve essere mietuto il raccolto, poi questo va riunito e
ammucchiato, poi deve essere trebbiato, poi si deve rimuovere la paglia,
poi si deve eliminare la pula, poi si deve setacciarlo e poi lo si deve
immagazzinare. Ora, quando si è fatto tutto questo, bisogna poi farlo di
nuovo l’anno successivo, e l’anno dopo ancora. Il lavoro non finisce
mai. Non c’è fine per il lavoro».

«Quand’è che ci sarà una fine per il lavoro? Quando avremo mai modo di
gratificare i cinque lidi dei desideri sensoriali dei quali siamo dotati
e provvisti?».

«Mio caro Anuruddha, il lavoro non finisce mai, non c’è fine per il
lavoro. Nostro padre e nostro nonno sono morti entrambi quando il lavoro
non era ancora finito. Questo è ciò che devi sapere su questa vita
famigliare. Io lascerò la vita famigliare per abbracciare la vita
religiosa».

Anuruddha andò dalla madre e le disse: «Madre, desidero lasciare la vita
famigliare per abbracciare la vita religiosa. Per favore, accordami il
tuo permesso».

Quando questo fu detto, lei gli disse: «Voi due, figli miei, mi siete
cari e preziosi, non sgraditi. Qualora moriste, dovremmo perdervi contro
i nostri desideri. Perché allora, giacché siete ancora in vita, dovrei
darvi il permesso di lasciare la vita famigliare per abbracciare la vita
religiosa?». Lui lo chiese una seconda e una terza volta. Allora la
madre disse: «Mio caro Anuruddha, se Bhaddiya il regio Sakya che governa
i Sakya abbraccerà la vita religiosa, potrai farlo anche
tu».footnote:[Non è chiaro se la parola _rājā_ (qui resa con “che
governa”) applicata a Bhaddiya il Sakya significhi “re” (nel qual caso
implicita è la morte del re Suddhodana) o solo “reggente”. Qui è stata
seguita la collocazione dell’evento offerta dal Commentario.]

In quel tempo Bhaddiya il regio Sakya che stava governando i Sakya era
un amico di Anuruddha e sua madre aveva pensato: «Bhaddiya è un amico di
Anuruddha. Egli non è ansioso di lasciare la vita famigliare per
abbracciare la vita religiosa». Per questa ragione lei aveva parlato in
quel modo.

Allora Anuruddha andò da Bhaddiya e disse: «Che io abbracci o no la vita
religiosa dipende da te».

«Se che tu abbracci la vita religiosa dipende da me, che non sia più
così, allora. Tu ed io lo vogliamo ... puoi abbracciare la vita
religiosa quando vuoi».

«Vieni, lasciamo insieme la vita famigliare e abbracciamo la vita
religiosa».

«Io non posso. Farò qualsiasi altra cosa per te. Sarai tu ad abbracciare
la vita religiosa».

«Mia madre ha detto: “Mio caro Anuruddha, se Bhaddiya il regio Sakya che
governa i Sakya abbraccerà la vita religiosa, potrai farlo anche tu”. E
queste sono state le tue parole: “Se che tu abbracci la vita religiosa
dipende da me, che non sia più così, allora. Tu e io lo vogliamo ...
puoi abbracciare la vita religiosa quando vuoi”. Vieni, lasciamo insieme
la vita famigliare e abbracciamo la vita religiosa».

In quel tempo la gente era solita dire la verità, era solita essere di
parola. Bhaddiya disse ad Anuruddha: «Aspetta sette anni. Al termine dei
sette anni abbracceremo entrambi la vita religiosa».

«Sette anni sono troppi. Non posso aspettare sette anni».

«Aspetta sei anni. Al termine dei sei anni abbracceremo entrambi la vita
religiosa».

«Sei anni sono troppi. Non posso aspettare sei anni».

«Aspetta cinque anni ... quattro ... tre ... due anni ... un anno ...
sette mesi ... due mesi ... un mese ... Aspetta mezzo mese. Al termine
di mezzo mese abbracceremo entrambi la vita religiosa».

«Mezzo mese è troppo. Non posso aspettare mezzo mese».

«Aspetta sette giorni. Al termine di sette giorni abbracceremo entrambi
la vita religiosa. Così io posso tramandare il regno ai miei figli e
fratelli».

«Sette giorni non sono troppi. Aspetterò».

Allora Bhaddiya il regio Sakya, Anuruddha, Ānanda, Bhagu, Kimbila e
Devadatta, insieme a Upāli il barbiere, che era il settimo, partirono
alla testa di un quadruplice esercito come se si recassero – così erano
soliti fare – per una parata nel parco.footnote:[La data in cui l’Anziano
Ānanda abbracciò la vita religiosa
non è del tutto certa. I versi da lui pronunciati nel _Theragātā_
indicano un momento successivo.] Allorché ebbero
percorso una certa distanza, abbandonarono l’esercito. Poi
attraversarono il confine di un altro regno e lì lasciarono le loro
insegne. Le avvolsero in una veste e dissero a Upāli il barbiere:
«Upāli, faresti meglio a tornare indietro. Qui per te c’è abbastanza di
cui vivere».

Da parte sua, Upāli pensò: «Questi Sakya sono feroci. Per questo
potrebbero anche mettermi a morte, per essere stato complice
dell’abbandono della vita famigliare da parte dei principi. Così, questi
principi Sakya stanno abbandonando la vita famigliare per la vita
religiosa. Che fare?». Aprì il fagotto e appese le cose a un albero,
dicendo: «Colui che le trova le prenda in dono». Poi tornò indietro dai
principi Sakya. Quando lo videro arrivare, gli chiesero: «Perché sei
tornato?».

Lui raccontò l’accaduto e aggiunse: «E così sono tornato».

«Hai fatto bene a non tornare a casa, Upāli, perché i Sakya sono feroci.
Per questo avrebbero potuto anche metterti a morte, per essere stato
complice dell’abbandono della vita famigliare da parte dei principi
Sakya».

Allora i principi Sakya si recarono dal Beato con Upāli il barbiere e,
dopo avergli prestato omaggio, si misero a sedere da un lato. Dopo
averlo fatto, dissero al Beato: «Signore, siamo Sakya orgogliosi. Upāli,
il barbiere, ci ha assistiti per lungo tempo. Che il Beato lo ammetta
per primo alla vita religiosa, così da potergli prestare omaggio,
alzarci in piedi per lui e offrirgli saluti reverenziali e onori. Così,
l’orgoglio dei Sakya sarà umiliato in noi Sakya». Allora il Beato ammise
per primo Upāli il barbiere alla vita religiosa e poi i principi Sakya.

Fu durante questa stagione delle piogge che il venerabile Bhaddiya
conseguì le tre vere conoscenze. Nel venerabile Anuruddha sorse l’occhio
divino. Il venerabile Ānanda realizzò la fruizione di Chi è Entrato
nella Corrente. Devadatta ottenne i poteri sovrannaturali di un uomo
ordinario.

In quel tempo, ogni volta che il venerabile Bhaddiya si recava nella
foresta o ai piedi di un albero o in una stanza vuota, esclamava in
continuazione: «Oh beatitudine! Oh beatitudine!».

Alcuni bhikkhu andarono dal Beato e glielo riferirono, aggiungendo: «Non
pare ci siano dubbi, Signore, che il venerabile Baddhiya sia
insoddisfatto della santa vita. Forse sta ricordando la sua precedente
condizione di governante».

Allora il Beato lo mandò a chiamare e gli chiese se era vero.

«È così, Signore».

«Bhaddiya, che cosa ci trovi di buono, però, nel farlo?». «Prima,
Signore, quando la mia condizione era quella di un sovrano, c’erano
guardie ben appostate sia all’interno sia all’esterno del palazzo, sia
all’interno sia all’esterno della città e sia all’interno sia
all’esterno del distretto. Sebbene io fossi così custodito e protetto,
avevo paura, ero ansioso, sospettoso e preoccupato. Ora, però, Signore,
quando vado nella foresta o ai piedi di un albero o in una stanza vuota,
non ho più paura, non sono ansioso o sospettoso o preoccupato. Vivo a
mio agio, in tranquillità, dipendo dai doni altrui, con una mente simile
a quella di un cervo selvatico. Questo ci trovo di buono nel farlo».

Conoscendo il significato di ciò, il Beato esclamò queste parole:

[quote]
____
Colui che dentro di sé non ha più conflitti in agguato +
ha superato ogni genere di esistenza, +
perché egli è senza paura, beato, libero dal dolore. +
Nessuna divinità può gareggiare con la sua gloria.
____

[.suttaref]
_Vin. Cv. 7:1; cfr. Ud. 2:10_

[.voice]
*Prima voce.* Il venerabile Nanda, il fratellastro del Beato, indossò
degli abiti variopinti e ben stirati, si truccò gli occhi e prese una
ciotola lucente. Poi andò dal Beato e, dopo avergli prestato omaggio, si
mise a sedere da un lato. Quando lo ebbe fatto, il Beato gli disse:
«Nanda, non è opportuno che tu, un uomo di rango che ha lasciato la sua
casa e la vita famigliare per la vita religiosa, abbia indossato degli
abiti variopinti e ben stirati, ti sia truccato gli occhi e abbia preso
una ciotola lucente. Quel che è opportuno per te, un uomo di rango che
ha lasciato la sua casa e la vita famigliare per la vita religiosa, è
dimorare nella foresta, mangiare solo cibo ottenuto in elemosina,
indossare vesti cucite con panni scartati, e dimorare senza alcun
interesse per i desideri sensoriali».

[.suttaref]
_S. 21:8_

[.narrator]
*Secondo narratore.* Nel frattempo il novizio Rāhula, che ora aveva dieci
anni, viveva sotto le cure dell’Anziano Sāriputta ad Ambalaṭṭhikā, nei
pressi di Rājagaha, dove il Buddha tornò a tempo debito.

[.voice]
*Prima voce.* Così ho udito. Una volta il Beato soggiornava a Rājagaha,
nel Boschetto di Bambù, nel Sacrario degli Scoiattoli e il venerabile
Rāhula viveva ad Ambalaṭṭhikā. Il venerabile Rāhula lo vide arrivare,
preparò per lui un posto a sedere e dell’acqua per lavarsi i piedi. Il
Beato si mise a sedere nel posto preparatogli e si lavò i piedi. Poi il
venerabile Rāhula gli prestò omaggio e si mise a sedere da un lato. Il
Beato versò una piccola quantità d’acqua nel mestolo e rivolse al
venerabile Rāhula queste parole: «Rāhula, vedi questo po’ d’acqua nel
mestolo?».

«Sì, Signore».

«Se le persone non fanno attenzione a evitare di mentire
intenzionalmente, altrettanto poco di buono vi è in loro».

Allora il Beato gettò via quella piccola quantità d’acqua, e chiese:
«Rāhula, vedi quel po’ d’acqua che ho gettato via?».

«Sì, Signore».

«Se le persone non fanno attenzione a evitare di mentire
intenzionalmente, quel che di buono che c’è in loro è gettato via in
questo modo».

Allora il Beato capovolse il mestolo e chiese: «Rāhula, vedi questo
mestolo capovolto?».

«Sì, Signore».

«Se le persone non fanno attenzione a evitare di mentire
intenzionalmente, quel che di buono v’è in loro è trattato in questo
modo».

Poi il Beato rimise il mestolo dritto e chiese: «Rāhula, vedi questo
mestolo completamente vuoto?».

«Sì, Signore».

«Se le persone non fanno attenzione a evitare di mentire
intenzionalmente, loro sono allo stesso modo vuoti di bene. Ora, Rāhula,
supponiamo che ci sia un elefante reale con le zanne lunghe come le aste
di un carro, del tutto cresciuto in statura, molto addestrato e ben
abituato a combattere, e che in battaglia usi le sue zampe anteriori e
le sue zampe posteriori, la parte anteriore del suo corpo e la parte
posteriore del suo corpo, la sua testa e i suoi orecchi e le sue zanne,
e tuttavia tenga indietro la proboscide. L’uomo che sta dietro di lui
penserebbe: “Benché faccia uso di tutte le sue membra, tiene indietro la
sua proboscide, e perciò non ha ancora offerto la sua vita al re”. Però,
se l’elefante usasse tutte le sue membra e anche la sua proboscide,
l’uomo che sta dietro di lui penserebbe: “Usa tutte le sue membra e
anche la sua proboscide, e perciò ha offerto la sua vita al re, non ha
più bisogno di essere addestrato”. Allo stesso modo, Rāhula, se le
persone non fanno attenzione a evitare di mentire intenzionalmente, di
loro non dico che non hanno più bisogno di essere addestrate. Perciò,
Rāhula, devi addestrarti a non affermare mai il falso, neanche per
scherzo. A che cosa pensi che serva uno specchio, Rāhula?».

«Per vedere se stessi, Signore».

«Proprio nello stesso modo devi continuare a osservare le tue azioni, le
tue parole e i tuoi pensieri».

[.suttaref]
_M. 61_

[.narrator]
*Secondo narratore.* Il Buddha continuò impartendogli istruzioni
dettagliate su come esaminare ogni azione prima, durante e dopo che sia
stata compiuta, giudicandola non salutare qualora essa sia a danno
proprio o degli altri e di entrambi, oppure giudicandola salutare se non
lo è, modellando di conseguenza le azioni future.
