= Anāthapiṇḍika
:chapter-number: 6

[.narrator]
`Secondo Narratore.` Il Buddha trascorse la prima stagione delle piogge
dopo la sua Illuminazione a Benares. La seconda e la terza stagione le
trascorse a Rājagaha nel Boschetto di Bambù. È dopo questa terza
stagione delle piogge che comparve Anāthapiṇḍika, il Nutritore del
Povero.

[.voice]
`Seconda Voce.` Avvenne questo. Il Buddha, il Beato, in quel tempo
soggiornava a Rājagaha nel Boschetto di Bambù, e fino a quel momento non
si era pronunciato a proposito delle dimore dei bhikkhu. Loro vivevano
qui e là, nelle foreste, ai piedi di un albero, sotto rocce sporgenti,
in crepacci, in caverne, in carnai, in boscaglie, all’aperto, su mucchi
di paglia. Quando il mattino presto lasciavano questi posti ispiravano
fiducia se andavano o se tornavano, se guardavano davanti o di lato, se
si piegavano o si distendevano. Tenevano gli occhi bassi e si muovevano
con grazia.

In quel tempo un ricco mercante di Rājagaha visitò il parco. Egli li
vide comportarsi in questo modo e nel suo cuore sorse fiducia nei loro
riguardi. Li avvicinò e chiese: «Signori, se io costruissi delle dimore,
voi vivreste in esse?».

«Il Beato non ha accordato il suo permesso riguardo alle dimore».

«Allora, Signori, chiedete al Beato e riferitemi cosa ha detto». Loro ne
parlarono al Beato. Egli accordò il suo permesso e, dopo che lo abbe
fatto, lo dissero al mercante, che in un solo giorno fece costruire
sessanta dimore. Poi invitò il Beato e il Saṅgha per il pasto del giorno
seguente. Al termine del pasto offrì formalmente le dimore al Saṅgha.

La sorella del mercante era la moglie di Anāthapiṇḍika, che allora aveva
deciso di venire a Rājagaha per alcuni affari e altre cose ancora,
proprio in quel momento, quando il Saṅgha dei bhikkhu guidato dal Buddha
era stato invitato dal mercante per il giorno seguente. Il mercante
stava impartendo istruzioni ai suoi domestici e inservienti:
«Svegliatevi presto. Cucinate del brodo di riso, riso e salse. E dolci».

Anāthapiṇḍika pensò: «Prima, quando arrivavo, questo capofamiglia
metteva da parte tutte le sue faccende per darmi il benvenuto. Ora
sembra impegnato a dare istruzioni ai suoi inservienti. C’è qualche
matrimonio? O qualche grande cerimonia sacrificale? Oppure ha forse
invitato per domani Seniya Bimbisāra, re di Magadha, con tutto il suo
seguito?».

Quando il mercante ebbe finito di impartire istruzioni ai suoi
inservienti, andò da Anāthapiṇḍika e gli diede il benvenuto. Poi, dopo
che si fu seduto al suo fianco, Anāthapiṇḍika gli raccontò i suoi
pensieri. Egli rispose: «Non c’è alcun matrimonio e neanche è stato
invitato il re con tutto il suo seguito. C’è però una grande cerimonia
sacrificale: ho invitato per domani il Saṅgha dei bhikkhu guidati dal
Buddha, l’Illuminato».

«Hai detto il Buddha?».

«Ho detto il Buddha».

«Hai detto il Buddha?».

«Ho detto il Buddha».

«Hai detto il Buddha?».

«Ho detto il Buddha».

«Questo evento, “il Buddha, il Buddha” è difficile che accada nel mondo.
È possibile andare e vedere il Beato, realizzato e completamente
illuminato, ora, in questo momento?».

«Non è questo il momento per andare e vederlo. Lo potrai vedere
domattina presto».

Allora Anāthapiṇḍika pensò: «Domattina presto potrò vedere un Beato,
realizzato e completamente illuminato».

Si mise disteso pensando al Buddha. Durante la notte si alzò tre volte,
immaginando che fosse l’alba. Poi andò alla Porta di Sīvaka. Degli
esseri non-umani aprirono la porta. Appena fu uscito dalla città, lasciò
la luce dietro di sé e davanti a lui ci fu l’oscurità. In lui sorsero
paura, sgomento e orrore. Voleva tornare indietro, ma lo spirito
invisibile di Sīvaka si fece sentire:

Cento elefanti, cento cavalli, +
Cento carri trainati da mule, +
centomila fanciulle adornate di gemme +
e orecchini: tutte queste cose non sono nemmeno degne della +
sedicesima parte di un passo in avanti, adesso.

«Vai avanti capofamiglia, vai avanti. È meglio che tu vada avanti invece
che indietro».

Quando quello spirito lo ebbe detto per la terza volta, lasciò
l’oscurità dietro di sé e davanti a lui ci fu la luce. In lui cessarono
paura, sgomento e orrore. Egli si recò allora nel Fresco Boschetto ove
il Buddha si trovava. In quell’occasione il Beato si era alzato presto,
verso l’alba, e stava facendo la meditazione camminata all’aperto. Vide
che Anāthapiṇḍika stava arrivando. Quando lo vide, smise di camminare e
si mise a sedere nel posto preparatogli. Quando lo ebbe fatto, disse ad
Anāthapiṇḍika: «Vieni Sudatta».

Anāthapiṇḍika pensò: «Si è rivolto a me chiamandomi per nome!» e fu
felice e pieno di speranza. Andò dal Beato e si prostrò ai suoi piedi, e
disse: «Mi auguro che il Beato abbia dormito bene».

[verse]
____
Un vero brāhmaṇafootnote:[Un’espressione che
indica un Arahant (BB.).] dorme sempre bene. +
Chi ha raggiunto il pieno Nibbāna, +
i desideri sensoriali lo lasciano intatto, +
sereno, privo di sostanza per l’esistenza. +
Ha respinto ogni attaccamento, +
Non ci sono conflitti nel suo cuore. +
Dorme beato chi è in pace +
con la pace fondata nella mente.
____

Allora il Beato impartì ad Anāthapiṇḍika un insegnamento progressivo.
Mentre Anāthapiṇḍika stava lì seduto, sorse in lui la pura, immacolata
visione del Dhamma: tutto quel che sorge deve cessare. Egli divenne
indipendente dagli altri nella Dispensazione del Maestro. Disse:
«Magnifico, Signore! … A partire da oggi che il Beato mi accolga come
suo seguace che si è recato da lui per prendere rifugio finché durerà il
mio respiro. Signore, che il Beato con il Saṅgha accetti il pasto di
domani da me».

Il Beato accettò in silenzio. Poi, sapendo che il Beato aveva accettato,
si alzò dal posto in cui sedeva e, dopo aver prestato omaggio al Beato,
se ne andò girandogli a destra.

Il ricco mercante di Rājagaha sentì dire: «Sembra che il Saṅgha dei
bhikkhu guidato dal Buddha sia stato invitato da Anāthapiṇḍika». Perciò
egli disse ad Anāthapiṇḍika: «Il Saṅgha dei bhikkhu guidato dal Buddha è
stato invitato da te per domani. Tu sei però un ospite. Ti darò del
denaro per procurarti il cibo per il Saṅgha dei bhikkhu guidato dal
Buddha».

«Non ce n’è bisogno. Ho del denaro per procurarmi il cibo per il Saṅgha
dei bhikkhu guidato dal Buddha».

Un abitante della città di Rājagaha sentì e si offrì per procurargli del
denaro, ma Anāthapiṇḍika rifiutò. E Seniya Bimbisāra, re di Magadha, gli
fece la stessa offerta, ma egli rifiutò.

Allora, quando quella notte fu terminata, Anāthapiṇḍika ebbe del buon
cibo di vario genere preparato presso l’abitazione del mercante, e
annunciò al Beato che era giunto il tempo: «È ora, Signore, il pasto è
pronto».

Essendo mattino, il Beato si vestì, prese la ciotola e la veste
superiore e, accompagnato dal Saṅgha dei bhikkhu, andò alla casa del
mercante e si mise a sedere nel posto preparatogli. Allora il
capofamiglia Anāthapiṇḍika servì con le sue stesse mani il Saṅgha
guidato dal Buddha e lo soddisfece con differenti tipi di buon cibo.
Quando il Beato aveva finito di mangiare e non teneva più la ciotola in
mano, Anāthapiṇḍika si mise a sedere da un lato. Egli disse al Beato:
«Signore, che il Beato con il Saṅgha dei bhikkhu acconsentano a dimorare
con me a Sāvatthī per la stagione delle piogge».

«Gli Esseri Perfetti sono deliziati da stanze vuote, capofamiglia».

«Lo so, Beato, lo so, Sublime».

Poi, quando il Beato ebbe istruito, esortato, risvegliato e incoraggiato
Anāthapiṇḍika con un discorso di Dhamma, si alzò dal posto in cui sedeva
e andò via.

In quel tempo Anāthapiṇḍika aveva molti amici e conoscenti. Quando ebbe
terminato i suoi affari a Rājagaha, partì per Sāvatthī. Per strada
impartì istruzioni alla gente: «Signori, approntate giardini, costruite
dimore, preparate doni in cibo. Un Buddha è apparso nel mondo. È stato
invitato da me. Passerà per questa strada».

Quella gente seguì le istruzioni da lui impartite.

Quando Anāthapiṇḍika arrivò a Sāvatthī, cercò un posto adatto in tutta
la città, un luogo di ritiro adatto, finché vide il parco per la
ricreazione del principe Jeta, che aveva tutte le qualità richieste.
Andò dal principe Jeta e disse: «Signore, consentitemi di utilizzare il
vostro parco».

«Questo parco può essere ceduto solo per la somma di centomila monete
d’oro cosparse su di esso».

«Il parco è ceduto, signore».

«Il parco non è ceduto, capofamiglia».

Chiesero un arbitrato ai sovrintendenti del principe, per sapere se il
parco fosse ceduto o no. I sovrintendenti dissero: «Appena avete fissato
un prezzo, signore, il parco era da considerarsi ceduto».

Allora Anāthapiṇḍika fece portare l’oro con dei carri e cosparse il
Boschetto di Jeta con centomila monete d’oro. L’oro portato all’inizio
non fu sufficiente per coprirlo del tutto e in prossimità dell’entrata
c’era un piccolo spazio ancora scoperto. Anāthapiṇḍika ordinò alla gente
di andare a prendere dell’oro per coprire quello spazio. Il principe
Jeta allora pensò: «Se Anāthapiṇḍika spende tanto oro deve trattarsi di
una ragione fuori dal comune». Egli disse ad Anāthapiṇḍika: «Va bene
così, capofamiglia, non coprire quello spazio. Lascialo a me. Sarà il
mio dono».

Anāthapiṇḍika pensò: «Questo principe Jeta è una persona prominente e
ben nota. Sarà un’ottima cosa se persone tanto note acquistano fiducia
nel Dhamma e nella Disciplina». Così lasciò quello spazio al principe
Jeta, che fece costruire un annesso in prossimità del cancello
d’entrata. Allora Anāthapiṇḍika costruì delle dimore nel Boschetto di
Jeta e delle ampie terrazze, cancelli, padiglioni per l’attesa, saune,
magazzini e ripostigli, sentieri per la meditazione camminata, pozzi,
gabinetti, stanze per il bagno, laghetti e padiglioni.

[.suttaref]
_Vin. Cv. 6:4; S. 10:8_

[.voice]
`Prima Voce.` Così ho udito.footnote:[Non ci sono argomenti per indicare
quando avvenne questo incontro con Māra.] Quando il Beato viveva a
Rājagaha, nel Boschetto di Bambù, una volta stava seduto all’aperto
nell’oscurità della notte mentre piovigginava lievemente. Allora Māra il
Malvagio, che voleva spaventarlo e fargli rizzare i capelli, assunse la
forma di un gigantesco serpente reale nāga e si avvicinò al Beato. Il
suo corpo era grande come una barca fatta con il tronco di un solo
albero, il suo cappuccio era ampio come la stuoia di un birraio, i suoi
occhi erano come i piatti di bronzo dei Kosala, la sua lingua saettava
dentro e fuori dalla bocca come un fulmine biforcuto dentro e fuori da
una nube tuonante, il suo respiro sembrava il soffio del mantice di un
fabbro.

Allora il Beato riconobbe Māra il Malvagio e si rivolse a lui con queste
strofe:

[verse]
____
Un eremita perfetto nel contenimento +
trascorre la sua vita in posti solitari, +
egli che ha rinunciato è lì che deve vivere, +
perché ciò è giusto per lui e per i suoi simili. +
Molti sono gli animali selvaggi, molti i terrori, +
molti gli insetti che pungono e gli esseri che strisciano. +
Quando un saggio si addestra nei luoghi selvaggi, +
nulla di tutto questo può fargli rizzare i capelli. +
Anche se il cielo si spacca, anche se la terra trema, +
anche se gli esseri tutti provano spavento, anche se gli uomini +
affondano un pugnale nel suo petto, +
nessun Risvegliato si rivolgerà a chiedere aiuto +
alle cose del mondo, agli essenziali dell’esistenza.
____

Allora Māra il Malvagio seppe: «Il Beato mi conosce, il Sublime mi
conosce». Triste e deluso, subito sparì.

[.suttaref]
_S. 4:6_

[.voice]
`Seconda Voce.` Ora, dopo essere rimasto a Rājagaha per tutto il tempo che
volle, il Beato si avviò per tappe verso Vesālī. Quando infine vi
arrivò, andò a vivere nel Salone con il Tetto Aguzzo nella Grande
Foresta. Allora la gente si dedicava con entusiasmo ai lavori di
costruzione, e i bhikkhu che sovrintendevano ai lavori erano
generosamente assistiti con vesti, cibo in elemosina, alloggio e, quelli
malati, con medicine.

C’era un povero sarto, che pensò: «Se questa gente si dedica con
entusiasmo ai lavori di costruzione e i bhikkhu sovrintendono ai lavori
generosamente assistiti con vesti, cibo in elemosina, alloggio e
medicine, deve trattarsi di una ragione fuori dal comune. E se
costruissi anch’io qualche edificio?».

Allora il povero sarto impastò un po’ di argilla, fece alcuni mattoni e
allestì un’impalcatura. Per mancanza di abilità, costruì il suo muro
storto ed esso cadde. La stessa cosa capitò una seconda e una terza
volta. Il povero sarto s’irritò e brontolò, lamentandosi: «I figli dei
Sakya consigliano e istruiscono le persone che offrono loro vesti e cibo
in elemosina e alloggio e medicine, ma io sono povero. Nessuno mi
consiglia e istruisce, o sovrintende alla costruzione del mio edificio».

I bhikkhu sentirono parlare di questa cosa e la riferirono al Beato.
Egli, allora, per questa ragione, tenne un discorso di Dhamma e si
rivolse ai bhikkhu in questo modo: «Bhikkhu, consento che i lavori di
costruzione siano formalmente distribuiti. Un bhikkhu che sovrintende ai
lavori di costruzione si prenderà cura di vedere che la dimora sia
celermente condotta a termine ed egli riparerà quel che è danneggiato o
rotto».

Quando il Beato restò a Vesālī per tutto il tempo che volle, partì per
recarsi per tappe a Sāvatthī. In quell’occasione i seguaci dei bhikkhu
che facevano parte di un certo gruppo di sei andarono più avanti del
Saṅgha dei bhikkhu guidati dal Buddha, e s’impadronirono di alloggi e
letti con queste parole: «Questo sarà per i nostri precettori, questo
sarà per i nostri insegnanti, questo sarà per noi». Quando il venerabile
Sāriputta arrivò dopo il Saṅgha dei bhikkhu guidati dal Buddha, gli
alloggi e i letti erano stati tutti presi. Non trovando alcun letto, si
andò a sedere ai piedi di un albero. Quando la notte stava per finire ed
era quasi l’alba, il Beato si alzò e tossì. Anche il venerabile
Sāriputta tossì.

«Chi è là?».

«Sono io, Sāriputta, Beato».

«Perché sei seduto lì, Sāriputta?».

Allora il venerabile Sāriputta gli riferì quel che era avvenuto. Per
questa ragione il Beato riunì i bhikkhu e chiese loro se fosse vero.
Loro dissero che era così. Egli li rimproverò: «Bhikkhu, questo non fa
sorgere la fiducia in chi non ne ha, né fa aumentare la fiducia in chi
ne ha. Fa invece restare privo di fiducia chi non ne ha e danneggia la
fiducia di chi ne ha».

Dopo che li ebbe rimproverati e tenuto un discorso di Dhamma, si rivolse
ai bhikkhu in questo modo: «Bhikkhu, chi è degno del luogo a sedere
migliore, dell’acqua migliore, del cibo in elemosina migliore?».

Alcuni bhikkhu dissero che lo era chi aveva abbracciato la vita
religiosa lasciando una famiglia di nobili guerrieri. Altri che lo era
chi aveva abbracciato la vita religiosa lasciando una famiglia di
brāhmaṇa … la famiglia di un capofamiglia. Altri che lo era chi è
specializzato nella recitazione dei Discorsi, nella recitazione della
Disciplina, chi predica il Dhamma … chi ha conseguito il primo jhāna …
il secondo jhāna … il terzo jhāna … il quarto jhāna … Chi è Entrato
nella Corrente … Chi Torna una Sola Volta … Chi è Senza Ritorno … un
realizzato Arahant …. che lo era chi ha le tre vere conoscenze. Altri
ancora dissero che lo era chi ha i sei generi di conoscenza diretta.
Allora il Beato si rivolse ai bhikkhu con queste parole:

«Una volta, bhikkhu, sull’Himalaya c’era un gigantesco baniano, sotto il
quale vivevano tre compagni: una pernice, una scimmia e un elefante.
Spesso erano scortesi e irrispettosi tra loro, e vivevano senza tenersi
in reciproca considerazione. Pensarono: “Se solo potessimo scoprire chi
di noi tre è il più anziano, allora potremmo onorarlo, rispettarlo,
riverirlo, venerarlo e seguire i suoi consigli”».

«La pernice e la scimmia chiesero all’elefante: “Quanto indietro riesci
ad andare con i tuoi ricordi?”».

«“Quando ero piccolo, ero solito camminare su questo baniano ed esso mi
passava tra le gambe, e la sua cima mi toccava la pancia”».

«Allora la pernice e l’elefante chiesero alla scimmia: “Quanto indietro
riesci ad andare con i tuoi ricordi?”».

«“Quando ero un cucciolo, ero solito sedere a terra e cibarmi dei
germogli più alti di questo baniano”».

«Allora la scimmia e l’elefante chiesero alla pernice: “Quanto indietro
riesci ad andare con i tuoi ricordi?”».

«“Da qualche parte c’era un grande baniano. Mangiai uno dei suoi semi e
lo evacuai in questo posto, e questo baniano crebbe da quel seme.
Perciò, sono più anziano di voi”».

«Allora la scimmia e l’elefante dissero alla pernice: “Sei più anziana
di noi. Ti onoreremo, rispetteremo, riveriremo, venereremo e seguiremo i
tuoi consigli”. Dopo di che la pernice fece assumere i cinque precetti
alla scimmia e all’elefante, e li assunse lei stessa. E furono cortesi e
rispettosi gli uni nei riguardi degli altri e vissero tenendosi in
reciproca considerazione. Alla dissoluzione del corpo, dopo la morte,
ricomparvero in una destinazione felice, in un mondo paradisiaco. E così
questa fu chiamata “la santa vita della pernice”».

[verse]
____
Coloro che riveriscono un anziano +
sono considerati abili nel Dhamma, +
perché ottengono lodi qui e ora +
e un felice destino nell’aldilà.
____

«Ora, bhikkhu, questi animali poterono essere cortesi e rispettosi gli
uni nei riguardi degli altri e vissero tenendosi in reciproca
considerazione. Cercate di fare come loro. Che voi siate scortesi e
irrispettosi e viviate senza tenervi in reciproca considerazione sotto
un Dhamma e una Disciplina ben proclamata come questa, non fa sorgere la
fiducia in chi non ne ha, né fa aumentare la fiducia in chi ne ha. Fa
invece restare privo di fiducia chi non ne ha e danneggia la fiducia di
chi ne ha».

Viaggiando per tappe il Beato arrivò infine a Sāvatthī. Lì andò a stare
nel Boschetto di Jeta, nel Parco di Anāthapiṇḍika. Allora Anāthapiṇḍika
andò dal Beato e lo invitò per il pasto del giorno seguente, che il
Beato accettò in silenzio. Quando il pasto fu finito e il Beato non
tenne più la ciotola in mano, Anāthapiṇḍika si mise a sedere da un lato
e chiese: «Signore, come dovrei comportarmi con questo Boschetto di
Jeta?».

«Capofamiglia, puoi offrirlo al Saṅgha dei bhikkhu dei quattro angoli
del mondo, a quello passato, futuro e presente».

«Così sia, Signore» egli rispose, e così fece. Allora il Beato si
rivolse a lui con queste strofe:

[verse]
____
Tiene lontani freddo e caldo, +
come pure animali selvatici, +
esseri striscianti e mosche, +
nonché brividi e pioggia. +
E offre protezione +
quando il sole e il vento sono agguerriti. +
Il fine è di essere riparati e a proprio agio +
per concentrarsi e praticare la visione profonda. +
Donare dimore all’Ordine +
è cosa altamente elogiata dal Buddha. +
Perciò, un uomo dotato di saggezza, +
che vede dove sia il suo bene, +
costruisce dimore confortevoli +
e in esse fa vivere i sapienti. +
Egli può dare loro cibo e bevande +
e vesti e un luogo in cui riposare, +
lasciando che il suo cuore riponga la sua fiducia +
in coloro che camminano in rettitudine, +
e loro gli insegneranno il Dhamma +
per la libertà da ogni sofferenza. +
Conoscendo il Dhamma, egli ottiene qui +
il Nibbāna ed è libero dalle contaminazioni.
____

Quando gli ebbe dato la sua benedizione, si alzò dal posto in cui sedeva
e se ne andò.

[.suttaref]
_Vin. Cv. 6:5-9_

[.narrator]
`Primo Narratore.` Il Buddha, che ora si trovava a Sāvatthī, capitale del
Kosala, proveniva dal regno di Magadha, la cui capitale era Rājagaha. In
quel tempo Magadha era uno dei più potenti regni dell’India centrale.
Era a sud del Gange e il suo confine settentrionale era il fiume stesso.
Il suo re era Bimbisāra, che si era già dichiarato seguace del Buddha.
Il cognato di Bimbisāra, il re Pasenadi, governava l’altro grande regno,
detto di Kosala, che si estendeva a nord, dalla riva settentrionale del
Gange ai piedi dell’Himalaya. Sembra che il re Pasenadi non avesse fino
a quel momento incontrato il Buddha.

[.voice]
`Prima Voce.` Così ho udito. Quando il Beato viveva a Sāvatthī, morì un
amatissimo figlio unico di un cittadino di Sāvatthī. Il padre andò dal
Beato, che gli disse: «Capofamiglia, le tue facoltà sembrano quelle di
uno fuori di senno, le tue facoltà non sembrano in uno stato normale».

«Come potrebbero essere le mie facoltà nel loro stato normale, Signore?
Il mio amatissimo figlio unico è morto. Da quando è morto non ho più
pensato al mio lavoro o a mangiare. Continuo ad andare al carnaio per
piangere e gridare: “Figlio mio, dove sei? Figlio mio, dove sei?”».

«È così, capofamiglia, è così. Le persone che ci sono care portano
afflizione e lamento, dolore, dispiacere e disperazione».

«Chi penserebbe mai in questo modo, signore? Le persone che ci sono care
portano felicità e gioia».

Egli si alzò, dissentendo e disapprovando le parole del Beato, e se ne
andò. In quell’occasione alcuni stavano giocando ai dadi non lontano dal
Beato. Il capofamiglia andò da loro e riferì la conversazione. Loro
dissero: «È così, capofamiglia, è così. Le persone che ci sono care
portano felicità e gioia».

Allora – pensando «Sono d’accordo con i giocatori di dadi» – si alzò e
se ne andò per la sua strada.

Infine questa storia giunse al palazzo reale. Il re Pasenadi di Kosala
disse alla regina: «Mallikā, perché il monaco Gotama ha detto: “Le
persone che ci sono care portano afflizione e lamento, dolore,
dispiacere e disperazione”?».

«Sire, se il Beato ha detto così, allora è così». «Non importa quel che
il monaco Gotama dice, Mallikā è sempre d’accordo: “Se il Beato ha detto
così, allora è così”. Lei parla come un’allieva che è sempre d’accordo
con quel che il maestro dice: “È così, maestro, è così”. Vattene
Mallikā, vai via di qui!».

Allora la regina Mallikā disse a Nāḷijangha della casta dei brāhmaṇa:
«Vai dal Beato e prestagli omaggio in mio nome. E chiedigli: “Signore,
queste parole sono state dette dal Beato: ‘Le persone che ci sono care
portano afflizione e lamento, dolore, dispiacere e disperazione’?”.
Prendi nota della sua risposta e vieni a riferirmela, perché gli Esseri
Perfetti non dicono nulla che non sia vero».

Lui fece come gli era stato richiesto. Il Beato disse: «Così è,
brāhmaṇa, così è. Le persone che ci sono care portano afflizione e
lamento, dolore, dispiacere e disperazione. E che sia così è possibile
capirlo da questo: una volta, in questa stessa Sāvatthī, c’era una donna
la cui madre era morta e per questo lei uscì di senno e, in preda alla
follia, vagò per strade e crocevia chiedendo: “Avete visto mia madre?
Avete visto mia madre?”».

[.narrator]
`Secondo Narratore.` Il Buddha proseguì raccontando un gran numero di
episodi con lo stesso significato e concluse in questo modo:

[.voice]
`Prima Voce.` «Una volta, in questa stessa Sāvatthī, c’era una donna
sposata che viveva con la famiglia del marito. I suoi parenti, però,
volevano che divorziasse dal marito per darla in moglie a un altro, che
a lei non piaceva. Lei lo raccontò al marito. Lui la bastonò a morte e
si uccise, pensando: “Saremo uniti dalla morte”. Anche da questo si può
capire come le persone che ci sono care portino afflizione e lamento,
dolore, dispiacere e disperazione».

Nāḷijangha tornò dalla regina e le raccontò quel che era stato detto.
Lei si recò dal re Pasenadi e gli chiese: «Sire, qual è la vostra
opinione? La principessa Vajirī vi è cara?».

«Si, Mallikā, mi è cara».

«Sire, qual è la vostra opinione? Se un cambiamento, un’alterazione
avvenisse nella principessa Vajirī, ciò porterebbe afflizione e lamento,
dolore, dispiacere e disperazione?».

«Qualsiasi cambiamento, qualsiasi alterazione che avvenisse nella
principessa Vajirī sarebbe un’alterazione nella mia vita. Come
potrebbero afflizione e lamento, dolore, dispiacere e disperazione non
sorgere in me?».

«Sire, è per questo motivo che il Beato, che conosce e vede, che è
realizzato e completamente illuminato, ha detto: “Le persone che ci sono
care portano afflizione e lamento, dolore, dispiacere e disperazione”».

[.narrator]
`Secondo Narratore.` La regina insistette con gli esempi della regina
Vāsabhā, del figlio del re Viḍūḍabha, di se stessa, e dei regni di Kāsa
e Kosala, nello stesso modo. Allora il re disse:

[.voice]
`Prima Voce.` «Mallikā, è meraviglioso, è stupefacente, fino a che punto
il Beato capisca e veda con comprensione. Vieni, portami l’acqua per
l’abluzione».

Allora il re Pasenadi si alzò dal posto in cui sedeva e, sistemando la
sua veste superiore su una spalla, levò le palme delle mani giunte verso
il luogo in cui il Beato si trovava ed esclamò per tre volte: «Onore al
Beato, realizzato e completamente illuminato!».

[.suttaref]
_M. 87_

[.narrator]
`Primo Narratore.` Il prossimo episodio forse registra come il re
incontrò per la prima volta il Buddha.

[.voice]
`Prima Voce.` Così ho udito. Una volta, quando il Beato viveva a Sāvatthī,
il re Pasenadi di Kosala andò da lui. Scambiò dei saluti con lui e,
quando questi formali doveri di cortesia ebbero termine, si mise a
sedere da un lato. Dopo averlo fatto, disse: «Il Maestro Gotama sostiene
di aver scoperto la piena Illuminazione?».

«Gran re, rettamente parlando si può dire che se qualcuno ha scoperto la
suprema piena Illuminazione, allora è di me che rettamente parlando si
può dirlo».

«Maestro Gotama, ci sono però questi monaci e brāhmaṇa, ognuno con il
proprio ordine, con il proprio gruppo da loro condotto, ognuno dei quali
è un rinomato e famoso filosofo, considerato da molti come un santo: mi
riferisco a Pūraṇa Kassapa, Makkhali Gosāla, Nigaṇṭha Nāthaputta,
Sañjaya Belaṭṭhiputta, Pakudha Kaccāyana e Ajita Kesakambali. Ora,
quando ho chiesto loro se sostenevano di aver scoperto la suprema piena
Illuminazione, loro non lo sostenevano. Com’è possibile? Perché il
Maestro Gotama è sia giovane negli anni sia ha da poco lasciato la vita
famigliare per la vita religiosa».

«Gran re, ci sono quattro cose che non si dovrebbero guardare dall’alto
in basso e disprezzare perché sono giovani. Quali quattro? Un nobile
guerriero, un serpente, un fuoco e un bhikkhu».

Così disse il Beato. Il Sublime, il Maestro, dopo aver detto queste
cose, proseguì:

[verse]
____
Che un uomo non disprezzi né condanni +
un giovane guerriero nato in un famoso lignaggio +
per la sua giovinezza. Forse quel giovane guerriero +
può diventare un sovrano dispotico e vendicativo +
e andarlo a trovare per sovrana vendetta +
Che lo eviti, allora, e salvi la propria vita.

Che un uomo non disprezzi né condanni +
il serpente che vede contorcersi in città o nella foresta +
per la sua giovinezza. Un serpente viaggia veloce +
in molti modi, può attaccare e mordere +
un uomo o una donna distratti in ogni momento. +
Che lo eviti, allora, e salvi la propria vita.

Che un uomo non disprezzi né condanni +
il fuoco che affamato arde e lascia una nera scia dietro di sé +
per la sua giovinezza. Se riesce a trovare combustibile +
per crescere e diffondersi, può attaccare e bruciare +
un uomo o una donna distratti in ogni momento. +
Che lo eviti, allora, e salvi la propria vita.

Benché gli incendi possano bruciare le foreste, +
tuttavia pochi giorni dopo che sono passati compaiono germogli, ma chi
sarà bruciato dal fuoco di un bhikkhu virtuoso,footnote:[«Chi sarà bruciato
dal fuoco di un bhikkhu virtuoso». Ecco
il commento di Ācariya Buddhaghosa: «Un bhikkhu che aggredisce chi l’ha
aggredito ... non è in grado di bruciare con il fuoco di un bhikkhu.
Quando egli (il bhikkhu) però non aggredisce in risposta a chi lo ha
aggredito, costui (chi lo ha aggredito) gli manca di rispetto ed è
bruciato dal fuoco della sua (del bhikkhu) virtù, ossia, non ha né figli
né figlie, e nemmeno bestiame, ecc.. Il significato è che tali individui
sono ridotti a nulla, “come ceppi di palma”. Essendo bruciati dal fuoco
dei bhikkhu, diventano come una palma alla quale sia stata tagliata la
corona delle foglie e alla quale resta solo il tronco. Il significato è
che per loro non ci saranno incrementi a riguardo di figli, figlie e
così via». – NDT. Questi versi – come pure altri passi di questa vita
del Buddha tratta dal canone in lingua pāli – possono sembrare duri e
arroganti, e forse perfino incomprensibili, soprattutto se si dimentica
che il concetto di _kamma_ implica l’assunzione di una diretta
responsabilità delle proprie intenzioni e azioni.] +
non avrà prole, non ci sarà chi ne erediterà il patrimonio. +
Come un ceppo di palma, non avrà né bambini né eredi.

Perciò l’uomo saggio, pensando al proprio bene, +
tratterà rettamente il serpente e il fuoco, +
il nobile guerriero e il bhikkhu virtuoso.
____

Quando ciò fu detto, il re Pasenadi disse al Beato: «Magnifico, Signore!
... Che il Beato mi accolga come suo seguace che si è recato da lui per
prendere rifugio finché durerà il mio respiro».

[.suttaref]
_S. 3:1_

[.voice]
`Seconda Voce.` Avvenne questo. Il Beato viveva a Rājagaha, nel Boschetto
di Bambù, nel Sacrario degli Scoiattoli, in un momento nel quale la
residenza presso un solo posto durante la stagione delle piogge non era
ancora stata resa obbligatoria dal Beato. I bhikkhu vagavano durante la
stagione fredda, durante la stagione calda e durante la stagione delle
piogge. La gente era infastidita, e mormorava e protestava: «Come fanno
questi monaci, questi figli dei Sakya, a vagare in tutte e tre le
stagioni, calpestando l’erba, molestando gli esseri che hanno solo il
tatto, uno solo dei sei sensi, e danneggiando molte piccole creature?
Perfino gli appartenenti ad altre sette, con i loro conclamati cattivi
insegnamenti, restano almeno nel luogo in cui risiedono durante le
piogge. Perfino questi avvoltoi che fanno i loro nidi sulle cime degli
alberi, almeno restano nel luogo in cui risiedono durante le piogge.
Questi monaci Sakya, invece, vagano in tutte e tre le stagioni,
calpestando l’erba, molestando gli esseri che hanno solo il tatto, uno
solo dei sei sensi, e danneggiando molte piccole creature».

I bhikkhu sentirono queste parole. Le raccontarono al Beato. Egli per
questa occasione offrì un discorso di Dhamma e si rivolse ai bhikkhu in
questo modo: «Bhikkhu, autorizzo ad avere una residenza fissa per la
stagione delle piogge».

[.suttaref]
_Vin. Mv. 3:1_

[.narrator]
`Primo Narratore.` Benché la morte di Anāthapiṇḍika avvenne molto tempo
 dopo – non è certo quando – è tuttavia opportuno raccontarla qui.

[.narrator]
`Secondo Narratore.` Durante la sua ultima malattia, Anāthapiṇḍika inviò
un messaggio all’Anziano Sāriputta, chiedendogli di andarlo a trovare.
Di conseguenza i due Anziani, Sāriputta e Ānanda, si recarono da lui.
Egli disse loro che la sua malattia stava peggiorando e così l’Anziano
Sāriputta lo istruì nel modo seguente.

[.voice]
`Prima Voce.` «Allora, capofamiglia, dovresti addestrarti così: “Non mi
attaccherò all’occhio; non ci sarà nessuna coscienza che abbia per base
l’occhio”. Così dovresti addestrarti».

[.narrator]
`Secondo Narratore.` Poi proseguì a istruirlo nello stesso modo sui
quattro altri sensi e sulla mente, su questi cinque generi di coscienza
e di contatto e di sensazione, sugli elementi terra, acqua, fuoco, aria,
sullo spazio e sulla coscienza, sui cinque aggregati, sui quattro stati
privi di forma, su questo mondo e su ciò che sta al di là di esso, e
infine su tutto ciò che è visto, udito, sentito – mediante il naso, la
lingua e il corpo – e percepito e cercato dalla mente e a essa
accessibile.

[.voice]
`Prima Voce.` Quando ciò fu detto, Anāthapiṇḍika pianse e le lacrime
scorsero sul suo viso. Allora il venerabile Ānanda gli chiese: «Ti stai
attaccando? Stai fallendo?». «Non mi sto attaccando, venerabile Ānanda,
non sto fallendo. Benché io abbia a lungo servito il Maestro e i bhikkhu
che praticano la meditazione, tuttavia non ho mai sentito un discorso di
Dhamma come questo». «Questi discorsi di Dhamma non sono offerti ai
devoti laici vestiti di bianco, capofamiglia, sono offerti a coloro che
hanno lasciato la vita famigliare». «Venerabile Sāriputta, nonostante
che questi discorsi di Dhamma siano offerti loro, ci sono alcuni che
hanno solo poca polvere negli occhi e saranno perduti se non ascoltano
questi discorsi di Dhamma. Alcuni otterranno la conoscenza ultima del
Dhamma».

[.suttaref]
_M. 143_

[.narrator]
`Secondo Narratore.` Anāthapiṇḍika spirò quello stesso giorno, e si
racconta che egli sia rinato in paradiso come Chi è Entrato nella
Corrente, perciò con non più di sette rinascite davanti a lui.
