= Il Periodo di Mezzo
:chapter-number: 10

[.narrator]
*Primo narratore.* Dopo il ventesimo anno successivo all’Illuminazione –
da quando il Buddha aveva cinquantacinque anni – tutte le tradizioni
rinunciano fino all’ultimo anno al tentativo di offrire un ordine
cronologico per gli eventi. L’evidenza intrinseca al _Tipiṭaka_ stesso
ci porta, da un punto di vista cronologico, solo fino alla comparsa dei
primi due discepoli eminenti, nel corso del secondo anno. La tradizione
incorporata nei commentari di Ācariya Buddhaghosa traccia alcuni schemi
molto generali per i primi vent’anni, consentendoci di collocare un bel
po’ di altro materiale dei _Piṭaka._ La tradizione molto posteriore del
_Mālāḷankāravatthu_ colloca certi eventi, alcuni dei quali non canonici
e perciò non inseriti qui, in ognuno di questi anni. Ogni tradizione
successiva presenta dei supplementi a quella precedente. Le affermazioni
contenute nelle scritture canoniche sono storicamente attendibili. In
assenza di contraddizioni, con prove rinvenibili al di fuori dei
Commentari, anche le affermazioni di questi ultimi possono essere
accettate. Quanto si trova nella tradizione successiva è, però,
probabilmente, frutto di congetture. Questa tuttavia non sembra essere
una ragione sufficiente per non accettare degli avvenimenti altrimenti
impossibili da datare. E la maggior parte del materiale presente nel
Vinaya e nel Sutta Piṭaka non è databile, benché talora sia possibile
elaborare una certa successione degli eventi. Segue ora un certo numero
di episodi e di discorsi, molti dei quali possono essere fatti risalire
a qualsiasi tempo.

[.narrator]
*Secondo narratore.* Deve essere innanzitutto menzionato un evento, che la
tradizione successiva colloca trentuno anni dopo l’Illuminazione. Si
tratta della donazione del Monastero Orientale a Sāvatthī effettuata da
Visākhā, devota laica. Ella fu scelta dal Buddha stesso come la più
eminente fra le sue seguaci. Poiché lei fu determinante per la
conversione all’insegnamento del suocero, Migāra, nella Dispensazione
[del Maestro] divenne nota con il nome di “Madre di Migāra”.

[.narrator]
*Primo narratore.* Questo è un episodio che le è tipico.

[.voice]
*Seconda voce.* Avvenne questo. Il Beato, dopo essere rimasto a Benares
per tutto il tempo che volle, si mise in viaggio per tappe verso
Sāvatthī. Quando infine vi giunse, andò a stare nel Boschetto di Jeta,
nel Parco di Anāthapiṇḍika. Allora Visākhā, Madre di Migāra, andò dal
Beato e, dopo avergli prestato omaggio, si mise a sedere da un lato.
Dopo che il Beato la ebbe istruita con un discorso di Dhamma, lei disse:
«Signore, che il Beato con il Saṅgha dei bhikkhu accetti domani il pasto
da me».

Il Beato accettò in silenzio. Quando lei vide che il Beato aveva
accettato, si alzò dal posto in cui sedeva e, dopo aver prestato
omaggio, andò via girandogli a destra.

Ora, in quell’occasione, verso la fine della notte un’ampia nuvola stava
facendo piovere su tutti i continenti. Allora il Beato si rivolse ai
bhikkhu in questo modo: «Bhikkhu, come sta piovendo sul boschetto di
Jeta, così sta piovendo su tutti i quattro i continenti. Consentite che
la pioggia bagni il vostro corpo, bhikkhu, questa è l’ultima volta che
c’è una grande nuvola colma di pioggia su tutti e quattro i continenti».

«E sia, Signore», risposero, e misero le loro vesti da una parte e
consentirono che la pioggia bagnasse il loro corpo.

Quando Visākhā ebbe finito di preparare buon cibo di vario genere, disse
a una domestica: «Vai al parco e annuncia che è giunto il momento in
questo modo: “È ora, Signore, il pasto è pronto”».

«Sì, signora», ella rispose.

Andò nel parco e lì vide i bhikkhu con le loro vesti messe da una parte,
consentendo che la pioggia bagnasse il loro corpo. Pensò: «Non ci sono
bhikkhu nel parco, ci sono asceti nudi che consentono alla pioggia di
bagnare il loro corpo». Tornò indietro e lo disse a Visākhā.

Allora Visākhā, che era saggia, intelligente e sagace, pensò:
«Certamente sarà avvenuto che i signori abbiano messo le loro vesti da
una parte e consentito alla pioggia di bagnare il loro corpo. Questa
ingenua ragazza ha pensato che non ci fossero bhikkhu, ma solo asceti
nudi che consentono alla pioggia di bagnare il loro corpo». Così, inviò
di nuovo la domestica con il messaggio.

Allora i bhikkhu avevano rinfrescato le loro membra e il loro corpo,
avevano preso le loro vesti e si erano recati nelle loro dimore. Quando
la domestica non vide alcun bhikkhu, pensò: «Non ci sono bhikkhu, il
parco è vuoto». Tornò indietro e lo disse a Visākhā.

Allora Visākhā, che era saggia, intelligente e sagace, pensò:
«Certamente i signori hanno rinfrescato le loro membra e il loro corpo,
e devono aver preso le loro vesti ed essersi recati nelle loro dimore.
Questa ingenua ragazza ha pensato che non ci fossero bhikkhu nel parco e
che esso fosse vuoto». Così, inviò di nuovo la domestica con il
messaggio.

Allora il Beato si rivolse ai bhikkhu con queste parole: «Bhikkhu,
prendete la vostra ciotola e la veste superiore. È tempo, il pasto è
pronto».

«Così sia, Signore», risposero.

Allora, essendo mattino, il Beato si vestì e, dopo aver preso la ciotola
e la veste superiore, con la stessa velocità con cui un uomo forte
distende il suo braccio piegato o piega il suo braccio disteso,
scomparve dal Boschetto di Jeta e apparve alla porta di Visākhā. Poi il
Beato si mise a sedere nel posto preparatogli e lo stesso fece il Saṅgha
dei bhikkhu. Visākhā disse: «È meraviglioso, Signore, è magnifico quanto
forte e potente sia il Perfetto, perché sebbene l’alluvione giunga fino
alle ginocchia e fino alla vita, né i piedi né l’abito di un solo
bhikkhu sono bagnati». E lei fu felice ed esultante. Allora con le sue
stesse mani servì il Saṅgha dei bhikkhu guidato dal Beato e li
soddisfece con buon cibo di vario genere. Quando il Beato ebbe finito di
mangiare e non teneva più la ciotola in mano, lei si mise a sedere da un
lato e disse: «Signore, chiedo otto favori al Beato».

«Gli Esseri Perfetti hanno lasciato dietro di loro i favori, Visākhā».

«Si tratta di cose possibili e non riprovevoli, Signore».

«Chiedi, allora, Visākhā».

«Signore, mi piacerebbe procurare al Saṅgha vesti per la pioggia finché
dura la mia vita. E allo stesso modo mi piacerebbe procurare cibo per i
bhikkhu in visita, cibo per chi parte per un viaggio, cibo per gli
ammalati e cibo per chi assiste gli ammalati. E allo stesso modo mi
piacerebbe procurare medicine e offrire costantemente del brodo di riso.
E allo stesso modo mi piacerebbe procurare per il Saṅgha delle bhikkhuṇī
le vesti per il bagno».

«Visākhā, quali benefici però prevedi, quando chiedi al Perfetto questi
otto favori?».

«Signore, quando ho inviato una domestica per annunciare il tempo del
pasto, lei ha visto i bhikkhu con le loro vesti messe da una parte,
consentendo che la pioggia bagnasse il loro corpo. Lei ha pensato che
non ci fossero bhikkhu nel parco, ma solo asceti nudi che consentivano
alla pioggia di bagnare il loro corpo, e me lo disse. La nudità,
Signore, è impropria, è disgustosa e repellente. Questo è il beneficio
che prevedo quando voglio procurare delle vesti per la pioggia al Saṅgha
finché dura la mia vita».

«Inoltre, Signore, un bhikkhu in visita che non conosce le strade e le
località per la questua, si stanca quando vaga per la questua. Dopo aver
mangiato il cibo da me offerto per un visitatore, può andare a conoscere
le strade e le località per la questua senza stancarsi a vagare per la
questua. Questo è il beneficio che prevedo quando voglio procurare del
cibo ai visitatori finché dura la mia vita».

«Inoltre, Signore, quando un bhikkhu parte per un viaggio, può perdere
la sua carovana perché deve cercare il cibo per sé, oppure può arrivare
tardi nel posto in cui vuole andare, e si stanca per il viaggio. Dopo
aver mangiato il cibo da me offerto per chi parte per un viaggio, egli
non soffrirà in quel modo. Questo è il beneficio che prevedo quando
voglio procurare del cibo per chi parte finché dura la mia vita».

«Inoltre, Signore, quando un bhikkhu ammalato non ha cibo adatto, la sua
malattia può peggiorare e lui può morire. Quando però mangia il cibo da
me offerto per gli ammalati può non peggiorare e può non morire. Questo
è il beneficio che prevedo quando voglio procurare del cibo agli
ammalati del Saṅgha finché dura la mia vita».

«Inoltre, Signore, quando un bhikkhu che assiste un ammalato deve
cercarsi il cibo per sé, può portare il cibo al bhikkhu ammalato dopo
mezzogiorno e, così, ci sarebbe un’infrazione alla regola di non
mangiare dopo mezzogiorno. Quando però mangia il cibo da me offerto per
chi assiste gli ammalati, egli può portare al bhikkhu ammalato il suo
cibo in tempo, e non ci sarà un’infrazione alla regola. Questo è il
beneficio che prevedo quando voglio procurare del cibo per chi assiste
gli ammalati del Saṅgha finché dura la mia vita».

«Inoltre, Signore, quando un bhikkhu ammalato non ha le medicine adatte,
la sua malattia può peggiorare e lui può morire. Quando però usa le
medicine da me offerte per gli ammalati, la sua malattia può non
peggiorare e può non morire. Questo è il beneficio che prevedo quando
voglio procurare medicine per gli ammalati del Saṅgha finché dura la mia
vita».

«Inoltre, Signore, il brodo di riso fu consentito ad Andhakavinda dal
Beato, che in esso vide dieci vantaggi. Vedendo questi dieci vantaggi,
voglio offrire constantemente del brodo di riso al Saṅgha finché dura la
mia vita».

«Inoltre, Signore, le bhikkhuṇī fanno il bagno nude nello stesso posto
del fiume Aciravatī in cui fanno il bagno le prostitute. Le prostitute
prendono in giro le bhikkhuṇī, dicendo: “Signore, perché praticare la
santa vita quando siete così giovani? Non si devono godere i piaceri
sensoriali? Potete vivere la santa vita quando siete anziane. Così
avrete i benefici di entrambe [le età]”. Quando le prostitute le
prendono in giro in questo modo, le bhikkhuṇī sono contrariate. La
nudità per le donne è impropria, Signore, è disgustosa e repellente.
Questo è il beneficio che prevedo quando voglio procurare delle vesti
per il bagno alle bhikkhuṇī finché dura la mia vita».

«Visākhā, quali benefici prevedi per te stessa, però, quando chiedi al
Perfetto questi otto favori?».

«Per quanto concerne questo, Signore, i bhikkhu che hanno trascorso la
stagione delle piogge in vari luoghi verranno a Sāvatthī per vedere il
Beato. Gli si avvicineranno e gli faranno questa domanda: “Signore, il
bhikkhu che portava questo nome è morto. Qual è la sua destinazione?
Qual è la sua rinascita?”. Il Beato dirà com’è quando uno ottiene il
frutto di Chi è Entrato nella Corrente, di Chi Torna Una Sola Volta, di
Chi è Senza Ritorno o della condizione di Arahant. Io li avvicinerò e
chiederò loro: “Signori, quel bhikkhu è mai giunto a Sāvatthī?”. Se loro
risponderanno di sì, io giungerò alla conclusione che certamente sono
stati usati una veste per la pioggia o il cibo per i visitatori o del
cibo per chi parte per un viaggio o del cibo per un ammalato o del cibo
per chi assiste un ammalato o delle medicine per un ammalato o del brodo
di riso costantemente offerto».

«Quando lo ricorderò, sarò contenta. Quando sarò contenta, sarò felice.
Quando la mia mente sarà felice, il mio corpo sarà tranquillo. Quando il
mio corpo sarà tranquillo, proverò piacere. Quando proverò piacere, la
mia mente sarà concentrata. Questo conserverà le mie facoltà spirituali
in essere, come pure i miei poteri spirituali e anche i fattori per
l’Illuminazione. Questo, Signore, è il beneficio che prevedo per me
stessa quando chiedo gli otto favori al Perfetto».

«Bene, bene, Visākhā. È bene che tu abbia chiesto al Perfetto gli otto
favori prevedendo questi benefici. Otterrai questi otto favori». Allora
il Beato diede la sua benedizione con queste strofe:

[quote]
____
Quando una donna, discepola di un Sublime, +
contenta della virtù, offre sia cibo sia bevande, +
e, dopo aver sconfitto l’avarizia, elargisce un dono +
che conduce in paradiso, seda il dolore e reca beatitudine, +
ella ottiene la santa vita con un cammino +
ugualmente senza macchia e immacolato. +
Così, amando il merito, con felicità e benessere, +
a lungo ella gioisce nel mondo paradisiaco.
____

[.suttaref]
_Vin. Mv. 8:15_

[.voice]
*Prima voce.* Così ho udito. Una volta il Beato soggiornava a Sāvatthī nel
Palazzo della Madre di Migāra, nel Parco Orientale. Allora morì una cara
e amata nipotina di Visākhā. In pieno giorno Visākhā andò dal Beato con
gli abiti e i cappelli bagnati. Dopo avergli prestato omaggio, ella si
mise a sedere da un lato e il Beato le disse: «Da dove vieni Visākhā, in
pieno giorno con gli abiti e i capelli bagnati?».

«Signore, una mia cara e amata nipotina è morta. Per questa ragione sono
venuta qui in pieno giorno con gli abiti e i capelli bagnati».

«Visākhā, vorresti avere tanti figli e nipoti quanti sono gli abitanti
di Sāvatthī?».

«Signore, vorrei avere tanti figli e nipoti quanti sono gli abitanti di
Sāvatthī».

«Visākhā, quante persone muoiono però a Sāvatthī ogni giorno?». «Dieci
persone muoiono a Sāvatthī ogni giorno, Signore, oppure nove o otto o
sette o sei o cinque o quattro o tre o due, oppure una persona muore a
Sāvatthī ogni giorno. A Sāvatthī muore sempre qualcuno».

«Cosa ne pensi, Visākhā, i tuoi abiti e i tuoi capelli sarebbero mai
asciutti?».

«No Signore. Di figli e nipoti ne ho a sufficienza!».

«Chi ha centinaia di persone care ha centinaia di dolori. Chi ha novanta
persone care ha novanta dolori. Chi ha ottanta persone care ha ottanta
dolori … venti … dieci … cinque … quattro … tre … due persone ha due
dolori. Chi ha una persona cara ha un dolore. Chi non ha persone care
non ha dolori. Sono privi di dolore, distaccati, non afflitti, questo
dico».

[quote]
____
Dolore e lutto nel mondo, +
sofferenza di ogni genere, +
succedono a causa delle persone care, +
ma non succedono quando non ce ne sono. +
È felice e privo di dolore +
chi non ha persone care al mondo. +
Chi cerca il distacco senza dolore +
non deve avere persone care al mondo.
____

[.suttaref]
_Ud. 8:8_

[.narrator]
*Primo narratore.* Lasciamo ora Visākhā.

[.voice]
*Seconda voce.* Avvenne questo. Il Beato stava soggiornando a Rājagaha sul
Picco dell’Avvoltoio, e a quel tempo gli asceti itineranti di altre
sette avevano l’abitudine di riunirsi nelle mezze lune del
quattordicesimo e del quindicesimo [giorno] e nel quarto di luna
dell’ottavo [giorno], e di predicare il loro Dhamma. La gente andava ad
ascoltare il Dhamma da loro. Si era molto affezionata a questi asceti
itineranti e credeva in loro. Gli asceti itineranti ottenevano così
supporto.

Ora, mentre Seniya Bimbisāra, re di Magadha, era solo in ritiro prese in
considerazione questa cosa e pensò: «Perché non dovrebbero riunirsi in
questi giorni pure i venerabili?».

Allora andò dal Beato e gli disse quel che aveva pensato, aggiungendo:
«Signore, sarebbe cosa buona se in questi giorni si riunissero pure i
venerabili».

Il Beato istruì il re con un discorso di Dhamma, dopo il quale il re se
ne andò. Allora il Beato per quest’occasione tenne un discorso di Dhamma
e si rivolse ai bhikkhu con queste parole: «Bhikkhu, consento che ci si
riunisca nelle mezze lune del quattordicesimo e del quindicesimo
[giorno] e nel quarto di luna dell’ottavo [giorno]».

Così i bhikkhu si riunirono in questi giorni come il Beato aveva
consentito, ma loro si misero a sedere in silenzio. La gente andò ad
ascoltare il Dhamma. Era annoiata, brontolava e protestava: «Come
possono i monaci, i figli dei Sakya, riunirsi in questi giorni e stare
seduti in silenzio muti come maiali? Non dovrebbero predicare il Dhamma
quando si incontrano?».

I bhikkhu sentirono. Andarono dal Beato e glielo raccontarono. Per
quest’occasione tenne un discorso di Dhamma e si rivolse ai bhikkhu con
queste parole: «Bhikkhu, consento che si predichi il Dhamma quando c’è
una riunione nelle mezze lune del quattordicesimo e del quindicesimo
[giorno] e nel quarto di luna dell’ottavo [giorno]».

[.suttaref]
_Vin. Mv. 2:1.2_

[.narrator]
*Primo narratore.* Nel Vinaya Piṭaka vi è un racconto degli eventi che
condussero all’istituzione del _Pātimokkha_ (o Codice delle Regole). Il
racconto è molto lungo e perciò qui lo riassumiamo.

[.narrator]
*Secondo narratore.* Sudinna era il figlio di un ricco mercante di
Kalanda, un villaggio nei pressi di Vesālī. Era sposato ma non aveva
figli. Ascoltò il Buddha predicare a Vesālī e il risultato fu che chiese
l’ammissione alla vita religiosa, ma gli venne detto che doveva ottenere
il consenso dei suoi genitori. Ci fu un lungo conflitto con loro e solo
dopo che egli rifiutò di mangiare glielo concessero. In seguito, dopo
che aveva abbandonato la vita famigliare, ci fu una carestia ed egli
pensò: «E se io vivessi con il supporto della mia famiglia? I miei
parenti mi procureranno offerte per il mio supporto e in questo modo
loro otterranno meriti, i bhikkhu ne beneficieranno e io non sarò a
corto di cibo in elemosina». I suoi parenti di Vesālī gli portarono gran
quantità di offerte.

Un giorno egli si recò a Kalanda con la sua ciotola e giunse alla casa
di suo padre, senza comunque annunciare il suo arrivo. Una domestica lo
riconobbe e lo disse al padre, che lo spinse a venire da lui per il
pasto del giorno seguente. Il giorno seguente, quando egli arrivò, i
suoi genitori usarono ogni mezzo per convincerlo a tornare alla vita
laica. La madre gli disse: «Sudinna, la nostra famiglia è ricca e ha
grandi possedimenti … per questo motivo tu devi generare un erede. Non
consentire ai Licchavi di prendere possesso della nostra proprietà priva
di eredi». Egli rispose: «Questo posso farlo, madre». Così la madre gli
portò nei pressi del Grande Bosco colei che era stata sua moglie. Egli
la condusse nel Bosco. Pensando che non ci fosse nulla di male, siccome
non c’era alcuna regola d’addestramento al riguardo, ebbe per tre volte
rapporti sessuali con lei. Lei rimase incinta. Allora le divinità della
terra si lamentarono con clamore: «Buoni signori, benché il Saṅgha dei
bhikkhu sia finora stato libero da infezioni e libero da pericoli, ora
però infezioni e pericoli sono stati in esso seminati da Sudinna di
Kalanda». Il clamore giunse in alto e attraversò tutti i paradisi,
finché raggiunse il mondo di Brahmā.

Colei che in precedenza era stata la moglie del venerabile Sudinna diede
alla luce un figlio. Gli amici lo chiamarono “Bījaka” e la madre la
chiamarono la “Madre di Bījaka”, e il venerabile Sudinna lo chiamarono
il “Padre di Bījaka”. In seguito sia Bījaka sia la madre lasciarono la
vita famigliare e abbracciarono la vita religiosa.

*Seconda voce.* Il venerabile Sudinna ebbe però dei rimorsi. A causa della
sua cattiva coscienza divenne magro e infelice. Quando un bhikkhu gli
chiese che cosa c’era che non andava, egli confessò. Venne rimproverato
e la questione venne esposta al Beato. Il Beato disse:

«Uomo fuorviato, questo è disdicevole, indecoroso, improprio e indegno
di un monaco, è scorretto e non deve essere fatto. Come hai potuto
vivere la santa vita non in completa perfezione e purezza dopo aver
abbracciato la vita religiosa in un Dhamma e in una Disciplina come
questa? Uomo fuorviato, non ho insegnato il Dhamma in molti modi per il
distacco, non per la passione? Non ho insegnato il Dhamma per la
liberazione dalle catene, non per l’incatenamento? Non ho insegnato il
Dhamma per l’abbandono, non per l’attaccamento? Il Dhamma così da me
insegnato per il distacco, la liberazione dalle catene e per l’abbandono
tu l’hai concepito per la passione, per l’incatenamento e per
l’attaccamento. Il Dhamma non è stato da me insegnato in molti modi per
il distacco, per la disintossicazione, per curare la sete, per abolire
l’attaccamento, per recidere il ciclo dell’esistenza, per estinguere la
brama, per il distacco, per la cessazione, per il Nibbāna? Non ho
descritto in molti modi l’abbandono dei desideri sensoriali, la piena
comprensione delle percezioni dei desideri sensoriali, la cura della
sete per i desideri sensoriali, lo sradicamento dei pensieri per i
desideri sensoriali, la mitigazione della febbre per i desideri
sensoriali?». 

«Uomo fuorviato, sarebbe stato meglio per te (che hai abbracciato la
vita religiosa) che il tuo membro fosse entrato nelle fauci di
un’orrenda e velenosa vipera o di un orrendo e velenoso cobra, piuttosto
che in una donna. Sarebbe stato meglio per te che il tuo membro fosse
entrato in una fossa di carboni infuocati, ardenti e incandescenti,
piuttosto che in una donna. Perché? Per la prima ragione tu avresti
rischiato la morte o sofferenze mortali, ma non, alla dissoluzione del
corpo, dopo la morte, di riapparire in una condizione di privazione, in
una destinazione infelice, nella perdizione, perfino all’inferno. Per la
seconda ragione, è quello che potrebbe succedere. Perciò, uomo
fuorviato, a causa di questo atto tu hai voluto perseguire l’opposto del
Dhamma, hai voluto perseguire l’ideale basso e volgare che è impuro e
termina con quelle abluzioni che le coppie compiono in segretezza. Tu
sei il primo ad attuare più che qualche idea sbagliata. Questo non fa
sorgere la fiducia in chi non ne ha, né fa aumentare la fiducia in chi
ne ha. Fa invece restare privo di fiducia chi non ne ha e danneggia la
fiducia di chi ne ha».

Allora, quando ebbe rimproverato il venerabile Sudinna (che non fu
espulso perché non era stata ancora prodotta alcuna regola), dopo aver
tenuto un discorso di Dhamma, si rivolse ai bhikkhu con queste parole:
«Bhikkhu, a causa di ciò istituirò una regola per l’addestramento dei
bhikkhu. Lo farò per dieci ragioni: per la prosperità del Saṅgha, per il
benessere del Saṅgha, per il contenimento di coloro che hanno cattivi
pensieri, in supporto dei bhikkhu virtuosi, per il contenimento delle
contaminazioni in questa vita, per la prevenzione delle contaminazioni
nella vita futura, in beneficio dei non credenti, per la crescita dei
credenti, per il fondamento del Buon Dhamma e per garantire le regole
per il contenimento. Questa (prima) regola deve essere così nota: ogni
bhikkhu che indulga in rapporti sessuali è sconfitto, egli non è più in
comunione».

È così che questa regola d’addestramento fu resa nota dal Beato.

[.suttaref]
_Vin. Sv. Pārā. 1_

Una volta, mentre il Beato era solo in ritiro, questo pensiero sorse
nella sua mente: «E se io consentissi che le regole già da me rese note
fossero recitate dai bhikkhu come loro _Pātimokkha_? Ciò costituirebbe
il loro giorno di osservanza _Uposatha_, il loro santo giorno di
osservanza».

Quando fu sera, si alzò dal ritiro e per questa occasione tenne un
discorso di Dhamma, si rivolse ai bhikkhu e riferì loro la sua
decisione.

[.suttaref]
_Vin. Mv. 2:3_

Avvenne questo. Il Beato soggiornava a Sāvatthī nel Palazzo della Madre
di Migāra, nel Parco Orientale. Era allora il giorno di _Uposatha_, e il
Beato stava sedendo attorniato dal Saṅgha dei bhikkhu.

In piena notte, quando era finita la prima veglia notturna, il
venerabile Ānanda si alzò dal posto in cui sedeva e, dopo aver sistemato
la veste su una spalla, levò le palme delle mani giunte verso il Beato e
disse: «Signore, ora siamo in piena notte e la prima veglia notturna è
finita. Il Saṅgha dei bhikkhu ha seduto a lungo. Che il Beato reciti il
_Pātimokkha_ ai bhikkhu».

Quando ciò fu detto, il Beato rimase in silenzio.

Una seconda volta, in piena notte, quando era finita la seconda veglia
notturna, il venerabile Ānanda si alzò dal posto in cui sedeva e, dopo
aver sistemato la veste su una spalla, levò le palme delle mani giunte
verso il Beato e disse: «Signore, ora siamo in piena notte e la seconda
veglia notturna è finita. Il Saṅgha dei bhikkhu ha seduto a lungo. Che
il Beato reciti il _Pātimokkha_ ai bhikkhu».

Una seconda volta il Beato rimase in silenzio.

Una terza volta, in piena notte, quando era finita la terza veglia
notturna, mentre la rossa alba sorgeva gioiosa sul volto della notte, il
venerabile Ānanda si alzò dal posto in cui sedeva e, dopo aver sistemato
la veste su una spalla, levò le palme delle mani giunte verso il Beato e
disse: «Signore, ora siamo in piena notte e la terza veglia notturna è
finita, mentre la [rossa] alba sorge gioiosa sul volto della notte. Il
Saṅgha dei bhikkhu ha seduto a lungo. Che il Beato reciti il
_Pātimokkha_ ai bhikkhu».

«L’assemblea non è pura, Ānanda».

Allora il venerabile Mahā-Moggallāna pensò: «A chi si riferisce il
Beato, dicendo questo?». Con la sua mente lesse le menti di tutto il
Saṅgha dei bhikkhu. Vide quella persona, non virtuosa, scellerata,
impura, di abitudine sospette, che nascondeva i suoi atti, che non era
monaco ma pretendeva di esserlo, che non conduceva la santa vita ma
pretendeva di condurla, guasto dentro, libidinoso e pieno di corruzione,
che sedeva nel mezzo del Saṅgha. Andò da lui e disse: «Alzati, amico,
sei stato visto dal Beato. Per te non è possibile vivere in comunione
con il Saṅgha dei bhikkhu».

Quando ciò fu detto, quella persona rimase in silenzio. Quando ciò gli
fu detto una seconda e una terza volta, rimase in silenzio. Allora il
venerabile Mahā-Moggallāna lo prese per un braccio e lo mise fuori della
porta, che sprangò. Andò dal Beato e disse: «Signore, ho espulso quella
persona. Ora l’assemblea è pura. Che il Beato reciti il _Pātimokkha_ al
Saṅgha dei bhikkhu».

«È meraviglioso, Moggallāna, è stupefacente come quell’uomo fuorviato
abbia aspettato fino che non è stato preso per un braccio». Poi il Beato
si rivolse ai bhikkhu con queste parole: «Bhikkhu, d’ora in poi non
parteciperò _all’Uposatha_. Non reciterò il _Pātimokkha_. D’ora in poi
parteciperete all’_Uposatha_ e reciterete il _Pātimokkha_ senza di me. È
impossibile, non può avvenire che un Perfetto partecipi all’_Uposatha_ e
reciti il _Pātimokkha_ in un’assemblea impura».

«Bhikkhu, ci sono otto qualità meravigliose e stupefacenti del grande
oceano per le quali i dèmoni _asura_ si deliziano quando le vedono. Allo
stesso modo ci sono otto qualità meravigliose e stupefacenti di questo
Dhamma e Disciplina per le quali i bhikkhu si deliziano quando le
vedono. Quali otto?».

«Proprio come il grande oceano inclina e scende senza alcuna improvvisa
pendenza, così anche in questo Dhamma e Disciplina c’è un graduale
addestramento, lavoro e pratica senza alcuna penetrazione improvvisa
della conoscenza finale. Ancora, proprio come il grande oceano è stabile
e si mantiene nei limiti dei suoi riflussi e fluisce senza eccederli,
così anche i miei discepoli non trasgrediscono le regole d’addestramento
da me rese note. Ancora, proprio come il grande oceano non tollera un
cadavere, ma quando c’è in esso un cadavere, subito lo scaglia a riva,
lo getta sulla terra asciutta, così anche il Saṅgha non tollera una
persona non virtuosa, scellerata, impura, di abitudine sospette, che
nasconde i suoi atti, che non è monaco ma pretende di esserlo, che non
conduce la santa vita ma pretende di condurla, guasto dentro, libidinoso
e pieno di corruzione, ma quando si trovano insieme subito lo getta
fuori. E anche se può star seduto nel mezzo del Saṅgha, egli è tuttavia
lontano dal Saṅgha e il Saṅgha è lontano da lui».

«Ancora, proprio come tutti i grandi fiumi, il Gange, la Yamunā,
l’Aciravatī, la Sarabhū e la Mahī, rinunciano ai loro precedenti nomi e
le loro precedenti identità quando raggiungono il grande oceano, e
divengono tutt’uno con lo stesso grande oceano, così anche queste
quattro caste – i nobili guerrieri _khattiya_, i sacerdoti _brāhmaṇa_, i
commercianti e artigiani _vessa_ e i servi _sudda_ – quando hanno
rinunciato alla vita familiare per la vita religiosa nel Dhamma e
Disciplina dichiarati dal Perfetto, rinunciano ai loro precedenti nomi e
lignaggi, e divengono tutt’uno con i bhikkhu che sono figli dei Sakya.
Ancora, proprio come i grandi fiumi del mondo fluiscono nel grande
oceano e la pioggia del cielo cade in esso, ma per tutto questo il
grande oceano non è mai descritto come non pieno o pieno, così, benché
molti bhikkhu ottengano il Nibbāna definitivo per mezzo dell’elemento
Nibbāna senza alcun residuo del passato attaccamento, per tutto questo
anche l’elemento Nibbāna non è mai descritto come non pieno o pieno.
Ancora, proprio con il grande oceano ha un solo sapore, il sapore del
sale, così anche questo Dhamma e Disciplina hanno un solo sapore, il
sapore della Liberazione. Ancora, proprio come il grande oceano
custodisce molti e vari tesori – tesori come perle, cristalli, berilli,
conchiglie, marmi, coralli, argento, oro, rubini, opali – così anche
questo Dhamma e Disciplina custodiscono molti e vari tesori – tesori
come i quattro fondamenti della consapevolezza, i quattro retti sforzi,
le quattro basi per il successo [spirituale], le cinque qualità
spirituali, i cinque poteri, i sette fattori dell’Illuminazione e il
Nobile Ottuplice Sentiero.

«Ancora, proprio come il grande oceano è la dimora di grandi esseri –
esseri come balene, serpenti di mare, dèmoni, mostri e tritoni – e nel
grande oceano ci sono creature che misurano cento leghe, due, tre,
quattro, cinquecento leghe, così anche questo Dhamma e questa Disciplina
sono la dimora di grandi esseri – esseri come Chi è Entrato nella
Corrente, e colui che è sulla via per realizzare il frutto di Chi è
Entrato nella Corrente; come Chi Torna Una Sola Volta, e colui che è
sulla via per realizzare il frutto di Chi Torna Una Sola Volta; come Chi
è Senza Ritorno, e colui che è sulla via per realizzare il frutto di Chi
è Senza Ritorno; come l’Arahant, e colui che è sulla via per realizzare
il frutto della condizione di Arahant».

Conoscendo il significato di ciò, il Beato esclamò queste parole:

[quote]
____
La pioggia infradicia quel che è tenuto ravvolto, +
ma non quel che è aperto. +
Si scopra, allora, quel che è celato, +
affinché essa non l’infradici.
____

[.suttaref]
_Vin. Cv. 9:1; Ud. 5:5; A. 8:20_

[.voice]
*Prima voce.* Così ho udito. Una volta, quando il Beato soggiornava a
Sāvatthī, il venerabile Mahā-Kassapa andò da lui. Gli chiese: «Signore,
qual è la causa, qual è la ragione, perché prima c’erano meno regole per
l’addestramento e più bhikkhu che raggiungevano e dimoravano nella
conoscenza finale? Qual è la causa, qual è la ragione, perché ora ci
sono più regole per l’addestramento e meno bhikkhu raggiungono e
dimorano nella conoscenza finale?».

«Così stanno le cose, Kassapa. Quando gli esseri stanno degenerando e il
Buon Dhamma va scomparendo, giungono più regole per l’addestramento e
meno bhikkhu raggiungono e dimorano nella conoscenza finale. Il Buon
Dhamma non scompare fino a quando la contraffazione del Buon Dhamma non
sorge nel mondo, ma appena la contraffazione del Buon Dhamma sorge nel
mondo, il Buon Dhamma scompare, proprio come l’oro non scompare dal
mondo fino a quando l’oro contraffatto non compare, ma appena l’oro
contraffatto compare nel mondo, l’oro scompare. Non sarà l’elemento
terra né l’elemento acqua né l’elemento fuoco né l’elemento aria a
causare la scomparsa del Buon Dhamma. Saranno piuttosto gli uomini
fuorviati che compariranno qui a causare la scomparsa del Buon Dhamma.
La scomparsa del Buon Dhamma, però, non avverrà come affonda una nave,
tutta in una volta».

«Ci sono queste cinque cose deleterie che conducono alla dimenticanza
del Buon Dhamma e alla sua sparizione. Quali cinque? I bhikkhu e le
bhikkhuṇī, i seguaci laici e le seguaci laiche divengono irrispettosi e
sprezzanti nei riguardi del Maestro, nei riguardi del Dhamma, nei
riguardi del Saṅgha, nei riguardi dell’addestramento e nei riguardi
della concentrazione. Ci sono anche queste cinque cose che conducono
alla durevolezza del Buon Dhamma, al suo non essere dimenticato e alla
sua non sparizione. Quali cinque? I bhikkhu e le bhikkhuṇī, i seguaci
laici e le seguaci laiche sono rispettosi e devoti nei riguardi del
Maestro, nei riguardi del Dhamma, nei riguardi del Saṅgha, nei riguardi
dell’addestramento e nei riguardi della concentrazione.

[.suttaref]
_S. 16:13; cf. A. 7:56_

Una volta il Beato soggiornava a Vesālī, nel Salone con il Tetto Aguzzo
nella Grande Foresta. Allora un certo bhikkhu Vajjiputtaka andò dal
Beato … e disse: «Signore, ogni due settimane bisogna recitare più di
centocinquanta regole di condotta. Non riesco ad addestrarmi in tutte
queste regole».

«Puoi addestrarti in queste tre regole, bhikkhu? La regola
d’addestramento della più alta virtù, la regola d’addestramento della
più alta consapevolezza e la regola d’addestramento della più alta
comprensione?».

«Posso farlo, Signore».

«Allora, bhikkhu, addestrati in queste tre regole d’addestramento.
Appena hai portato a termine quell’addestramento, allora, del tutto
addestrato, in te saranno stati abbandonati brama, avversione e
illusione. Con ciò, tu non compirai atti non salutari né coltiverai il
male».

In seguito quel bhikkhu portò a termine quell’addestramento; allora, del
tutto addestrato, furono in lui completamente abbandonati brama,
avversione e illusione. Con ciò, egli non compì atti non salutari né
coltivò il male.

[.suttaref]
_A. 3:83_

[.voice]
*Seconda voce.* Avvenne questo. Dopo che il Beato aveva soggiornato a
Rājagaha per tutto il tempo che volle, si avviò per tappe verso Vesālī.
Ora, mentre era in viaggio tra le due città vide molti bhikkhu carichi
di vesti, con fardelli di vesti sul loro capo, sulle loro spalle e ai
loro fianchi. Pensò: «Questi uomini fuorviati con le loro vesti tornano
con troppa facilità al lusso. E se stabilissi un massimo, un limite per
le vesti monastiche?».

Allora, al termine del suo viaggio il Beato giunse infine a Vesālī, dove
soggiornò nel Sacrario di Gotamaka. In quel tempo il Beato sedeva
all’aperto, durante le notti invernali degli “otto giorni di ghiaccio”,
indossò solo una veste, ma senza sentire il freddo. Quando la prima
veglia della notte fu terminata, sentì freddo, indossò una seconda veste
e non sentì più freddo. Quando la veglia mediana fu terminata, sentì
freddo, indossò una terza veste e non sentì più freddo. Quando l’ultima
veglia fu terminata, mentre la rossa alba sorgeva gioiosa sul volto
della notte, sentì freddo, indossò una quarta veste e non sentì più
freddo. Allora pensò: «Perfino gli uomini di rango che sono sensibili al
freddo, che temono il freddo, che hanno abbandonato la vita famigliare
per questo Dhamma e Disciplina possono sopravvivere con tre vesti.
Perché non dovrei stabilire un massimo, un limite per le vesti
monastiche, consentendone tre?».

Il Beato allora si rivolse ai bhikkhu e, dopo aver detto loro quel che
aveva pensato, annunciò la regola che prevedeva di non indossare più di
tre vesti monastiche: «Bhikkhu, consento che siano indossate tre vesti:
una veste esterna rappezzata di doppio spessore, una sola veste interna
e un solo panno da portare alla vita».

[.suttaref]
_Vin. Mv. 8:13_

Un’altra volta il Beato, quando era in viaggio da Rājagaha verso le
Colline Meridionali, disse al venerabile Ānanda: «Ānanda, vedi il
territorio di Magadha, che è a quadrati, a strisce, che ha bordi e linee
trasversali?».

«Sì, Signore».

«Cerca di fare in modo che la veste dei bhikkhu sia così, Ānanda».

[.suttaref]
_Vin. Mv. 8:12_

[.voice]
*Prima voce.* Così ho udito. Una volta, quando il Beato soggiornava a
Sāvatthī, il venerabile Mahā-Kaccāna soggiornava nel territorio di
Avantī, sulla Rupe di Pavatta a Kururaghara, e riceveva supporto da un
seguace laico chiamato Soṇa Kuṭikaṇṇa. Soṇa Kuṭikaṇṇa andò dal
venerabile Mahā-Kaccāna e, dopo avergli prestato omaggio, si mise a
sedere da un lato. Poi gli disse: «Signore, per quel che so del Dhamma
insegnato dal venerabile Mahā-Kaccāna non è facile per chi vive in
famiglia condurre una santa vita oltremodo perfetta e immacolata come
una conchiglia lucidata. Perché non dovrei allora radermi i capelli e la
barba, indossare la veste ocra e abbandonare la vita famigliare per la
vita religiosa? Il venerabile Mahā-Kaccāna mi consentirà di abbracciare
la vita religiosa?».

Il venerabile Mahā-Kaccāna gli disse: «Soṇa, è difficile vivere la vita
religiosa per la restante vita, mangiando solo in una parte del giorno e
giacendo soli. Per favore, dedicati all’insegnamento del Buddha laddove
ti trovi, nella vita famigliare, e cerca di condurre la santa vita lì,
mangiando a tempo opportuno in una sola parte del giorno e giacendo
solo».

Allora l’idea di abbracciare la vita religiosa di Soṇa Kuṭikaṇṇa venne
meno.

Poi egli fece di nuovo la stessa richiesta e ricevette la stessa
risposta. In seguito fece questa stessa richiesta una terza volta.
Allora il venerabile Mahā-Kaccāna gli concesse di “andare
oltre”.footnote:[NDT. Nel testo inglese si ha “going forth” con il senso di
“lasciare la propria dimora per diventare senza dimora” per tradurre il
termine _pabbajjā_, con il quale nei testi buddhisti in lingua pāli si
indica il passaggio dalla vita laica a quella di monaco privo di dimora;
tale termine è utilizzato nella prima ordinazione d’ingresso nel Saṅgha,
tramite la quale si diventa novizi o _sāmanera_. Già il Vinaya menziona
in alcuni casi l’«attesa di tre anni» necessaria per la piena
ordinazione monastica, la completa accettazione nel Saṅgha, indicata in
lingua pāli con il termine _upasampadā_. “Go forth” ricorre di frequente
nel testo e solo quando strettamente necessario è letteralmente tradotto
con “andare oltre”, come in questo caso, per rispettare la successione
tra prima e completa ordinazione monastica. In altri punti del testo,
però, questa espressione risulterebbe poco comprensibile per chi non ha
molta familiarità con le consuetudini monastiche _theravādin_. Così, per
facilitare il lettore, altrove si è scelto di rendere “go forth” in modo
vario, in base al contesto.] Allora c’erano però solo pochi bhikkhu nel
territorio di Avanti e fu solo dopo tre anni che il venerabile
Mahā-Kaccāna fu in grado, con problemi e difficoltà, di radunare un
collegio di dieci bhikkhu. Dopo averlo fatto, impartì l’ammissione alla
vita religiosa al venerabile Soṇa.

Dopo la stagione delle piogge, una sera si alzò dal ritiro e andò dal
venerabile Mahā-Kaccāna. Gli disse: «Signore, quando ero solo in ritiro
questo pensiero sorse in me: “Non ho mai visto il Beato di persona, ma
ho sentito che lui è in questo modo e in quest’altro. Così, Signore, se
il mio precettore lo consente, andrò e vedrò il Beato, realizzato e
completamente illuminato”».

«Bene, Soṇa, bene. Vai e vedi il Beato, realizzato e completamente
illuminato. Tu vedrai il Beato, che ispira fiducia e sicurezza, le cui
facoltà sensoriali sono acquietate, il cui cuore è acquietato, che ha
raggiunto il supremo controllo e la suprema serenità, un elefante
auto-controllato e auto-sorvegliato con le facoltà sensoriali contenute.
Quando lo vedrai, porgigli omaggio da parte mia prostrando il tuo capo
ai suoi piedi. Chiedigli se è libero da malattie, libero da disturbi, se
è sano, forte e vive a suo agio, e digli che io questo gli chiedo».

«E sia, Signore», egli rispose. Fu contento e gioì alle parole del
venerabile Mahā-Kaccāna. Prese la ciotola e la veste superiore e partì
viaggiando per tappe verso Sāvatthī, ove il Beato si trovava. Quando fu
lì, andò nel Boschetto di Jeta e prestò omaggio al Beato. Poi si mise a
sedere da un lato e gli portò il messaggio del suo precettore.

«Stai bene, bhikkhu? Sei felice? È stato faticoso il viaggio, qualche
difficoltà per la questua?».

«Sto bene, Beato. Sono felice. Il viaggio è stato poco faticoso e non ho
avuto difficoltà per la questua».

Il Beato disse ad Ānanda: «Ānanda, che sia preparato un posto ove questo
bhikkhu in visita possa riposare».

Allora il venerabile Ānanda pensò: «Quando il Beato mi parla così, è
perché vuole stare assieme al bhikkhu in visita. Il Beato vuole stare
assieme al venerabile Soṇa». Così, nel luogo ove dimorava il Beato fu
preparato un posto in cui il bhikkhu in visita potesse riposare».

Il Beato trascorse gran parte della notte sedendo all’aperto. Poi si
lavò i piedi ed entrò nel luogo ove dimorava, e lo stesso fece il
venerabile Soṇa. Quando si avvicinò l’alba, il Beato si alzò e disse al
venerabile Soṇa: «Puoi recitare qualcosa del Dhamma, bhikkhu».

«E sia, Signore», egli rispose, e recitò, intonandoli, tutti i sedici
Ottetti.footnote:[“Gli Ottetti” sono gli _Aṭṭhaka-vagga_ del
_Sutta-nipāta_.] Quando ebbe finito, il Beato approvò, dicendo:
«Bene, bhikkhu, bene. Hai imparato bene tutti i sedici Ottetti. Li sai e
li ricordi bene. Hai una bella voce, incisiva e priva di difetti, che
rende chiaro il significato. Quante sono le tue stagioni delle piogge,
bhikkhu?».

«Una, Signore».

«Perché hai atteso così a lungo, bhikkhu?».

«È da molto che ho visto i pericoli dei desideri sensoriali, Signore. La
vita famigliare, però, è così gravosa, molte sono le cose da fare, è
così piena di doveri».

Conoscendo il significato di ciò, il Beato esclamò queste parole:

[quote]
____
Vedendo che il mondo è insoddisfacente, +
conoscendo la condizione priva degli essenziali per la rinascita, +
l’Essere Nobile non si delizia del male, +
il male non delizia il puro di cuore.
____

[.suttaref]
_Ud. 5:6; cf. Vin. Mv. 5:13_

Una volta il Beato soggiornava a Vesālī, nel Salone con il Tetto Aguzzo
nella Grande Foresta, assieme a molti discepoli anziani veramente ben
addestrati: il venerabile Cāla, il venerabile Upacāla, il venerabile
Kakkaṭa, il venerabile Kalimbha, il venerabile Nikaṭa, il venerabile
Kaṭissaha e molti altri discepoli anziani veramente ben addestrati.

Allora molti eminenti Licchavi entrarono nella Grande Foresta per vedere
il Beato e arrivarono con molte carrozze di stato con postiglioni e
battistrada, che facevano molto tumulto e rumore. Allora quei venerabili
pensarono: «Ci sono questi molti Licchavi che sono venuti a vedere il
Beato … Il Beato ha però detto che il rumore è una spina per la
meditazione. E se andassimo nella Foresta degli alberi _gosinga sāla?_
Andiamo a dimorare là con agio, e senza rumore e compagnia».

Così andarono nella Foresta degli alberi _gosinga sāla_, e dimorarono là
con agio, e senza rumore e compagnia. Allora il Beato si rivolse ai
bhikkhu con queste parole: «Bhikkhu, dov’è Cāla, dove sono Upacāla,
Kakkaṭa, Kalimbha, Nikaṭa e Kaṭissaha? Dove sono andati quei bhikkhu
anziani?».

I bhikkhu gli dissero che cosa era avvenuto. Il Beato disse: «Bene,
bhikkhu, bene. Dicono bene coloro che dicono come hanno fatto quei
grandi discepoli, perché da me è stato detto che il rumore è una spina
per la meditazione. Ci sono queste dieci spine. Quali spine? L’amore
della compagnia è una spina per chi ama la solitudine. La devozione al
segno della bellezza è una spina per chi si vota alla contemplazione del
segno della ripugnanza nel corpo. Vedere spettacoli è una spina per chi
custodisce le sue porte sensoriali. La vicinanza di donne è una spina
per chi conduce la santa vita. Il rumore è una spina per la meditazione
nel primo jhāna. Il pensiero e l’esplorazione [della mente] sono una
spina per la meditazione nel secondo jhāna. La felicità è una spina per
la meditazione nel terzo jhāna. L’inspirazione e l’espirazione sono una
spina per la meditazione nel quarto jhāna. Percezione e sensazione sono
una spina per il raggiungimento della cessazione della percezione e
della sensazione. La brama è una spina, l’odio è una spina, l’illusione
è una spina. Dimorate senza spine, bhikkhu, dimorate privi di spine,
dimorate senza spine e privi di spine. Gli Arahant sono senza spine,
bhikkhu, gli Arahant sono privi di spine, gli Arahant sono senza spine e
privi di spine».

[.suttaref]
_A. 10:72_

Una volta il Beato soggiornava a Vesālī, nel Salone con il Tetto Aguzzo
nella Grande Foresta. Avvenne che parlò con i bhikkhu in molti modi
della contemplazione della ripugnanza (del corpo), raccomandò la
contemplazione della ripugnanza e il suo mantenimento in essere. Allora
egli disse ai bhikkhu: «Bhikkhu, desidero andare in ritiro per mezzo
mese. Non devo essere avvicinato da nessuno, ad eccezione di chi mi
porta il cibo in elemosina».

«E sia, Signore», risposero, e fecero come erano stati istruiti.

Allora quei bhikkhu pensarono a quello che il Beato aveva detto per
raccomandare la contemplazione della ripugnanza (del corpo), e
dimorarono devoti per conseguire il mantenimento in essere di quella
contemplazione. Nel farlo, si sentirono umiliati, provarono vergogna e
disgusto verso questo corpo e cercarono di usare un coltello (per
togliersi la vita). In un solo giorno, dieci, venti o trenta bhikkhu
usarono il coltello.

Al termine del mezzo mese il Beato si alzò dal ritiro e si rivolse al
venerabile Ānanda con queste parole: «Ānanda, come mai il Saṅgha dei
bhikkhu si è così assottigliato?».

Il venerabile Ānanda gli raccontò che cosa era avvenuto, e aggiunse:
«Signore, che il Beato annunci un altro modo affinché questo Saṅgha di
bhikkhu trovi fondamento nella conoscenza finale».

«In questo caso, Ānanda, raduna tutti i bhikkhu che vivono nel
territorio di Vesālī e falli incontrare nella sala delle riunioni».

Il venerabile Ānanda fece così e, quando i bhikkhu si erano riuniti,
informò il Beato. Allora il Beato andò nella sala delle riunioni, ove si
mise a sedere nel posto preparatogli. Dopo averlo fatto, si rivolse ai
bhikkhu con queste parole:

«Bhikkhu. Quando la consapevolezza del respiro è mantenuta in essere e
sviluppata, offre sia la pace sia un più alto scopo, è intatta (dalla
ripugnanza), è una piacevole dimora e induce lo svanire dei cattivi e
non salutari oggetti mentali appena sorgono, proprio come la sporcizia e
la polvere sono portati via nell’ultimo mese della stagione calda,
quando una grande pioggia fuori stagione li fa svanire appena sorgono».

[.suttaref]
_S. 54:9_

Una volta, quando il Beato viveva a Rājagaha, un bhikkhu chiamato Thera
viveva da solo e raccomandava di vivere da soli. Andava in un villaggio
per la questua da solo, tornava da solo, sedeva in privato da solo e
camminava su e giù da solo. Allora un certo numero di bhikkhu andarono
dal Beato e gliene parlarono. Il Beato mandò a chiedergli se fosse vero.
Egli rispose che era così. Il Beato disse: «C’è questo modo di vivere da
soli, Thera, non dico che non c’è. Non di meno, ascolta ora come vivere
da soli sia perfetto nei dettagli, e presta bene attenzione a quello che
dirò».

«Sì, Signore», rispose il venerabile Thera. Il Beato disse: «E com’è che
vivere da soli è perfetto nei dettagli? Ecco, Thera, quel che è passato
viene lasciato alle spalle, si rinuncia a quello che è il futuro, e la
brama e il desiderio per l’io acquisiti nel presente sono del tutto
messi da parte. In questo modo il vivere da soli è perfetto nei
dettagli».

Così disse il Beato. Dopo che il Sublime aveva detto questo, lui stesso,
il Maestro, disse ancora:

[quote]
____
Colui che ha trasceso tutto saggiamente, che tutto conosce, +
incontaminato da tutte le cose, rinunciando a tutto, +
s’è liberato grazie alla cessazione della brama: lo chiamo +
un uomo che vive da solo e in perfezione.
____

[.suttaref]
_S. 21:10_

[.voice]
*Seconda voce.* Avvenne questo. Il Beato stava soggiornando a Rājagaha sul
Picco dell’Avvoltoio quando Seniya Bimbisāra, re di Magadha, stava
governando e dominando ottantamila villaggi. In quel tempo c’era pure
uno della stirpe dei Kolivisa chiamato Soṇa, che viveva a Campā. Era il
figlio di un magnate. Era così delicato che peli nascevano sulle piante
dei suoi piedi. Ora il re, che aveva riunito rappresentanti dagli
ottantamila villaggi per alcuni affari e altre cose ancora, inviò a Soṇa
Kolivisa un messaggio che diceva: «Che Soṇa venga. Voglio che Soṇa
venga».

Così i genitori di Soṇa gli dissero: «Il re vuole vedere i tuoi piedi,
caro Soṇa. Ora, non stendere i tuoi piedi in direzione del re. Siedi di
fronte a lui a gambe incrociate con le piante rivolte verso l’alto, così
che egli sia in grado di vedere i tuoi piedi quando stai lì seduto».

Lo portarono in una lettiga, ed egli andò a vedere il re. Dopo avergli
prestato omaggio, si mise a sedere a gambe incrociate di fronte a lui e
il re vide le piante dei suoi piedi con i peli che vi crescevano sopra.

Allora il re diede istruzioni ai rappresentanti degli ottantamila
villaggi per le finalità di questa vita, dopo di che li congedò dicendo:
«Avete ricevuto istruzioni da me per le finalità di questa vita. Ora
andate a prestare omaggio al Beato. Egli vi darà istruzioni per le
finalità delle vite a venire».

Loro andarono sul Picco dell’Avvoltoio. Quando il Beato ebbe parlato a
loro, essi presero i Tre Rifugi. Subito dopo che se ne furono andati,
però, Soṇa si avvicinò al Beato e gli chiese di entrare nella vita
religiosa. Egli ricevette l’ammissione alla vita religiosa.

Non molto tempo dopo che era stato ammesso nel Saṅgha, egli andò a
vivere nel Fresco Boschetto. Quando faceva la meditazione camminata
andando avanti e indietro, sforzandosi per ottenere dei progressi, gli
vennero le vesciche ai piedi e il sentiero per la meditazione si coprì
tutto di sangue come un mattatoio. Il Beato andò nel luogo in cui il
venerabile Soṇa dimorava e si mise a sedere nel posto preparatogli, e il
venerabile Soṇa gli prestò omaggio e si mise a sedere da un lato. Il
Beato disse: «Quando eri da solo in ritiro e non solamente ora, Soṇa, ti
è forse venuto in mente: “Tra i discepoli energici del Beato, ci sono
anch’io. Ora il mio cuore non è libero dalle contaminazioni per mezzo
del non-attaccamento. Ci sono ancora ricchezze nella mia famiglia.
Potrei usare quelle ricchezze e ottenere meriti. E se io tornassi alla
vita laica e usassi quelle ricchezze per ottenere meriti?”».

«È così, Signore».

«Cosa ne pensi, Soṇa, da laico eri un buon suonatore di liuto?».

«È così, Signore».

«Quando le corde del tuo liuto erano troppo tese, il tuo liuto suonava e
rispondeva bene?».

«No, Signore».

«Quando le corde del tuo liuto erano troppo allentate, il tuo liuto
suonava e rispondeva bene?».

«No, Signore».

«Quando le corde del tuo liuto non erano né troppo tese né troppo
allentate ed erano uniformemente accordate, il tuo liuto suonava e
rispondeva bene?».

«Sì, Signore».

«Allo stesso modo, Soṇa, sforzarsi troppo conduce all’agitazione e
sforzarsi poco conduce alla rilassatezza. Perciò deciditi per
l’uniformità dell’energia, acquisisci uniformità delle facoltà
spirituali, e assumi questo quale tua indicazione».

«E sia, Signore», egli rispose.

[.suttaref]
_Vin. Mv. 5:1; cf. A. 6:55_

[.voice]
*Prima voce.* Così ho udito. Una volta il Beato soggiornava a Rājagaha,
nel Boschetto di Bambù, nel Sacrario degli Scoiattoli. In quel tempo a
Rājagaha c’era un lebbroso chiamato Suppabuddha. Era un povero e
miserabile sciagurato.

Quando il Beato stava seduto a esporre il Dhamma circondato da un grande
raduno di persone, il lebbroso vide da lontano quella gran folla. Pensò:
«Là sarà certamente distribuito qualcosa da mangiare. E se io mi
avvicinassi a quella gran folla? Forse otterrò qualcosa da mangiare». Si
avvicinò alla folla e vide il Beato che stava seduto a esporre il Dhamma
circondato da un grande raduno di persone. Pensò: «Non viene distribuito
nulla da mangiare. È il monaco Gotama che espone il Dhamma a un gruppo
di persone. E se io ascoltassi il Dhamma?». Si mise a sedere da un lato,
pensando: «Ascolterò il Dhamma». Allora il Beato osservò tutto
l’assembramento e lesse la mente delle persone con la sua mente,
chiedendosi chi fosse in grado di comprendere il Dhamma. Vide
Suppabuddha il lebbroso lì seduto. Allora pensò: «Egli è in grado di
comprendere il Dhamma».

A beneficio di Suppabuddha il lebbroso impartì un insegnamento
progressivo sulla generosità, sulla virtù e sui paradisi, e poi
sull’inadeguatezza, sulla vanità e sulle contaminazioni dei piaceri
sensoriali, e sulle beatitudini della rinuncia. Quando vide che la sua
mente era pronta … espose l’insegnamento peculiare dei Buddha: la
sofferenza, la sua origine, la sua cessazione e il Sentiero per la sua
cessazione.

La pura, immacolata visione del Dhamma sorse in lui: tutto quel che
sorge deve cessare. Egli disse: «Magnifico, Signore! … Che il Beato mi
ricordi come uno che si è recato da lui per prendere rifugio finché
durerà il mio respiro».

Quando Suppabuddha il lebbroso fu istruito … egli fu soddisfatto dalle
parole del Beato e, gioioso, prestò omaggio al Beato e se ne andò
girandogli a destra.

Allora una mucca con un giovane vitello assalì Suppabuddha il lebbroso e
lo uccise.

In seguito molti bhikkhu andarono dal Beato. Gli dissero: «Signore,
Suppabuddha, il lebbroso che è stato istruito dal Beato … è morto. Qual
è la sua destinazione? Qual è la sua vita futura?».

«Bhikkhu, Suppabuddha il lebbroso era saggio. È entrato nella via del
Dhamma, non mi ha infastidito con discussioni sul Dhamma. Mediante la
distruzione delle tre catene [inferiori] Suppabuddha è Entrato nella
Corrente, non è più soggetto a stati di privazione, è certo della
rettitudine ed è destinato all’Illuminazione».

Quando ciò fu detto, un bhikkhu chiese: «Signore, qual è la causa, qual
è la ragione, perché Suppabuddha il lebbroso era un povero e un così
miserabile sciagurato?».

«Precedentemente, bhikkhu, Suppabuddha il lebbroso era il figlio di un
uomo ricco in questa stessa Rājagaha. Mentre andava in un parco di
divertimenti, egli vide il
__Paccekabuddha__footnote:[Un _Paccekabuddha_ è una persona che diviene
illuminata senza la guida di un Buddha e che non cerca di far diventare illuminati
gli altri (BB).] Tagarasikhī che si recava in città
per la questua. Allora egli pensò: “Chi è quel lebbroso che vaga?”. Gli
sputò addosso, lo insultò e se ne andò. Sperimentò la maturazione di
quell’azione in inferno per molti anni, molti secoli, molti millenni.
Con la maturazione di quella stessa azione ora egli è stato un povero e
un miserabile sciagurato in questa stessa Rājagaha. Per mezzo del Dhamma
e della Disciplina proclamati dal Perfetto, egli ha acquisito fiducia,
virtù, saggezza, generosità e comprensione. Con la maturazione di tutto
questo, alla dissoluzione del corpo, dopo la morte, egli è riapparso nel
paradiso in compagnia delle Trentatré Divinità. Là egli offusca le altre
divinità per aspetto e rinomanza.

[.suttaref]
_Ud. 5:3_

[.voice]
*Seconda voce.* Avvenne questo. C’erano due bhikkhu chiamati Yamelu e
Tekula che vivevano a Sāvatthī ed erano fratelli. Erano di casta
brāhmaṇa e avevano una bella voce e una chiara dizione. Chiesero al
Beato: «Signore, ora i bhikkhu hanno vari nomi, sono di varie razze, di
varia nascita, hanno abbracciato la vita religiosa proveniendo da varie
casate. Guastano le parole del Beato usando il loro linguaggio.
Consentici di rendere le parole del Beato in metri classici».

Il Buddha, il Beato, li rimproverò: «Uomini fuorviati, come potete dire:
“Consentici di rendere le parole del Beato in metri classici”? Questo
non fa sorgere la fiducia in chi non ne ha, né fa aumentare la fiducia
in chi ne ha. Fa invece restare privo di fiducia chi non ne ha e
danneggia la fiducia di chi ne ha». Dopo averli rimproverati e offerto
un discorso di Dhamma, si rivolse ai bhikkhu con queste parole:
«Bhikkhu, le parole del Buddha non devono essere rese in metri classici.
Chiunque faccia questo commette un’infrazione di atto errato. Consento
che le parole del Buddha siano imparate nella lingua propria di ognuno».

[.suttaref]
_Vin. Cv. 5:33_

Una volta il Beato starnutì mentre stava esponendo il Dhamma circondato
da un gran numero di bhikkhu. I bhikkhu fecero un gran baccano nel dire:
«Lunga vita a te, Signore, lunga vita a te, Signore». Il baccano
interruppe il discorso di Dhamma. Allora il Beato si rivolse ai bhikkhu
con queste parole: «Bhikkhu, quando viene detto a qualcuno che
starnutisce “Lunga vita a te”, egli può vivere o morire a causa di
ciò?».

«No, Signore».

«Bhikkhu, non bisogna dire “Lunga vita a te” a chi starnutisce. Chiunque
lo fa commette un’infrazione di atto errato».

Così, quando i bhikkhu starnutivano e i capifamiglia dicevano «Lunga
vita e te, Signore», loro si sentivano imbarazzati e non rispondevano.
La gente disapprovava, mormorava e protestava: «Come possono questi
monaci, questi figli dei Sakya, non rispondere quando a loro si dice
“Lunga vita a te” ?».

I bhikkhu lo riferirono al Beato. Egli disse: «Bhikkhu, i capifamiglia
sono abituati a queste superstizioni. Quando loro dicono “Lunga vita a
te” vi consento di rispondere “Che tu possa vivere a lungo”».

[.suttaref]
_Vin. Cv. 5:33_

[.voice]
*Prima voce.* Così ho udito. Una volta il Beato soggiornava a Sāvatthī nel
Palazzo della Madre di Migāra, nel Parco Orientale. In quell’occasione
si era alzato dal ritiro verso sera e stava seduto fuori dal cancello,
nel porticato. Allora il re Pasenadi di Kosala lo raggiunse e, dopo
avergli prestato omaggio, si mise a sedere da un lato.

Proprio allora, però, sette asceti dai capelli intrecciati, sette
Nigaṇṭha, sette asceti nudi, sette asceti vestiti con un solo panno,
sette asceti itineranti, tutti con unghie e capelli lunghi, e dotati di
varie tenute monastiche, passarono non lontani dal Beato. Il re Pasenadi
si alzò dal luogo in cui sedeva e, dopo aver aggiustato la sua veste su
una spalla, s’inginocchiò in terra con la gamba destra. Poi, alzando le
mani giunte in alto verso gli asceti, pronunciò il suo nome per tre
volte: «Signori, io sono Pasenadi, re di Kosala».

Dopo che erano passati, tornò dal Beato e, dopo avergli prestato
omaggio, si mise a sedere da un lato. Disse: «Signore, alcuni di loro
sono da annoverare tra gli Arahant del mondo, oppure sono sulla via di
raggiungere la condizione di Arahant?».

«Gran re, in quanto laico tu ti delizi con i piaceri sensoriali. Vivi
ingombrato dai figli, utilizzi legno di sandalo di Benares, indossi
ghirlande, profumi e unguenti, fai uso di oro e argento. È difficile per
te sapere se le persone sono Arahant oppure sulla via di raggiungere la
condizione di Arahant. Per conoscere la virtù di un uomo bisogna vivere
con lui, dobbiamo aver a che far con lui non solo un po’ ma per un lungo
periodo, essere attenti né mancare di comprensione. La purezza di un
uomo la si conosce parlando con lui … La forza di un uomo la si conosce
in tempi di avversità … La comprensione di un uomo la si conosce
discutendo con lui, dobbiamo aver a che fare con lui non solo un po’ ma
per un lungo periodo, essere attenti né mancare di comprensione».

«È meraviglioso, Signore, è magnifico quanto il Beato si sia ben
espresso! Ci sono uomini, miei agenti, che vengono da me ancora
travestiti da comuni furfanti dopo essere stati a spiare nelle campagne.
In un primo momento sono ingannato da loro e solo in seguito capisco chi
sono. Quando però si sono ripuliti da tutta quella sporcizia e polvere,
e si sono ben lavati e profumati, con la barba e i capelli rifilati, e
vestiti con abiti bianchi, deliziano se stessi circondati da tutti e
cinque i tipi di piaceri sensoriali».

Conoscendo il significato di ciò, il Beato esclamò queste parole:

[quote]
____
È difficile conoscere un uomo dalla sua apparenza, +
né si può giudicarlo con un colpo d’occhio. +
L’incontinente può andare per il mondo +
travestito da uomo contenuto, +
perché ci sono alcuni che, nascosti da una maschera, +
risplendono fuori e sono corrotti dentro, +
come gioielli contraffatti di argilla +
o monete dorate di rame.
____

[.suttaref]
_S. 3:11; Ud. 6:2_

[.center]
(_Il sutta per i Kālāma_)

Una volta il Beato stava viaggiando per tappe nel regno di Kosala con un
certo numero di bhikkhu. Arrivò in una città che apparteneva ai Kālāma,
chiamata Kesaputta. Quando gli abitanti di Kesaputta sentirono che il
Beato era arrivato, si recarono da lui e gli chiesero: «Signore, alcuni
monaci e brāhmaṇa vengono a Kesaputta ed espongono solo i loro principi,
mentre insultano, lacerano, censurano e inveiscono contro i principi
degli altri. E anche altri monaci e brāhmaṇa vengono a Kesaputta, e
anche loro espongono solo i loro principi, mentre insultano, lacerano,
censurano e inveiscono contro i principi degli altri. Siamo perplessi e
dubbiosi nei loro riguardi, Signore. Quali di questi reverendi monaci
hanno detto il vero e quali hanno detto il falso?».

«Siete perplessi a ragione, Kālāma. Siete dubbiosi a ragione. Perché il
vostro dubbio è sorto esattamente a riguardo di ciò che deve essere
messo in dubbio. Venite, Kālāma, non accontentatevi delle dicerie o
della tradizionefootnote:[Se questo passo viene letto come un’ingiunzione generale a
trascurare qualsiasi istruzione, allora sarebbe impossibile attuarla,
perché allora la si potrebbe attuare solo non attuandola: si tratta di
un ben conosciuto dilemma logico. Il resto del discorso dovrebbe però
consentire di comprendere quel che si vuole dire. Per quanto concerne la
fiducia (_saddhā_), si veda il cap. 11, p. 222.] o delle leggende, di quel che è
esposto nelle vostre scritture o delle congetture, delle inferenze
logiche o delle ponderate evidenze, della predilezione per un punto di
vista dopo averlo esaminato voi stessi o con l’abilità di qualcun altro
oppure con il pensiero “Il monaco è il nostro insegnante”. Quando voi
conoscete dentro voi stessi: “Queste cose sono non salutari, soggette a
essere censurate, condannate dal saggio, adottate e messe in atto
portano al malanno e alla sofferenza”, allora dovete abbandonarle. Che
cosa ne pensate, Kālāma: quando la bramosia sorge in una persona, è bene
o male?». «È male, Signore». «Ora, è quando una persona è bramosa ed è
vinta dalla brama, con la mente ossessionata dalla brama, uccide esseri
che respirano, prende quel che non è dato, commette adulterio, dice il
falso e porta gli altri a fare lo stesso, è  una cosa che gli sarà per
lungo tempo causa di malanno e di sofferenza». «E sia, Signore». «Che
cosa ne pensate, Kālāma: quando l’odio sorge in una persona … ? Quando
l’illusione sorge in una persona … ?». «E sia, Signore». «Che cosa ne
pensate, Kālāma: queste cose sono salutari o non salutari?». «Non
salutari, Signore». «Censurabili o irreprensibili?». «Censurabili,
Signore». «Condannate o raccomandate dal saggio?». «Condannate dal
saggio, Signore». «Adottate e messe in atto, portano al malanno e alla
sofferenza oppure no, che cosa vi sembra in questo caso?». «Adottate e
messe in atto, Signore, portano al malanno e alla sofferenza. Così ci
sembra in questo caso». «Allora, Kālāma, queste sono le ragioni per cui
vi ho detto: “Venite, Kālāma, non accontentatevi delle dicerie … o del
pensiero “Il monaco è il nostro insegnante”. Quando voi conoscete dentro
voi stessi: “Queste cose sono non salutari” … allora dovete
abbandonarle».

«Venite, Kālāma, non accontentatevi delle dicerie … o del pensiero “Il
monaco è il nostro insegnante”. Quando voi conoscete dentro voi stessi:
“Queste cose sono salutari, irreprensibili, raccomandate dal saggio,
adottate e messe in atto conducono al benessere e alla felicità”, allora
dovreste praticarle e dimorare in esse. Che cosa ne pensate, Kālāma:
quando la non-bramosia sorge in una persona, è bene o male?». «È bene,
Signore». «Ora, è quando una persona non è bramosa e non è vinta dalla
brama, con la mente non ossessionata dalla brama, non uccide esseri che
respirano, né prende quel che non è dato, né commette adulterio, né dice
il falso, e neanche porta gli altri a fare lo stesso, è una cosa che gli
sarà per lungo tempo causa di benessere e di felicità». «E sia,
Signore». «Che cosa ne pensate, Kālāma: quando il non-odio sorge in una
persona … ? Quando la non-illusione sorge in una persona … ?». «E sia,
Signore». «Che cosa ne pensate, Kālāma: queste cose sono salutari o non
salutari?». «Salutari, Signore». «Censurabili o irreprensibili?».
«Irreprensibili, Signore». «Condannate o raccomandate dal saggio?».
«Raccomandate dal saggio, Signore». «Adottate e messe in atto, portano
al benessere e alla felicità oppure no, che cosa vi sembra in questo
caso?». «Adottate e messe in atto, Signore, portano al benessere e alla
felicità. Così ci sembra in questo caso». «Allora, Kālāma, queste sono
le ragioni per cui vi ho detto: “Venite, Kālāma, non accontentatevi
delle dicerie … o del pensiero “Il monaco è il nostro insegnante”.
Quando voi conoscete dentro voi stessi: “Queste cose sono salutari” …
allora dovete praticarle e dimorare in esse».

«Ora, quando un nobile discepolo è in questo modo libero dall’avidità,
libero dalla malevolenza e privo di illusioni, allora, pienamente
presente e consapevole, dimora con un cuore dotato di gentilezza
amorevole che si diffonde nelle quattro direzioni, nella prima e allo
stesso modo nella seconda, nella terza e nella quarta, e così verso
l’alto, il basso, tutt’intorno e ovunque, verso tutto come pure verso se
stesso. Egli dimora con un cuore dotato di abbondante, elevata,
smisurata gentilezza amorevole, priva di ostilità e non afflitta dalla
malevolenza, che si estende verso il mondo intero. Egli dimora con un
cuore dotato di compassione … Egli dimora con un cuore dotato di
contentezza … Egli dimora con un cuore dotato di equanimità … che si
estende verso il mondo intero».

«Con il suo cuore così privo di ostilità e non afflitto da malevolenza,
così privo di contaminazioni e unificato, un nobile discepolo qui e ora
acquisisce questi quattro benesseri. Egli pensa: “Se c’è un altro mondo
e c’è il frutto e la maturazione delle azioni buone e cattive, allora è
possibile che alla dissoluzione del corpo, dopo la morte, io possa
rinascere in un mondo paradisiaco”. Questo è il primo benessere
acquisito. “Se però non c’è un altro mondo e non c’è il frutto e la
maturazione delle azioni buone e cattive, allora qui e ora, in questa
vita, io sarò libero dall’ostilità, dall’afflizione e dall’ansia, e io
vivrò felice”. Questo è il secondo benessere acquisito. “Se il male
succede a chi fa il male, allora poiché non nutro cattivi pensieri nei
riguardi di nessuno, come potranno cattive azioni portare sofferenza a
me, che non faccio del male?”. Questo è il terzo benessere acquisito.
“Se però il male non succede a chi fa il male, allora so di essere puro
in questa vita da entrambi questi punti di vista”. Questo è il quarto
benessere acquisito».

[.suttaref]
_A. 3:65_

Una volta avvenne che un bhikkhu fosse malato di dissenteria e giacesse
sporco della propria urina e dei propri escrementi. Quando il Beato
stava facendo il giro delle dimore con il venerabile Ānanda come suo
attendente, giunse nel luogo in cui si trovava il bhikkhu. Quando lo
vide giacere nel luogo in cui stava, gli si avvicinò e disse: «Qual è la
tua malattia, bhikkhu?».

«La dissenteria, Beato».

«Bhikkhu, non hai un attendente?».

«No, Beato».

«Perché i bhikkhu non si occupano di te, bhikkhu?».

«Sono inutile per i bhikkhu, Signore, per questa ragione non si occupano
di me».

Allora il Beato disse al venerabile Ānanda: «Ānanda, va a prendere
dell’acqua. Laviamo questo bhikkhu».

«E sia, Signore». rispose il venerabile Ānanda, e portò dell’acqua. Il
Beato versò l’acqua e il venerabile Ānanda lavò il bhikkhu. Poi il Beato
lo prese per il capo e il venerabile Ānanda per i piedi, lo sollevarono
e lo misero su un letto.

In questa occasione e per questa ragione, il Beato convocò i bhikkhu e
chiese loro: «Bhikkhu, c’è un bhikkhu malato in qualche dimora?».

«Sì, Signore».

«Qual è la malattia di quel bhikkhu?».

«Ha la dissenteria, Signore».

«Ha qualcuno che si prenda cura di lui?».

«No, Beato».

«Perché i bhikkhu non si occupano di lui?».

«Signore, quel bhikkhu è inutile per i bhikkhu, per questa ragione non
si occupano di lui».

«Bhikkhu, non avete né una madre né un padre che si prendano cura di
voi. Se non vi prendete cura reciprocamente di voi stessi, chi si
prenderà cura di voi? Chi si prenderebbe cura di me, si prenda cura di
uno che è malato. Se egli ha un precettore, il suo precettore deve
prendersi cura di lui fino a quando non guarisce. Il suo maestro, se ne
ha uno, deve fare altrettanto. Chi vive con lui, oppure il suo allievo,
o chi ha lo stesso precettore, o chi ha lo stesso maestro. Se non ne ha,
il Saṅgha deve prendersi cura di lui. Se ciò non avviene, è
un’infrazione di atto errato».footnote:[La cura del malato qui ingiunta
riguarda un bhikkhu che si
prende cura di un bhikkhu malato. La generale pratica della medicina da
parte di bhikkhu nei riguardi dei laici è considerata alla stregua di un
errato mezzo di sussistenza per un bhikkhu e, perciò, non è consentita.]

«Quando un malato ha queste cinque qualità, di lui è difficile prendersi
cura. Fa quel che non è appropriato. Non conosce la misura di quel che è
appropriato. Non prende le medicine. Non rivela la sua malattia a chi
gli fa da infermiere e mira al suo benessere, né gli dice quando va
meglio o quando va peggio o quando va uguale. È una persona che non è in
grado di sopportare le sensazioni dolorose, aspre, tormentose, pungenti,
sgradevoli e minacciose per la vita che sono sorte. Quando una persona
ha le opposte cinque qualità, di lui è facile prendersi cura».

[.suttaref]
_Vin. Mv. 8:26_

«Quando un infermiere ha cinque qualità, è inadatto a prendersi cura del
malato. Non è abile nel preparare la medicina. Non conosce quel che è
appropriato e quel che non è appropriato, e così porta quel che non è
appropriato e porta via quel che è appropriato. Si prende cura del
malato per ragioni d’interesse invece che con pensieri di gentilezza
amorevole. È schifiltoso nel rimuovere gli escrementi, l’urina, la
saliva o il vomito. Non è abile nell’istruire, nel sollecitare, nel
risvegliare e nell’incoraggiare il malato con opportuni discorsi di
Dhamma. Quando un infermiere ha le opposte cinque qualità, è adatto a
prendersi cura del malato».

[.suttaref]
_Vin. Mv. 8:26; A. 5:123-24_

[.voice]
*Prima voce.* Il Beato una volta era seduto all’aperto, nell’oscurità
della notte, e delle lampade a olio erano accese. In quell’occasione un
gran numero di falene incontravano rovina, calamità e disastro cadendo
nelle lampade a olio. Conoscendo il significato di ciò, il Beato esclamò
queste parole:

[quote]
____
Benché alcuni corteggino gli estremi, non trovano +
alcuna essenza ma rinnovano i loro legami, +
perché dimorano in quel che vedono e nelle loro sensazioni +
come le falene che cadono in una fiamma.
____

[.suttaref]
_Ud. 6:9_

Un giorno il Beato si vestì, prese la ciotola e la veste superiore, e si
recò a Sāvatthī per la questua. Tra il Boschetto di Jeta e Sāvatthī vide
un gruppo di ragazzi che maltrattavano dei pesci. Andò da loro e disse:
«Ragazzi, temete il dolore? Vi ripugna il dolore?».

«Sì, Signore, temiamo il dolore, ci ripugna il dolore».

Conoscendo il significato di ciò, il Beato esclamò queste parole:

[quote]
____
Chi non vuole soffrire +
non dovrebbe compiere cattive azioni +
né in pubblico né in segreto. +
Se ora fai del male +
la sofferenza tuttavia certo ti trova +
per quanto in seguito si possa tentare di sfuggirle.
____

[.suttaref]
_Ud. 5:4_

[quote, Sn. 1:8, role=cantor]
____
*Cantore*{empty}footnote:[Questo canto, conosciuto come «Canto della Gentilezza
Amorevole» (Mettā Sutta), è quello al giorno d’oggi più noto. Se viene
trascurato il passo del discorso diretto (indicato tra «…» nella
traduzione), va persa l’architettura del sutta. Non si tratta di
un’ingiunzione, ma di una descrizione dei pensieri di chi pratica la
Dimora Divina della gentilezza amorevole (l’_iti_ che normalmente
conclude i discorsi diretti in lingua pāli è spesso escluso nei versi).
«Questa è una Dimora Divina» significa che loro – ossia gli Esseri
Nobili, coloro che hanno realizzato l’estinzione della brama, dell’odio
e dell’illusione – affermano che il dimorare in tal modo proprio in
questa vita equivale alla pura consapevolezza che si sperimenta nei
paradisi più elevati. Le ultime quattro righe sottolineano che se le
quattro Divine Dimore conducono al paradiso, esse tuttavia non
assicurano il conseguimento di ciò che è privo di forma,
dell’incondizionato Nibbāna – la cessazione della nascita,
dell’invecchiamento e della morte – a meno che non sia associato con la
visione profonda nella natura impermanente di tutto quel che sorge e che
è condizionato, sia esso dotato di forma o privo di forma, inclusi tutti
i modi di esistenza paradisiaca (cf. ad esempio A. 4:125-26).]

Questo dovrebbe essere fatto da chi è abile nel bene +
per raggiungere la condizione di pace.

Che sia valente, retto, onesto, +
mite e gentile, non orgoglioso. +
Appagato, che sia facile recargli sostentamento, +
non affaccendato, ma frugale e sereno. +
In possesso delle sue facoltà, prudente e modesto, +
non avido tra le famiglie. +
E che non faccia la benché minima cosa +
che altri uomini saggi possano deplorare.

(Che poi pensi:) «In felicità e sicurezza, +
che gioisca il cuore di ogni essere. +
Qualsiasi creatura che respiri, +
non importa se debole o ardita, +
senza alcuna eccezione, lunga o grande +
di media grandezza o corta o sottile +
o grossa, visibile o invisibile +
che dimori lontana o vicina, +
nata o in procinto di nascere, +
che il cuore di ogni essere gioisca. +
Che nessuna di esse tradisca la fiducia dell’altra +
né affatto la offenda, +
né che a vicenda si augurino del male +
per rabbia o per vendetta».

Come una madre con la sua vita stessa +
protegge il figlio, il suo unico figlio, +
che lui sconfinatamente estenda +
il suo cuore per abbracciare ogni essere vivente. +
E con amore per tutto il mondo +
che estenda sconfinatamente +
il suo cuore in basso e in alto e tutt’intorno, +
senza riserve, privo di malevolenza o di odio.

Che stia in piedi o seduto, che cammini +
o stia disteso (finché non s’addormenta) +
che persegua questa consapevolezza: +
questa è una Dimora Divina, loro dicono.

Lui che però non ha a che fare con le opinioni, +
è virtuoso, dotato di perfetta visione, +
e non brama più desideri sensoriali: +
di nuovo non nascerà più in un utero.
____
