= La dottrina
:chapter-number: 12

== Questioni varie

[.narrator]
*Primo narratore.* Che cos’è il “Dhamma” che è “ben proclamato” dal
“Medico Supremo”? È un tentativo di realizzare una completa descrizione
del mondo? È un sistema metafisico?

[.voice]
*Prima voce.* Una volta il Beato soggiornava a Sāvatthī, nel Boschetto di
Jeta. Una divinità di nome Rohitassa andò da lui a notte tarda, gli
prestò omaggio e chiese: «Signore, la fine del mondo, nella quale non si
nasce, né si invecchia, né si muore, né si scompare e neanche si
ricompare: è possibile conoscerla o vederla viaggiando fin là?».

«Amico, che ci sia una fine del mondo, nella quale non si nasce, né si
invecchia, né si muore, né si scompare e neanche si ricompare, che possa
essere conosciuta o vista arrivando fin là: questo non lo dico. Non dico
tuttavia che ci sia una fine della sofferenza senza raggiungere la fine
del mondo. Piuttosto è in questa carcassa lunga un braccio, con le sue
percezioni e la sua mente che io descrivo il mondo, l’origine del mondo,
la cessazione del mondo, e la via che conduce alla cessazione del
mondo».

[quote]
____
È assolutamente impossibile +
raggiungere la fine del mondo camminando. +
Nessuno però sfugge alla sofferenza +
a meno che non sia stata raggiunta la fine del mondo.

È un Saggio, un conoscitore del mondo, colui +
che raggiunge la fine del mondo, ed è da lui +
che è stata vissuta la santa vita. +
Conoscendo la fine del mondo egli è in pace +
e non ripone speranza né in questo mondo né nel successivo.
____

[.suttaref]
_S. 2:36; A. 4:46_

Una volta il Beato soggiornava a Kosambī, in una foresta di alberi
_siṃsapa_. Prese poche foglie in mano e chiese ai bhikkhu: «Cosa ne
pensate bhikkhu, sono di più le poche foglie che ho in mano o quelle
degli alberi nella foresta?».

«Le foglie che il Beato ha preso in mano sono poche, Signore. Quelle
nella foresta sono molte di più».

«Allo stesso modo, bhikkhu, le cose che ho conosciuto per conoscenza
diretta sono molte, le cose che vi ho detto sono solo poche. Perché non
ve le ho dette? Perché esse non recano beneficio, progresso nella santa
vita e perché non conducono al distacco, al disincanto, alla cessazione,
all’acquietamento, alla conoscenza diretta, all’Illuminazione, al
Nibbāna. Per questa ragione non ve le ho dette. E quali sono le cose che
vi ho detto? “Questa è la sofferenza, questa è l’origine della
sofferenza, questa è la cessazione della sofferenza, questo è il
Sentiero che conduce alla cessazione della sofferenza”. Queste sono le
cose che vi ho detto. Perché ve le ho dette? Perché esse recano
beneficio, progresso nella santa vita e perché conducono al distacco, al
disincanto, alla cessazione, all’acquietamento, alla conoscenza diretta,
all’Illuminazione, al Nibbāna. Così, bhikkhu, che questo sia il vostro
compito: Questa è la sofferenza, questa è l’origine della sofferenza,
questa è la cessazione della sofferenza, questo è il Sentiero che
conduce alla cessazione della sofferenza».

[.suttaref]
_S. 56:31_

[.narrator]
*Primo narratore.* Non si tratta, allora, di un tentativo di realizzare
una completa descrizione del mondo, sia interiore sia esteriore. È un
sistema metafisico, una costruzione logica coerente? E, se è così, su
quale fondamento poggia?

[.voice]
*Prima voce.* Una volta, quando il Beato era entrato a Rājagaha per la
questua, l’asceta itinerante nudo Kassapa andò da lui e, dopo averlo
salutato, disse: «Qualora il Maestro Gotama acconsentisse a darci una
risposta, vorremmo chiedere una cosa al Maestro Gotama». – «Non è il
momento di fare domande, Kassapa, ci troviamo in mezzo ad abitazioni».
Egli chiese una seconda e una terza volta e ricevette la stessa
risposta. Poi disse: «Non è molto quel che vogliamo chiedere, Maestro
Gotama». – «Domanda, allora, Kassapa, quel che vuoi domandare».

«Com’è che stanno le cose, Maestro Gotama, la sofferenza è una propria
creazione?». – «Non metterla in questi termini, Kassapa». – Allora la
sofferenza è la creazione di un altro?». – «Non metterla in questi
termini, Kassapa». – «Allora la sofferenza è una creazione sia propria
sia di un altro?». «Non metterla in questi termini, Kassapa». – «Allora
la sofferenza non è una creazione propria né di un altro, bensì
accidentale?». – «Non metterla in questi termini, Kassapa». – «Allora
non c’è sofferenza?». – «Non è un dato di fatto che non ci sia la
sofferenza, la sofferenza c’è, Kassapa». – «Allora il Maestro Gotama non
conosce né vede la sofferenza?». – «Non è un dato di fatto che io non
conosca né veda la sofferenza: io sia conosco sia vedo la sofferenza,
Kassapa».

[.suttaref]
_S. 12:17_

Una volta anche l’asceta itinerante Uttiya andò dal Beato e, dopo averlo
salutato, si mise a sedere da un lato. Poi gli chiese: «Com’è, Maestro
Gotama, il mondo è eterno: questa è la sola verità e tutto il resto è
errato?». – «A questo non ho dato risposta, Uttiya». – «Allora il mondo
non è eterno: questa è la sola verità e tutto il resto è errato?». –
«Nemmeno a questo ho dato risposta, Uttiya». – «Allora il mondo è
finito: questa è la sola verità e tutto il resto è errato?». – «Nemmeno
a questo ho dato risposta, Uttiya». – «Allora il mondo è infinito:
questa è la sola verità e tutto il resto è errato?». – «Nemmeno a questo
ho dato risposta, Uttiya». – «Allora, l’anima è la stessa cosa del
corpo: questa è la sola verità e tutto il resto è errato?». – «Nemmeno a
questo ho dato risposta, Uttiya». – «Allora l’anima è una cosa e il
corpo un’altra: questa è la sola verità e tutto il resto è errato?». –
«Nemmeno a questo ho dato risposta, Uttiya». – «Dopo la morte un
Perfetto esiste: questa è la sola verità e tutto il resto è errato?». –
«Nemmeno a questo ho dato risposta, Uttiya». – «Dopo la morte un
Perfetto non esiste: questa è la sola verità e tutto il resto è
errato?». – «Nemmeno a questo ho dato risposta, Uttiya». – «Allora dopo
la morte un Perfetto sia esiste sia non esiste: questa è la sola verità
e tutto il resto è errato?». – «Nemmeno a questo ho dato risposta,
Uttiya». – «Allora dopo la morte un Perfetto né esiste né non esiste:
questa è la sola verità e tutto il resto è errato?». – «Nemmeno a questo
ho dato risposta, Uttiya».

«Perché il Maestro Gotama rifiuta di rispondere quando gli pongo queste
domande? A quali domande risponde allora il Maestro Gotama?».

«Io insegno il Dhamma ai discepoli per mezzo della conoscenza diretta,
Uttiya, per la purificazione degli esseri, per il superamento
dell’afflizione e del lamento, per la fine del dolore e del dispiacere,
per il raggiungimento della meta suprema, per l’ottenimento del
Nibbāna».

«Maestro Gotama, questo Dhamma fornisce una via d’uscita dalla
sofferenza per tutto il mondo, oppure per la metà o per un terzo?».

Quando questo fu detto, il Beato rimase in silenzio.

Allora il venerabile Ānanda pensò: «L’asceta itinerante Uttiya non deve
concepire un punto di vista pernicioso quale “Quando al monaco Gotama è
posta una domanda insolita che mi è tipica e non è di nessun altro, si
trova in difficoltà e non risponde, ciò avviene perché non è in grado di
farlo?”. Ciò gli procurerebbe danno e sofferenza». Così egli disse:
«Amico Uttiya, ti offrirò una similitudine, perché qui alcuni saggi
comprendono il significato di ciò che viene detto tramite la conoscenza
mediante una similitudine. Supponiamo che un re abbia una città con
profondi fossati, forti terrapieni e bastioni, e una sola porta, e abbia
un guardiano saggio, intelligente, sagace che blocchi alla porta chi non
conosce e faccia entrare solamente chi conosce. E siccome lui stesso ha
fatto un giro intorno alla città e non ha visto varchi nei terrapieni né
alcun foro abbastanza grande per farci passare un gatto, può giungere
alla conclusione che esseri viventi più grandi d’una certa dimensione
debbano entrare e uscire usando la porta. Così, amico Uttiya, interesse
di un Perfetto non è che “Mediante questo [Dhamma] trovi una via
d’uscita tutto il mondo, oppure la metà o un terzo”, bensì che “Chiunque
abbia trovato o trovi o troverà una via d’uscita dal mondo della
sofferenza, questo avviene sempre abbandonando i cinque impedimenti –
ossia desiderio di sensorialità, malevolenza, torpore-e-sonnolenza,
agitazione-e-preoccupazione, dubbio – contaminazioni che indeboliscono
la comprensione, e mantenendo in essere i sette fattori
dell’Illuminazione con la mente ben fondata sui quattro fondamenti della
consapevolezza”. La domanda che hai posto al Beato era presentata in
modo sbagliato, per questa ragione il Beato non ha risposto».

[.suttaref]
_A. 10:95_

Un’altra volta l’asceta itinerante Vacchagotta andò dal Beato e scambiò
con lui saluti. Poi gli chiese: «Com’è che stanno le cose, Maestro
Gotama, il sé esiste?». Quando ciò fu detto, il Beato rimase in
silenzio. «Com’è che stanno le cose, Maestro Gotama, il sé non esiste?».
E per la seconda volta il Beato rimase in silenzio. Allora l’asceta
itinerante Vacchagotta si alzò dal luogo in cui sedeva e andò via. Non
molto tempo dopo che se n’era andato il venerabile Ānanda chiese al
Beato: «Signore, com’è che al Beato sono state poste delle domande e lui
non ha risposto?».

«Se quando mi è stato chiesto “Il sé esiste?”. io avessi risposto “Il sé
esiste”, ciò avrebbe implicato la credenza di coloro che sostengono la
teoria dell’eternalismo. E se quando mi è stato chiesto “Il sé non
esiste?”. io avessi risposto “Il sé non esiste”, ciò avrebbe implicato
la credenza di coloro che sostengono la teoria del nichilismo. Inoltre,
se quando mi è stato chiesto “Il sé esiste?” io avessi risposto “Il sé
esiste”, ciò sarebbe stato conforme con la mia conoscenza che tutte le
cose sono non-sé? E se quando mi è stato chiesto “Il sé non esiste? Io
avessi risposto “Il sé non esiste” allora, confuso com’è, l’asceta
itinerante Vacchagotta sarebbe diventato ancor più confuso, pensando:
“Certamente prima avevo un sé e ora non ce l’ho”».

[.suttaref]
_S. 44:10_

Una volta il Beato soggiornava a Sāvatthī e a quel tempo un gran numero
di asceti itineranti e brāhmaṇa di varie sette si erano recati a
Sāvatthī per la questua. Avevano differenti punti di vista, opinioni e
nozioni, e per ottenere supporto contavano sui loro differenti punti di
vista. C’erano alcuni asceti e brāhmaṇa che asserivano e credevano che
«Il mondo è eterno: questa è la sola verità e tutto il resto è errato»,
e altri che asserivano e credevano in ognuno degli altri nove punti di
vista. Litigavano, bisticciavano, disputavano e si ferivano a vicenda
con frecce fatte di parole: «Il Dhamma è così, il Dhamma non è così! Il
Dhamma non è così, il Dhamma è così!».

Allora un gruppo di bhikkhu di ritorno dal giro per la questua lo
raccontò al Beato. Il Beato disse:

«Bhikkhu, una volta a Sāvatthī c’era un re. Egli disse a un uomo:
“Vieni, uomo, riunisci tutti gli uomini che a Sāvatthī sono nati
ciechi”. – “Sì, Signore”, egli rispose. E quando lo ebbe fatto, lo
comunicò al re, il quale disse: “Mostra loro un elefante”. Lo fece
dicendo: “Voi, uomini che siete ciechi fin dalla nascita, così è un
elefante”, e ad alcuni fece toccare la testa dell’elefante, ad altri un
orecchio, ad altri una zanna, ad altri la proboscide, ad altri il corpo,
ad altri una zampa, ad altri la parte posteriore, ad altri la coda e ad
altri ancora il ciuffo di peli alla fine della coda. Poi andò dal re e
gli disse quel che aveva fatto. Il re allora si recò dagli uomini ciechi
fin dalla nascita e chiese loro: “Vi è stato mostrato un elefante?”. –
“Sì, sovrano”. – “Descrivetemi allora com’è un elefante”. Coloro ai
quali era stata fatta toccare la testa dissero “Sovrano, l’elefante è
come una giara”, coloro ai quali era stato fatto toccare un orecchio
dissero “È come un setaccio”, coloro ai quali era stata fatta toccare
una zanna dissero “È come un palo”, coloro ai quali era stata fatta
toccare la proboscide dissero “È come l’asta di un aratro”, coloro ai
quali era stato fatto toccare il corpo dissero “È come un granaio”,
coloro ai quali era stata fatta toccare una zampa dissero “È come la
base di una colonna”, coloro ai quali era stata fatta toccare la parte
posteriore dissero “È come un mortaio”, coloro ai quali era stata fatta
toccare la coda dissero “È come un pestello” e coloro ai quali era stato
fatto toccare il ciuffo di peli alla fine della coda dissero “È come una
scopa”. Si prendevano a pugni, urlando “Un elefante è così, non è così.
Un elefante non è così, è così!”. Il re, però, era compiaciuto. Allo
stesso modo, anche gli asceti itineranti di altre sette sono ciechi e
privi di occhi. Per questa ragione litigano, bisticciano, disputano e si
feriscono a vicenda con frecce fatte di parole: “Il Dhamma è così, il
Dhamma non è così! Il Dhamma non è così, il Dhamma è così!”».

[.suttaref]
_Ud. 6:4_

[.narrator]
*Primo narratore.* Sarebbe perciò un errore definire l’insegnamento del
Buddha sia un tentativo di realizzare una completa descrizione del mondo
sia un sistema metafisico costruito mediante la logica. Esso è allora un
comandamento etico, una religione di fede rivelata o, semplicemente, un
codice comportamentale stoico? Prima di tentare di trovare delle
risposte a queste domande, è necessario un sommario delle dottrine
insegnate. Il materiale contenuto nei Discorsi sembra, nei fatti, avere
piuttosto le caratteristiche del materiale necessario all’elaborazione
di una mappa, per consentire a ognuno di realizzarne una propria, ma che
conduca tutti verso una sola direzione. Queste descrizioni orientate di
sfaccettature dell’esperienza, infatti, consentono a una persona di
valutare la propria posizione e di giudicare da sé cosa sia meglio fare.
I Discorsi offrono non tanto una descrizione quanto, piuttosto, una
serie di descrizioni sovrapposte. In un esame condotto da vicino,
dell’esistenza si rinviene sempre un qualcosa che ha le qualità d’un
miraggio e, dietro l’apparenza, d’un paradosso, ma delle conclusioni non
è mai possibile individuarle. Le numerosissime diverse sfaccettature
offerte nei sutta con innumerevoli ripetizioni di alcune di tali
sfaccettature in varie combinazioni e contesti, ricorda un insieme di
fotografie aeree mediante le quali si debbano realizzare delle mappe. Le
sfaccettature presenti nei Discorsi sono tutte orientate verso la
cessazione della sofferenza, grazie a una bussola i cui quattro punti
cardinali sono le Quattro Nobili Verità. Proviamo a realizzare una mappa
campione da una parte di questi materiali. Siccome da qualche parte pur
si deve cominciare, possiamo farlo prendendo la nascita come punto di
partenza, che, assieme alla morte, rappresenta per l’uomo comune un
evento quotidiano e, nello stesso tempo, un mistero irrisolvibile.

== Non c’è un Primo Inizio

[.narrator]
*Secondo narratore.* La coscienza è concepibile senza un passato? Si può
dire che abbia un inizio?

[.voice]
*Prima voce.* «Bhikkhu, il cerchio non ha inizio. Degli esseri che
viaggiano e arrancano in questo cerchio, rinserrati come sono
nell’ignoranza e incatenati dalla brama, non si può descrivere alcun
inizio».

[.suttaref]
_S. 15:1_

«Che sia io sia voi abbiamo dovuto viaggiare e arrancare in questo lungo
cerchio è dovuto al fatto che non abbiamo scoperto, non abbiamo
penetrato quattro verità. Quali quattro? Esse sono: (I) la Nobile Verità
della Sofferenza, (II) la Nobile Verità dell’Origine della Sofferenza,
(III) la Nobile Verità della Cessazione della Sofferenza, e (IV) la
Nobile Verità del Sentiero che conduce alla Cessazione della
Sofferenza».

[.suttaref]
_D. 16_

== Le Quattro Nobili Verità

[.narrator]
*Secondo narratore.* Ecco una descrizione delle Quattro Nobili Verità.

[.voice]
*Prima voce.* I. «Qual è la Nobile Verità della Sofferenza? La nascita è
sofferenza, la vecchiaia è sofferenza, la malattia è sofferenza, la
morte è sofferenza. L’afflizione, il lamento, il dolore, il dispiacere e
la disperazione sono sofferenza. Associarsi con quel che si detesta è
sofferenza, separarsi da quel che si ama è sofferenza, non ottenere ciò
che si vuole è sofferenza. In breve, i cinque aggregati affetti
dall’attaccamento sono sofferenza».footnote:[I “cinque aggregati affetti dall’attaccamento”
(_upādāna-kkhanda_) possono essere considerati come le cinque apposite
“classi” o categorie sotto le quali ogni componente dell’esperienza (nel
senso più ampio del termine) che si trova a sorgere può essere
raggruppato per l’analisi e la discussione. Esse non hanno esistenza
separata dai componenti che li rappresentano. Quel che rappresentano non
si verifica separatamente. Essi sono d’altra parte interdipendenti, come
un bicchiere di vetro implica contemporaneamente materiale (il vetro),
affettività (attraente, non attraente o indifferente), caratteristiche
individuali (forma, colore, ecc.), determinatezza (essere formato)
quanto all’utilità (tutte cose che sono costitutive di “nome-e-forma”),
e la coscienza di tutto ciò che non è.]

[.suttaref]
_S. 56:11_

{empty}II. «Qual è la Nobile Verità dell’Origine della Sofferenza? È la brama,
che rinnova l’esistenza e che è accompagnata dal diletto e dal
desiderio, dall’assaporare questo e quello: in altre parole, brama per i
desideri sensoriali, brama per l’esistenza, brama per la non-esistenza.
Su cosa sorge e fiorisce, però, questa brama? Ovunque ci sia qualcosa
che sembra amabile e gratificante, su questo sorge e fiorisce».

[.suttaref]
_D. 22_

«È con l’ignoranza quale condizione che le formazioni [mentali] giungono
a esistere; con le formazioni [mentali] quale condizione, la coscienza;
con la coscienza quale condizione, nome-e-forma; con nome-e-forma quale
condizione, la sestuplice base per il contatto; con la sestuplice base
quale condizione, il contatto; con il contatto quale condizione, la
sensazione; con la sensazione quale condizione, la brama; con la brama
quale condizione, l’attaccamento; con l’attaccamento quale condizione,
l’esistenza; con l’esistenza quale condizione, la nascita; con la
nascita quale condizione, giungono all’esistenza la vecchiaia e la
morte, e anche l’afflizione, il lamento, il dolore, il dispiacere e la
disperazione. Così ha origine tutto questo aggregato di sofferenza.
Questa è detta Nobile Verità dell’Origine della Sofferenza».

[.suttaref]
_A. 3:61_

{empty}III. «Qual è la Nobile Verità della Cessazione della sofferenza? È lo
svanire senza residuo e la cessazione di quella stessa brama, il
rifiuto, l’abbandono, la rinuncia a essa. Ma dove questa brama è
abbandonata e fatta cessare? Ovunque ci sia qualcosa che sembra amabile
e gratificante, è qui che essa è abbandonata e condotta a cessazione».

[.suttaref]
_D. 22_

Con lo svanire senza residuo e la cessazione dell’ignoranza, c’è la
cessazione delle formazioni [mentali]; con la cessazione delle
formazioni [mentali], la cessazione della coscienza … con la cessazione
della nascita, la vecchiaia e la morte cessano, e anche l’afflizione, il
lamento, il dolore, il dispiacere e la disperazione. Così c’è la
cessazione di tutto questo aggregato di sofferenza. Questa è detta
Nobile Verità della Cessazione della Sofferenza».

[.suttaref]
_A. 3:61_

{empty}IV. «Qual è la Nobile Verità del Sentiero che conduce alla Cessazione
della Sofferenza? È il Nobile Ottuplice Sentiero, ossia: retta visione,
retta intenzione, retta parola, retta azione, retto modo di vivere,
retto sforzo, retta consapevolezza, retta concentrazione».

[.suttaref]
_D. 22_

«Di queste Quattro Nobili Verità, la Nobile Verità della Sofferenza deve
essere penetrata con piena comprensione della sofferenza; la Nobile
Verità dell’Origine della Sofferenza deve essere penetrata mediante
l’abbandono della brama; la Nobile Verità della Cessazione della
Sofferenza deve essere penetrata realizzando la cessazione della brama;
la Nobile Verità del Sentiero che conduce alla Cessazione della
Sofferenza deve essere penetrata mantenendo in essere il Nobile
Ottuplice Sentiero».

[.suttaref]
_S. 56:11 e 29 (adattati)_

«Queste Quattro Nobili Verità (Realtà) sono reali, non irreali, non
diverse da quello che sembrano».

[.suttaref]
_S. 56:27_

[.narrator]
*Primo narratore.* Ognuna delle Quattro Nobili Verità è analizzata e
definita dettagliatamente.

== La Verità della Sofferenza

[.narrator]
*Secondo narratore.* È stato detto che la Verità della Sofferenza era «in
breve, i cinque aggregati affetti dall’attaccamento». Ecco una
definizione di essi.

[.voice]
*Prima voce.* I. «Quali sono i cinque aggregati affetti dall’attaccamento?
Essi sono l’aggregato della forma (materiale) affetto dall’attaccamento,
l’aggregato della sensazione affetto dall’attaccamento, l’aggregato
della percezione affetto dall’attaccamento, l’aggregato delle formazioni
[mentali] affetto dall’attaccamento e l’aggregato della coscienza
affetto dall’attaccamento».

[.suttaref]
_D. 22_

«Perché si dice “forma”? Essa è deformata (_ruppati_), ecco perché è
chiamata “forma” (_rūpa_). Deformata da che cosa? Dal freddo e dal
caldo, dalla fame e dalle sete, dal contatto con i tafani, le zanzare,
il vento, le scottature del sole e le cose striscianti».

[.suttaref]
_S. 22:79_

«Che cos’è la forma? Le quattro grandi entità e ogni forma ricavata da
esse per mezzo dell’attaccamento sono chiamate forma».

[.suttaref]
_S. 22:56_

«Ogni cosa in un essere, appartenente a un essere, che sia solida,
solidificata e attaccata [a qualcosa di organico], come capelli, peli,
unghie, denti, pelle, carne, muscoli, ossa, midollo osseo, reni, cuore,
fegato, diaframma, milza, polmoni, intestino, viscere, cibo non
digerito, feci, o qualsiasi altra cosa in un essere, che appartiene a un
essere, che sia solida, solidificata e attaccata: ciò è chiamato
elemento terrafootnote:[La “terra” rappresenta la solidità, l’“acqua” la coesione,
il “fuoco” sia la temperatura sia la maturazione, l’“aria” sia
l’estensione (distensione) sia il moto.] in un essere. Ora, l’elemento terra in
un essere e l’elemento terra esteriore sono solo elemento terra».

«Ogni cosa in un essere … che sia acqua, acquosa e attaccata, come bile,
flegma, pus, sangue, sudore, grasso, lacrime, materia oleosa, saliva,
muco, liquido sinoviale, urina, o qualsiasi altra cosa in un essere …
che sia acqua, acquosa e attaccata: ciò è chiamato elemento acqua in un
essere. Ora, l’elemento acqua in un essere e l’elemento acqua esteriore
sono solo elemento acqua».

«Ogni cosa in un essere … che sia fuoco, infuocata e attaccata, come ciò
per mezzo del quale ci si scalda, si invecchia e ci si consuma, e per
mezzo del quale ciò che è mangiato, bevuto, masticato e gustato viene
digerito e assimilato, o qualsiasi altra cosa in un essere … che sia
fuoco, infuocata e attaccata: ciò è chiamato elemento fuoco in un
essere. Ora, l’elemento fuoco in un essere e l’elemento fuoco esteriore
sono solo elemento fuoco».

«Ogni cosa in un essere … che sia aria, ariosa e attaccata, come i venti
(forze) che vanno verso l’alto, i venti (forze) che vanno verso il
basso, i venti (forze) nella pancia e nelle viscere, i venti (forze) che
pervadono tutte le membra, l’inspirazione e l’espirazione, o qualsiasi
altra cosa in un essere … che sia aria, ariosa e attaccata: ciò è
chiamato elemento aria in un essere. Ora, l’elemento aria in un essere e
l’elemento aria esteriore sono solo elemento aria».

«Ogni cosa in un essere … che sia spazio, spaziosa e attaccata, come il
foro dell’orecchio, il foro della bocca, la porta della bocca, e ciò
(l’apertura) mediante cui si deglutisce quel che si mangia, beve,
mastica e assapora, e ciò in cui questo è contenuto, e ciò mediante cui
questo passa verso il basso, o qualsiasi altra cosa in un essere … che
sia spazio, spazioso e attaccato: ciò è chiamato elemento spazio [in un
essere]. Ora, l’elemento spazio in un essere e l’elemento spazio
esteriore sono solo elemento spazio … E l’elemento spazio non ha alcun
luogo nel quale può esistere di per sé».

[.suttaref]
_M. 62_

«Qualsiasi forma, passata, futura o presente, in un essere oppure
esteriore, grossolana o sottile, inferiore o superiore, lontana o
vicina, che sia affetta da contaminazioni e provochi l’attaccamento:
essa è chiamata aggregato della forma affetto da attaccamento».

[.suttaref]
_S. 22:48_

«Perché si dice “sensazione”? È sentita, ecco perché è chiamata
“sensazione”. Sentita come che cosa? Sentita come piacere, come dolore,
oppure come né-dolore-né-piacere».

[.suttaref]
_S. 22:79; cf. M. 43_

«Qualsiasi cosa sia sentita con il corpo o con la mente come piacevole e
gratificante è sensazione piacevole. Qualsiasi cosa sia sentita con il
corpo o con la mente come dolorosa e lesiva è sensazione dolorosa.
Qualsiasi cosa sia sentita con il corpo o con la mente come né
gratificante né lesiva è sensazione né-dolorosa-né-piacevole … La
sensazione piacevole è piacevole in ragione della presenza e dolorosa in
ragione del cambiamento. La sensazione dolorosa è dolorosa in ragione
della presenza e piacevole in ragione del cambiamento. La sensazione
né-dolorosa-né-piacevole è piacevole in ragione della conoscenza e
dolorosa in ragione della mancanza di conoscenza».

[.suttaref]
_M. 44_

«Ci sono questi sei corpi di sensazione: la sensazione nata dal contatto
con l’occhio, dal contatto con l’orecchio, dal contatto con il naso, dal
contatto con la lingua, dal contatto con il corpo e dal contatto con la
mente».

[.suttaref]
_S. 22:56_

«Qualsiasi sensazione … che sia affetta da contaminazioni e provochi
l’attaccamento: essa è chiamata aggregato della sensazione affetto da
attaccamento».

[.suttaref]
_S. 22:48_

«Perché si dice “percezione”? È percepita, ecco perché è chiamata
“percezione”. Percepita come che cosa? Percepita, ad esempio, blu e
gialla e rossa e bianca».

[.suttaref]
_S. 22:79_

«Ci sono questi sei corpi della percezione: percezione delle forme
(visibili), dei suoni, degli odori, dei sapori, degli oggetti tangibili
e delle idee».

[.suttaref]
_S. 22:56_

«Qualsiasi percezione … che sia affetta da contaminazioni e provochi
l’attaccamento: essa è chiamata aggregato della percezione affetto da
attaccamento».

[.suttaref]
_S. 22:48_

«Perché si dice “formazioni”? Danno forma al formato, ecco perché si
chiamano “formazioni”. Che cos’è il formato al quale danno forma? La
forma (materiale), in quanto stato (essenza) della forma, è il formato
(composto) al quale esse danno forma (il composto). La sensazione, in
quanto stato della sensazione, è il formato al quale esse danno forma.
La percezione, in quanto stato della percezione, è il formato al quale
esse danno forma. Le formazioni, in quanto stato delle formazioni, è il
formato al quale esse danno forma. La coscienza, in quanto stato della
coscienza, è il formato al quale esse danno forma».footnote:[«Qualsiasi
cosa abbia la caratteristica di dare forma
dovrebbe essere compresa, tutt’insieme, come aggregato delle formazioni
… ha la caratteristica di agglomerare … (ed) ha la funzione di
accumulare»; cf. _The Path of Purification (Visuddhimagga)_, tr. da
Ñāṇamoli, XIV, 131 (Nyp.).]

[.suttaref]
_S. 22:79_

«Tre tipi di formazioni: formazione del merito (in quanto azione che
matura in piacere), formazione del demerito (in quanto azione che matura
in dolore), e formazione dell’imperturbabilità (in quanto azione, ossia,
la meditazione, che matura in stati privi di forma che, per il tempo che
durano, non sono perturbati dalla percezione della forma, della
resistenza o della differenza)».

[.suttaref]
_D. 33_

«Tre formazioni: inspirazione ed espirazione appartengono a un corpo,
queste sono cose legate a un corpo, per questa ragione sono formazioni
corporee. Dopo aver pensato ed esplorato, si irrompe nel parlare, per
questa ragione pensare ed esplorare sono formazioni verbali. Percezione
e sensazione appartengono alla coscienza, queste sono cose legate alla
coscienza, per questa ragione esse sono formazioni mentali».

[.suttaref]
_M. 44; cf. M. 9_

«Che cosa sono le formazioni? Ci sono sei corpi di
scelta:footnote:[_Cetanā_, di solito tradotto con “volizione”,
volontà (Nyp.).] scelta tra le forme visibili, tra i suoni, tra
gli odori, tra i sapori, tra gli oggetti tangibili e tra gli oggetti
mentali».

[.suttaref]
_S. 22:56_

«Chiamo azione la scelta».

[.suttaref]
_A. 6:63_

«Qualsiasi formazione … che sia affetta da contaminazioni e provochi
l’attaccamento: essa è chiamata aggregato delle formazioni affetto da
attaccamento».

[.suttaref]
_S. 22:48_

«Perché si dice “coscienza”? Essa ha cognizione, ecco perché si chiama
“coscienza”. Di che cosa ha cognizione? Essa ha cognizione, ad esempio,
dell’aspro, dell’amaro, del pungente, del dolce, dell’alcalino, del non
alcalino, del salato e del non salato».

[.suttaref]
_S. 22:79_

«Di che cosa ha cognizione la coscienza? Essa ha cognizione, ad esempio,
che c’è il piacere, che c’è il dolore, che c’è né-dolore-né-piacere».

[.suttaref]
_M. 43, 140_

«Ci sono questi sei corpi della coscienza: coscienza visiva, coscienza
uditiva, coscienza olfattiva, coscienza gustativa, coscienza corporea e
coscienza mentale».

[.suttaref]
_S. 22:56_

«La coscienza ha un nome in base alle condizioni che la fanno sorgere.
Quando la coscienza sorge a causa dell’occhio e delle forme, è chiamata
coscienza visiva. Se sorge a causa dell’orecchio e dei suoni, coscienza
uditiva ... Se sorge a causa della mente e delle idee, coscienza
mentale».

[.suttaref]
_M. 38_

«Sensazione, percezione e coscienza sono congiunte, non disgiunte, ed è
impossibile separarle una dall’altra al fine di descrivere le loro
differenti potenzialità. Perché quando uno ha una sensazione, è quello
stesso a percepire, e quando uno ha una percezione, è quello stesso ad
averne cognizione. Mediante la mera coscienza mentale disgiunta dalle
cinque facoltà sensoriali, la base (esterna) che consiste
nell’infinitezza dello spazio può essere conosciuta come “spazio
infinito”. La base (esterna) che consiste nella infinitezza della
coscienza può essere conosciuta come “coscienza infinita”. E la base
(esterna) che consiste nel nulla può essere conosciuta come “nulla-è”.
Un’idea conoscibile è compresa mediante l’occhio della comprensione».

[.suttaref]
_M. 43_

«La coscienza per la sua esistenza poggia su un dualismo (il dualismo
dell’interiorità e le basi esterne per il contatto).

[.suttaref]
_S. 35:93_

«Qualsiasi coscienza, passata, futura o presente, in un essere oppure
esteriore, grossolana o sottile, inferiore o superiore, lontana o
vicina, che sia affetta da contaminazioni e provochi l’attaccamento:
essa è chiamata aggregato della coscienza affetto da attaccamento».

[.suttaref]
_S. 22:48_

«Questi cinque aggregati affetti da attaccamento hanno il desiderio per
la loro radice ... Le quattro grandi entità (di terra, acqua, fuoco e
aria) sono la causa e la condizione per descrivere l’aggregato della
forma. Il contatto è la causa e la condizione per descrivere gli
aggregati della sensazione, della percezione e delle formazioni
[mentali]. Nome-e-forma è la causa e la condizione per descrivere
l’aggregato della coscienza».

[.suttaref]
_M. 109_

«Qualsiasi monaco o brāhmaṇa ricordi la sua vita passata nei suoi vari
modi, ricorda i cinque aggregati affetti da attaccamento o uno o l’altro
di essi».

[.suttaref]
_S. 22:79_

== La Verità dell’Origine della Sofferenza

[.narrator]
*Secondo narratore.* Ecco alcune definizioni dettagliate della Seconda
Nobile Verità.

[.voice]
*Prima voce.* «Questi cinque aggregati affetti dall’attaccamento provano
desiderio per la loro radice ... L’attaccamento non è la stessa cosa dei
cinque aggregati affetti dall’attaccamento, né è qualcosa di separato da
essi. È il desiderio e la brama in essi contenuto che è l’attaccamento».

[.suttaref]
_M. 109_

«Quello giunge all’esistenza quando c’è questo, quello sorge con il
sorgere di questo».footnote:[Nel senso di condizione necessaria.]

[.suttaref]
_M. 38_

«(Nell’esposizione della genesi interdipendente:)footnote:[Sulla genesi
interdipendente, o originazione interdipendente
e coproduzione condizionata, si veda _The Path of Purification_, cap.
XVII.] Che cos’è l’invecchiamento? Nei vari generi di esseri è l’invecchiare, la
vecchiaia, i denti che si rompono, il grigiore dei capelli e la
rugosità, il declino della vita e l’indebolimento delle facoltà
sensoriali.

Che cos’è la morte? Nei vari generi di esseri è la
scomparsa, il trapasso, la dissoluzione, lo scomparire, il morire, il
completamento del tempo, la dissoluzione degli aggregati, il giacere
della carcassa.

Che cos’è la nascita? Nei vari generi di esseri è la
nascita, il venire alla nascita, il depositarsi in un utero, la
generazione, la manifestazione degli aggregati, l’acquisizione delle
basi di contatto.

Che cos’è l’esistenza? Tre sono i tipi di esistenza:
l’esistenza nella modalità del desiderio sensoriale, l’esistenza nella
modalità della forma, l’esistenza nella modalità del senza forma. Che
cos’è l’attaccamento? Quattro sono le varietà di attaccamento:
l’attaccamento come abitudine al desiderio sensoriale, l’attaccamento
come abitudine all’errata visione, l’attaccamento come abitudine (al
fraintendimento) della virtù e del dovere,footnote:[_Sīlabbatupādāna_,
l’attaccamento a riti e rituali (Nyp.).] e
l’attaccamento come abitudine alla teoria del sé.

Che cos’è la brama?
Sei sono i corpi della brama: la brama per le forme visibili, per i
suoni, per gli odori, per i sapori, per gli oggetti tangibili e per le
idee.

Che cos’è la sensazione? Sei sono i corpi (delle tre specie) della
sensazione: sensazione nata dal contatto con l’occhio, dal contatto con
l’orecchio, dal contatto con il naso, dal contatto con la lingua, dal
contatto con il corpo e dal contatto con la mente.

Che cos’è il
contatto?footnote:[Il “contatto” è contatto tra l’“in-sé” e l’“esterno” (ad
esempio, la vista insieme a ciò che è visto), il quale è reso possibile
solo dalla presenza della coscienza (ad esempio, coscienza visiva). È
perciò un fattore basilare nell’essenziale complessità di qualsiasi cosa
sorga, sia percepita e formata, tanto dai cinque sensi quanto dalla
mente, sia dai sensi e dalla mente insieme.] Sei sono i corpi del contatto: il contatto
con l’occhio, il contatto con l’orecchio, il contatto con il naso, il
contatto con la lingua, il contatto con il corpo e il contatto con la
mente.

Che cos’è la sestuplice base? È la base dell’occhio, la base
dell’orecchio, la base del naso, la base della lingua, la base del corpo
e la base della mente.

Che cos’è nome-e-forma?footnote:[“Nome-e-forma”
è contemporaneamente il percepire e quel che
è percepito, esperito e riconosciuto (“nominato”). È l’immaginato
insieme alla materia, che insieme costituiscono la forma
individualizzata e soggettivamente determinata di un oggetto. Nei sutta,
però, essa non include la coscienza, grazie alla quale ciò è reso
possibile. La successiva letteratura include la coscienza all’interno
del “nome”, creando così le basi per un’opposizione tra mente e materia
priva di riscontri nel Canone.] Quel che
è chiamato nome comprende la sensazione, la percezione, la
scelta,footnote:[Altre traduzioni di _cetanā_ (qui reso con “scelta”) sono
“volizione” e “intenzione”.] il contatto e l’attenzione; quel che è
chiamato forma comprende i quattro grandi elementi e qualsiasi forma da
essi derivata mediante l’attaccamento, perciò questo nome e questa forma
sono ciò che viene chiamato nome-e-forma.

Che cos’è la coscienza? Sei
sono i corpi della coscienza: coscienza visiva, coscienza uditiva,
coscienza olfattiva, coscienza gustativa, coscienza corporea e coscienza
mentale.

Che cosa sono le formazioni? Tre sono le formazioni: formazioni
corporee, formazioni verbali e formazioni mentali.

Che cos’è
l’ignoranza? È la nescienza in relazione alla sofferenza, all’origine
della sofferenza, alla cessazione della sofferenza e al sentiero che
conduce alla cessazione della sofferenza».

[.suttaref]
_S. 12:2_

«In dipendenza dall’occhio e dalle forme visibili, sorge la coscienza
visiva. La coincidenza dei tre è data dal contatto. Con il contatto
quale condizione, la sensazione. Con la sensazione quale condizione, la
brama. Ecco come ha origine la sofferenza (e così con l’orecchio ... la
mente)».

[.suttaref]
_S. 12:43_

«Infiammato dalla brama, reso furente dall’odio, confuso dall’illusione,
da essi trasceso e con la mente ossessionata, un uomo sceglie per la
propria afflizione, per l’afflizione degli altri, per l’afflizione
propria e per quella degli altri, e sperimenta dolore e afflizione».

[.suttaref]
_A. 3:55_

«Gli esseri sono possessori delle loro azioni, eredi delle loro azioni,
hanno le loro azioni come progenitori, le azioni come loro congiunti (e
responsabilità), le azioni come loro rifugio, sono le azioni che
differenziano gli esseri in inferiori e superiori».

[.suttaref]
_M. 135_

«Che cosa sono vecchie azioni? Occhio, orecchio, naso, lingua, corpo
sono vecchie azioni (già) determinate e scelte che devono essere
sperimentate per essere viste. Che cosa sono le nuove azioni? È
qualsiasi azione che si compia ora, sia per mezzo del corpo, della
parola o della mente».

[.suttaref]
_S. 35:145_

«Questo corpo non appartiene a voi o ad altri, ma è azione passata (già)
determinata e scelta che deve essere sperimentata per essere vista».

[.suttaref]
_S. 12:37_

«Chiamo azione la scelta. È scegliendo che un uomo agisce con il corpo,
con la parola e con la mente. Ci sono azioni la cui maturazione sarà
sperimentata nell’inferno, nel regno degli spiriti, in un utero animale,
tra gli esseri umani e nei mondi paradisiaci. Le azioni maturano in tre
modi; possono maturare qui e ora, ricomparendo, oppure, al di là di
questo, in un qualche altro processo vitale».

[.suttaref]
_A. 6:63_

«Le azioni compiute dietro spinta della brama, dell’odio o
dell’illusione maturano ovunque sia generato un sé individuale, e
ovunque queste azioni maturino, là viene sperimentata la loro
maturazione, sia qui e ora o in un successivo ricomparire oppure in un
qualche altro processo vitale».

[.suttaref]
_A. 3:33_

«Ci sono quattro cose incommensurabili, che non possono essere misurate,
e un tentativo di concepirle condurrebbe a frustrazione e follia. Quali
quattro? Esse sono la sfera d’influsso dei Buddha, la sfera d’influsso
di chi ha raggiunto i jhāna, la maturazione delle azioni e la stima del
mondo».

[.suttaref]
_A. 4:77_

«Il mondo è condotto dalla mente».

[.suttaref]
_S. 1:72_

== La Verità della Cessazione della Sofferenza

[.narrator]
*Secondo narratore.* Ecco alcune definizioni dettagliate della Terza
Nobile Verità.

[.voice]
*Prima voce.* «Quello non giunge all’esistenza quando non c’è questo,
quello cessa con la cessazione di questo».

[.suttaref]
_M. 38_

«In dipendenza dall’occhio e dalle forme visibili, sorge la coscienza
visiva. La coincidenza dei tre è data dal contatto. Con il contatto
quale condizione, là sorge quel che è sentito come piacevole, o
doloroso, oppure né-doloroso-né-piacevole. Se, sperimentando il contatto
con una sensazione piacevole, non la si assapora, né le si dà il
benvenuto e nemmeno la si accoglie, e se non vi è più la soggiacente
tendenza di fondo a provare desiderio per essa. – Se, sperimentando il
contatto con una sensazione dolorosa, non si prova dispiacere, né ci si
lamenta e nemmeno ci si batte il petto, si piange e ci si sconvolge, e
se non vi è più la soggiacente tendenza di fondo a resistere a essa. –
Se, sperimentando il contatto con una sensazione né-dolorosa-né-
piacevole, si comprende, così com’essa è in realtà, il sorgere, lo
scomparire, la gratificazione, la pericolosa inadeguatezza e la via di
fuga nel caso di quella sensazione, e se non vi è più la soggiacente
tendenza di fondo a ignorarla. – È allora in verità che si può porre
fine alla sofferenza mediante l’abbandono della soggiacente tendenza di
fondo a provare desiderio per la sensazione piacevole, mediante
l’eliminazione della soggiacente tendenza di fondo a resistere alla
sensazione dolorosa e mediante l’abolizione della soggiacente tendenza
di fondo a ignorare la sensazione né-dolorosa-né-piacevole: tutto questo
è possibile».

[.suttaref]
_M. 148_

«Quando la brama, l’odio e l’illusione sono abbandonate, un uomo non
sceglie per la propria afflizione, per l’afflizione degli altri, per
l’afflizione propria e per quella degli altri. In questo modo giunge in
essere l’estinzione qui e ora che, senza indugio, invita
all’investigazione e conduce verso l’interiorità, e che è [direttamente]
sperimentabile dal saggio.

[.suttaref]
_A. 3:55_

«Le azioni compiute sulla base della non-brama, del nonodio e della
non-illusione, sono compiute quando la brama, l’odio e l’illusione sono
scomparse, sono state abbandonate, [eliminate,] recise alla radice, rese
come un ceppo di palma, abolite e non più soggette a sorgere in futuro».

[.suttaref]
_A. 3:33_

«Gli stati privi di forma sono più sereni degli stati dotati di forma,
la cessazione è più serena degli stati privi di
forma».footnote:[È necessario evitare di confondere il “privo di forma”
(_arūpa_), che è un tipo di esistenza (_bhava_), con “non-formato” (o
“incondizionato”, _asankhata_), che è ciò che non ha formazioni (o
condizioni, _sankhāra_). Quest’ultimo è un termine per il Nibbāna. Il
“privo di forma” è sempre condizionato.]

[.suttaref]
_Iti. 73_

«C’è quella base (esterna) ove non (c’è) terra, acqua, fuoco, aria, e
neanche una base consistente dell’infinità dello spazio, una base
consistente dell’infinità della coscienza, una base consistente del
nulla-è, una base consistente della né-percezione-né-non-percezione, e
neanche questo mondo, un altro mondo, la luna o il sole. E questo io lo
chiamo né venire, né andare, né stare, né morire, né ricomparire. Non ha
base, non ha evoluzione, non ha supporto. È la fine della sofferenza».

[quote]
____
Il Non-Condizionato è difficile da vedere, +
non è facile vedere la Verità. +
Per conoscere bisogna togliere il velo alla brama, +
per vedere bisogna essersi affrancati dal possesso.
____

«C’è un non-nato, un non-condotto-all’esistenza, un non-fatto, un
non-formato. Se non ci fosse, non si potrebbe far conoscere una via
d’uscita a chi è nato, condotto all’esistenza, fatto, formato. Siccome
c’è un non-nato, un non-condotto-all’esistenza, un non-fatto, un
non-formato è perciò possibile descrivere una via d’uscita a chi è nato,
condotto all’esistenza, fatto, formato».

[.suttaref]
_Ud. 8:1-3_

«Ci sono due elementi del Nibbāna. Quali due? C’è un elemento del
Nibbāna con residuo del passato attaccamento e l’elemento del Nibbāna
senza residuo del passato attaccamento. Qual è l’elemento del Nibbāna
con residuo del passato attaccamento? Ecco un bhikkhu che è un Arahant
con le contaminazioni esaurite, che ha vissuto la vita [santa], che ha
fatto quel che doveva essere fatto, che ha poggiato il fardello, che ha
raggiunto lo scopo supremo, che ha distrutto le catene dell’esistenza e
che si è completamente liberato mediante la conoscenza finale. Restano
le sue cinque facoltà sensoriali, in ragione della cui presenza egli
ancora incontra il piacevole e lo spiacevole, ancora sperimenta il
piacevole e il doloroso. È in lui l’esaurimento della brama, dell’odio e
dell’illusione che è chiamato elemento del Nibbāna con residuo del
passato attaccamento. E qual è l’elemento del Nibbāna senza residuo del
passato attaccamento? Ecco un bhikkhu che è un Arahant [con le
contaminazioni esaurite,] che ha vissuto la vita [santa] ... che si è
completamente liberato mediante la conoscenza finale. Tutte le
sensazioni che in lui sono provate, poiché egli non le assapora, si
raffreddano qui, proprio in questa vita: questo è chiamato elemento del
Nibbāna senza residuo del passato attaccamento».

[.suttaref]
_Iti. 44_

«Quel che è l’esaurimento della brama, dell’odio e dell’illusione è
chiamato Nibbāna».

[.suttaref]
_S. 38:1_

[quote]
____
«Proprio come una fiamma soffiata via dalla forza del vento, +
Upasīva», disse il Beato, +
«si spegne, e come tale non può più essere designata, +
così pure il Saggio Silenzioso, essendosi liberato dal nome-corpo, +
si spegne, e come tale non può più essere designato».

«Quando allora egli se n’è così andato, non esiste più? +
Oppure egli è reso immortale per l’eternità? +
Piaccia al Saggio chiarirmi questo punto, +
poiché si tratta d’una condizione che egli ha compreso».

«Non c’è modo di definire chi se n’è così andato, +
Upasīva», disse il Beato, +
«e nulla di lui si può dire, +
perché quando tutte le idee sono state abolite, +
sono stati aboliti anche tutti i modi di dire».
____

[.suttaref]
_Sn. 5:7_

== La Verità del Sentiero

[.narrator]
*Secondo narratore.* La Quarta Nobile Verità è il Nobile Ottuplice
Sentiero. Ognuna delle sue otto componenti necessita di essere definita
separatamente.

== Retta visione

[.voice]
*Prima voce.* «Proprio come l’alba annuncia e prevede il sorgere del sole,
così la retta visione annuncia e prevede la penetrazione delle Quattro
Nobili Verità in accordo con quel che esse in realtà sono».

[.suttaref]
_S. 56:37_

[.narrator]
*Secondo narratore.* La retta visione ha molte sfaccettature. Osserviamole
una per una, iniziando con la “maturazione dell’azione” che, in certe
forme e con alcune riserve, è pure condivisa con altri insegnamenti.

[.voice]
*Prima voce.* «Viene prima la retta visione.footnote:[Fino ad ora sono stati
offerti solo dettagli analitici
delle prime tre Nobili Verità. Qui incontreremo mere descrizioni che ci
aiutano a comprenderle.] Come? Si
comprende l’errata visione come errata visione e si comprende la retta
visione come retta visione. Che cos’è l’errata visione? La visione che
non c’è niente di dato, offerto o sacrificato,footnote:[Ciò significa che
in queste azioni non c’è significato morale (Nyp.).] che
non c’è frutto o maturazione delle buone e delle cattive azioni, non c’è
questo mondo né un altro mondo, non c’è madre né padre, non ci sono
esseri che compaiono, non ci sono monaci buoni e virtuosi e brāhmaṇa che
hanno realizzato se stessi mediante conoscenza diretta e dichiarato
[com’è] questo mondo e l’altro mondo: questa è errata visione».

«Che cos’è la retta visione? Ci sono due tipi di retta visione: c’è
quella affetta da contaminazioni, che porta meriti e matura negli
essenziali dell’esistenza. E c’è la retta visione degli Esseri Nobili
priva di contaminazioni, che è sovramondana ed è un fattore del
Sentiero. Che cos’è la retta visione affetta da contaminazioni? La
visione che c’è quel che è dato, offerto o sacrificato, che c’è frutto e
maturazione delle buone e delle cattive azioni, e che c’è questo mondo e
un altro mondo, madre e padre, ed esseri che compaiono, e monaci buoni e
virtuosi e brāhmaṇa che hanno realizzato se stessi mediante conoscenza
diretta e dichiarato [com’è] questo mondo e l’altro mondo: questa è
retta visione affetta da contaminazioni che porta meriti e matura negli
essenziali dell’esistenza. E che cos’è la retta visione degli Esseri
Nobili? Ogni comprensione, facoltà di comprensione, potere di
comprensione, fattore dell’Illuminazione d’investigazione degli stati,
retta visione come fattore del Sentiero, in chi ha la mente nobilitata e
pura, possiede il Sentiero e lo mantiene in essere: questa è la retta
visione degli Esseri Nobili priva di contaminazioni, che è sovramondana
ed è un fattore del Sentiero».

[.suttaref]
_M. 117_

[.narrator]
*Secondo narratore.* Ancora, è la retta visione della genesi
interdipendente – la struttura basilare dell’“insegnamento peculiare ai
Buddha” e la prima delle nuove scoperte fatte dal Buddha. Niente può
sorgere da sé, senza il supporto di altre cose dalle quali l’esistenza
di una cosa dipende.

[.voice]
*Seconda voce.*

[quote]
____
Il Perfetto ha dichiarato la causa +
del sorgere delle cose condizionate, +
e anche quel che conduce alla loro cessazione: +
questa è la dottrina predicata dal Grande Monaco.
____

«La pura, immacolata visione del Dhamma sorse in lui: tutto quel che
sorge deve cessare».

[.suttaref]
_Vin. Mv. 1:23_

[.voice]
*Prima voce.* «Quello giunge all’esistenza quando c’è questo, quello sorge
con il sorgere di questo. Quello non giunge all’esistenza quando non c’è
questo, quello cessa con la cessazione di questo».

[.suttaref]
_M. 38_

«Chi vede la genesi interdipendente vede il Dhamma, chi vede il Dhamma
vede la genesi interdipendente».

[.suttaref]
_M. 28_

«Che gli Esseri Perfetti compaiano o no, questo elemento resta, questa
struttura delle cose (dei fenomeni), questa certezza nelle cose, ossia:
una specifica condizionalità. Un Perfetto l’ha scoperta».

[.suttaref]
_S. 12:20_

«Se non ci fosse affatto nascita, di nulla, da nessuna parte ... non
essendoci nascita, con la cessazione della nascita, potrebbero essere
descritte la vecchiaia e la morte?». – «No, Signore». – «Di conseguenza,
questa è una ragione, una fonte, un’origine, una condizione per la
vecchiaia e la morte». (E così via, con le altre coppie della formula
della genesi interdipendente.)

[.suttaref]
_D. 15_

«Signore, “retta visione, retta visione” è stato detto. A che cosa si
riferisce la “retta visione”?». – «Di solito, Kaccāyana, questo mondo
dipende dal dualismo dell’esistenza e della non-esistenza. Quando però
uno vede l’origine del mondo com’è nella realtà con retta comprensione,
per lui non c’è niente della (cosiddetta) non-esistenza nel mondo, e
quando egli vede la cessazione del mondo com’è nella realtà con retta
comprensione, per lui non c’è niente della (cosiddetta) esistenza nel
mondo».

«Di solito il mondo è incatenato da pregiudizi, attaccamenti e
ostinazioni, ma per uno come costui (che ha retta visione) – il quale,
invece di accogliere pregiudizi, invece di aggrapparsi e invece di
decidere in relazione a “me stesso” con questi pregiudizi, con
quest’aggrapparsi e con queste decisioni legati alla soggiacente
tendenza di fondo a ostinarsi – non ci sono dubbi o incertezze sul fatto
che quel che sorge è solo sofferenza che sorge, e che quel che cessa è
solo sofferenza che cessa, e in questo la sua conoscenza è indipendente
dagli altri. A questo si riferisce “retta visione”. “(Un) tutto esiste è
un estremo”, “(un) tutto non esiste” è l’altro estremo. Invece di
ricorrere a uno di questi due estremi, un Perfetto espone il Dhamma
mediante la Via di Mezzo: “È con l’ignoranza quale condizione che le
formazioni [mentali] giungono all’esistenza; con le formazioni [mentali]
quale condizione, la coscienza; con la coscienza…” (e così via sia con
il sorgere sia con il cessare)».

[.suttaref]
_S. 12:15_

«Se si afferma: “Chi produce (sofferenza), (la) prova: essendo egli fin
dall’inizio, è lui stesso a produrre la sua sofferenza”, allora si
giunge all’eternalismo. Se però si afferma: “Uno produce (sofferenza),
un altro (la) prova: essendo egli schiacciato dalla sensazione, la sua
sofferenza è prodotta da un altro”, allora si giunge al nichilismo.
Invece di ricorrere a uno di questi due estremi, un Perfetto espone il
Dhamma mediante la Via di Mezzo: … (ossia, mediante la genesi
interdipendente e la cessazione)».

[.suttaref]
_S. 12:17_

«Tutti gli esseri sono mantenuti dal nutrimento».

[.suttaref]
_D. 33; A. 10:27, 28; Khp. 2_

«Che cos’è il nutrimento? Ci sono questi quattro generi di nutrimento
per mantenere gli esseri che già esistono, e per soccorrere quelli che
cercano di tornare a esistere: essi sono il cibo fisico come nutrimento
grossolano o sottile, il secondo è il contatto, la scelta è il terzo e
la coscienza è il quarto».

[.suttaref]
_S. 12:63; M. 38_

[.narrator]
*Secondo narratore.* La stessa essenza della retta visione è, tuttavia, la
comprensione delle Quattro Nobili Verità, la quale abbraccia la genesi
interdipendente e costituisce l’“insegnamento peculiare dei Buddha”.
Esse costituiscono l’oggetto del Primo Sermone.

[.voice]
*Prima voce.* «Che cos’è la retta visione? È la conoscenza della
sofferenza, dell’origine della sofferenza, della cessazione della
sofferenza e del Sentiero che conduce alla cessazione della sofferenza:
questa è detta retta visione».

[.suttaref]
_S. 45:8; D. 22_

{empty}(I) «“Quattro serpenti velenosi” è un nome per i quattro grandi
elementi (terra, acqua, fuoco e aria)».

[.suttaref]
_S. 35:197_

[quote]
____
La forma è come un grumo di schiuma, +
la sensazione è come una bolla d’acqua, +
la percezione anche è come un miraggio, +
le formazioni [mentali] come il tronco di un banano.footnote:[Il tronco
di un banano è fatto solo d’un involucro, è privo di nucleo.] +
E la coscienza, manifestazione dei figli di Āditi,footnote:[NDT.
L’espressione rinvia ai figli del Dio Sole (Āditi), dodici
come i mesi dell’anno nel _Bhāgavata Purāṇa_, che si manifestano appunto
in modo via via differente.] +
altro non è che un gioco di prestigio.
____

[.suttaref]
_S. 22:95_

«Le sei basi, di per se stesse, possono essere definite come un
villaggio vuoto, perché se un uomo saggio le investiga quali occhio,
orecchio, naso, lingua, corpo o mente, esse appaiono come cavità, vuote
e vacue. Le sei basi esterne possono essere definite come briganti che
fanno incursioni in un villaggio, perché l’occhio è assillato da forme
gradevoli e sgradevoli, l’orecchio da suoni siffatti, il naso da odori
siffatti, la lingua da sapori siffatti, il corpo da oggetti tangibili
siffatti e la mente da oggetti mentali siffatti».

[.suttaref]
_S. 35:197_

[quote]
____
{empty}(II) Nel mondo vedo questa generazione tormentata +
dalla brama per l’esistenza, +
miserevoli uomini che farfugliano di fronte alla Morte, +
ancora bramosi, speranzosi per un qualche tipo di esistenza. +
Guardate come fremono per quel che pretendono essere “mio”, +
come pesci in una pozzanghera che si sta prosciugando.
____

[.suttaref]
_Sn. 4:2_

{empty}(III) «Questa è (la più alta) serenità, questa è (la meta) superiore (a
tutto), ossia è la pacificazione di tutte le formazioni [mentali],
l’abbandono di tutti gli essenziali dell’esistenza, l’esaurimento della
brama, la cessazione, il Nibbāna».

[.suttaref]
_A. 10:60_

[quote]
____
{empty}(IV) La più grande delle acquisizioni (mondane) è la ricchezza, +
il Nibbāna è la più grande beatitudine. +
Il Nobile Ottuplice Sentiero è il sentiero migliore, +
per arrivare al sicuro a Ciò che Non Muore.
____

[.suttaref]
_M. 75_

[.narrator]
*Secondo narratore.* È di nuovo la retta visione delle tre caratteristiche
universali dell’impermanenza, della sofferenza (o insicurezza) e del
non-sé, che esprime globalmente quel che la genesi interdipendente
esprime strutturalmente. Esse costituiscono l’oggetto del Secondo
Sermone.

[.voice]
*Prima voce.* «Tre sono le caratteristiche formate di ciò che è
formato:footnote:[“Formato” è _saṅkhata_, tradotto anche con “composto”
o “condizionato”; “non-formato” è _asaṅkhata_, tradotto anche con
“non-composto” o “incondizionato”. Quest’ultimo è identificato come Nibbāna (Nyp.)]
il sorgere è evidente, il declino è evidente
e l’alterazione di ciò che è presente è evidente. Tre sono le
caratteristiche non-formate di ciò che è non-formato: il non-sorgere è
evidente, il nondeclino è evidente e la non-alterazione è evidente».

[.suttaref]
_A. 3:47_

«Allorché si comprende come forma, sensazione, percezione, formazioni
[mentali] e coscienza (e come l’occhio, ecc.) sono impermanenti, in ciò
si possiede retta visione».

[.suttaref]
_S. 22:51; 35:155_

«Tutto è impermanente. E che cos’è il tutto che è impermanente? L’occhio
è impermanente, le forme sono impermanenti, la coscienza visiva è
impermanente … il contatto con l’occhio, qualsiasi cosa sia sentita come
piacevole, dolorosa o né-dolorosa-né-piacevole nata dal contatto con
l’occhio è impermanente. L’orecchio, ecc. … Il naso, ecc. … La lingua,
ecc. … Il corpo, ecc. … La mente è impermanente, gli oggetti mentali …
la coscienza mentale … il contatto mentale … qualsiasi cosa sia sentita
… nata dal contatto mentale è impermanente».

[.suttaref]
_S. 35:43_

«Quel che è impermanente è sofferenza, quel che è sofferenza è non-sé».

[.suttaref]
_S. 35:1; 22:46_

«Che un Perfetto compaia o no, questo elemento resta, questa struttura
delle cose (dei fenomeni), questa certezza nelle cose: tutte le
formazioni sono impermanenti, tutte le formazioni sono sofferenza, tutte
le cose sono non-sé».

[.suttaref]
_A. 3:134_

«Bhikkhu, io non disputo con il mondo: il mondo disputa con me. Chi
proclama il Dhamma non disputa con nessuno nel mondo. Quello che gli
uomini saggi del mondo dicono non esserci, anche io dico non esserci. E
quel che gli uomini saggi del mondo dicono esserci, anche io dico
esserci. Gli uomini saggi del mondo dicono che non c’è forma permanente,
durevole, eterna che non sia soggetta al cambiamento, e anche io dico
che non ce n’è alcuna. (E così anche degli altri quattro aggregati.) Gli
uomini saggi del mondo dicono che c’è una forma impermanente, che è
sofferenza e soggetta al cambiamento, e anche io dico che c’è. (E così
con gli altri quattro.)».

[.suttaref]
_S. 22:94_

«Questo corpo è impermanente, è formato ed è sorto in dipendenza».

[.suttaref]
_S. 36:7_

«Per un uomo ignorante e ordinario sarebbe meglio trattare come se fosse
un sé questo corpo, che è costruito sulla base di quattro grandi
elementi, invece che la mente.footnote:[_citta_: mente, mentalità, cognizione]
Perché? Perché questo
corpo può durare un anno, due anni … cento anni. Quel che però è
chiamato “mente” e “coscienza” sorge e cessa in vari modi notte e
giorno, proprio come una scimmia che attraversa una foresta passando di
ramo in ramo e, lasciandone uno, ne afferra un altro».

[.suttaref]
_S. 12:61_

«L’atto del donare è fruttuoso … tuttavia è ancor più fruttuoso prendere
rifugio con cuore fiducioso nel Buddha, nel Dhamma e nel Saṅgha, e
prendere i cinque precetti della virtù … Questo è fruttuoso … tuttavia è
ancor più fruttuoso mantenere in essere la gentilezza amorevole anche
solo per il tempo di mungere una mucca … Questo è fruttuoso … tuttavia è
ancor più fruttuoso mantenere in essere la percezione dell’impermanenza
anche solo per il tempo di far schioccare le dita».

[.suttaref]
_A. 9:20 (condensato)_

«Chiunque apprezza l’occhio, apprezza la sofferenza, e non sarà libero
dalla sofferenza, questo dico».

[.suttaref]
_S. 35:19_

«Che cos’è la maturazione della sofferenza? Quando qualcuno è
sopraffatto e la sua mente è ossessionata dalla sofferenza, o si
addolora e si lamenta e, battendosi il petto, piange e diviene
sconvolto, oppure intraprende una ricerca esteriormente: “C’è qualcuno
che sa una parola, due parole, per la cessazione della sofferenza?”.
Dico che la sofferenza matura o nella confusione o nella ricerca».

[.suttaref]
_A. 6:63_

«Che qualcuno possa vedere le formazioni come piacere … oppure il
Nibbāna come sofferenza, e abbia una predilezione conforme [alla
Verità], questo non è possibile. (L’opposto però) è possibile».

[.suttaref]
_A. 6:99_

«Qualsiasi forma, sensazione, percezione, formazione e coscienza, di
qualsiasi genere, passata, futura o presente, interna o esterna,
grossolana o sottile, inferiore o superiore, lontana o vicina, dovrebbe
essere considerata come realmente è in questo modo: “Questo non è mio,
questo non è quel che io sono, questo non è il mio sé”».

[.suttaref]
_S. 22:59_

«Nel mondo mediante cui si percepisce il mondo e si concepiscono
concetti a proposito del mondo, ciò è chiamato “il mondo” nella
Disciplina degli Esseri Nobili. E con che cosa si fa tutto questo nel
mondo? Con l’occhio, l’orecchio, il naso, la lingua, il corpo e la
mente».

[.suttaref]
_S. 35:116_

«Si va logorando (_lujjati_), ecco perché è chiamato “il mondo”
(_loka_)».

[.suttaref]
_S. 35:82_

«“Mondo vuoto, mondo vuoto” si dice, Signore. In quale modo si dice
“mondo vuoto”? – «È perché è vuoto del sé e della proprietà del sé che
si dice “mondo vuoto” Ānanda. E che cosa è vuoto del sé e della
proprietà del sé? L’occhio … le forme … la coscienza visiva … il
contatto visivo … qualsiasi sensazione … nata dal contatto visivo …
L’orecchio, ecc. … Il naso, ecc. … La lingua, ecc. … Il corpo, ecc. … La
mente, ecc. … qualsiasi sensazione piacevole o dolorosa oppure
né-piacevole-né-dolorosa nata dal contatto mentale è vuota del sé e
della proprietà del sé».

[.suttaref]
_S. 35:85_

«Quando un bhikkhu dimora molto con la sua mente fortificata dalla
percezione dell’impermanenza, la sua mente retrocede, si ritrae e
indietreggia dal guadagno, dall’onore e dalla fama invece di avvicinarsi
ad essi, come la piuma di un gallo o un brandello di tendine gettati su
un fuoco retrocedono, si ritraggono e indietreggiano invece di
avvicinarsi ad esso … Quando egli dimora molto con la sua mente
fortificata dalla percezione della sofferenza nell’impermanenza, si
stabilisce in lui una vivida percezione di timore verso la rilassatezza,
l’indolenza, la pigrizia, la negligenza, la mancanza di dedizione e di
riflessione, come se si trovasse al cospetto di un assassino con un’arma
pronta a colpirlo … Quando egli dimora molto con la sua mente
fortificata dalla percezione del non-sé nella sofferenza, la sua mente
si libera di quelle presunzioni che considerano come “io” e “mio” questo
corpo con la sua coscienza e tutti i segni esteriori».

[.suttaref]
_A. 7:46_

[.narrator]
*Secondo narratore.* La razionalizzata “teoria del sé” che,
indipendentemente dalla forma che assume, è chiamata «sia un’opinione
sia una catena», si fonda su una sottile distorsione di fondo nell’atto
del percepire, la «presunzione “io sono”», che è «una catena, ma non
un’opinione». Le teorie del sé possono o non possono essere formulate,
ma se lo sono, non è possibile descriverle in modo specifico senza far
riferimento ai cinque aggregati. Per questa ragione esse possono essere
ricondotte, quando descritte, a uno dei tipi di quel che è chiamata
“opinione della personificazione”,footnote:[“Personificazione”:
_sakkāya_ = _sa_ (“esistente” o “
proprio”) più _kāya_ (corpo). L’identificazione del sé (_attā_) con uno
o più dei cinque aggregati costituisce perciò una “personificazione” di
quel sé, e ciò fonda un’errata visione. Si noti che _sakkāyadiṭṭhi è_ di
solito più tradotto con “opinione dell’io” (Nyp.).] che è esposta
schematicamente. Tutto ciò è abbandonato da Chi è Entrato nella
Corrente, anche se la presunzione “io sono” non lo è.

[.voice]
*Prima voce.* «Com’è che perviene a esistere l’opinione della
personificazione?». – «Un uomo ignorante e ordinario che non ha
considerazione per gli Esseri Nobili e non è versato con il loro Dhamma
e Disciplina … vede la forma come sé o il sé come dotato di una forma, o
la forma come nel sé o il sé come nella forma. (E così via con ognuno
degli altri quattro aggregati: sensazione, percezione, formazioni
[mentali] e coscienza.) Un ben istruito nobile discepolo non lo fa».

[.suttaref]
_M. 44; M. 109_

«L’uomo ignorante e ordinario che non ha considerazione per gli Esseri
Nobili … presta un’irragionevole (acritica) attenzione a queste cose:
“In passato io esistevo? Non esistevo io in passato? Che cos’ero io in
passato? Com’ero io in passato? Essendo stato quello, che cos’ero io in
passato? Esisterò io in futuro? Non esisterò io in futuro? Che cosa sarò
io in futuro? Come sarò io in futuro? Essendo stato quello, che cosa
sarò io in futuro?”. Oppure così si domanda in relazione a se stesso,
ora, in quanto sorto nel presente: “Io sono? Io non sono? Che cosa sono
io? Come sono io? Da dove è venuto questo essere? Dov’è diretto?”».

«Allorché egli presta un’irragionevole attenzione a queste cose, allora
uno dei sei tipi di opinione del sé sorge in lui come vera e fondata:
“il mio sé esiste” o “il mio sé non esiste”, “io percepisco il sé con il
sé” o “io percepisco il non-sé con il sé”, “io percepisco il sé con il
non-sé” oppure altre opinioni quali “questo è il mio sé che parla, ha
sensazioni e sperimenta qui o là la maturazione delle buone e delle
cattive azioni, ma questo mio sé è permanente, durevole, non soggetto al
cambiamento, e durerà in eterno”. Questo ambito di opinioni è chiamato
cespuglio di opinioni, bosco di opinioni, contorsione di opinioni,
tentennamento di opinioni, catena di opinioni. L’uomo ignorante e
ordinario legato dalla catena di opinioni non è libero dalla nascita,
dalla vecchiaia e dalla morte, dall’afflizione, dal lamento, dal dolore,
dal dispiacere e dalla disperazione: egli non si è liberato dalla
sofferenza, dico».

[.suttaref]
_M. 2_

«Bhikkhu, ci sono due tipi di (errata) visione, e quando le divinità e
gli esseri umani sono nella loro morsa, alcuni restano indietro e altri
vanno troppo oltre. Sono solo quelli con [retta] visione che vedono.
Com’è che alcuni restano indietro? Divinità ed esseri umani amano
l’esistenza, si deliziano dell’esistenza, apprezzano l’esistenza. Quando
il Dhamma viene loro esposto per la fine dell’esistenza, il loro cuore
non viene raggiunto né acquisisce fiducia, fermezza e decisione. È così
che alcuni restano indietro. E com’è che alcuni vanno troppo oltre?
Alcuni si vergognano, si sentono umiliati e disgustati da questa stessa
esistenza, e guardano più oltre in direzione della non-esistenza in
questo modo: “Signori, quando alla dissoluzione del corpo questo sé è
eliminato, annullato e perciò dopo la morte non esiste più, quella è la
serenità maggiore, la meta superiore a tutte le altre, questa è la
realtà”. È così che alcuni vanno troppo oltre. E com’è che quelli con
[retta] visione vedono? Un bhikkhu vede qualsiasi cosa giunta
all’esistenza come giunta all’esistenza. Vedendo in questo modo egli si
è messo sulla strada del distacco per essa, del disincanto e della
cessazione della brama per essa. È così che uno con la [retta] visione
vede».

[.suttaref]
_Iti. 49_

«Bhikkhu, i possedimenti che uno può possedere che siano permanenti,
perenni … Vedete possedimenti di questo genere?». – «No. Signore». – «…
Una teoria del sé, alla quale ci si attacca ovunque ci si possa
attaccare, senza che faccia mai sorgere afflizione e … disperazione in
chi ad essa si attacca. Vedete una teoria del sé di questo genere?». –
«No, Signore». – «Un’opinione che sia di supporto, che si possa prendere
quale supporto senza che faccia mai sorgere afflizione e … disperazione
in chi la sceglie quale supporto. Vedete un’opinione di supporto di
questo genere?». – «No, Signore». – «… Bhikkhu, esistendo un sé,
esisterebbe anche una proprietà del sé?». – «Sì, Signore». – «Ed
esistendo una proprietà del sé, esisterebbe anche un sé?». – «Sì,
Signore». – «Bhikkhu, essendo sé e proprietà del sé inafferrabili come
veri e fondati, non sarebbe allora questa opinione: “Questo è il mondo,
questo è il sé, dopo la morte io sarò permanente, perenne, eterno, non
soggetto al cambiamento, durerò per l’eternità” [nient’altro che] la
pura perfezione dell’idea di un folle?». – «Come potrebbe non essere
così, Signore? Sarebbe la pura perfezione dell’idea di un folle».

[.suttaref]
_M. 22_

«Ogni qual volta monaci o brāhmaṇa vedono il sé nelle sue varie forme,
tutti loro vedono i cinque aggregati affetti dall’attaccamento, o uno o
l’altro di essi. L’uomo ignorante e ordinario che non ha considerazione
per gli Esseri Nobili … vede la forma come sé o il sé come dotato di
forma, la forma come nel sé o il sé come nella forma (oppure egli fa la
stessa cosa con gli altri quattro aggregati). Egli ha perciò questo
(razionalizzato) modo di pensare ed ha anche l’attitudine (di fondo) “io
sono”. Fino a quando, però, c’è l’attitudine “io sono” c’è
organizzazione delle cinque facoltà sensoriali dell’occhio,
dell’orecchio, del naso, della lingua e del corpo. Poi c’è la mente e ci
sono le idee, e c’è l’elemento dell’ignoranza. Quando un uomo ignorante
e ordinario è toccato dalla sensazione nata dal contatto con
l’ignoranza, gli capita di pensare “io sono” e “io sono questo”, “io
sarò” e “io non sarò”, “io sarò dotato di forma” e “io sarò privo di
forma”, “io sarò percettivo” e “io sarò impercettivo” e “io sarò né
percettivo né impercettivo”. Nel caso però di un ben istruito nobile
discepolo, mentre le cinque facoltà sensoriali restano così come sono,
l’ignoranza a riguardo di esse è abbandonata ed è sorta la vera
conoscenza. Con essa non gli capita di pensare “io sono” o … “io sarò né
percettivo né impercettivo”».

[.suttaref]
_S. 22:47_

[.narrator]
*Secondo narratore.* L’uomo ignorante e ordinario è ignaro della sottile
attitudine di fondo, della soggiacente tendenza o presunzione “io sono”.
Essa, nella percezione di un percetto, lo fa automaticamente e
simultaneamente presumere in termini di “io”, presupponendo una
relazione dell’io con il percetto, come identica con esso o come
contenuta all’interno di esso, o come separata da esso oppure in termini
di possesso. Quest’attitudine, questa concezione, è abbandonata solo con
il raggiungimento della condizione di Arahant, non prima (si veda ad es.
M. 1 e M. 49).

[.voice]
*Prima voce.* «“Io sono” è una derivazione, non una non-derivazione. Una
derivazione da che cosa? È una derivazione da forma, sensazione,
percezione, formazioni [mentali] e coscienza».

[.suttaref]
_S. 22:83_

«Quando ogni monaco o brāhmaṇa con la forma (e il resto) quale mezzo,
che è impermanente, è sofferenza e soggetta al cambiamento, pensa “io
sono superiore”, “io sono uguale” o “io sono inferiore”, che cos’è
questo se non cecità rispetto a quello che in realtà è?».

[.suttaref]
_S. 22:49_

(Interrogato dagli Anziani, l’Anziano Khemada disse:) «In questi cinque
aggregati affetti dall’attaccamento non vedo alcun sé o proprietà del sé
… tuttavia non sono un Arahant con le contaminazioni esaurite. Al
contrario, ho ancora l’attitudine “io sono” riguardo a questi cinque
aggregati affetti dall’attaccamento sebbene io non pensi “io sono
questo” rispetto ad essi … Non dico “io sono forma”, “io sono
sensazione”, “io sono percezione”, “io sono formazioni [mentali] o “io
sono coscienza”, e nemmeno dico “io sono separato dalla forma … separato
dalla coscienza”. Tuttavia ho ancora l’attitudine “io sono” rispetto ai
cinque aggregati affetti dall’attaccamento sebbene io non pensi “io sono
questo” rispetto ad essi. Benché un nobile discepolo possa aver
abbondonato le cinque catene inferiori (si veda sotto), la sua
presunzione “io sono”, il desiderio “io sono”, la soggiacente tendenza
“io sono” rispetto ai cinque aggregati affetti dall’attaccamento non è
ancora abolita. In seguito egli dimora contemplando il sorgere e lo
scomparire in questo modo: “Questa è la forma, questa è la sua origine,
questo è il suo scomparire” (e così con gli altri quattro [aggregati],
finché, così facendo, alla fine la sua presunzione “io sono” giunge a
essere abolita».

[.suttaref]
_S. 22:89_

[.narrator]
*Secondo narratore.* Siamo infine giunti alle dieci catene, che sono
progressivamente spezzate dai quattro stadi della realizzazione.

[.voice]
*Prima voce.* «L’uomo ignorante e ordinario che non ha considerazione per
gli Esseri Nobili … vive con il suo cuore posseduto e reso schiavo
dall’opinione della personificazione, dal dubbio, dall’errata
comprensione della virtù e del dovere,footnote:[O “attaccamento a riti
e rituali” (_sīlabbata-parāmāsa_) (Nyp.).] dal desiderio
sensoriale e dalla malevolenza, ed egli non vede come sfuggire ad essi
quando sorgono. Questi, quando sono abituali e permangono non sradicati
in lui, sono chiamati catene inferiori».

[.suttaref]
_M. 64_

«Le cinque catene superiori sono: desiderio per la forma, desiderio per
i fenomeni privi di forma, presunzione (la presunzione “io sono”),
agitazione e ignoranza».

[.suttaref]
_D. 33_

«Ci sono bhikkhu che, con l’esaurimento delle (prime) tre catene, sono
Entrati nella Corrente, e non sono più soggetti alla perdizione, sono
certi della rettitudine e destinati all’Illuminazione. Ci sono bhikkhu
che, con l’esaurimento delle tre catene e l’attenuazione della brama,
dell’odio e dell’illusione, Tornano una Sola Volta: tornando una sola
volta in questo mondo, porranno fine alla sofferenza. Ci sono bhikkhu
che, con la distruzione delle cinque catene inferiori, sono [Senza
Ritorno, sono] destinati a ricomparire spontaneamente altrove e lì
otterranno il Nibbāna definitivo, senza tornare nel frattempo da quel
mondo. Ci sono bhikkhu che sono Arahant con le contaminazioni esaurite,
che hanno vissuto la vita [santa], che hanno fatto quel che doveva
essere fatto, che hanno poggiato il fardello, che hanno raggiunto lo
scopo supremo, che hanno distrutto le catene dell’esistenza e che si
sono completamente liberati mediante la conoscenza finale».

[.suttaref]
_M. 118_

«L’esaurimento della brama, dell’odio e dell’illusione è chiamato
condizione di Arahant».

[.suttaref]
_S. 38:2_

«Quando un bhikkhu viaggia in molti paesi, gente colta di ogni
condizione sociale gli pone delle domande. Persone colte e indagatrici
gli chiederanno: “Che cosa dice il Maestro degli esseri venerabili, che
cosa predica?”. Per rispondere rettamente, potete dire: “Il nostro
Maestro predica la rimozione del desiderio e della brama”. E se vi
chiedono: “Rimozione del desiderio e della brama per che cosa?”, potete
rispondere: “Rimozione del desiderio e della brama per la forma (e così
via)”. E se poi vi chiedono: “Quale inadeguatezza (pericolo) vedete in
queste cose?”, potete rispondere: “Quando uno non è privo di brama,
desiderio, amore, sete, febbre e avidità per queste cose, poi, con il
loro cambiamento e alterazione, sorgono in lui l’afflizione, il lamento,
il dolore, il dispiacere e la disperazione”. E se poi vi chiedono: “E
quale vantaggio vedete nel fare in questo modo?”, potete rispondere:
“Quando uno è libero da brama, desiderio, amore, sete, febbre e avidità
per forma, sensazione, percezione, formazioni [mentali] e coscienza,
poi, con il loro cambiamento e alterazione, non sorgono in lui
l’afflizione, il lamento, il dolore, il dispiacere e la disperazione”».

[.suttaref]
_S. 22:2_

== Retta intenzione

[.narrator]
*Secondo narratore.* Il riassunto della retta visione è concluso. Il
successivo fattore del Nobile Ottuplice Sentiero è la retta intenzione.

[.voice]
*Prima voce.* «Che cos’è la retta intenzione? È l’intenzione della
rinuncia, l’intenzione della non-malevolenza, l’intenzione della
non-crudeltà: questa è chiamata retta intenzione».

[.suttaref]
_S. 45:8; D. 22_

«Quando un nobile discepolo ha chiaramente visto con retta comprensione
come in realtà stanno le cose, quanto sia piccola la gratificazione
offerta dai desideri sensoriali e quanto dolore e disperazione essa
comporti, e quanto grande sia la loro inadeguatezza, e consegue la
felicità e il piacere dissociati dai desideri sensoriali e dagli stati
non salutari, o qualcosa di ancor più alto di questo, allora egli non è
più interessato ai desideri sensoriali».

[.suttaref]
_M. 14_

«Anche se dei banditi lo tagliassero a pezzi con una sega da boscaiolo,
se nel suo cuore concepisse odio nei loro riguardi, costui non potrebbe
essere considerato uno che segue il mio insegnamento».

[.suttaref]
_M. 21_

«Egli non sceglie per la propria afflizione, per l’afflizione degli
altri o per l’afflizione propria e per quella degli altri».

[.suttaref]
_M. 13_

== Retta parola

[.narrator]
*Secondo narratore.* Questi due fattori della retta visione e della retta
intenzione insieme costituiscono (quel gruppo dei fattori del Sentiero
chiamato) “saggezza” (_paññā_). Passiamo ora al terzo fattore, la retta
parola.

[.voice]
*Prima voce.* «Che cos’è la retta parola? Astenersi dalla menzogna, dalla
calunnia, dall’insulto e dal pettegolezzo. Questo è la retta parola».

[.suttaref]
_S. 45:8; D. 22_

«Qualcuno abbandona la menzogna: quando è convocato in giudizio, in una
riunione e alla presenza dei suoi parenti o dell’associazione della
quale fa parte o al cospetto della famiglia reale, se richiesto come
testimone in questo modo “Allora, buon uomo, dicci quello che sai”, se
egli non sa dice “io non so”, se egli sa dice “io so”, se non ha visto
dice “io non ho visto”, se ha visto dice “io ho visto”. Egli non afferma
il falso in piena consapevolezza a suo vantaggio, a vantaggio di un
altro o di un qualche meschino fine terreno. Egli abbandona la calunnia:
come chi non ripete altrove quel che ha sentito qui allo scopo di
causare divisioni da questi, né ripete a questi ciò che ha udito altrove
allo scopo di causare divisioni da quelli, ed egli così riunisce ciò che
è diviso, è promotore dell’amicizia, gioisce della concordia, si
rallegra nella concordia, si delizia nella concordia, pronuncia parole
che promuovono la concordia. Egli abbandona l’insulto: pronuncia parole
che non suscitano sofferenza, che sono piacevoli da ascoltare e amabili,
che vanno [dritte] al cuore, che sono educate, desiderate da molti e a
molti care. Egli abbandona il pettegolezzo: come chi dice quel che è
opportuno, concreto, buono, e il Dhamma e la Disciplina, parla con un
linguaggio giusto che merita di essere ricordato, che è motivato,
preciso e connesso al bene».

[.suttaref]
_M. 41_

== Retta azione

[.narrator]
*Secondo narratore.* Il quarto fattore, retta azione.

[.voice]
*Prima voce.* «Che cos’è la retta azione? Astenersi dall’uccidere esseri
viventi, dal rubare, da una cattiva condotta sessuale. Questo è la retta
azione».

[.suttaref]
_S. 45:8; D. 22_

«Quando un seguace laico possiede cinque cose, egli vive fiducioso nella
propria casa, e si troverà in paradiso tanto certamente come se fosse
stato trascinato via e messo là». Quali cinque? Si astiene dall’uccidere
esseri viventi, dal prendere ciò che non gli è stato dato, dalla cattiva
condotta sessuale, dal dire il falso e dall’indulgere ai liquori, al
vino e alle bevande fermentate».

[.suttaref]
_A. 5:172-73_

== Retti mezzi di sostentamento

[.narrator]
*Secondo narratore.* Il quinto fattore, retti mezzi di sostentamento.

[.voice]
*Prima voce.* «Che cosa sono i retti mezzi di sostentamento? Un nobile
discepolo abbandona gli errati mezzi di sostentamento e si guadagna da
vivere mediante retti mezzi di sostentamento».

[.suttaref]
_S. 45:8; D. 22_

«Manovrare (ingannare), persuadere, alludere, sminuire, mercanteggiare.
Questi sono errati mezzi di sostentamento (per i bhikkhu)».

[.suttaref]
_M. 117_

«Cinque sono i tipi di commercio che un seguace laico non dovrebbe
esercitare. Quali cinque? Commerciare armi, esseri viventi, carne,
liquori e veleni».

[.suttaref]
_A. 5:177_

== Retto sforzo

[.narrator]
*Secondo narratore.* Gli ultimi tre fattori, retta parola, retta azione e
retti mezzi di sostentamento, costituiscono (quel gruppo dei fattori del
Sentiero chiamato) “virtù” (_sīla_). Sono noti in quanto stadio
preliminare del Sentiero. Ora si giunge al sesto fattore, il retto
sforzo.

[.voice]
*Prima voce.* «Che cos’è il retto sforzo? Un bhikkhu risveglia il
desiderio per il non-sorgere degli stati non salutari non sorti, per cui
egli si sforza, suscita energia, esercita la sua mente, si applica
intensamente … Egli risveglia il desiderio per l’abbandono degli stati
non salutari già sorti, per cui egli si sforza … Egli risveglia il
desiderio per il sorgere degli stati salutari non sorti, per cui egli si
sforza … Egli risveglia il desiderio per la continuazione, la
non-corruzione, il rafforzamento, il mantenimento in essere e il
perfezionamento degli stati salutari già sorti, per cui egli si sforza,
suscita energia, esercita la sua mente, si applica intensamente. Questo
è chiamato retto sforzo».

[.suttaref]
_S. 45:8; D. 22_

== Retta presenza mentale

[.narrator]
*Secondo narratore.* Siamo giunti al settimo fattore, la retta presenza
mentale.

[.voice]
*Prima voce.* «Che cos’è la retta presenza mentale? Un bhikkhu dimora
contemplando il corpo come corpo, ardente, con piena consapevolezza e
presenza mentale, avendo messo da parte la cupidigia e il rimpianto per
il mondo. Dimora contemplando le sensazioni come sensazioni, ardente …
Dimora contemplando la coscienza come coscienza, ardente … Dimora
contemplando gli oggetti mentali come oggetti mentali, ardente, con
piena consapevolezza e presenza mentale, avendo messo da parte la
cupidigia e il rimpianto per il mondo. Questa è la retta presenza
mentale».

[.suttaref]
_S. 45:8; D. 22_

«Come dimora un bhikkhu contemplando il corpo come corpo? Un bhikkhu,
recatosi nella foresta o ai piedi di un albero o in una stanza vuota,
siede a terra. Dopo aver incrociato le gambe, siede con il corpo eretto
e fissa la consapevolezza di fronte a sé, consapevole inspira,
consapevole espira.footnote:[L’esercizio qui descritto è l’osservazione
mentale, non lo
sviluppo corporeo mediante controllo del respiro come nell’_hathayoga_.
Questo sutta, il _Satipaṭṭhāna Sutta,_ è attualmente molto noto quale
fondamento della pratica meditativa. L’argomento di cui tratta, la
costituzione della consapevolezza, è la pietra angolare
dell’insegnamento del Buddha.] Come un tornitore esperto o come
un suo esperto apprendista quando fa una tornitura lunga sa “io sto
facendo una tornitura lunga”, o quando fa una tornitura corta sa “io sto
facendo una tornitura corta”, allo stesso modo quando sta facendo
un’inspirazione lunga un bhikkhu sa “sto facendo un’inspirazione lunga”,
o quando fa un’espirazione lunga sa “sto facendo un’espirazione lunga”;
quando sta facendo un’inspirazione corta, egli sa “sto facendo
un’inspirazione corta”, o quando fa un’espirazione corta, egli sa “sto
facendo un’espirazione corta”. Egli si addestra in questo modo:
“Inspirerò sperimentando l’intero corpo (del respiro)”. Egli si addestra
in questo modo: “Espirerò sperimentando l’intero corpo (del respiro)”.
Egli si addestra in questo modo: “Inspirerò tranquillizzando la
formazione corporea (le funzioni corporee)”. Egli si addestra in questo
modo: “Espirerò tranquillizzando la formazione corporea (le funzioni
corporee)”».footnote:[Secondo il Commentario, “sperimentare l’intero
corpo (del respiro)” significa essere del tutto consapevole dell’intera
inspirazione e dell’intera espirazione. “Tranquillizzare la formazione
corporea” significa rendere il respiro sempre più sottile e calmo (BB).]

«Egli dimora contemplando il corpo come corpo in questo modo in se
stesso, o esternamente, o in se stesso ed
esternamente».footnote:[Secondo il Commentario, “esternamente” significa il corpo
di qualcun altro, ecc. (ma potrebbe riferirsi anche alla pura
oggettività vista nel proprio corpo); questo primo paragrafo enfatizza
la concentrazione. Il secondo, sul sorgere e sul cessare (decadimento)
si riferisce alla visione profonda (retta visione). Il terzo descrive la
piena consapevolezza in chi ha raggiunto il traguardo finale.]

«Oppure egli contempla nel corpo i fattori della sua origine, o i
fattori del suo decadimento, o i fattori della sua origine e del suo
decadimento».

«Oppure la consapevolezza che “c’è un corpo” si fonda in lui nella
misura di mera conoscenza e rammemorazione di essa mentre egli dimora
indipendente, senza attaccarsi a nulla nel mondo».

«Così un bhikkhu dimora contemplando il corpo come corpo».

«Ancora, quando cammina, un bhikkhu sa “sto camminando” o, quando è in
piedi, sa “sto in piedi” o, quando è seduto, sa “sto seduto” oppure,
quando giace, sa “sto giacendo”. In qualsiasi posizione si trovi il suo
corpo, egli sa che è in quella posizione».

«Egli dimora contemplando il corpo come corpo … esternamente».

«Oppure, anche, egli contempla … i fattori della sua origine e i fattori
del suo decadimento».

«Oppure, anche, la consapevolezza … senza attaccarsi a nulla nel mondo».

«È pure così che un bhikkhu dimora contemplando il corpo come corpo».

«Ancora, un bhikkhu è del tutto consapevole quando si muove avanti e
indietro, quando guarda avanti e lontano, quando piega ed estende gli
arti, quando indossa la veste superiore fatta di toppe, la ciotola e le
altre vesti, quando mangia, quando beve, quando mastica, quando
assapora, quando evacua l’intestino e urina, ed ha piena consapevolezza
e presenza mentale quando cammina, quando sta in piedi, quando sta
seduto, quando va a dormire, quando si sveglia, parla e mantiene il
silenzio».

«Egli dimora contemplando …».

«È pure così che un bhikkhu dimora contemplando il corpo come corpo».

«Ancora, come se ci fosse una borsa con due aperture, piena di molti
tipi di granaglie, come riso delle alture, riso rosso, fagioli, piselli,
miglio e riso bianco, e un uomo dotato di buona vista l’avesse aperta e
la stesse passando in rassegna: “Questo è riso delle alture, questo è
riso rosso, questi sono fagioli, questi sono piselli, questo è miglio,
questo è riso bianco”. Allo stesso modo un bhikkhu passa in rassegna
questo corpo, dalle punte dei piedi in su e dalla cima dei capelli in
giù, in quanto pieno di molte cose sudicie: “In questo corpo ci sono
capelli, peli, unghie, denti, pelle, carne, tendini, ossa, midollo
osseo, reni, cuore, fegato, diaframma, milza, polmoni, intestino,
viscere, cibo non digerito, feci, bile, flegma, pus, sangue, sudore,
grasso, lacrime, materia oleosa, saliva, muco, liquido sinoviale e
urina”.

«Egli dimora contemplando …».

«È pure così che un bhikkhu dimora contemplando il corpo come corpo».

«Ancora, come se un macellaio esperto o un suo esperto apprendista
avessero macellato una mucca e stessero seduti a un crocevia con
l’animale fatto a pezzi. Allo stesso modo, un bhikkhu, in qualsiasi
posizione sia il suo corpo, lo passa in rassegna in base ai [quattro]
elementi: “In questo corpo ci sono l’elemento terra, l’elemento acqua,
l’elemento fuoco e l’elemento aria”».

«Egli dimora contemplando …».

«È pure così che un bhikkhu dimora contemplando il corpo come corpo».

«Ancora, un bhikkhu considera questo corpo come se stesse guardando un
cadavere gettato in un carnaio, morto da un giorno, morto da due giorni,
morto da tre giorni, gonfio, livido, e che trasuda materia: “Anche
questo corpo ha tale natura, sarà così, non è esente da questo”».

«Egli dimora contemplando …».

«È pure così che un bhikkhu dimora contemplando il corpo come corpo».

«Ancora, un bhikkhu considera questo corpo come se stesse guardando un
cadavere gettato in un carnaio, mentre viene divorato da corvi, nibbi,
avvoltoi, cani, sciacalli e da una molteplice varietà di vermi: … come
se stesse guardando un cadavere gettato in un carnaio, uno scheletro con
carne e sangue, e tenuto assieme da tendini … uno scheletro scarno e
macchiato di sangue, e tenuto assieme da tendini … uno scheletro senza
carne e sangue, e tenuto assieme da tendini … ossa prive di tendini,
sparpagliate in tutte le direzioni, qui le ossa di una mano, là le ossa
di un piede, là le ossa di uno stinco, là un femore, là il bacino, là la
colonna vertebrale, là un teschio … ossa sbiancate, del colore delle
conchiglie … ossa ammucchiate, vecchie più di un anno … ossa decomposte
e sminuzzate fino a divenire polvere: “Anche questo corpo ha tale
natura, sarà così, non è esente da questo”».

«Egli dimora contemplando …».

«È pure così che un bhikkhu dimora contemplando il corpo come corpo».

«E come dimora un bhikkhu contemplando le sensazioni come sensazioni?».

«Un bhikkhu, quando prova una sensazione piacevole, sa “provo una
sensazione piacevole”. Quando prova una sensazione dolorosa sa “provo
una sensazione dolorosa”. Quando prova una sensazione
né-dolorosa-né-piacevole, sa “provo una sensazione
né-dolorosa-né-piacevole”. Quando prova una sensazione piacevole
materiale, sa “provo una sensazione piacevole
materiale”.footnote:[“Materiale” (_āmisa_) si riferisce a cose fisiche come il
cibo, il vestirsi, ecc., e con le sensazioni a ciò connesse.] …
(E così via con le altre due.) Quando
prova una sensazione piacevole non materiale, sa “provo una sensazione
piacevole non materiale”. … (E così via con le altre due)».

«Egli dimora contemplando le sensazioni come sensazioni in questo modo
in se stesso, o esternamente, o in se stesso ed esternamente».

«Oppure egli contempla nelle sensazioni i fattori della loro origine, o
i fattori del loro decadimento, o i fattori della loro origine e del
loro decadimento».

«Oppure la consapevolezza che “ci sono sensazioni” si fonda in lui nella
misura di mera conoscenza e rammemorazione di essa mentre egli dimora
indipendente, senza attaccarsi a nulla nel mondo».

«Ecco come dimora un bhikkhu contemplando le sensazioni come
sensazioni».

«E come dimora un bhikkhu contemplando la coscienza come coscienza?».

«Un bhikkhu comprende la coscienza affetta dalla brama come affetta
dalla brama, e quella non affetta dalla brama come non affetta dalla
brama. Egli comprende la coscienza affetta dall’odio come affetta
dall’odio, e quella non affetta dall’odio come non affetta dall’odio.
Egli comprende la coscienza affetta dall’illusione come affetta
dall’illusione, e quella non affetta dall’illusione come non affetta
dall’illusione. Egli comprende la coscienza contratta come contratta, e
quella distratta come distratta. Egli comprende la coscienza esaltata
come esaltata, e quella non esaltata come non esaltata. Egli comprende
la coscienza superata come superata, e quella non superata come non
superata.footnote:[“Contratta” dal torpore; “esaltata” dallo stato sensoriale
a quello meditativo; “superata” nella meditazione o nella realizzazione.]
Egli comprende la coscienza concentrata
come concentrata, e quella non concentrata come non concentrata. Egli
comprende la coscienza liberata come liberata, e quella non liberata
come non liberata».

«Egli dimora contemplando la coscienza come coscienza in questo modo in
se stesso, o esternamente, o in se stesso ed esternamente».

«Oppure egli contempla nella coscienza i fattori della sua origine, o i
fattori del suo decadimento, o i fattori della sua origine e del suo
decadimento».

«Oppure la consapevolezza che “c’è la coscienza” si fonda in lui nella
misura di mera conoscenza e rammemorazione di essa mentre egli dimora
indipendente, senza attaccarsi a nulla nel mondo».

«Ecco come dimora un bhikkhu contemplando la coscienza come coscienza».

«E come dimora un bhikkhu contemplando gli oggetti mentali come oggetti
mentali?».

«Un bhikkhu dimora contemplando gli oggetti mentali come oggetti mentali
nei termini dei cinque impedimenti.footnote:[“Impedimento” dovrebbe essere
inteso nel senso, per così
dire, di barriera che fa restare nella corrente della brama, dell’odio e
dell’illusione, piuttosto che come un ostacolo che blocca la strada.]
E come lo si fa?
Quando in lui c’è desiderio sensoriale, egli sa “in me c’è desiderio
sensoriale”, o quando in lui non c’è desiderio sensoriale, egli sa “in
me non c’è desiderio sensoriale”. Ed egli comprende anche come giunge in
essere il sorgere del non sorto desiderio sensoriale, e come giunge in
essere l’abbandono del sorto desiderio sensoriale, e come giunge in
essere il futuro non-sorgere dell’abbandonato desiderio sensoriale.
Quando in lui c’è malevolenza … Quando in lui c’è torpore e sonnolenza …
Quando in lui c’è agitazione e preoccupazione … Quando in lui c’è dubbio
… egli comprende come giunge in essere il futuro non-sorgere
dell’abbandonato dubbio».

«Egli dimora contemplando gli oggetti mentali come oggetti mentali in
questo modo in se stesso, o esternamente, o in se stesso ed
esternamente».

«Oppure egli contempla negli oggetti mentali i fattori della loro
origine, o i fattori del loro decadimento, o i fattori della loro
origine e del loro decadimento».

«Oppure la consapevolezza che “ci sono gli oggetti mentali” si fonda in
lui nella misura di mera conoscenza e rammemorazione di essa, mentre
egli dimora indipendente, senza attaccarsi a nulla nel mondo».

«Ecco come dimora un bhikkhu contemplando gli oggetti mentali negli
oggetti mentali nei termini dei cinque impedimenti».

«Ancora, un bhikkhu dimora contemplando gli oggetti mentali come oggetti
mentali nei termini dei cinque aggregati affetti dall’attaccamento. E
come lo si fa? Un bhikkhu comprende: “Questa è la forma, questa è la sua
origine, questo è il suo scomparire; questa è la sensazione, questa è la
sua origine, questo è il suo scomparire; questa è la percezione, questa
è la sua origine, questo è il suo scomparire; queste sono le formazioni
[mentali], questa è la loro origine, questo è il loro scomparire; questa
è la coscienza, questa è la sua origine, questo è il suo scomparire”».

«Egli dimora contemplando …».

«Ecco come dimora un bhikkhu contemplando gli oggetti mentali come
oggetti mentali nei termini dei cinque aggregati affetti
dall’attaccamento».

«Ancora, un bhikkhu dimora contemplando gli oggetti mentali come oggetti
mentali nei termini delle sei basi in se stesso ed esternamente. E come
lo si fa? Un bhikkhu comprende l’occhio e le forme visibili e le catene
che sorgono a causa di entrambi. Comprende come giunge in essere il
sorgere di catene non sorte, e come giunge in essere l’abbandono delle
catene sorte, e come giunge in essere il futuro non sorgere delle catene
abbandonate. Egli comprende l’orecchio e i suoni … il naso e gli odori …
la lingua e i sapori … il corpo e gli oggetti tangibili … la mente e gli
oggetti mentali e le catene che sorgono a causa di entrambi … ed egli
comprende come giunge in essere il futuro non sorgere delle catene
abbandonate».

«Egli dimora contemplando …».

«Ecco come dimora un bhikkhu contemplando gli oggetti mentali come
oggetti mentali nei termini delle sei basi in se stesso ed
esternamente».

«Ancora, un bhikkhu dimora contemplando gli oggetti mentali come oggetti
mentali nei termini dei sette fattori dell’Illuminazione. E come lo si
fa? Quando in lui c’è la consapevolezza quale fattore
dell’Illuminazione, un bhikkhu sa “in me c’è la consapevolezza quale
fattore dell’Illuminazione”, e quando non c’è la consapevolezza quale
fattore dell’Illuminazione, egli sa “in me non c’è la consapevolezza
quale fattore dell’Illuminazione”. Ed egli sa come giunge in essere il
sorgere della non sorta consapevolezza quale fattore dell’Illuminazione
e come giunge in essere lo sviluppo e il perfezionamento della sorta
consapevolezza quale fattore dell’illuminazione. Quando in lui c’è
l’investigazione degli stati [mentali] quale fattore dell’Illuminazione
… in lui c’è l’energia quale fattore dell’Illuminazione … in lui c’è la
felicità quale fattore dell’Illuminazione … in lui c’è la tranquillità
quale fattore dell’Illuminazione … in lui c’è la concentrazione quale
fattore dell’Illuminazione … in lui c’è l’equanimità quale fattore
dell’Illuminazione … Ed egli sa come giunge in essere il sorgere della
non sorta equanimità quale fattore dell’Illuminazione e come giunge in
essere lo sviluppo e il perfezionamento della sorta equanimità quale
fattore dell’Illuminazione».

«Egli dimora contemplando …».

«Ecco come dimora un bhikkhu contemplando gli oggetti mentali come
oggetti mentali nei termini dei sette fattori dell’Illuminazione».

«Ancora, un bhikkhu dimora contemplando gli oggetti mentali come oggetti
mentali nei termini delle Quattro Nobili Verità. E come lo si fa? Un
bhikkhu comprende in accordo con ciò che nei fatti è: “Questa è la
sofferenza” e “Questa è l’origine della sofferenza” e “Questa è la
cessazione della sofferenza” e “Questo è il Sentiero che conduce alla
cessazione della sofferenza”».

«Egli dimora contemplando gli oggetti mentali come oggetti mentali in
questo modo in se stesso, o esternamente, o in se stesso ed
esternamente».

«Oppure egli contempla negli oggetti mentali i fattori della loro
origine, o i fattori del loro decadimento, o i fattori della loro
origine e del loro decadimento».

«Oppure la consapevolezza che “ci sono gli oggetti mentali” si fonda in
lui nella misura di mera conoscenza e rammemorazione di essa, mentre
egli dimora indipendente, senza attaccarsi a nulla nel mondo».

«Ecco come dimora un bhikkhu contemplando gli oggetti mentali come
oggetti mentali nei termini delle Quattro Nobili Verità».

«Bhikkhu, se qualcuno mantenesse in essere questi quattro fondamenti
della consapevolezza per sette anni … i sette anni a parte … per sette
giorni, allora egli si potrebbe attendere uno di questi due frutti: la
conoscenza finale qui e ora, oppure il non-ritorno».

[.suttaref]
_D. 22; M. 10_

«Bhikkhu, vi esporrò l’origine e lo scomparire dei quattro fondamenti
della consapevolezza: il corpo ha [bisogno del] nutrimento per la sua
origine, e scompare con la cessazione del nutrimento; le sensazioni
hanno [bisogno del] contatto per la loro origine, e scompaiono con la
cessazione del contatto; la coscienza ha [bisogno di] nome-e-forma per
la sua origine, e scompare con la cessazione di nome-e-forma; gli
oggetti mentali hanno [bisogno dell’]attenzione per la loro origine, e
scompaiono con la cessazione dell’attenzione».

[.suttaref]
_S. 47:42_

«Tutte le cose hanno come loro radice il desiderio, l’attenzione
provvede alla loro esistenza, il contatto alla loro origine, la
sensazione al loro luogo d’incontro, la concentrazione al confronto con
esse, la consapevolezza al loro controllo, la comprensione è la più alta
di esse e la liberazione il loro nucleo».

[.suttaref]
_A. 8:83_

«Se s’intende custodire se stessi, sono i fondamenti della
consapevolezza a dover essere coltivati. Se s’intende custodire gli
altri, sono i fondamenti della consapevolezza a dover essere coltivati.
Chi custodisce se stesso, custodisce gli altri. Chi custodisce gli
altri, custodisce se stesso».

[.suttaref]
_S. 47:19_

== Retta concentrazione

[.narrator]
*Secondo narratore.* Siamo giunti all’ottavo e ultimo fattore, la retta
concentrazione.

[.voice]
*Prima voce.* «Che cos’è la retta concentrazione? Un bhikkhu, del tutto
isolato dai desideri sensoriali, isolato dagli stati [mentali] non
salutari, entra e dimora nel primo jhāna, che è accompagnato dal
pensiero e dall’esplorazione uniti alla felicità e al piacere nati
dall’isolamento».

[.suttaref]
_D. 2; D. 22; M. 39; S. 45:8_

«Proprio come un esperto addetto al lavacro o come un suo esperto
apprendista accumula polvere di sapone in una bacinella di metallo e,
irrorandola gradualmente d’acqua, la impasta fino a che la mistura non
diventa una palla di sapone, la impregna dentro e fuori senza che la
palla diventi liquida, allo stesso modo un bhikkhu imbeve il corpo della
felicità e del piacere nati dall’isolamento, lo immerge in essi, di essi
lo ricolma fino a che non vi è alcuna parte di tutto il corpo nella
quale tale felicità e tale piacere non giungano».

[.suttaref]
_D. 2; M. 39_

«Con l’acquietarsi del pensiero e dell’esplorazione egli entra e dimora
nel secondo jhāna, privo di pensiero ed esplorazione, che è accompagnato
da fiducia interiore e unificazione della mente unite alla felicità e al
piacere nati dalla concentrazione».

[.suttaref]
_D. 2; D. 22; M. 39; S. 45:8_

«Proprio come un lago, la cui acqua sgorga dal basso e che non ha
afflussi da est, da ovest, nord o sud, né viene riempito di tanto in
tanto dalla pioggia del cielo, e la fresca fonte d’acqua che zampilla
dal lago imbeve, impregna, riempie il lago, estendendosi del tutto in
esso, e non c’è parte dell’intero lago nel quale l’acqua fresca non si
estenda, allo stesso modo un bhikkhu imbeve, impregna, riempie questo
corpo con la felicità e il piacere nati dalla concentrazione,
estendendola del tutto in esso, così che non c’è parte dell’intero corpo
nel quale tale felicità e tale piacere non giungano».

[.suttaref]
_D. 2; M. 39_

«Con lo svanire anche di questa felicità egli dimora nell’equanimità e,
consapevole e pienamente presente, provando ancora piacere nel corpo,
entra e dimora nel terzo jhāna, in relazione al quale gli Esseri Nobili
affermano: “Dimora piacevolmente chi osserva con equanimità e
consapevolezza”».

[.suttaref]
_D. 2; D. 22; M. 39; S. 45:8_

«Proprio come in un laghetto alcuni fiori di loto blu, bianchi o rossi,
nati sotto la superficie dell’acqua, cresciuti sott’acqua, non
fuoriescono dall’acqua ma fioriscono immersi nell’acqua, e l’acqua li
imbeve, impregna, riempie, estendendosi dalla loro sommità fino alle
loro radici, e non c’è parte di tutti questi fiori di loto sui quale
l’acqua non si estenda, allo stesso modo un bhikkhu imbeve, impregna,
riempie questo corpo con il piacere spoglio della felicità, estendendolo
del tutto in esso, così che non c’è parte dell’intero corpo nel quale
tale piacere spoglio della felicità non giunga».

[.suttaref]
_D. 2; M. 39_

«Con l’abbandono del piacere e del dolore, e con la precedente scomparsa
della gioia e dell’afflizione mentale, egli entra e dimora nel quarto
jhāna, nel quale non c’è né piacere né dolore, e la purezza della
consapevolezza è dovuta all’equanimità».

[.suttaref]
_D. 2; D. 22; M. 39; S. 45:8_

«Proprio come un uomo seduto vestito di bianco da capo a piedi, senza
che ci sia una sola parte di tutto il suo corpo sulla quale il bianco
non giunga, allo stesso modo un bhikkhu siede con una pura e luminosa
cognizione che si estende su tutto il suo corpo, senza che ci sia una
sola parte di esso nella quale tale pura e luminosa cognizione non
giunga».

[.suttaref]
_D. 2; M. 39_

«Qual è quella retta concentrazione degli Esseri Nobili con le sue cause
e il suo corredo? È qualsiasi unificazione della mente che sia corredata
dagli altri sette fattori del Sentiero. Prima viene la retta visione: si
comprendono l’errata visione, l’errata intenzione, l’errata parola,
l’errata azione, gli errati mezzi di sostentamento come errati. Si
comprendono la retta visione, la retta intenzione, la retta parola, la
retta azione, i retti mezzi di sostentamento come retti, ossia ognuno
dei due tipi come associati alle contaminazioni e che maturano negli
essenziali dell’esistenza, oppure come sovra-mondani e come fattori del
Sentiero. Si fanno sforzi per abbandonare l’errata visione e gli altri
quattro, e per acquisire la retta visione e gli altri quattro: questo è
il retto sforzo. Consapevolmente si abbandona ciò che è errato e si
entra sul Sentiero del giusto: questa è la retta presenza mentale».

[.suttaref]
_M. 117 (condensato)_

[.narrator]
*Secondo narratore.* Questi ultimi tre fattori, retto sforzo, retta
presenza mentale e retta concentrazione, tutti insieme costituiscono la
“concentrazione”. Gli otto fattori, insieme alla retta conoscenza e alla
retta liberazione, sono chiamati le “dieci rettitudini”, che
costituiscono la “certezza della rettitudine” raggiunta con il Sentiero
di Chi è Entrato nella Corrente. Prima di abbandonare il tema della
concentrazione, però, ci sono quattro ulteriori stadi raggiungibili,
chiamati i quattro “stati privi di forma”. Essi sono un aggiuntivo alla
“retta concentrazione”, solo degli affinamenti del quarto jhāna.

[.voice]
*Prima voce.* «Con il completo superamento della percezione della forma,
con la scomparsa delle percezioni della resistenza, mediante il non
prestare attenzione alle percezioni della differenza, (consapevole
dello) “spazio infinito”, un bhikkhu entra e dimora nella base
consistente nell’infinità dello spazio».

«Ancora, mediante il completo superamento della base consistente
nell’infinità dello spazio, (consapevole della) “coscienza infinita”,
egli entra e dimora nella base consistente nell’infinità della
coscienza».

«Ancora, mediante il completo superamento della base consistente
nell’infinità della coscienza, (consapevole del) “non c’è nulla”, egli
entra e dimora nella base consistente nel nulla-è».

«Ancora, mediante il completo superamento della base consistente nel
nulla è, egli entra e dimora nella base consistente nella
né-percezione-né-non-percezione».

«I quattro jhāna nella Disciplina degli Esseri Nobili non sono chiamati
annullamento, nella Disciplina degli Esseri Nobili sono chiamati
piacevole dimorare qui e ora. I quattro stati privi di forma non sono
chiamati annullamento, nella Disciplina degli Esseri Nobili sono
chiamati sereno dimorare».

[.suttaref]
_M. 8_

«Il bhikkhu (che pratica tali otto conseguimenti) si dice che ha bendato
Māra, che ha (temporaneamente) privato Māra della vista dei suoi oggetti
e che è diventato invisibile al Malvagio».

[.suttaref]
_M. 25_

[.narrator]
*Secondo narratore.* Nessuno di questi otto conseguimenti (né le quattro
Divine Dimore, cfr. p. 200) sono rivendicate come peculiari
dell’insegnamento dei Buddha. La loro pratica priva di retta visione
conduce solo al paradiso, ma non al Nibbāna. L’insegnamento peculiare
dei Buddha è le Quattro Nobili Verità. Un nono conseguimento, il
“conseguimento della cessazione” è descritto come raggiunto nei due più
alti stadi di realizzazione ed è perciò peculiare dei Buddha e dei loro
discepoli.

[.voice]
*Prima voce.* «Con il completo superamento della base consistente nella
né-percezione-né-non-percezione, un bhikkhu entra e dimora nella
cessazione della percezione e della sensazione, e le sue contaminazioni
si esauriscono allorché egli le vede con comprensione. Allora si dice
che un bhikkhu ha bendato Māra, che ha privato Māra della vista dei suoi
oggetti e che è diventato invisibile al Malvagio e, quel che più conta,
che è andato al di là di ogni attaccamento per il mondo».


[.suttaref]
_M. 25_

[quote]
____
Quando un saggio, ben fondato nella virtù, +
sviluppa consapevolezza e comprensione, +
allora come un bhikkhu, ardente e sagace, +
riesce a dipanare il groviglio.
____

[.suttaref]
_S. 1:23_

«Bhikkhu, se un uomo dovesse viaggiare e arrancare attraverso un’era,
allora il cumulo, la pila, la massa delle sue ossa, se riunite né
distrutte, sarebbe tanto alto quanto il Monte Vepulla».

[.suttaref]
_Iti. 24_

«Supponiamo che un uomo gettasse nell’oceano un giogo con un foro in
esso e, poi, che il vento dell’est lo sospingesse a ovest, il vento
dell’ovest lo sospingesse a est, il vento del nord lo sospingesse a sud
e il vento del sud lo sospingesse a nord. E che ci fosse una tartaruga
cieca che sale in superficie solo una volta ogni cento anni. Che cosa ne
pensate, bhikkhu, quella tartaruga cieca potrebbe infilare la testa in
quel giogo con un foro in esso?».

«Potrebbe, Signore, solo dopo un lungo periodo».

«Bhikkhu, la tartaruga cieca metterebbe la sua testa in quel giogo con
un solo foro in esso prima che un folle, destinato alla perdizione,
possa trovare la via per tornare alla condizione umana».

[.suttaref]
_M. 129_

«Bhikkhu, il Dhamma da me ben proclamato è schietto, aperto, evidente e
spoglio di parole inutili. In questo Dhamma così da me ben proclamato
chiunque abbia semplice fiducia in me, semplice amore per me, è
destinato al paradiso».

[.suttaref]
_M. 22_

«Ciò che dovrebbe essere fatto per i discepoli per compassione da un
Maestro che cerca il loro benessere ed è compassionevole, questo ho
fatto io per voi. Ci sono questi spazi ai piedi degli alberi, queste
stanze vuote: praticate la meditazione, bhikkhu, evitate di rimandare
per rimpiangerlo in seguito. Questo è il mio insegnamento per voi».

[.suttaref]
_M. 8; M. 152_

[.narrator]
*Secondo narratore.* Con questo si conclude tale esposizione. Ma come è in
realtà percorso il Sentiero?

== Il Nobile Ottuplice Sentiero in pratica

[.voice]
*Prima voce.* Un mattino il venerabile Ānanda si vestì, prese la ciotola e
la veste superiore e si recò a Sāvatthī per la questua. Egli vide il
brāhmaṇa Jānussoni che usciva da Sāvatthī alla guida di un carro
trainato da quattro giumente, tutto era bianco: bianchi i cavalli,
bianche le imbracature, bianco il carro, bianca la tappezzeria, bianchi
i sandali, e lui stesso era rinfrescato da un bianco ventaglio. Quando
la gente vide tutto questo, disse: «Che divino veicolo! Ecco com’è un
veicolo divino!».

Quando tornò, il venerabile Ānanda lo raccontò al Beato e gli chiese:
«Signore, in questo Dhamma e Disciplina può essere individuato un divino
veicolo?».

«Sì, Ānanda, disse il Beato: “Divino veicolo” è un nome per il Nobile
Ottuplice Sentiero, ed è “veicolo del Dhamma” e “impareggiabile vittoria
nella battaglia”. Per tutti i componenti del Nobile Ottuplice Sentiero
esso culmina nell’espulsione della brama, dell’odio e dell’illusione».

[.suttaref]
_S. 45:4_

«(Un bambino viene concepito e con la nascita e la crescita) le sue
facoltà sensoriali maturano, viene dotato e investito dei cinque
componenti dei desideri sensoriali e li utilizza. Le forme conoscibili
mediante l’occhio sono ambìte e desiderate, sono gradevoli e piacevoli,
connesse con il desiderio sensoriale e inducono la brama. Lo stesso è
per i suoni conoscibili mediante l’orecchio, gli odori conoscibili
mediante il naso, i sapori conoscibili mediante la lingua e gli oggetti
tangibili mediante il corpo».

«Vedendo una forma visibile con l’occhio, ascoltando un suono con
l’orecchio, sentendo un odore con il naso, gustando un sapore con la
lingua, toccando un oggetto tangibile con il corpo, conoscendo un’idea
con la mente, egli li brama se sono attraenti, oppure prova malevolenza
nei loro riguardi se sono spiacevoli. Egli dimora senza la
consapevolezza del corpo fondata e con la mente ristretta, mentre non
comprende come in realtà sono la liberazione della mente e la
liberazione per mezzo della comprensione, ove questi stati non salutari
cessano senza residuo. Impegnato com’è nell’indulgere e nell’opporsi
quando prova ogni sensazione, piacevole o dolorosa oppure
né-piacevole-né-dolorosa, egli assapora quella sensazione, la conferma e
l’accetta. L’assaporamento sorge in lui quando lo fa. Ogni assaporamento
di quelle sensazioni è attaccamento. Con l’attaccamento quale
condizione, l’esistenza; con l’esistenza quale condizione, la nascita;
con la nascita quale condizione, giungono all’esistenza l’invecchiamento
e la morte, e anche l’afflizione, il lamento, il dolore, il dispiacere e
la disperazione. Così ha origine tutto questo aggregato di sofferenza».

«Un Perfetto appare nel mondo, realizzato e completamente illuminato,
perfetto per vera conoscenza e condotta, conoscitore dei mondi,
incomparabile guida degli uomini che devono essere addestrati,
insegnante di dèi e uomini, illuminato, beato. Egli dichiara a questo
mondo con i suoi deva, con i suoi Māra e con le sue divinità, a questa
generazione con i suoi monaci e brāhmaṇa, con i suoi principi e uomini
che egli ha realizzato se stesso mediante conoscenza diretta. Egli
insegna un Dhamma salutare al principio, nel mezzo e alla fine, con il
significato e il senso letterale, e spiega la santa vita che è
assolutamente perfetta e pura».

«Un capofamiglia, o suo figlio, oppure uno nato nello stesso clan,
ascolta questo Dhamma. Ascoltandolo, egli ha fiducia nel Perfetto.
Avendo questa fiducia, egli pensa: “La vita in famiglia è affollata e
polverosa, l’abbandono di essa comporta spaziose aperture. Vivendo in
famiglia non è facile condurre una santa vita assolutamente perfetta e
immacolata come una conchiglia ben lucidata. E se mi rasassi i capelli e
la barba, indossassi l’abito ocra, e rinunciassi alla vita in famiglia
per una senza dimora?”».

«E in un’ulteriore circostanza, abbandonando forse una piccola fortuna,
forse una grande fortuna, abbandonando forse una piccola, forse una
grande cerchia di parenti, si rasa i capelli e la barba, indossa l’abito
ocra e rinuncia alla vita in famiglia per una senza dimora».

«Avendo così abbracciato la vita religiosa e in possesso
dell’addestramento e del modo di vivere di un bhikkhu, egli abbandona
l’uccidere esseri viventi, astenendosi da ciò mettendo da parte bastoni
e armi; in modo gentile e benevolo, egli dimora nella compassione per
tutti gli esseri. Egli abbandona il prendere quel che non è dato,
astenendosi da ciò prendendo solo quel che è dato; aspettandosi solo
quel che è dato, dimora puro in se stesso mediante il non rubare. Egli
abbandona il non celibato, vivendo la vita celibataria come uno che vive
appartato, astenendosi dalla volgare lascivia. Egli abbandona l’errata
parola, astenendosi da ciò dicendo il vero; aderendo al vero quando
parla, egli è affidabile, attendibile e non inganna il mondo. Egli
abbandona la calunnia … Egli abbandona l’insulto … Egli abbandona il
pettegolezzo … parla con un linguaggio giusto che merita di essere
ricordato, che è motivato, preciso e connesso al
bene».footnote:[Si veda sopra, la “retta parola” (p. 265) per
il testo completo.]

«Egli si astiene dal danneggiare semi e piante. Egli mangia solo in una
parte del giorno, astenendosi dal cibo di notte e dai pasti tardivi.
Egli si astiene dal ballo, dal canto, dalla musica e dagli spettacoli
teatrali; dall’indossare ghirlande, dall’abbellirsi con profumi e
dall’adornarsi con unguenti; da letti alti e grandi; dall’accettare oro
e argento, grano, carne cruda, donne e ragazze, schiave e schiavi,
pecore e capre, pollame e maiali, elefanti, bovini, cavalli e cavalle,
campi e terreni; dall’andare a fare commissioni; da acquisti e vendite;
da falsi pesi, falsi metalli e false misure; da truffe, raggiri, frodi e
inganni; da mutilazioni, esecuzioni, imprigionamenti, rapine, saccheggi
e violenze».

«Si accontenta dell’abito [monastico] per proteggere il corpo, del cibo
ricevuto in elemosina per sostentarsi, così che ovunque vada porta tutto
con sé, proprio come un uccello dotato di ali vola usando le proprie
ali. Possedendo l’insieme delle virtù degli Esseri Nobili, egli prova in
se stesso un’irreprensibile beatitudine».

«Egli diviene uno che, vedendo una forma con l’occhio, non afferra segni
e caratteristiche mediante i quali possa essere invaso da non salutari
stati di cupidigia e afflizione, come se egli avesse lasciato la facoltà
visiva incustodita. Pratica la via del contenimento, custodisce la
facoltà visiva, porta a effetto il contenimento della facoltà visiva.
(Allo stesso modo, quando ascolta un suono con l’orecchio, quando sente
un odore con il naso, quando assapora un sapore con la lingua, quando
tocca un oggetto tangibile con il corpo e quando concepisce un’idea con
la mente.) Possedendo questa facoltà del contenimento degli Esseri
Nobili, egli prova in se stesso un’incontaminata beatitudine».

«È del tutto consapevole quando si muove avanti e indietro … e mantiene
il silenzio».footnote:[Si veda sopra, la “retta presenza mentale”
(p. 267) per il testo.]

«Possedendo l’insieme delle virtù degli Esseri Nobili, e questa facoltà
del contenimento degli Esseri Nobili, e questa consapevolezza e piena
presenza mentale degli Esseri Nobili, egli si avvale di un posto isolato
per riposare – una foresta, uno spazio ai piedi di un albero, un
precipizio, una caverna d’una montagna, un carnaio, una boscaglia d’una
giungla, uno spiazzo, un mucchio di paglia. Di ritorno dal giro per
l’elemosina dopo il pasto, egli si mette seduto, a gambe incrociate, con
il corpo eretto e con la consapevolezza fissa davanti a lui».

«Abbandonando la bramosia per il mondo, egli dimora con una mente priva
di bramosia; egli purifica la sua mente dalla bramosia. Abbandonando la
malevolenza e l’odio, egli dimora privo di pensieri di malevolenza,
compassionevole per il benessere di tutti gli esseri viventi; egli
purifica la sua mente dalla malevolenza e dall’odio. Abbandonando il
torpore e la sonnolenza, egli dimora con una mente libera dal torpore e
dalla sonnolenza, percettivo della luce, consapevole e pienamente
presente; egli purifica la sua mente dal torpore e dalla sonnolenza.
Abbandonando l’agitazione e la preoccupazione, egli dimora privo di
agitazione, con la mente pacificata in se stesso; egli purifica la sua
mente dall’agitazione e dalla preoccupazione. Abbandonando il dubbio,
egli dimora con una mente che ha superato il dubbio, senza più
interrogarsi sugli stati [mentali] non salutari; egli purifica la sua
mente dal dubbio».

[.suttaref]
_M. 38_

«Supponiamo che un uomo prenda un prestito, che intraprenda delle
attività e che tali attività abbiano successo, così che egli sia in
grado di restituire tutto il denaro del vecchio prestito e gliene
rimanga altro per la moglie e i figli, e che, poi, considerando queste
cose, egli si senta soddisfatto e felice. Oppure, supponiamo che un uomo
sia afflitto, sofferente e gravemente malato e che il suo cibo non gli
sia di sostegno, che il suo corpo sia privo di vigore, ma che in seguito
egli guarisca da questa afflizione e che il suo corpo riottenga vigore.
Oppure, supponiamo che un uomo sia imprigionato in una prigione, ma che
in seguito egli sia liberato dalla prigione sano e salvo, senza perdita
alcuna dei suoi beni. Oppure, supponiamo che un uomo sia in schiavitù,
che non sia autonomo ma che dipenda dagli altri e che non sia in grado
di andare dove vuole, ma che in seguito egli venga liberato da quelle
catene e diventi autonomo, indipendente dagli altri, un uomo libero in
grado di andare dove vuole. Oppure, supponiamo che un uomo il quale
rechi con sé beni e possessi entri in una strada che attraversa un
deserto, ma che in seguito attraversi sano e salvo il deserto, senza
perdita alcuna dei suoi beni, e che poi, considerando queste cose, egli
si senta soddisfatto e felice. Allo stesso modo, quando i cinque
impedimenti non sono in lui abbandonati, un bhikkhu li vede
rispettivamente come un debito, una malattia, una prigione, delle catene
e una strada che attraversa un deserto, e quando sono in lui
abbandonati, egli li vede come un non debito, la salute, l’uscita dalla
prigione, la libertà dalle catene e una terra sicura».

[.suttaref]
_M. 39_

«Avendo abbandonato i cinque impedimenti, le imperfezioni mentali che
indeboliscono la comprensione, allora, del tutto isolato dai desideri
sensoriali, isolato dagli stati [mentali] non salutari, entra e dimora
nel primo jhāna … nel secondo jhāna … nel terzo jhāna … nel quarto
jhāna».

«Vedendo una forma visibile con l’occhio, ascoltando un suono con
l’orecchio, sentendo un odore con il naso, assaporando un sapore con la
lingua, toccando un oggetto tangibile con il corpo, conoscendo un’idea
con la mente, egli non li brama se sono attraenti, e non prova
malevolenza nei loro riguardi se sono spiacevoli. Egli dimora con la
consapevolezza del corpo fondata e con un incommensurabile stato
mentale, mentre comprende come in realtà sono la liberazione della mente
e la liberazione per mezzo della comprensione, ove questi stati non
salutari cessano senza residuo. Avendo così abbandonato l’indulgere e
l’opporsi quando prova ogni sensazione, piacevole o dolorosa oppure
né-piacevole-né-dolorosa, egli non assapora quella sensazione, né la
conferma e nemmeno l’accetta. Quando non lo fa, l’assaporamento di
quelle sensazioni cessa. Con la cessazione del suo assaporamento, cessa
l’attaccamento. Con la cessazione dell’attaccamento, cessa l’esistenza;
con la cessazione dell’esistenza, cessa la nascita; con la cessazione
della nascita, cessano l’invecchiamento e la morte, e anche
l’afflizione, il lamento, il dolore, il dispiacere e la disperazione.
Così c’è la cessazione di tutto questo aggregato di sofferenza».

[.suttaref]
_M. 38_

== I mezzi

«Supponiamo che un uomo, volendo un serpente, ne veda uno grande e in
seguito lo afferri in modo sbagliato, per le spire o per la coda, così
che il serpente si giri e lo morda, e a causa di questo egli muoia o
patisca sofferenze mortali. – Perché? Perché ha afferrato il serpente in
modo sbagliato. – Allo stesso modo, alcuni uomini fuorviati imparano il
Dhamma senza esaminare il significato degli insegnamenti con
comprensione, così che non acquisiscono alcun diletto nel meditare su di
essi. Imparandolo invece allo scopo di cavillare e confutare, non
riescono ad apprezzare il fine per cui il Dhamma viene imparato, ma
sperimentano che gli insegnamenti, essendo da loro stati erroneamente
compresi, li conducono per lungo tempo verso danno e sofferenza.
Supponiamo invece che un uomo, volendo un serpente, ne veda uno grande e
in seguito lo catturi in modo giusto, con un bastone a forcella per il
collo, ma, benché il serpente possa avvolgere le sue spire intorno alla
sua mano o al suo braccio o ai suoi arti, a causa di questo tuttavia
egli né muoia né patisca sofferenze mortali. Allo stesso modo, alcuni
uomini di rango che imparano il Dhamma esaminando il significato degli
insegnamenti con comprensione, acquisiscono una preferenza nel meditare
su di essi. Non imparandolo allo scopo di cavillare e confutare,
apprezzano il fine per cui il Dhamma viene imparato, e sperimentano che
quegli insegnamenti, essendo da loro stati rettamente compresi, li
conducono per lungo tempo verso benessere e felicità».

«Bhikkhu, supponiamo che un viaggiatore veda una grande distesa d’acqua,
la cui riva più vicina è pericolosa e temibile e quella più lontana
sicura e innocua, ma che non ci sia né un traghetto né un ponte. Dopo
aver preso in considerazione tutto questo, che egli raccolga erba, rami,
ramoscelli, foglie e che li leghi assieme facendone una zattera, aiutato
dalla quale, e sforzandosi con mani e piedi, riesca sano e salvo nella
traversata. Poi quando è riuscito, pensa: “Questa zattera mi è stata
molto utile, perché grazie ad essa sono riuscito sano e salvo nella
traversata. E se io me la caricassi sulla testa o sulle spalle e andassi
dove intendo andare?”. Farebbe in questo caso quel che deve essere fatto
con una zattera?».

«No, Signore». – «Che cosa dovrebbe fare con la zattera? Se, quando è
riuscito nella traversata, pensasse: “Questa zattera mi è stata molto
utile, perché grazie ad essa sono riuscito sano e salvo nella
traversata. E se io la tirassi in secco o la mandassi alla deriva e
andassi dove intendo andare?”, allora farebbe quel che deve essere fatto
con la zattera. Vi ho così mostrato come il Dhamma somigli a una zattera
che serve alla traversata, non ad attaccarsi. Bhikkhu, quando conoscete
la Similitudine della Zattera, (allora perfino i buoni) insegnamenti
dovrebbero essere da voi abbandonati, e a maggior ragione quelli
cattivi».

[.suttaref]
_M. 22 (condensato)_

== La Meta

«La cessazione della brama, dell’odio e dell’illusione è il Non-Formato
(Incondizionato), la Meta, l’Incontaminato, la Verità, l’Altra Sponda,
il Sottile, il Molto Difficile da Vedere, l’Indeclinabile, il Perenne,
l’Indisintegrabile, l’Invisibile, l’Indiversificato, la Pace, Ciò che
Non Muore, Il Fine Supremo, la Beatitudine, la Sicurezza, l’Esaurimento
della Brama, il Magnifico, il Meraviglioso, la Non Afflizione, il
Naturalmente Non Angustiato, il Nibbāna, la Non Sofferenza (la Non
Ostilità), lo Svanire del Desiderio, la Purezza, la Libertà,
l’Indipendenza dal dipendente, l’Isola, il Ricovero, il Porto, il
Rifugio, l’Oltre.

[.suttaref]
_S. 43:1-44_

