= Devadatta

[.narrator]
`SECONDO NARRATORE.` Devadatta era il primo cugino del Buddha. Il suo
tentativo di usurpare il posto del Buddha è collocato trentasette anni
dopo l’Illuminazione: quando, in altre parole, il Buddha aveva
settantadue anni.

[.narrator]
`PRIMO NARRATORE.` Questo è il racconto offerto nel _Vinaya Piṭaka_.

[.voice]
`SECONDA VOCE.` Avvenne questo. Una volta, quando Devadatta era da solo in
ritiro, questo pensiero sorse nella sua mente: «Di chi posso
conquistarmi la fiducia e così acquisire profitto, onore e fama?». Poi
pensò: «Il principe Ajātasattu. È giovane, e ha un futuro glorioso. E se
io mi guadagnassi la sua fiducia? Se lo faccio, me ne verrà molto
profitto, onore e fama».

Così Devadatta ripose il suo giaciglio, prese la ciotola e la veste
superiore e partì per Rājagaha, dove infine arrivò. Qui abbandonò la
forma della sua persona e assunse quella di un giovane con una cintura
di serpenti e, in quelle sembianze, comparve in grembo al principe
Ajātasattu. Il principe Ajātasattu divenne allora timoroso, ansioso,
sospettoso e preoccupato. Devadatta gli chiese: «Hai paura di me,
principe?».

«Sì, ho paura. Chi sei?».

«Sono Devadatta».

«Se sei Devadatta, signore, per favore mostrati nella tua forma».

Devadatta abbandonò la forma del giovane e, con la ciotola e indossando
la veste superiore rappezzata e il resto dell’abito monastico, si mise
in piedi di fronte al principe Ajātsattu. Allora il principe nutrì una
grandissima fiducia in Devadatta in ragione dei suoi poteri
sovrannaturali. Poi lo servì alla sera e al mattino con cinquecento
carrozze e cinquecento offerte di latte di riso, quale dono in derrate
di cibo. Devadatta fu travolto da profitto, onore e fama. L’ambizione
ossessionò la sua mente e un desiderio sorse nella sua mente: «Governerò
il Saṅgha dei bhikkhu». Contemporaneamente a questo pensiero svanirono i
suoi poteri sovrannaturali.

[.suttaref]
_Vin. Cv. 7:2; cf. S. 17:36_

Allorché il Beato aveva soggiornato a Benares per tutto il tempo che
volle, si mise in viaggio per tappe verso Rājagaha, ove giunse a tempo
debito. Andò a vivere nel Boschetto di Bambù, nel Sacrario degli
Scoiattoli. Allora un certo numero di bhikkhu si recò da lui e gli
disse: «Signore, il principe Ajātasattu serve Devadatta ogni sera e ogni
mattino con cinquecento carrozze e cinquecento offerte di latte di riso,
quale dono in derrate di cibo».

«Bhikkhu, non invidiate a Devadatta il suo profitto, onore e fama.
Proprio come quando si rompe una cistifellea sotto il naso di un cane
inferocito e il cane s’inferocisce ancora di più, così, fino a quando il
principe Ajātasattu continua a servire Devadatta come sta facendo ora,
altrettanto a lungo si può prevedere che gli stati [mentali] salutari in
Devadatta diminuiscano e non aumentino. Proprio come un banano produce i
suoi frutti per la propria distruzione e rovina,footnote:[NDT. Dopo aver
prodotto fiori e frutti, il banano muore.] allo
stesso modo il profitto, l’onore e la fama di Devadatta sono sorti per
la sua stessa distruzione e rovina».

[.suttaref]
_Vin. Cv. 7:2; cfr. S. 17:35-36 e A. 4:68_

Avvenne questo. Il Beato stava seduto a insegnare il Dhamma, circondato
da un grande raduno di persone, incluso il re. Allora Devadatta si alzò
dal posto in cui sedeva e, sistemando la sua veste superiore su una
spalla, levò le palme delle mani giunte verso il Beato: «Signore, il
Beato ora è anziano, gravato dagli anni, avanti nella vita e giunto allo
stadio finale. Che il Beato riposi, ora. Che dimori nella beatitudine in
questa vita. Che ceda a me il Saṅgha. Io governerò il Saṅgha dei
bhikkhu».

«Basta così, Devadatta. Non aspirare al governo del Saṅgha dei bhikkhu».

Una seconda volta Devadatta fece la stessa proposta e ricevette la
stessa risposta. Quando fece la stessa proposta per la terza volta, il
Beato disse: «Non cederei il Saṅgha dei bhikkhu neanche a Sāriputta e
Moggallāna. Come potrei cederlo a un buono a nulla, a un grumo di sputo
quale tu sei?».

Allora Devadatta pensò: «In pubblico, re compreso, il Beato mi ha
disonorato con le parole “grumo di sputo” e ha lodato Sāriputta e
Moggallāna». Era molto arrabbiato e indignato. Prestò omaggio al Beato e
se andò, girandogli a destra. Questo fu il primo rancore nei riguardi
del Beato.

Il Beato si rivolse ai bhikkhu: «Ora bhikkhu, effettuiamo un atto di
pubblica denuncia a Rājagaha contro Devadatta in questo modo: “Prima
Devadatta aveva una natura, ora ne ha un’altra. Qualsiasi cosa Devadatta
possa fare con il corpo o con la parola, si deve ritenere che né il
Beato né il Dhamma né il Saṅgha vi abbiano preso parte: solo Devadatta
stesso deve esserne ritenuto responsabile”».

Allora il Beato si rivolse al venerabile Sāriputta: «Ora, Sāriputta, tu
devi denunciare Devadatta a Rājagaha».

«Signore, finora ho parlato in favore di Devadatta in questo modo: “Il
figlio di Godhī è forte e potente”. Come posso denunciarlo a Rājagaha?».

«Quando lodavi Devadatta stavi dicendo la verità?».

«Sì, Signore».

«Allo stesso modo, dicendo la verità devi denunciarlo a Rājagaha».

«E sia, Signore», rispose il venerabile Sāriputta.

Quando il venerabile Sāriputta fu autorizzato formalmente dal Saṅgha,
egli si recò a Rājagaha accompagnato da un certo numero di bhikkhu e
denunciò Devadatta. La gente priva di fede e di fiducia, di saggezza e
di discrezione disse: «Questi monaci, figli dei Sakya, sono gelosi del
profitto, dell’onore e della fama di Devadatta». Quelli invece dotati di
fede e di fiducia, di saggezza e discrezione dissero: «Non devono essere
ragioni di poco conto a spingere il Beato a denunciare Devadatta a
Rājagaha».

Allora Devadatta andò dal principe Ajātasattu e gli disse: «Prima gli
uomini vivevano a lungo, ora vivono per poco. Forse morirai quando sei
ancora solo un principe, e allora perché non uccidi tuo padre e diventi
re? E io ucciderò il Beato e diverrò il Buddha».

Il principe Ajātasattu pensò: «Devadatta è forte e potente, lui sa». Si
allacciò un pugnale alla coscia e, spaventato, sospettoso e preoccupato,
in pieno giorno cercò di introdursi nella parte interna del palazzo. Gli
ufficiali del re che stavano all’ingresso della parte interna del
palazzo lo videro mentre tentava di entrare e lo arrestarono.
Perquisendolo, trovarono il pugnale allacciato alla coscia. Gli
chiesero: «Che cosa vuoi fare, principe?».

«Voglio uccidere mio padre».

«Chi ti ha suggerito di farlo?».

«Devadatta».

Alcuni ufficiali erano dell’opinione che il principe doveva essere
ucciso, come pure Devadatta e anche tutti i bhikkhu. Altri erano
dell’opinione che i bhikkhu non dovevano essere uccisi, perché non
avevano fatto nulla di male, ma che il principe e Devadatta dovevano
essere uccisi. Altri ancora erano dell’opinione che né il principe, né
Devadatta e nemmeno i bhikkhu dovevano essere uccisi, ma che il re
doveva essere informato e i suoi ordini eseguiti.

Allora gli ufficiali portarono il principe Ajātasattu al cospetto di
Seniya Bimbisāra, re di Magadha, e gli raccontarono quel che era
successo.

«Qual è l’opinione degli ufficiali?».

Loro lo informarono.

«Che cosa hanno a che fare il Buddha, il Dhamma e il Saṅgha con tutto
questo? Devadatta non è stato denunciato a Rājagaha dal Beato?».

Egli allora bloccò la paga a quegli ufficiali che erano stati
dell’opinione che il principe Ajātasattu, Devadatta e i bhikkhu dovevano
essere uccisi. Degradò quegli ufficiali che erano stati dell’opinione
che i bhikkhu, non avendo fatto nulla di male, non dovevano essere
uccisi, ma che il principe e Devadatta dovevano essere uccisi. Promosse
quegli ufficiali che erano stati dell’opinione che né il principe, né
Devadatta e nemmeno i bhikkhu dovevano essere uccisi, ma che il re
doveva essere informato e i suoi ordini eseguiti. Poi il re Bimbisāra
chiese: «Perché vuoi uccidermi, principe?».

«Voglio il regno, sire».

«Se vuoi il regno, principe, il regno è tuo».

Con ciò gli passò il regno.

Devadatta andò dal principe Ajātasattu e gli disse: «Gran re, invia
alcuni uomini a uccidere il monaco Gotama».

Così il principe Ajātasattu impartì l’ordine ad alcuni uomini: «Fate
come dice Devadatta». E Devadatta disse a uno degli uomini: «Vai, amico.
Il monaco Gotama vive in tal posto. Uccidilo e torna per questa strada».
Poi fece appostare due uomini su quella strada, e disse loro: «Uccidete
l’uomo che camminerà su quella strada, e tornate per questa strada». Poi
fece appostare quattro uomini su quella strada … otto uomini su quella
strada … sedici uomini su quella strada …

Allora quell’uomo prese la sua spada e il suo scudo, il suo arco e la
sua faretra, e andò dove si trovava il Beato. Egli, però, non appena si
avvicinò la sua paura crebbe, finché non rimase impalato in piedi, con
il corpo completamente rigido. Il Beato lo vide così e gli disse: «Vieni
amico, non avere paura». Allora l’uomo posò da un lato la spada e lo
scudo, e poggiò a terra l’arco e la faretra. Andò dal Beato e si prostrò
ai suoi piedi, dicendo: «Signore, ho trasgredito, ho sbagliato come un
pazzo confuso e maldestro, perché io sono giunto qui con un’intenzione
malvagia, con l’intenzione di commettere un omicidio. Signore, che il
Beato perdoni la mia infrazione al fine che mi contenga in futuro».

«Amico, certamente hai trasgredito, hai sbagliato come un pazzo confuso
e maldestro, perché sei giunto qui con un’intenzione malvagia, con
l’intenzione di commettere un omicidio. Siccome, però, hai compreso e
visto la tua infrazione come tale e, perciò, agito in accordo con il
Dhamma, ti perdoniamo, perché significa una crescita nella disciplina
degli Esseri Nobili quando un uomo vede un’infrazione come tale e,
perciò, agisce in accordo con il Dhamma e s’impegna nel contenimento per
il futuro».

Allora il Beato impartì all’uomo un insegnamento progressivo …

Infine sorse in lui la pura, immacolata visione del Dhamma … Egli
divenne indipendente dagli altri nella Dispensazione del Maestro. Egli
disse: «Magnifico, Signore! … Che il Beato mi accolga come suo seguace
…».

Il Beato gli disse: «Amico, non tornare indietro per quella strada,
prendi quest’altra». Ed egli lo congedò dall’altra strada.

Allora i due uomini pensarono: «Com’è? Quell’uomo sarebbe dovuto
arrivare da tempo». Essi seguirono la strada finché videro il Beato che
sedeva ai piedi di un albero. Lo raggiunsero e, dopo avergli prestato
omaggio, si misero a sedere da un lato. Il Beato impartì loro un
insegnamento progressivo. Infine loro dissero: «Magnifico, Signore! …
Che il Beato ci accolga come suoi seguaci …». Allora il Beato li congedò
da un’altra strada. Lo stesso avvenne con i quattro, gli otto e i sedici
uomini.

Il primo uomo andò da Devadatta e gli disse: «Non ho ucciso il Beato,
Signore. Il Beato è forte e potente».

«Basta così, amico. Non uccidere il monaco Gotama. Io stesso ucciderò il
monaco Gotama».

In quel momento il Beato stava facendo la meditazione camminata
all’ombra del Picco dell’Avvoltoio. Allora Devadatta si arrampicò sul
Picco dell’Avvoltoio e gettò giù un enorme sasso, pensando: «In questo
modo ucciderò il monaco Gotama».

Due speroni di roccia si riunirono e bloccarono la pietra, ma una sua
scheggia fece sanguinare un piede del Beato. Allora egli guardò verso
l’alto e disse a Devadatta: «Uomo fuorviato, molto è il tuo demerito,
perché con intenzione malvagia, con l’intenzione di uccidere, hai fatto
sanguinare un Perfetto».

Poi il Beato si rivolse ai bhikkhu con queste parole: «Bhikkhu, questa è
la prima azione con effetto immediato sulla rinascita che Devadatta ha
accumulato, perché con intenzione malvagia, con l’intenzione di
uccidere, ha fatto sanguinare un Perfetto».

[.suttaref]
_Vin. Cv. 7:3_

[.voice]
`PRIMA VOCE.` In quel tempo, quando il piede del Beato era stato ferito
dalla scheggia, egli soffrì per gravi sensazioni corporee, che erano
dolorose, acute, tormentose, sgradevoli e spiacevoli. Consapevole e
pienamente presente, egli le sopportò senza irritazione e, allargando la
sua veste superiore fatta di toppe ripiegata in quattro, si mise a
giacere sul lato destro nella posizione del leone, con un piede
sovrapposto all’altro, consapevole e pienamente presente.

Allora Māra il Malvagio andò da lui e gli si rivolse in strofe:

[verse, S. 4:13]
____
Com’è che giaci, sei inebetito? +
Oppure sei estasiato da qualche divagazione? +
Non ci sono molti scopi da raggiungere? +
Perché, intento a dormire, te ne vai lontano coi sogni +
da solo nel luogo appartato ove dimori?

Non è perché sono inebetito che sto giacendo, +
neppure sono estasiato da qualche divagazione. +
Il mio scopo l’ho raggiunto. +
Dormo per compassione di tutti gli esseri +
da solo nel luogo appartato ove dimoro.

Allora Māra il Malvagio seppe: «Il Beato mi conosce, il Sublime mi
conosce». Triste e deluso, subito sparì.
____

[.voice]
`SECONDA VOCE.` I bhikkhu sentirono: «Sembra che Devadatta abbia cercato
di assassinare il Beato». Camminarono sopra, sotto e tutt’intorno al
luogo in cui il Beato dimorava. Fecero un gran rumore, un gran clamore,
recitando canti per la custodia, la salvaguardia e la protezione del
Beato. Quando il Beato sentì, chiese al venerabile Ānanda: «Ānanda, che
cos’è questo gran rumore, questo gran clamore, questa recitazione di
canti?».

«Signore, i bhikkhu hanno sentito che Devadatta ha cercato di
assassinare il Beato» e gli disse quello che stavano facendo.

«Allora, Ānanda, dì a quei bhikkhu da parte mia: “Il Maestro vi chiama,
venerabili”».

«E sia, Signore», rispose il venerabile Ānanda. Ed egli andò dai bhikkhu
e disse loro: «Il Maestro vi chiama, venerabili».

«E sia», loro risposero. E si recarono dal Beato. Il Beato disse loro:
«Bhikkhu, è impossibile, non può succedere che qualcuno uccida
violentemente un Perfetto. Quando i Perfetti raggiungono il Nibbāna
definitivo, ciò non avviene per un atto di violenza compiuto da un
altro. Tornate alle vostre dimore, bhikkhu. I Perfetti non hanno bisogno
di protezione».

In quel tempo a Rājagaha c’era un elefante, selvaggio e uccisore di
uomini, chiamato Nāḷagiri. Devadatta andò nella stalla degli elefanti di
Rājagaha. Egli disse ai mahout: «Conosco il re e sono influente. Posso
ottenere che quanti occupano posizioni basse siano promossi, e procurare
aumenti di salario e di cibo. Perciò, quando il monaco Gotama arriva su
questa strada, liberate l’elefante Nāḷagiri su questa stessa strada». «E
sia, Signore», loro risposero.

Quando fu mattino, il Beato si vestì, prese la ciotola e la veste
superiore, ed entrò a Rājagaha per la questua con un certo numero di
bhikkhu. Allora il Beato entrò in quella strada. I mahout lo videro e
lasciarono libero l’elefante Nāḷagiri su quella stessa strada.
L’elefante vide il Beato che arrivava da lontano. Quando lo vide, alzò
la proboscide e, con le orecchie aperte e la coda eretta, caricò il
Beato.

I bhikkhu lo videro arrivare da lontano. Dissero: «Signore, l’elefante
Nāḷagiri, selvaggio e uccisore di uomini, è libero sulla strada.
Signore, che il Beato torni indietro, Signore, che il Beato torni
indietro».

«Venite, bhikkhu, non abbiate paura. È impossibile, non può succedere
che qualcuno uccida violentemente un Perfetto. Quando i Perfetti
raggiungono il Nibbāna definitivo, ciò non avviene per un atto di
violenza compiuto da un altro».

Una seconda e una terza volta i bhikkhu dissero la stessa cosa e
ricevettero la stessa risposta.

Allora la gente nei palazzi, nelle case e nelle capanne attendeva con
apprensione. Chi era privo di fede e di fiducia, di saggezza e di
discrezione disse: «Il monaco Gotama, che ha un così bell’aspetto, sarà
ferito dall’elefante». Chi era invece dotato di fede e di fiducia, di
saggezza e discrezione disse: «Presto avverrà che un pachiderma combatta
un altro pachiderma».

Allora il Beato abbracciò l’elefante Nāḷagiri con pensieri di gentilezza
amorevole. L’elefante abbassò la sua proboscide, raggiunse il Beato e si
mise di fronte a lui. Il Beato accarezzò la fronte dell’elefante con la
mano destra e gli rivolse queste strofe:

[verse]
____
Elefante, non attaccare un pachiderma, +
perché è dannoso attaccare un pachiderma. +
Non c’è dopo alcun felice destino +
per chi uccide un pachiderma. +
Avendolo fatto per vanità e avventatezza +
l’avventato non ha felice destino. +
Agisci perciò in modo da poterti dirigere +
verso un felice destino.
____

L’elefante Nāḷagiri tolse la polvere dai piedi del Beato con la sua
proboscide e la sparse sulla sua testa, e si ritirò camminando a ritroso
finché il Beato uscì dalla sua vista. Andò nella stalla degli elefanti e
si mise al suo posto. Così fu che egli venne domato. Allora la gente
cantò questa strofa:

[verse]
____
Alcuni domano mediante bastoni, +
altri con pungoli e sferze. +
Qui però un saggio ha domato un pachiderma +
senza usare né bastoni né armi.
____

La gente era irritata, mormorava e protestava: «Questo sciagurato di
Devadatta è in realtà così malvagio da cercare di uccidere il monaco
Gotama che è così forte e potente!». E la fama e l’onore di Devadatta
svanirono mentre la fama e l’onore del Beato crebbero ancor di più.

[.suttaref]
_Vin. Cv. 7:3_

Ora, dopo che la fama e l’onore di Devadatta erano svaniti, lui e i suoi
seguaci erano soliti andare a mangiare insieme presso le famiglie,
informandole in precedenza di quello che volevano. La gente era
irritata, mormorava e protestava: «Come possono dei monaci, figli dei
Sakya, andare a mangiare insieme presso le famiglie, informandole in
precedenza di quello che vogliono? Chi non prova diletto per le cose
buone? A chi non piacciono le cose buone?». Pure i bhikkhu che avevano
pochi desideri erano irritati. Lo dissero al Beato. Il Beato chiese a
Devadatta: «È vero, come sembra, che stai facendo questo?».

«È vero, Signore».

Il Beato lo rimproverò e, dopo aver tenuto un discorso di Dhamma, si
rivolse ai bhikkhu con queste parole: «Ora, bhikkhu, consentirò ai
bhikkhu di mangiare presso le famiglie in gruppi di non più di tre.
Questo per tre ragioni: per il contenimento di coloro che pensano in
modo erroneo e per l’agio di coloro che sono ragionevoli, affinché
coloro che hanno desideri malvagi non si riuniscano in fazioni e causino
uno scisma nel Saṅgha, e per compassione nei riguardi delle famiglie.
Mangiare in gruppo, però, dovrà avvenire secondo la procedura già
prevista».

[.suttaref]
_Vin. Cv. 7:3; Vin. Sv. Pāc. 32_

Devadatta andò da Kokālika, Kaṭamoraka-Tissa, Khaṇḍādeyīputta e
Samuddadatta e disse: «Venite, amici, causiamo uno scisma e una
lacerazione nella concordia del Saṅgha del monaco Gotama». Kokālika
disse: «Il monaco Gotama è forte e potente, amico. Come possiamo
farlo?».

«Venite, amici, possiamo andare dal monaco Gotama e interrogarlo su
cinque punti: “Signore, il Beato ha in molti modi lodato chi ha pochi
desideri, si accontenta, si dedica all’eliminazione [della brama],
scrupoloso e amabile, dedito alla diminuzione (dell’attaccamento) ed
energico. Ora, ci sono cinque punti che conducono a questi stati.
Signore, sarebbe bene che i bhikkhu dimorassero nella foresta per tutta
la vita e che chiunque di loro andasse a vivere in un villaggio fosse
rimproverato. Che mangiassero cibo elemosinato per tutta la vita e che
chiunque di loro accettasse un invito fosse rimproverato. Che
indossassero panni scartati per tutta la vita e che chiunque di loro
indossasse una veste donata da capifamiglia fosse rimproverato. Che
dimorassero ai piedi di un albero per tutta la vita e che chiunque di
loro dimorasse in edifici fosse rimproverato. Che non mangiassero pesce
o carne per tutta la vita e che chiunque lo facesse fosse rimproverato.
Il monaco Gotama non potrà mai concedere queste cose. Così potremo
informare la gente in relazione a questi cinque punti. Sarà possibile
causare uno scisma e una lacerazione nella concordia del Saṅgha del
monaco Gotama, perché la gente ammira l’abnegazione».

Allora Devadatta andò con i suoi seguaci dal Beato e, dopo avergli
prestato omaggio, si mise a sedere da un lato. Dopo averlo fatto, egli
disse: «Signore, il Beato ha in molti modi lodato chi ha pochi desideri,
si accontenta, si dedica all’eliminazione [della brama], scrupoloso e
amabile, dedito alla diminuzione (dell’attaccamento) ed energico. Ora,
ci sono cinque punti che conducono a [questi stati] ...». Ed egli
enumerò i cinque punti.

«Basta così, Devadatta. Lascia che nella foresta dimori chi desidera
dimorarci e lascia che in un villaggio dimori chi desidera dimorarci.
Lascia che mangi cibo elemosinato chi desidera mangiarlo e lascia che
accetti inviti chi desidera accettarli. Lascia che indossi panni
scartati chi desidera indossarli e lascia che indossi una veste donata
da capifamiglia chi desidera indossarla. Vivere ai piedi di un albero è
da me permesso per otto mesi all’anno, ma non durante la stagione delle
piogge. Ho permesso [di mangiare] pesce o carne che sia pura per questi
tre aspetti: quando un bhikkhu non vede, sente o sospetta che
[l’animale] sia ucciso appositamente per i bhikkhu».

Devadatta fu contento ed esultante: «Il Beato non concede questi cinque
punti». Si alzò con i suoi seguaci e, dopo aver prestato omaggio al
Beato, se ne andò, girandogli a destra.

Andò a Rājagaha e iniziò a informare la gente a proposito dei cinque
punti in questo modo: «Amici, siamo stati dal monaco Gotama e lo abbiamo
interrogato su questi cinque punti …» e disse loro i cinque punti,
concludendo: «Il Beato non concede questi cinque punti. Noi, però, ci
impegnamo a vivere seguendoli».

La gente che mancava di fiducia disse: «Questi monaci, figli dei Sakya,
sono scrupolosi nell’eliminazione [della brama], invece il monaco Gotama
vive nel lusso, pensando al lusso». La gente saggia e fiduciosa, però,
era irritata, mormorava e protestava: «Come può Devadatta mirare a
causare uno scisma e una lacerazione nella concordia del Saṅgha?».

I bhikkhu li ascoltarono disapprovando. Quei bhikkhu che avevano pochi
desideri disapprovarono allo stesso modo e lo dissero al Beato. Egli
chiese a Devadatta: «Devadatta, è vero, come sembra, che tu stai mirando
a causare uno scisma e una lacerazione nella concordia del Saṅgha?».

«È vero, Signore».

«Basta così, Devadatta, non cercare di causare uno scisma e una
lacerazione nella concordia del Saṅgha. Chi lacera la concordia del
Saṅgha matura un’infelicità che dura per quanto resta di quest’era, egli
la matura nell’inferno per quanto resta di quest’era. Chi invece
riunisce il Saṅgha già diviso matura la più grande ricompensa in meriti
e gode del paradiso per quanto resta di quest’era. Basta così,
Devadatta, non cercare di causare uno scisma nel Saṅgha: uno scisma nel
Saṅgha è una cosa grave».

[.suttaref]
_Vin. Cv. 7:3; Vin. Sv. Saṇgh. 10_

Quando fu mattino, il venerabile Ānanda si vestì, prese la ciotola e la
veste superiore, e si recò a Rājagaha per la questua. Devadatta lo vide,
andò da lui e gli disse: «Ora, amico Ānanda, a cominciare da oggi io
osserverò il santo giorno dell’_Uposatha_ e adempirò gli atti del Saṅgha
separatamente dal Beato e dal Saṅgha dei bhikkhu».

Al ritorno il venerabile Ānanda lo disse al Beato. Conoscendo il
significato di ciò, il Beato esclamò queste parole:

[verse]
____
Il bene può farlo con facilità chi è buono, +
il bene non può farlo con facilità chi è malvagio. +
Il male può farlo con facilità chi è malvagio, +
gli Esseri Nobili non possono fare cattive azioni.
____

Il successivo giorno dell’_Uposatha_ Devadatta organizzò una votazione:
«Amici, siamo andati dal Beato e lo abbiamo interrogato su cinque punti.
Egli non ce li ha concessi. Ora noi ci impegnamo a vivere seguendoli.
Che i venerabili votino in favore di questi cinque punti».

In quel tempo c’erano cinquecento bhikkhu che provenivano da Vesālī,
figli dei Vajji. Erano bhikkhu da poco, privi di discernimento.
Pensando: «Questo è il Dhamma, questa è la Disciplina, questo è
l’insegnamento del Maestro», votarono favorevolmente. Dopo aver causato
uno scisma nel Saṅgha, Devadatta partì per Gayāsīsa con i cinquecento
bhikkhu.

[.suttaref]
_Vin. Cv. 7:3; Ud. 5:8_

[.voice]
`PRIMA VOCE.` Il Beato stava soggiornando a Rājagaha sul Picco
dell’Avvoltoio. Era subito dopo la partenza di Devadatta. Allora, a
notte inoltrata, Brahmā Sahampati, con un aspetto meraviglioso che
illuminava tutto il Picco dell’Avvoltoio, andò dal Beato e, dopo avergli
prestato omaggio, si mise in piedi da un lato. Poi, si rivolse al Beato
con queste strofe:

[verse, S. 6:12; cf. A. 4:68]
____
L’atto di fruttificare distrugge +
l’aloe, il banano e il bambù. +
E la fama distrugge pure il perdigiorno, +
come avviene alla mula con il parto.
____

[.voice]
`SECONDA VOCE.` Sāriputta e Moggallāna andarono dal Beato. Loro gli
dissero: «Signore, Devadatta ha causato uno scisma nel Saṅgha ed è
partito per Gayāsīsa con cinquecento bhikkhu».

«Non provate pietà per quei bhikkhu inesperti? Andate, prima che la loro
rovina si compia».

«E sia, Signore», loro risposero. E poi partirono per Gayāsīsa. Dopo che
se n’erano andati, un bhikkhu era in lacrime, non lontano dal Beato. Il
Beato gli chiese: «Perché piangi, bhikkhu?».

«Signore, quando i due discepoli eminenti del Beato, Sāriputta e
Moggallāna, si recheranno da Devadatta, anche loro passeranno al suo
insegnamento».

«È impossibile, bhikkhu, non può succedere che Sāriputta e Moggallāna
passino all’insegnamento di Devadatta. Loro, al contrario, convertiranno
quei bhikkhu che sono passati al suo insegnamento».

Devadatta stava seduto a insegnare il Dhamma circondato da un grande
raduno di persone. Egli vide il venerabile Sāriputta e il venerabile
Moggallāna che arrivavano da lontano. Egli disse ai bhikkhu: «Guardate,
bhikkhu, il Dhamma è da me ben proclamato. Perfino i discepoli eminenti
del monaco Gotama, Sāriputta e Moggallāna, vengono da me e passano al
mio insegnamento».

Quando ciò fu detto, Kokālika avvertì Devadatta: «Amico Devadatta, non
fidarti di loro. Sono preda di desideri malvagi».

«Basta così, amico. Loro sono benvenuti dal momento che devono passare
al mio insegnamento».

Allora Devadatta offrì al venerabile Sāriputta metà del posto in cui
sedeva: «Vieni, amico Sāriputta, siediti qui».

«Basta così, amico», rispose il venerabile Sāriputta e, prendendo posto,
si mise a sedere da un lato. Il venerabile Moggallāna fece lo stesso.
Ora, quando Devadatta ebbe istruito, esortato, risvegliato e
incoraggiato con un discorso di Dhamma i bhikkhu per gran parte della
notte, egli disse al venerabile Sāriputta: «Amico Sāriputta, il Saṅgha
dei bhikkhu è ancora libero dalla stanchezza e dalla sonnolenza. Forse
può venirti in mente un discorso di Dhamma. Mi duole la schiena, perciò
mi riposerò».

«E sia amico», rispose il venerabile Sāriputta. Allora Devadatta allargò
la sua veste superiore fatta di toppe ripiegata in quattro e si mise a
giacere sul lato destro nella posizione del leone, con un piede
sovrapposto all’altro. Però era stanco e cadde addormentato per un po’,
distratto e non pienamente presente.

Allora il venerabile Sāriputta, usando il miracolo di leggere le menti,
consigliò e ammonì i bhikkhu con un discorso di Dhamma e il venerabile
Moggallāna, usando il miracolo del potere sovrannaturale, li consigliò e
ammonì con un discorso di Dhamma, finché in loro sorse la pura,
immacolata visione del Dhamma: tutto quel che sorge deve cessare

A quel punto il venerabile Sāriputta si rivolse ai bhikkhu: «Bhikkhu,
noi stiamo tornando dal Beato. Chiunque accolga il Dhamma del Beato
venga con noi». E così il venerabile Sāriputta e il venerabile
Moggallāna portarono con loro i cinquecento bhikkhu nel Boschetto di
Bambù.

Kokālika svegliò Devadatta: «Amico Devadatta, alzati! Sāriputta e
Moggallāna hanno portato via i bhikkhu! Non ti avevo detto di non
fidarti di loro perché hanno desideri malvagi e sono preda di desideri
malvagi?» E lì e allora sangue bollente sgorgò dalla bocca di Devadatta.

Il venerabile Sāriputta e il venerabile Moggallāna andarono dal Beato.
Loro dissero: «Signore, sarebbe bene per i bhikkhu che hanno affiancato
chi ha causato uno scisma nel Saṅgha ottenere nuovamente l’ammissione
[monastica]».

«Basta così, Sāriputta. Non proporre che i bhikkhu che hanno affiancato
chi ha causato uno scisma nel Saṅgha ottengano nuovamente l’ammissione
[monastica]. Che confessino questa grave infrazione. Come si è però
comportato Devadatta?».

«Signore, Devadatta si è comportato esattamente come quando il Beato,
dopo aver istruito, esortato, risvegliato e incoraggiato con un discorso
di Dhamma i bhikkhu per gran parte della notte, mi dice: “Sāriputta, il
Saṅgha dei bhikkhu è ancora libero dalla stanchezza e dalla sonnolenza.
Forse può venirti in mente un discorso di Dhamma. Mi duole la schiena,
perciò mi riposerò”».

Allora il Beato si rivolse ai bhikkhu: «Una volta, bhikkhu, in una
foresta c’erano alcuni elefanti che vivevano nei pressi di un grande
stagno. Entravano nello stagno e prendevano degli steli di loto con le
loro proboscidi e, dopo averli ben lavati, li masticavano e li
deglutivano quando li avevano del tutto puliti dal fango. Questo era
bene sia per il loro aspetto che per la loro salute, e non incorrevano
né nella morte né in sofferenze mortali a causa di ciò. Alcuni giovani
cuccioli, però, non istruiti da questi elefanti, entrarono nello stagno
e presero degli steli di loto con le loro proboscidi ma, senza lavarli
per bene, li masticarono e li deglutirono insieme al fango. Questo non
fu bene né per il loro aspetto né per la loro salute, e incorsero nella
morte o in sofferenze mortali a causa di ciò. Allo stesso modo, bhikkhu,
Devadatta morirà miseramente per avermi imitato».

[verse]
____
Per avermi scimmiottato egli morirà meschinamente +
proprio come un cucciolo che mangia il fango +
quando imita il pachiderma che, vigile nel fiume, +
cibandosi del loto scrolla via la terra.
____

[.suttaref]
_Vin. Cv. 7:4_

«Bhikkhu, un bhikkhu è adatto ad andare in una missione quando ha otto
qualità. Quali otto? Egli è un bhikkhu che ascolta, che ottiene che gli
altri ascoltino, che impara, che ricorda, che riconosce, che ottiene che
gli altri riconoscano, che è abile con quanto è coerente e con quanto è
incoerente e che non causa problemi. Un bhikkhu è adatto ad andare in
una missione quando ha queste otto qualità. Ora, Sāriputta ha queste
otto qualità e, di conseguenza, egli è adatto ad andare in una
missione».

[verse]
____
Egli non vacilla quando è al cospetto +
di un’assemblea d’alto rango. +
Egli non perde il filo del discorso, +
né ammanta il suo messaggio. +
Privo di esitazione, parla, +
nessuna domanda può turbarlo. +
Un bhikkhu così è adatto +
ad andare in una missione.
____

[.suttaref]
_Vin. Cv. 7:4; A. 8:16_

«Bhikkhu, Devadatta è sconfitto e la sua mente è ossessionata da otto
cose malvagie, per le quali egli inevitabilmente finirà in stati di
privazione, all’inferno, per la durata di un’era. Quali otto? Esse sono
profitto, mancanza di profitto, fama, mancanza di fama, onore, mancanza
di onore, cattivi desideri e cattivi amici. Devadatta finirà in stati di
privazione, all’inferno, per la durata di un’era perché egli è sconfitto
e la sua mente è ossessionata da queste otto cose».

«Bhikkhu, è bene vincere costantemente ognuna e tutte queste otto cose
quando sorgono. E mirando a quale beneficio un bhikkhu lo fa? Mentre
inquinanti e febbre delle contaminazioni possono sorgere in chi non
vince costantemente ognuna e tutte queste cose quando sorgono, non ci
sono inquinanti e febbre delle contaminazioni in chi vince costantemente
ognuna e tutte queste cose quando sorgono. Perciò, bhikkhu, addestratevi
in questo modo: “Noi vinceremo costantemente ognuna e tutte queste cose
quando sorgono”».

«Devadatta è vinto e la sua mente è ossessionata da tre cose malvagie,
per le quali egli inevitabilmente finirà in stati di privazione,
all’inferno, per la durata di un’era. Quali tre? Esse sono cattivi
desideri, cattivi amici e fermarsi a mezza strada con l’ottenimento
della sola terrena distinzione dei poteri sovrannaturali».

[.suttaref]
_Vin. Cv. 7:4; A. 8:7; Iti. 89_

[.narrator]
`SECONDO NARRATORE.` Il Canone non fornisce notizie sulle effettive
circostanze della morte di Devadatta. Secondo il Commentario la terra si
aprì ed egli fu ingoiato e inghiottito nell’inferno, per rimanervi fino
alla distruzione degli inferni, fino all’avvento del successivo ciclo di
contrazione del mondo. Il Commentario – ma non il Canone – racconta pure
che, dopo l’abdicazione del re Bimbisāra, suo figlio Ajātasattu lo
imprigionò e poi lo mise a morte. La successione dell’ambizioso
Ajātasattu fu seguita da guerre tra i due regni dominanti di Magadha e
di Kosala, tra nipote e zio.

[.voice]
`PRIMA VOCE.` Così ho udito. Il Beato viveva a Sāvatthī. Ora, in quel
tempo Ajātasattu Vedehiputta, re di Magadha, radunò un quadruplice
esercito composto di elefanti, cavalleria, carri e fanteria, e marciò
nella regione di Kāsi contro Pasenadi, re di Kosala. Il re Pasenadi lo
venne a sapere ed egli stesso, radunando un quadruplice esercito, avanzò
nella regione di Kāsi per dare battaglia al re Ajātasattu. I due sovrani
combatterono. In quella guerra il re Ajātasattu vinse il re Pasenadi,
che si ritirò nella capitale del suo regno, Sāvatthī. I bhikkhu che
facevano la questua a Sāvatthī ne sentirono parlare e andarono a
riferirlo al Beato. Egli disse:

«Bhikkhu, Ajātasattu Vedehiputta, re di Magadha, ha cattivi amici,
cattivi alleati, cattivi confidenti. Pasenadi, re di Kosala, ha buoni
amici, buoni alleati, buoni confidenti. Il re Pasenadi, però,
trascorrerà questa notte soffrendo come uno che è stato sconfitto».

[verse]
____
La conquista genera nemici, +
chi è vinto ha un letto fatto di dolore, +
un uomo in pace può giacere quieto, +
per lui non c’è vittoria né sconfitta.
____

In seguito i due sovrani combatterono come prima. Nella battaglia, però,
il re Pasenadi catturò il re Ajātasattu vivo. Allora il re Pasenadi
pensò: «Benché questo Ajātasattu Vedehiputta, re di Magadha, mi abbia
offeso senza che io offendessi lui, è pur sempre mio nipote. Perché non
dovrei confiscare tutti i suoi elefanti, i suoi cavalli, i suoi carri e
la sua fanteria, e lasciarlo andare vivo?». I bhikkhu che facevano la
questua a Sāvatthī ne sentirono parlare e andarono a riferirlo al Beato.
Conoscendo il significato di ciò, il Beato esclamò queste parole:

[verse]
____
Un uomo può depredare quanto vuole. +
Quando gli altri di rinvio lo deprederanno, +
egli, depredato, li deprederà di nuovo. +
Il folle crede di essere fortunato +
finché il male non matura, +
ma quando ciò avviene, il folle paga il male.

L’assassino troverà chi lo assassina, +
il vincitore troverà un conquistatore, +
l’aggressore sarà aggredito, +
il persecutore perseguitato. +
La ruota delle azioni fa un altro giro +
e fa diventare saccheggiati i saccheggiatori.
____

[.suttaref]
_S. 3:14-15_

