= La Vecchiaia

[.voice]
`Prima Voce.` Così ho udito. Una volta, quando il Beato risiedeva a
Sāvatthī, il re Pasenadi di Kosala andò a trovarlo a mezzogiorno. Il
Beato gli chiese: «Da dove vieni, a mezzogiorno, gran re?».

«Signore, mi sono molto occupato dell’amministrazione di quelle cose che
devono essere fatte da sovrani consacrati guerrieri, ubriachi d’autorità
e ossessionati dalla brama per i piaceri sensoriali, che hanno reso
stabili i loro territori e sono sopravvissuti alla conquista di un’ampia
distesa di terra».

«Cosa ne pensi, gran re? Se un uomo fidato e affidabile venisse da te
giungendo dall’est e dicesse: “Sappiate, sire, che io vengo dall’est. Là
ho visto un’imponente montagna che, alta fino ai cieli, avanza e
schiaccia ogni essere vivente. Fai quel che dovresti fare, sire”. E poi
un uomo giungesse dall’ovest, un altro dal nord e un altro ancora dal
sud, e ognuno dicesse la stessa cosa. Ora, con una minaccia così
poderosa che incombe, quella di un’impietosa distruzione dell’umanità,
dell’impossibilità di conservare l’esistenza umana, che cosa faresti?».

«In una circostanza come quella, Signore, che cos’altro potrei fare se
non camminare nel Dhamma, camminare nella rettitudine, coltivare quel
che è salutare e ottenere meriti?».

«Ti dico, gran re, ti dichiaro: la vecchiaia e la morte incombono su di
te. Con la vecchiaia e la morte che incombono su di te, gran re, che
cosa faresti?».

«Con la vecchiaia e la morte che incombono su di me, Signore, che
cos’altro potrei fare se non camminare nel Dhamma, camminare nella
rettitudine, coltivare quel che è salutare e ottenere meriti? Per quanto
riguarda quelle cose che possono essere fatte da sovrani consacrati
guerrieri, ubriachi d’autorità e ossessionati dalla brama per i piaceri
sensoriali, che hanno reso stabili i loro territori e sono sopravvissuti
alla conquista di un’ampia distesa di terra – intendo battagliare con
elefanti, cavalli, carri e fanteria – esse sono prive di scopo e di
utilità quando la vecchiaia e la morte incombono su di me. Nella mia
corte ci sono ministri esperti in incanti capaci di confondere
l’avanzare dei nemici, ma essi sono privi di scopo e di utilità quando
la vecchiaia e la morte incombono su di me. Nella mia corte ci sono oro
e lingotti immagazzinati sottoterra e riposti in magazzini per comprare
con il denaro i nemici che avanzano, ma essi sono privi di scopo e di
utilità quando la vecchiaia e la morte incombono su di me. Quando la
vecchiaia e la morte incombono su di me, Signore, che cos’altro potrei
fare se non camminare nel Dhamma, camminare nella rettitudine, coltivare
quel che è salutare e ottenere meriti?».

«È così, gran re, è così. Quando la vecchiaia e la morte incombono su di
te, che cos’altro puoi fare se non camminare nel Dhamma, camminare nella
rettitudine, coltivare quel che è salutare e ottenere meriti?».

[.suttaref]
_S. 3:25_

Una volta, quando il Beato soggiornava a Sāvatthī nel Monastero
Orientale, il Palazzo della Madre di Migāra, egli si era alzato dal
ritiro al crepuscolo e stava seduto a scaldarsi la schiena ai raggi del
sole che tramontava. Il venerabile Ānanda andò da lui e gli rese
omaggio. Mentre sfregava gli arti del Beato, disse: «È meraviglioso,
Signore, è magnifico! Ora il colore della pelle del Beato non è più
chiaro e luminoso. Tutte le sue membra sono flaccide e grinzose, il suo
corpo è piegato in avanti e sembra che ci sia un mutamento nelle facoltà
sensoriali dei suoi occhi, dei suoi orecchi, del suo naso, della sua
lingua e delle sue sensazioni corporee».

«È così, Ānanda, è così. La giovinezza deve invecchiare, la salute deve
ammalarsi, la vita deve morire. Ora il colore della mia pelle non è più
chiaro e luminoso. Tutte le mie membra sono flaccide e grinzose, il mio
corpo è piegato in avanti e sembra che ci sia un mutamento nelle facoltà
sensoriali dei miei occhi, dei miei orecchi, del mio naso, della mia
lingua e delle mie sensazioni corporee».

Così disse il Beato. Quando il Sublime ebbe detto questo, il Maestro
disse ancora:

[verse]
____
Vergognati, sordida Età, +
artefice di bruttezza! +
L’Età ha ora calpestato +
quella forma che un tempo aveva grazia. +
Per vivere cento anni +
non si può ingannare il Decadimento +
nel quale nessuno alloggia [a lungo] +
ma schiaccia ogni cosa.
____

[.suttaref]
_S. 48:41_

Una volta il Beato soggiornava a Sāmagāna, nel territorio dei Sakya,
subito dopo che Nigaṇṭha Nāthaputta era morto a Pāvā. Dopo la sua morte
i Nigaṇṭha si erano divisi in due fazioni, e litigavano, bisticciavano,
disputavano e si ferivano a vicenda con frecce fatte di parole: «Tu non
conosci questo Dhamma e Disciplina. Come puoi comprendere questo Dhamma
e Disciplina? Sei in torto. Io ho ragione. Io sono coerente. Tu non sei
coerente. Quel che avrebbe dovuto essere detto all’inizio tu l’hai detto
alla fine. Quel che avrebbe dovuto essere detto alla fine tu l’hai detto
all’inizio. Quel che hai ideato è stato capovolto. Il tuo insegnamento è
stato smentito. Sei stato sconfitto. Va e impara meglio, o districatene
da solo se puoi». Sembrava che ci fosse una conflittualità interna tra
gli allievi di Nigaṇṭha Nāthaputta. E i suoi discepoli vestiti di bianco
erano delusi, costernati e disgustati dai suoi allievi, come se costoro
dimorassero nel suo mal dichiarato Dhamma e Disciplina, che era
difficile da penetrare, che non conduceva da nessuna parte, che non era
in grado di favorire la pace, [che era stato] proclamato da chi non era
completamente illuminato, [un Dhamma e una Disciplina] il cui luogo
sacro era spezzato e lasciato privo di un rifugio.

Allora il novizio Cunda, che aveva trascorso la stagione delle piogge a
Pāva, andò dal venerabile Ānanda e gli disse quel che era successo. Loro
andarono insieme dal Beato e il venerabile Ānanda lo informò di quello
che il novizio Cunda aveva detto. Egli aggiunse: «Signore, io penso:
“Che non ci siano controversie quando il Beato se ne sarà andato. Le
controversie conducono alla sventura e all’infelicità di molti, al
danno, alla sventura e alla sofferenza di divinità e uomini”».

«Ānanda, cosa ne pensi? Questi insegnamenti che io ho appreso per
conoscenza diretta e vi ho insegnato – ossia i quattro fondamenti della
consapevolezza, i quattro retti sforzi, le quattro basi per il successo
[spirituale], le cinque facoltà spirituali, i cinque poteri, i setti
fattori dell’Illuminazione e il Nobile Ottuplice Sentiero – vedi anche
due soli bhikkhu che li descrivano in modo discorde?».

«No, Signore, ma ci sono persone che sono ora remissive nei riguardi del
Beato, ma che potrebbero, quando egli se ne sarà andato, generare nel
Saṅgha controversie sui mezzi di sostentamento e sul Codice della
Disciplina Monastica. Queste controversie condurrebbero alla sventura e
all’infelicità di molti».

«Le controversie sui mezzi di sostentamento o sul Codice della
Disciplina Monastica sono marginali, Ānanda. Se però nel Saṅgha
dovessero sorgere controversie sul Sentiero o sul modo di praticare,
controversie come queste condurrebbero davvero alla sventura e
all’infelicità di molti».

[.suttaref]
_M. 104_

Una volta il Beato soggiornava a Vesālī, nel boschetto a nord della
città. Allora Sunakkhatta, un figlio dei Licchavi, aveva appena lasciato
questo Dhamma e Disciplina e durante le riunioni, a Vesālī, affermava
questo: «Il monaco Gotama non ha ottenuto alcuna condizione sovrumana,
alcuna distinzione nella conoscenza e nella visione che sia degna di un
Essere Nobile. Il monaco Gotama insegna un Dhamma elaborato solo
mediante il pensiero, seguendo il suo proprio modo di indagare, così
come a lui è venuto in mente, e a chiunque quel Dhamma venga insegnato
per il suo beneficio, esso, se praticato, conduce solo alla completa
cessazione della sofferenza (ma a nient’altro)».

Il venerabile Sāriputta sentì queste cose e le raccontò al Beato.
«Sāriputta, Sunakkhatta, uomo fuorviato, è un uomo in collera ed è con
collera che queste parole sono pronunciate. Pensando di screditare il
Perfetto, in realtà egli lo loda. Perché significa lodare il Perfetto,
quando si dice: “E a chiunque quel Dhamma venga insegnato per il suo
beneficio, esso, se praticato, conduce solo alla completa cessazione
della sofferenza”».

«Ora, come uno che ha vissuto [le cose di cui parla], ho avuto
esperienza diretta di questo genere di santa vita conosciuta come quella
dotata di quattro fattori: io ho praticato gli estremi dell’ascetismo,
della rozzezza, della scrupolosità e dell’isolamento».

«Questo era il mio ascetismo.footnote:[Le austerità qui descritte
sono principalmente quelle raccomandate dalla religione jainista.]
Andavo nudo, rifiutavo le
convenzioni, mi leccavo le mani. Non andavo quando ero chiamato, non mi
fermavo quando me lo si chiedeva. Non accettavo una cosa quando mi
veniva portata né una cosa appositamente fatta [per me], oppure un
invito. Non accettavo nulla da una pentola, da una ciotola, attraverso
la soglia [di una porta], attraverso un bastone, attraverso un pestello,
da due persone che mangiavano insieme, da una donna con un bambino, da
una donna che allattava, da un luogo in cui una donna giaceva con un
uomo, dal quale veniva distribuito del cibo, in cui c’era un cane che
aspettava, nel quale c’erano mosche che ronzavano. Non accettavo né
pesce né carne, non bevevo alcolici, vino oppure liquori fermentati. Mi
attenevo a un boccone ogni casa, a due bocconi ogni due case … a sette
bocconi ogni sette case. Vivevo di un piattino [di cibo], di due
piattini … di sette piattini ogni giorno. Mangiavo una volta al giorno,
una volta ogni due giorni … una volta ogni sette giorni, e così una
volta ogni due settimane, dimoravo seguendo la pratica di mangiare a
intervalli prestabiliti. Mi cibavo di ortaggi oppure di miglio, di riso
selvatico, bucce, muschio, crusca di riso, sciacquature, farina di
sesamo, erba, sterco di mucca. Vivevo delle radici degli alberi e di
frutti, come uno che si ciba di frutti fatti cadere dal vento. Mi
vestivo di canapa, in misto canapa, di sudari, di stracci scartati, di
corteccia d’albero, di pelle d’antilope, di tessuto d’erba kusa, di
tessuto di corteccia, di tessuto di legno, di lana fatta di capelli, di
lana d’animale, di penne di gufo. Ero uno che s’estirpava capelli e
barba, attuando la pratica dell’estirparsi capelli e barba. Ero uno che
stava in piedi in continuazione, rifiutavo di mettermi a sedere. Ero uno
che stava accovacciato in continuazione, mi dedicavo a mantenere la
posizione accovacciata. Ero uno che usava giacigli di spine, usai come
letto un giaciglio di spine. Dimorai nella pratica di balnearmi per la
terza volta al calar della notte. Nei fatti, dimorai nella pratica dei
supplizi e della tortura del corpo nei suoi vari aspetti. Così era il
mio ascetismo».

«Questa era la mia rozzezza. Proprio come un albero _tinduka_ con il
tronco che nel corso degli anni accumula strati su strati, s’incrosta e
poi si scrosta, così anche sul mio corpo nel corso degli anni la polvere
e lo sporco s’accumulavano, s’incrostavano e poi si scrostavano. Non mi
veniva in mente: “Oh, che io strofini via questa polvere e questo sporco
con la mano, o che qualcun altro strofini via questa polvere e questo
sporco con la sua mano”, non mi venne mai in mente. Così era la mia
rozzezza».

«Questa era la mia scrupolosità. Ero sempre consapevole quando facevo un
passo in avanti o indietro, fino al punto che ero colmo di compassione
perfino per una goccia d’acqua: “Che io non faccia del male alle
minuscole creature che stanno nelle fenditure del terreno”. Così era la
mia scrupolosità».

«Questo era il mio isolamento. Me ne andavo in una qualche foresta e là
restavo. Proprio come un cervo cresciuto nella foresta quando vede degli
esseri umani fugge da un bosco all’altro, da una boscaglia all’altra, da
una cavità all’altra, da un poggio all’altro, anche io quando vedevo un
bovaro, un pastore o qualcuno che raccoglieva erba o rami, oppure un
boscaiolo, fuggivo da un bosco all’altro, da una boscaglia all’altra, da
una cavità all’altra, da un poggio all’altro. Perché? Così loro non
avrebbero visto me o io non avrei visto loro. Così era il mio
isolamento».

«Andavo a carponi per le stalle quando il bestiame era uscito e il
bovaro se n’era andato, e mi nutrivo degli escrementi dei vitelli da
latte. Fin quando duravano i miei stessi escrementi e la mia stessa
urina, mi nutrivo dei miei stessi escrementi e della mia stessa urina.
Così grande era la mia deformazione nel nutrirmi».

«Andavo in qualche bosco che ispirava timore e là vivevo, in un bosco
che ispirava un tale timore che normalmente a un uomo che non fosse
stato libero dalla brama gli si sarebbero drizzati i capelli. Di notte
dimoravo all’aperto e di giorno nel bosco, quando quelle fredde notti
invernali arrivavano durante gli “otto giorni di ghiaccio”. Di giorno
dimoravo all’aperto e di notte nel bosco nell’ultimo mese della stagione
calda. E là mi venne in mente in modo spontaneo questa strofa, mai udita
prima:

[verse]
____
Congelato di notte e bruciato di giorno, +
da solo in boschi che ispirano timore, +
nudo, senza un fuoco vicino al quale sedersi, +
l’eremita ancora persegue la sua ricerca».
____

«Dormivo in un carnaio con le ossa di un morto come cuscino. E giovani
pastori si avvicinavano e mi sputavano addosso, mi urinavano addosso, mi
gettavano sporcizia e mi conficcavano bastoncini negli orecchi. Io però
non nutrii rancore per loro. Così era la mia equanimità».

«Ci sono alcuni monaci e brāhmaṇa che sostengono e credono che la
purificazione provenga dal cibo. E dicono: “Viviamo di noci di cola”. E
mangiano noci di cola, mangiano polvere di noci di cola, bevono acqua di
noci di cola e fanno molte preparazioni con le noci di cola. Ho fatto
esperienza di mangiare una sola noce di cola al giorno. Potresti però
pensare, Sāriputta, che allora una noce di cola fosse più grande, ma non
dovresti pensare così. La noce di cola allora aveva grosso modo la
stessa grandezza che ha ora. Mangiando una sola noce di cola al giorno,
il mio corpo divenne estremamente emaciato … Ancora, ci sono alcuni
monaci e brāhmaṇa che sostengono e credono che la purificazione provenga
dal cibo. E dicono: “Viviamo di fagioli” … Dicono: “Viviamo di sesamo” …
Dicono: “Viviamo di riso” … Ho fatto esperienza di mangiare un solo
fagiolo … un solo seme di sesamo … un solo grano di riso al giorno …
Mediante quel rito, quell’osservanza, quella pratica di difficili
imprese, però, non ho ottenuto alcuna condizione sovrumana, alcuna
distinzione nella conoscenza e nella visione che sia degna di un Essere
Nobile. Perché no? Perché non ho acquisito la nobile comprensione che,
se acquisita, conduce alla completa cessazione della sofferenza in chi
la pratica, in quanto essa appartiene a una nobile condizione e conduce
al di là (del mondo)».

«Ci sono alcuni monaci e brāhmaṇa che sostengono e credono che la
purificazione provenga da un particolare ciclo di rinascite. È però
impossibile rinvenire un ciclo di rinascite che io non abbia già
attraversato in questo lungo viaggio, ad eccezione delle Pure
Dimore,footnote:[Le “Pure Dimore” sono parte dell’alto mondo di Brahmā
(_brahmaloka_), abitate solo da chi ha raggiunto la condizione di Chi è
Senza Ritorno (si veda il cap. 12, p. 263), che sono là rinati alla
morte e là vivono senza tornare in nessun altro mondo finché non
raggiungono il Nibbāna definitivo.] perché se io fossi nato nelle
Pure Dimore non sarei mai dovuto tornare in questo mondo».

«Ci sono alcuni monaci e brāhmaṇa che sostengono e credono che la
purificazione provenga da pratiche sacrificali. È però impossibile
rinvenire un tipo di sacrificio che non sia stato da me offerto in
questo lungo viaggio, quale sovrano consacrato e guerriero o quale ricco
membro della casta brāhmaṇa».

«Ci sono alcuni monaci e brāhmaṇa che sostengono e credono che la
purificazione provenga dall’adorazione del fuoco. È però impossibile
rinvenire quel tipo di fuoco che non sia già stato da me venerato in
questo lungo viaggio, quale sovrano consacrato e guerriero o quale ricco
membro della casta brāhmaṇa».

«Ci sono alcuni monaci e brāhmaṇa che sostengono e credono questo: “Per
tutto il tempo che questo buon uomo è ancora giovane, un ragazzo dai
capelli neri, benedetto dalla gioventù, nella prima fase della vita,
altrettanto a lungo egli sarà perfetto per lucida comprensione. Quando
però questo buon uomo sarà anziano, vecchio, appesantito dagli anni,
avanti nella vita e giunto allo stadio finale, avendo ottanta, novanta o
cento anni, allora la lucidità della sua comprensione sarà perduta”. Non
si dovrebbe pensare così. Ora io sono anziano, vecchio, appesantito
dagli anni, avanti nella vita e giunto allo stadio finale: i miei anni
hanno superato gli ottanta. Supponiamo che io abbia quattro discepoli
che possano giungere ai cento anni, la cui vita possa durare cento anni,
perfetti in consapevolezza, attenzione, memoria e lucidità di
comprensione – proprio come un arciere ben dotato, addestrato, esperto e
provato, può con facilità scagliare una freccia attraverso l’ombra di
una palma, supponiamo che loro siano fino a tal punto perfetti in
consapevolezza, attenzione, memoria e lucidità di comprensione. E
supponiamo che loro mi facciano continuamente domande sui quattro
fondamenti della consapevolezza, e io risponda, e loro ricordino ogni
risposta, finché non abbiano più domande supplementari, e che non
facciano pause se non per mangiare, bere, masticare e assaporare, per
orinare e defecare e per riposare per vincere la sonnolenza: e
l’esposizione del Dhamma del Perfetto, le sue spiegazioni dei fattori
del Dhamma e le sue risposte alle domande non siano ancora terminate. E
che nel frattempo, però, quei quattro miei discepoli che possono
giungere ai cento anni, la cui vita può durare cento anni, siano morti
alla fine di quei cento anni. Sāriputta, anche se tu dovessi portarmi in
giro su un letto, non ci sarà alcun cambiamento nella lucidità della
comprensione del Perfetto».

[.suttaref]
_M. 12_

[.narrator]
`Primo Narratore.` Negli ultimi anni del Buddha si verificarono un certo
numero di vessazioni – eventi, ossia, che sarebbero stati vessatorî
secondo il comune buon senso. Poco sopra si è detto come Sunakkhatta,
che in precedenza era stato un bhikkhu (oltre che attendente personale
del Buddha), lasciò il Buddha, parlò pubblicamente contro di lui e
sminuì i suoi poteri sovrannaturali, per cui il Buddha fece il suo
“ruggito del leone” , dichiarando che non c’era auto-mortificazione che
non avesse praticato e metodo di auto-purificazione che non avesse
provato. Egli avrebbe poi presto perso i suoi due discepoli eminenti.
Nel frattempo, il re Pasenadi di Kosala, suo devoto sostenitore per più
di quarant’anni, fu sempre più infastidito da problemi politici.

[.narrator]
`Secondo Narratore.` Il re Pasenadi aveva la stessa età del Buddha e,
perciò, aveva superato gli ottant’anni. Era stato travagliato da guerre
occasionali e prive di risultati con suo nipote, re Ajātasattu di
Magadha, e da sommosse politiche all’interno del suo stesso regno. Di
conseguenza a un intrigo di palazzo, il suo comandante in armi, il
generale Bandhula, fu accusato di aver complottato contro di lui e messo
a morte. Solo in seguito egli apprese che era innocente. Il rimorso lo
assediava. Forse al fine di fare ammenda, promosse a quella stessa
carica il nipote del generale, Dīgha Kārāyana.

[.suttaref]
_Commentario a M. 89 e D. 16_

[.narrator]
`Primo Narratore.` Il re Pasenadi andò dal Buddha per chiedergli
consiglio. Quando morì la sua devota consorte, la regina Mallikā, si
recò profondamente sconsolato dal Buddha, che allora si trovava a
Sāvatthī, per cercare consolazione.

[.suttaref]
_Si veda A. 5:49_

[.narrator]
`Secondo Narratore.` Il palazzo del re e la sua smagliante capitale non
gli recavano più alcun piacere. Li lasciò per un po’ per errare di luogo
in luogo con un grande seguito, ma senza alcuna meta.

[.narrator]
`Primo Narratore.` Durante questo vagare nostalgico e sconsolato, quando
la strada dell’anziano sovrano incrociava quella del Buddha, il re
andava a trovarlo. La sua morte non è registrata nel Tipiṭaka. Un
discorso [del Buddha] è però collocato dal Commentario tra gli eventi
che immediatamente la precedettero. Questo è il racconto del loro ultimo
incontro.

[.voice]
`Prima Voce.` Così ho udito. Una volta il Buddha soggiornava nel
territorio dei Sakya, in una città dei Sakya chiamata Medaḷumpa. In
quella circostanza il re Pasenadi di Kosala giunse a Nāgaraka per alcuni
affari e altre cose ancora. Egli disse allora a Dīgha Kārāyana: «Amico
mio, chiama a raduno le carrozze di corte. Andiamo nel parco degli
svaghi per vedere un piacevole panorama».

«E sia, sire», rispose Dīgha Kārāyana. Quando le carrozze furono pronte,
egli informò il re: «Sire, le carrozze di corte sono pronte. È tempo
ora, gran re, di fare quel che ritenete opportuno».

Così il re Pasenadi montò su una carrozza di corte e, con tutto il
seguito regio, si diresse verso il parco. Procedette finché la strada lo
consentì alle carrozze e poi scese e continuò a piedi. Mentre stava
camminando e vagando per fare un po’ d’esercizio, osservò le radici
degli alberi che infondevano in lui fiducia e sicurezza. Erano calme, le
voci non le disturbavano, con un’aria distaccata, su di esse si sarebbe
potuto giacere nascosti dalla gente, favorevoli al ritiro. Vederle gli
ricordò il Beato. Allora egli disse: «Dīgha Kārāyana, amico mio, queste
radici degli alberi sono come quelle … quando noi eravamo soliti
prestare omaggio al Beato, realizzato e completamente illuminato. Dove
vive ora il Beato, realizzato e completamente illuminato?».

«C’è una città dei Sakya, sire, chiamata Medaḷumpa. Il Beato, realizzato
e completamente illuminato vive lì ora».

«Quanto dista Nāgaraka da Medaḷumpa?».

«Non dista molto, sire. Circa tre leghe. C’è abbastanza luce del giorno
per arrivare fin là».

«Allora prepara le carrozze, amico mio. Andiamo a trovare il Beato,
realizzato e completamente illuminato».

«E sia, sire», rispose Dīgha Kārāyana. Così il re condusse [il suo
seguito] da Nāgaraka fino alla città dei Sakya, Medaḷumpa, arrivando lì
quando era ancora giorno. Attraversò il parco, andando avanti finché la
strada consentì alle carrozze di procedere, e poi scese e continuò a
piedi.

In quell’occasione numerosi bhikkhu stavano facendo la meditazione
camminata all’aperto. Il re si avvicinò a loro e chiese: «Venerabili
signori, dove sta vivendo ora il Beato, realizzato e completamente
illuminato? Vorremmo vedere il Beato, realizzato e completamente
illuminato».

«Quella è la sua dimora, gran re, quella con la porta chiusa. Vai fino
lì silenziosamente, fino al porticato, senza affrettarti, poi tossisci e
bussa. Il Beato ti aprirà».

Il re Pasenadi lì e allora si tolse la spada e il turbante reale, e le
consegnò a Dīgha Kārāyana. Dīgha Kārāyana pensò: «Il re sta ora
recandosi a un incontro privato: devo ora aspettare qui da solo?».

Seguendo le indicazioni, il re si recò fino alla porta. Quando egli
bussò, il Beato aprì la porta. Il re entrò nella dimora e si prostrò ai
piedi del Beato. Ricoprì di baci i piedi del Beato, e li accarezzò con
le sue mani pronunciando il suo nome in questo modo: «Signore, io sono
re Pasenadi di Kosala, Signore, io sono re Pasenadi di Kosala».

«Gran re, quale beneficio vedi nel prestare un così estremo omaggio a
questo corpo e a mostrare una tale amicizia?».

«Signore, io credo che in relazione al Beato queste cose siano vere: il
Beato è completamente illuminato, il Dhamma è ben proclamato dal Beato,
il Saṅgha dei discepoli del Beato è sulla buona strada. Ora, Signore, io
vedo alcuni monaci e brāhmaṇa che conducono la santa vita per dieci,
venti, trenta, quarant’anni, e poi li vedo godere di tutti e cinque i
tipi di piacere sensoriale e indulgere a essi. Qui, invece, vedo i
bhikkhu condurre la santa vita in tutte le sue perfezioni per tutta la
vita e finché dura il loro respiro. Infatti, Signore, da nessun’altra
parte vedo una santa vita così perfetta come qui. Ecco perché credo che
in relazione al Beato queste cose siano vere: il Beato è completamente
illuminato, il Dhamma è ben proclamato dal Beato, il Saṅgha dei
discepoli del Beato è sulla buona strada».

«Ancora una volta, Signore, i sovrani litigano con i sovrani, i nobili
guerrieri con i nobili guerrieri, i brāhmaṇa con i brāhmaṇa, i
capifamiglia con i capifamiglia, la madre con il figlio, il figlio con
la madre, il padre con il figlio, il figlio con il padre, il fratello
con il fratello, il fratello con la sorella, la sorella con il fratello,
l’amico con l’amico. Qui, però, vedo i bhikkhu dilettarsi nella
concordia, vivere senza contrasti come il latte con l’acqua e guardarsi
l’uno l’altro con occhi gentili. In verità, Signore, non ho visto in
alcun altro posto un gruppo di persone vivere così armoniosamente
insieme. Anche per questa ragione credo che in relazione al Beato queste
cose siano vere».

«Ancora, Signore, ho camminato e vagato di parco in parco, di giardino
in giardino, e ho visto alcuni monaci e brāhmaṇa scarni, infelici,
sgradevoli, itterici, con le vene sporgenti sulle loro membra, che a
malapena si potrebbe pensare che uno possa volerli guardare una seconda
volta. Pensai: “Certamente questi venerabili stanno conducendo la santa
vita insoddisfatti, oppure hanno commesso un qualche crimine e lo stanno
nascondendo, per questo sono così”. Andai da loro e chiesi perché
fossero così, e mi risposero: “Siamo scontenti, gran re”. Qui, invece,
vedo i bhikkhu sorridenti e allegri, sinceramente gioiosi, chiaramente
deliziati, le loro facoltà sono fresche, non agitate, imperturbate, e
che vivono di ciò che gli altri donano loro, dimorando con menti simili
a quelle di un cerbiatto libero. Pensai: “Se sono così, questi
venerabili certamente percepiscono che vi siano delle qualità
straordinarie e distintive nella Dispensazione del Beato”. Anche per
questa ragione credo che in relazione al Beato queste cose siano vere».

«Ancora, Signore, in quanto nobile sovrano consacrato e guerriero, sono
in grado di far giustiziare coloro che devono essere giustiziati, di
multare coloro che devono essere multati e di esiliare coloro che devono
essere esiliati. Quando però sono seduto in consiglio, [mentre parlo] mi
interrompono, benché io dica: “Buoni uomini, quando sono seduto in
consiglio [mentre parlo] non interrompetemi, aspettate che io finisca di
parlare”. Qui vedo però un uditorio di molte centinaia di bhikkhu e,
mentre il Beato espone il Dhamma, tra i suoi discepoli non si sente
neanche uno starnuto o qualcuno che si schiarisce la gola. Una volta,
mentre il Beato esponeva il Dhamma a un uditorio di molte centinaia [di
bhikkhu], un discepolo del Beato si schiarì la gola. Allora uno dei suoi
compagni nella santa vita lo toccò con il ginocchio, dicendogli:
“Silenzio, venerabile signore, non fare rumori. Il Maestro sta esponendo
il Dhamma”. Pensai: “È meraviglioso, è stupefacente come un uditorio
possa essere così ben disciplinato senza né punizioni né armi”. Infatti,
Signore, non ho visto in alcun altro posto un uditorio così ben
disciplinato. Anche per questa ragione credo che in relazione al Beato
queste cose siano vere».

«Ancora, Signore, ho visto alcuni allievi di nobili guerrieri, alcuni
allievi di brāhmaṇa, alcuni allievi di capifamiglia, alcuni allievi di
monaci, che erano intelligenti e conoscevano le teorie altrui come un
provetto tiratore scelto sa tirare con l’arco: uno avrebbe pensato che
sarebbero certamente riusciti a demolire falsi punti di vista con la
conoscenza che possedevano. Loro sentirono dire: “Il monaco Gotama
visiterà questo villaggio o questa città”. E formulavano una domanda:
“Se egli sarà interrogato in questo modo, egli risponderà in questo
modo, e noi refuteremo la sua teoria in questo modo. E se sarà
interrogato in quest’altro modo, egli risponderà in quest’altro modo, e
noi refuteremo la sua teoria in quest’altro modo”. Loro sentirono dire:
“Il monaco Gotama è venuto a visitare questo villaggio o questa città”.
Loro andarono dal monaco Gotama. Il monaco Gotama li istruì, esortò,
risvegliò e incoraggiò con un discorso di Dhamma. Dopo di questo non gli
posero neanche la domanda: come avrebbero potuto refutare la sua teoria?
Nei fatti divennero suoi discepoli. Anche per questa ragione credo che
in relazione al Beato queste cose siano vere».

«Ancora, Signore, ci sono Isidatta e Purāṇa, due miei carpentieri, che
da me ricevono cibo e sono mantenuti, per i quali io sono colui che
provvede ai loro mezzi di sostentamento e latore della loro buona fama.
Nonostante ciò loro hanno più rispetto del Beato che di me. Una volta,
quando ero uscito con un esercito per delle manovre e stavo mettendo
alla prova questi carpentieri, avvenne che trovammo ospizio in una
dimora molto stretta. Allora questi due carpentieri trascorsero la
maggior parte della notte parlando di Dhamma, dopo di che si misero a
giacere rivolgendo la loro testa verso il luogo nel quale avevano
sentito che si trovava il Beato e i loro piedi verso di me. Pensai: “È
meraviglioso, è stupefacente! Certamente questi buoni uomini
percepiscono che vi siano delle qualità straordinarie e distintive nella
Dispensazione del Beato”. Anche per questa ragione credo che in
relazione al Beato queste cose siano vere: il Beato è completamente
illuminato, il Dhamma è ben proclamato dal Beato, il Saṅgha dei
discepoli del Beato è sulla buona strada».

«Ancora, Signore, il Beato è un nobile guerriero e io sono un nobile
guerriero, il Beato è un Kosala e io sono un Kosala, il Beato ha
ottant’anni e io ho ottant’anni. Queste sono le ragioni per cui penso
sia opportuno porgere un così estremo omaggio al Beato e mostrare una
tale amicizia. E ora, Signore, noi andiamo, siamo impegnati e abbiamo
molto da fare».

«È tempo ora, gran re, di fare quel che ritieni opportuno».

Allora il re Pasenadi di Kosala si alzò dal posto in cui sedeva e, dopo
aver prestato omaggio al Beato, se ne andò, girandogli a destra.

Subito dopo che se ne fu andato, il Beato si rivolse ai bhikkhu con
queste parole: «Bhikkhu, questo re Pasenadi ha proferito parole
monumentali sul Dhamma. Ricordatele, perché esse favoriscono il
benessere e riguardano i fondamenti della santa vita».

Questo è ciò che il Beato disse. I bhikkhu si sentirono soddisfatti, e
si deliziarono alle sue parole.

[.suttaref]
_M. 89_

[.narrator]
`Primo Narratore.` Quel che avvenne dopo che il re era stato a colloquio
[con il Beato] è raccontato solo nel Commentario.

[.narrator]
`Secondo Narratore.` Quando il re entrò nel luogo in cui il Buddha
dimorava, lasciando le insegne reali a Dīgha Kārāyana, quest’ultimo,
risentitosi, divenne sospettoso. Iniziò a fantasticare, pensando che il
sovrano avesse fatto giustiziare suo zio, il generale, dopo un
precedente colloquio con il Buddha, e si chiese se ora non stesse per
venire il suo turno. Appena il re entrò nel luogo in cui il Buddha
dimorava, Ḍīgha Kārāyana se ne andò, prese con sé le insegne e si recò
nell’accampamento. Là intimò al figlio del re, il principe Viḍūḍabha, di
salire al trono immediatamente, minacciando di farlo lui stesso se non
avesse obbedito. Il principe acconsentì. Lasciando là solo un cavallo,
una spada e una donna del gineceo, Ḍīgha Kārāyana e il resto del seguito
partirono molto rapidamente per Sāvatthī, dopo aver detto alla donna che
aspettava di avvertire il re di non seguirli, se alla sua vita ci
teneva. Quando il re uscì dalla dimora dal luogo in cui il Buddha
dimorava, vedendo che lì non c’era nessuno, andò ove prima si trovava
l’accampamento. La donna che l’attendeva gli disse quel che era
avvenuto.

Egli decise di chiedere aiuto a suo nipote, re Ajātasattu. Durante il
lungo viaggio per Rājagaha egli mangiò del cibo grossolano, di un genere
del quale non era solito cibarsi e bevette molta acqua. Quando arrivò a
Rājagaha era tardi e le porte della città erano chiuse, così che fu
costretto a trascorrere la notte in un pubblico ricovero. Durante la
notte fu attaccato da una violenta malattia e verso l’alba spirò. La
donna che l’aveva atteso, tra le braccia della quale il re era spirato,
lamentò ad alta voce: «Il mio signore, il re di Kosala, che governò due
regni, è morto come un povero e ora giace in un pubblico ricovero fuori
dalle mura d’una città straniera!». La notizia giunse al re Ajātasattu,
che subito ordinò un regio funerale. In seguito fece mostra
d’indignazione, ordinando un attacco punitivo contro suo cugino, ora re
Viḍūḍabha, ma venne subito persuaso dai suoi ministri che, siccome
l’anziano sovrano era morto, un tentativo del genere sarebbe stato
inutile ed egli puntualmente riconobbe la successione di suo cugino.
