= Il Primo Concilio
:chapter-number: 16

[.narrator]
`Primo Narratore.` Dopo l’ottenimento del Nibbāna definitivo da parte del
Buddha, i bhikkhu si allontanarono da Kusinārā e si dispersero.
L’Anziano Mahā-Kassapa emerge quale figura più eminente nel Saṅgha dei
bhikkhu.

[.narrator]
`Secondo Narratore.` Egli era già stato in precedenza menzionato dal
Buddha come il quarto nella lunga lista dei discepoli di particolare
distinzione. Il primo era l’Anziano Kondañña, il primo convertito; il
secondo e il terzo erano gli Anziani Sāriputta e Moggallāna, i due
discepoli eminenti, che già avevano ottenuto il Nibbāna defintivo. Ci
sono molti racconti riguardanti l’Anziano Mahā-Kassapa nel Canone, nel
quale egli appare come una figura austera ed energica, senza compromessi
nella sua dedizione all’ascetismo. Egli impartì più di un brusco
rimprovero all’Anziano Ānanda per il suo indulgere ad atti di gentile
altruismo, invece di dedicarsi a beni più duraturi, portando a
compimento la sua perfezione, quella perfezione già raggiunta dallo
stesso Anziano Mahā-Kassapa.

[.narrator]
`Primo Narratore.` Ecco un episodio appartenente a questo periodo di
transizione, che ben illustra il suo carattere.

[.voice]
`Prima Voce.` Così ho udito. Una volta il venerabile Mahā-Kassapa
soggiornava a Rājagaha, nel Boschetto di Bambù, nel Sacrario degli
Scoiattoli. In quel momento il venerabile Ānanda andava errando nelle
Colline Meridionali con una larga comunità di bhikkhu. Fu allora che
trenta fra coloro che risiedevano con lui, la maggior parte dei quali
erano giovani, abbandonarono l’addestramento monastico e tornarono a
quel che avevano lasciato.

Quando il venerabile Ānanda ebbe errato per le Colline Meridionali per
tutto il tempo che volle, andò dal venerabile Mahā-Kassapa nel Boschetto
di Bambù, a Rājagaha. Dopo avergli prestato omaggio, si mise a sedere da
un lato. Il venerabile Mahā-Kassapa disse: «Amico Ānanda, in ragione di
quale beneficio il Beato rese nota la regola che non più di tre bhikkhu
insieme possono mangiare presso delle famiglie?».

«Egli fece così, Signore, Kassapa, in ragione di tre benefici: per il
contenimento delle persone che pensano in modo errato e per l’agio delle
persone ragionevoli, così che quanti hanno desideri malvagi non formino
una fazione nel Saṅgha, e per compassione nei riguardi delle famiglie».

«Allora, amico Ānanda, perché vai errando con questi nuovi bhikkhu, le
cui porte delle facoltà sensoriali sono incustodite, che non conoscono
la giusta misura nel mangiare, che non sono votati alla vigilanza? Si
potrebbe pensare che vai errando per distruggere raccolti. Si potrebbe
pensare che vai errando per distruggere famiglie. Il tuo seguito va in
pezzi. I tuoi nuovi convertiti si allontanano. E neanche questo ragazzo
conosce ancora la sua propria misura!».

«Signore, Kassapa, in realtà stanno crescendo dei capelli bianchi sulla
mia testa. Che il venerabile Kassapa la smetta di chiamarmi ragazzo».

«Questo è però quel che sei, amico Ānanda. Tu vai errando con questi
nuovi bhikkhu, le cui porte delle facoltà sensoriali sono incustodite,
che non conoscono la giusta misura nel mangiare, che non sono votati
alla vigilanza. Si potrebbe pensare che vai errando per distruggere
raccolti. Si potrebbe pensare che vai errando per distruggere famiglie.
Il tuo seguito va in pezzi. I tuoi nuovi convertiti si allontanano. E
neanche questo ragazzo conosce ancora la sua propria misura!».

La bhikkhuṇī Thullānandāfootnote:[La bhikkhunī Thullānandā compare
spesso nel Vinaya come una
donna orgogliosa, intelligente e faziosa, che causò la stesura di
numerose regole.] udì queste parole. Ella pensò:
«Sembra che il Signore Ānanda, il Veggente Videha, si sia dispiaciuto
perché il Signore Kassapa l’ha chiamato ragazzo». E lei si sentì offesa
ed esclamò parole di dispiacere: «Come può il Signore Mahā-Kassapa, che
apparteneva a una setta, sognarsi di dispiacere il Signore Ānanda, il
Veggente Videha, chiamandolo ragazzo?».

Il venerabile Mahā-Kassapa la sentì mentre pronunciava queste parole.
Allora egli disse al venerabile Ānanda: «In verità, amico Ānanda, la
bhikkhuṇī Thullānandā ha parlato frettolosamente, senza riflettere. Da
quando ho rasato i capelli e la barba e indossato l’abito ocra, e
rinunciato alla vita in famiglia per una senza dimora, non ho guardato
alcun altro maestro che non fosse il Beato, realizzato e completamente
illuminato. Prima ero un laico che pensava: “La vita in famiglia è
affollata e polverosa, l’abbandono di essa comporta spaziose aperture.
Vivendo in famiglia non è facile condurre una santa vita assolutamente
perfetta e immacolata come una conchiglia ben lucidata. E se mi rasassi
i capelli e la barba, indossassi l’abito ocra, e rinunciassi alla vita
in famiglia per una senza dimora?”. In seguito mi cucii una veste con
dei panni scartati. Poi mi rasai i capelli e la barba e indossai l’abito
ocra per lo stesso scopo di coloro che nel mondo sono degli Arahant, e
rinunciai alla vita in famiglia per una senza dimora».

«Quando abbracciai la vita religiosa, mentre ero in cammino su una
strada, tra Rājagaha e Nālandā vidi il Beato che sedeva nel Sacrario di
Bahaputta. Allorché lo vidi, pensai: “Se io mai riconoscessi un Maestro,
che io riconosca come tale solo il Beato. Se io mai riconoscessi un
Sublime, che io riconosca come tale solo il Beato. Se io mai
riconoscessi un Essere Completamente Illuminato, che io riconosca come
tale solo il Beato”. Allora, prostrandomi ai suoi piedi, dissi:
“Signore, il Beato è il mio Maestro, io sono il suo discepolo. Il Beato
è il mio Maestro, io sono il suo discepolo”. Allora il Beato disse:
“Kassapa, se qualcuno dicesse ‘io conosco’ senza conoscere o ‘io vedo’
senza vedere a un discepolo schietto e leale come te, la sua testa
andrebbe a fuoco. È però conoscendo che dico ‘io conosco’ e vedendo che
dico ‘io vedo’. Perciò, Kassapa, devi addestrarti in questo modo: ‘Una
scrupolosa coscienza e un senso di vergogna si insedierà in me a
riguardo dei bhikkhu più anziani, dei nuovi bhikkhu e di coloro di media
anzianità monastica’. E in questo modo: ‘Io ascolterò il Dhamma con
orecchio attento, ascoltando, prestando attenzione e offrendo tutta la
mia mente a qualsiasi cosa sia favorevole a quel che è salutare’. E in
questo modo: ‘Non mancherò mai di praticare volentieri la consapevolezza
del corpo nel corpo’. Devi addestrarti in questo modo”. Dopo che il
Beato mi ebbe dato questi consigli, si alzò dal posto in cui sedeva e se
ne andò».

«Come un debitore mangiai cibo elemosinato in quel posto per soli sette
giorni. Nell’ottavo giorno sorse la conoscenza finale. Allora il Beato
lasciò la strada e andò ai piedi di un albero. Io piegai in quattro la
mia veste fatta di panni scartati e gli dissi: “Signore, che il Beato si
metta a sedere qui, così che ciò possa essere per lungo tempo a
vantaggio del mio benessere e della mia felicità”. Il Beato si mise a
sedere nel posto preparatogli. Poi disse: “La tua veste fatta di panni
scartati è morbida, Kassapa”. – “Che il Beato accetti da me per
compassione la veste fatta di panni scartati”. – “Tu indosserai però la
veste fatta di panni scartati di canapa che io dismetterò, Kassapa?”. –
“Signore, io indosserò la veste fatta di panni scartati di canapa del
Beato che egli dismetterà”».

«Io diedi al Beato la mia veste fatta di panni scartati e, in cambio,
presi la veste fatta di panni scartati di canapa del Beato che egli
aveva dismesso. Se di qualcuno si potrebbe dire: “Egli è il figlio
stesso del Beato, nato dalla sua bocca, nato dal Dhamma, creato dal
Dhamma, un erede del Dhamma, che riceve una veste dismessa fatta di
panni scartati di canapa”, è di me che in verità ciò potrebbe essere
detto».

[.narrator]
`Primo Narratore.` Egli proseguì raccontando come fosse in grado, ogni
volta che lo desiderava, di entrare e dimorare nei quattro jhāna e anche
nei quattro stati privi di forma, come pure nella cessazione della
percezione e della sensazione, avendo inoltre acquisito i cinque tipi di
diretta conoscenza mondana, ossia i poteri sovrannaturali: l’elemento
dell’orecchio divino, la penetrazione delle menti, il ricordo delle vite
passate e l’occhio divino per mezzo del quale si vede come gli esseri
scompaiono e ricompaiono in accordo con le loro azioni. Egli concluse:

[.voice]
`Prima Voce.` «Ogni volta che lo desidero, mediante la realizzazione di me
stesso con la conoscenza diretta qui e ora, io entro e dimoro nella
liberazione della mente e nella liberazione per mezzo della
comprensione, che è priva delle contaminazioni per l’esaurimento delle
contaminazioni. Chi pensa che un pachiderma alto quattordici piedi o più
possa essere occultato da una foglia di palma, può fantasticare di
riuscire a superarmi a riguardo di questi sei tipi di conoscenza
diretta».

In seguito la bhikkhuṇī Thullānandā abbandonò la santa vita.

[.suttaref]
_S. 16:11_

[.narrator]
`Secondo Narratore.` Sono passate ancora solo poche settimane dal
Parinibbāna.

[.voice]
`Terza Voce.` Il venerabile Mahā-Kassapa disse: «Ora, amici, recitiamo
l’Insegnamento e la Disciplina, il Dhamma e il Vinaya. Già erronei
insegnamenti ed erronea disciplina sono stati corteggiati, e retti
insegnamenti e retta disciplina sono stati derisi. E già sostenitori di
erronei insegnamenti ed erronea disciplina sono diventati forti, e
sostenitori di retti insegnamenti e retta disciplina si sono
indeboliti».

«Allora, Signore, che l’Anziano convochi un’assemblea dei bhikkhu».

Così, il venerabile Mahā-Kassapa convocò un’assemblea di cinquecento
Arahant meno uno, perché i bhikkhu avevano detto: «C’è il venerabile
Ānanda. Benché egli sia solo un allievo – nella condizione di Chi è
Entrato nella Corrente – è tuttavia impossibile che vada a finire in una
destinazione infelice a causa del desiderio, dell’ira, dell’illusione o
della paura. Egli conosce a fondo una grande e varia parte del Dhamma e
della Disciplina per essere stato in presenza del Beato. Che l’Anziano
convochi anche il venerabile Ānanda».

Così egli convocò anche il venerabile Ānanda. Allora egli chiese ai
bhikkhu: «Dove avrà luogo la ripetizione?».

I bhikkhu anziani pensarono: «Rājagaha è una grande residenza, con
abbondanza di alloggi. Perché non andare a Rājagaha e restare là per la
stagione delle piogge?». Così il venerabile Mahā-Kassapa offrì tale
argomento di decisione al cospetto del Saṅgha:

«Che il Saṅgha mi ascolti, amici. Se al Saṅgha sembra opportuno, che il
Saṅgha autorizzi quanto segue: che questi cinquecento bhikkhu restino a
Rājagaha per questa stagione delle piogge allo scopo di ripetere il
Dhamma e la Disciplina, e che nessun altro bhikkhu resti a Rājagaha per
questa stagione delle piogge. Questo è argomento di decisione. Che il
Saṅgha mi ascolti, amici. Il Saṅgha autorizzi quanto segue: che questi
cinquecento bhikkhu restino a Rājagaha per questa stagione delle piogge
allo scopo di ripetere il Dhamma e la Disciplina, e che nessun altro
bhikkhu resti a Rājagaha per questa stagione delle piogge. Chi è
d’accordo resti in silenzio, chi non è d’accordo lo dica. Il Saṅgha è
d’accordo che questa decisione è autorizzata dal Saṅgha, perciò il
Saṅgha resta in silenzio. Così lo memorizzo».

Allora i bhikkhu anziani si incontrarono a Rājagaha per ripetere il
Dhamma e la Disciplina. Loro tuttavia pensarono: «La riparazione di quel
che è rotto e cadente era raccomandata dal Beato. Perciò, amici,
occupiamoci di questo durante il primo mese. Il secondo mese ci
riuniremo per la ripetizione».

Intanto giunse il tempo in cui il venerabile Ānanda pensò: «L’assemblea
è domani. Non è decoroso che io mi presenti all’assemblea come un
semplice discente». Egli trascorse la maggior parte della notte nella
contemplazione del corpo nel corpo. Quando si avvicinò l’alba, egli
pensò: «Mi metterò a giacere». Egli, però, mantenne la consapevolezza
del corpo nel corpo. Prima che il suo capo toccasse il cuscino e dopo
che i suoi piedi si furono staccati dal suolo, nel corso di questo
intervallo il suo cuore fu liberato dalle contaminazioni per mezzo del
non-attaccamento. Così il venerabile Ānanda si recò all’assemblea come
Arahant.

Allora il venerabile Mahā-Kassapa offrì tale argomento di decisione al
cospetto del Saṅgha: «Che il Saṅgha mi ascolti, amici. Se al Saṅgha
sembra opportuno, interrogherò il venerabile Upāli sulla Disciplina».

Allora il venerabile Upāli offrì tale argomento di decisione al cospetto
del Saṅgha: «Che il Saṅgha mi ascolti, Signori. Se al Saṅgha sembra
opportuno, io, interrogato sulla Disciplina dal venerabile Mahā-Kassapa,
risponderò».

Allora il venerabile Mahā-Kassapa disse al venerabile Upāli: «Amico
Upāli, dove fu resa nota la Prima Sconfitta?».

«A Vesālī, Signore».

«A riguardo di chi?».

«A riguardo di Sudinna Kalandaputta».

«Per quale argomento?».

«Sull’argomento del rapporto sessuale».

[.narrator]
`Secondo Narratore.` L’Anziano Mahā-Kassapa allora interrogò l’Anziano
Upāli sull’argomento della Prima Sconfitta, sulla sua origine, sulla
persona, sulla proclamazione, sulle modifiche, sull’infrazione e su quel
che non rappresentava un’infrazione. Poi egli lo interrogò nello stesso
modo a proposito delle altre tre Sconfitte: rubare, uccidere degli
esseri umani e fare deliberatamente false dichiarazioni in relazione a
conquiste spirituali. In questo modo egli lo interrogò sui due Codici,
ossia il _Pātimokkha_ dei bhikkhu o Codice delle Regole Monastiche e
quello delle bhikkhuṇī, come pure su tutte le altre regole. L’Anziano
Upāli rispose a ogni domanda.

[.voice]
`Terza Voce.` Allora il venerabile Mahā-Kassapa offrì tale argomento di
decisione al cospetto del Saṅgha: «Che il Saṅgha mi ascolti, amici. Se
al Saṅgha sembra opportuno, interrogherò il venerabile Ānanda sul
Dhamma».

Allora il venerabile Ānanda offrì tale argomento di decisione al
cospetto del Saṅgha: «Che il Saṅgha mi ascolti, Signori. Se al Saṅgha
sembra opportuno, io, interrogato sul Dhamma dal venerabile
Mahā-Kassapa, risponderò».

Allora il venerabile Mahā-Kassapa disse al venerabile Ānanda: «Amico
Ānanda, dove fu pronunciato il _Brahmajāla Sutta?_».

«Tra Rājagaha e Nālandā, Signore, nella Casa del Re ad Ambalaṭṭhikā».

[.narrator]
`Secondo Narratore.` L’anziano lo interrogò poi sull’origine del
_Brahmajāla Sutta_, il primo nella Raccolta dei Discorsi Lunghi, e sulla
persona. Poi egli lo interrogò nello stesso modo a proposito del
_Sāmaññaphala Sutta_. In questo maniera egli lo interrogò su tutti i
discorsi di tutte le quattro Principali Raccolte del _Sutta Piṭaka._

[.voice]
Terza Voce. Allora il venerabile Ānanda disse ai bhikkhu anziani:
«Signori, il Beato nel tempo in cui ottenne il Nibbāna definitivo mi
disse: “Quando me ne sarò andato, il Saṅgha potrà, se lo desidera,
abolire le regole più minute e minori”».

«Amico Ānanda, ma tu hai chiesto al Beato quali erano le regole più
minute e minori?».

«No, Signori, non l’ho chiesto».

[.narrator]
`Secondo Narratore.` Gli anziani espressero diverse opinioni in relazioni
a quali regole, a parte le Quattro Sconfitte, dovessero essere
considerate minute e minori. Allora il venerabile Mahā-Kassapa offrì un
argomento di decisione al cospetto del Saṅgha.

[.voice]
`Terza Voce.` «Che il Saṅgha mi ascolti, amici. Ci sono alcune delle
nostre regole d’addestramento che coinvolgono i laici, mediante le quali
i laici conoscono quello che è permesso ai monaci che sono figli dei
Sakya e quello che non lo è. Se noi aboliamo queste regole più minute e
minori, ci sarà chi dirà: “Le regole d’addestramento proclamate dal
monaco Gotama ai suoi discepoli esistettero solo per il periodo che
terminò con la sua cremazione; loro osservarono le sue regole
d’addestramento finché egli fu presente ma, ora che egli ha ottenuto il
Nibbāna definitivo, loro hanno rinunciato a osservare le sue regole
d’addestramento”. Se il Saṅgha lo ritiene opportuno, non permettiamo che
quello che non è stato proclamato sia proclamato e non permettiamo che
quello che è stato proclamato sia abolito. Che il Saṅgha proceda in
accordo con le regole d’addestramento così come esse sono state
proclamate». Questo argomento di decisione fu offerto al cospetto del
Saṅgha e approvato.

Allora i bhikkhu anziani dissero al venerabile Ānanda: «Amico Ānanda,
questa fu una mancanza da parte tua: che tu non abbia chiesto al Beato
quali fossero le regole più minute e minori. Riconosci questa mancanza».

«Non fu deliberatamente, Signori, che non lo chiesi al Beato. Non la
considero una mancanza. Tuttavia, per fiducia nei venerabili, la
riconosco come mancanza».

«Anche questa fu una mancanza da parte tua: che tu abbia camminato sulla
veste per la pioggia del Beato mentre la stavi cucendo. Riconosci questa
mancanza».

«Non lo feci per mancanza di rispetto nei riguardi del Beato, Signori.
Non la considero una mancanza. Tuttavia, per fiducia nei venerabili, la
riconosco come mancanza».

«Anche questa fu una mancanza da parte tua: che tu abbia fatto salutare
i resti del Beato prima dalle donne. Riconosci questa mancanza. Loro
stavano piangendo, e i resti del Beato vennero macchiati dalle loro
lacrime. Riconosci questa mancanza».

«Sono stato costretto a comportarmi così, Signori, affinché l’ora non
divenisse inadatta per loro. Non la considero una mancanza. Tuttavia,
per fiducia nei venerabili, la riconosco come mancanza».

«Anche questa fu una mancanza da parte tua: che pure quando il Beato ti
ha offerto un’allusione così chiara, un’indicazione così evidente, tu
non hai implorato il Beato: “Signore, che il Beato viva per un’era, che
il Beato viva un’era per il benessere e la felicità di molti, per
compassione nei riguardi del mondo, per il bene, il benessere e la
felicità di divinità e uomini”. Riconosci questa mancanza».

«Fu perché la mia mente era sotto l’influsso di Māra, per questo non
l’ho chiesto al Beato. Non la considero una mancanza. Tuttavia, per
fiducia nei venerabili, la riconosco come mancanza».

«Anche questa fu una mancanza da parte tua: che tu ti sia interessato
acché le donne abbracciassero la vita religiosa nel Dhamma e nella
Disciplina proclamate dal Beato. Riconosci questa mancanza».

«L’ho fatto, Signori, pensando che Mahāpajāpatī Gotamī era la sorella
della madre del Beato, era stata la sua nutrice, la sua madre adottiva,
gli aveva dato il latte, aveva allattato il Beato quando sua madre morì.
Non la considero una mancanza. Tuttavia, per fiducia nei venerabili, la
riconosco come mancanza».

[.suttaref]
_Vin. Cv. 11:1-10_

In quel tempo il venerabile Purāṇa stava errando nelle Colline
Meridionali con una grande comunità di bhikkhu, con cinquecento bhikkhu.
Allora, dopo che il Dhamma e la Disciplina erano state ripetute dagli
Anziani, quando l’Anziano Purāṇa fu rimasto nelle Colline Meridionali
per tutto il tempo che volle, egli andò dagli anziani nel Boschetto di
Bambù a Rājagaha. Loro gli dissero: «Amico Purāṇa, il Dhamma e la
Disciplina sono stati ripetuti dagli Anziani. Tu appoggi questa
ripetizione?».

«Amici, il Dhamma e la Disciplina sono stati ben ripetuti dagli Anziani.
Io li ricorderò tuttavia come li ho uditi dalle labbra stesse del
Beato».

[.suttaref]
_Vin. Cv. 11:11_

[.narrator]
`Primo Narratore.` Ecco ora un ultimo episodio, che mostra il giovane
Saṅgha che continua a vivere dopo la scomparsa del fondatore, un
organismo affermato, che è sopravvissuto in modo ininterrotto e fiorente
per due millenni e mezzo, fino a oggi.

[.voice]
`Terza Voce.` Così ho udito. Una volta il venerabile Ānanda viveva a
Rājagaha, nel Boschetto di Bambù, nel Sacrario degli Scoiattoli, non
molto tempo dopo che il Beato aveva ottenuto il Nibbāna definitivo.

In quel momento, tuttavia, il re Ajātasattu Vedehiputta di Magadha stava
fortificando Rājagaha, perché era diffidente nei riguardi del re Pajjota
di Avanti.

Al mattino il venerabile Ānanda si vestì, prese la ciotola e la veste
superiore, e andò a Rājagaha per la questua. Allora pensò: «È ancora
troppo presto per errare per la questua a Rājagaha. E se io andassi dove
sono in corso i lavori del ministro della difesa Moggallāna il
brāhmaṇa?».

Così fece. Il brāhmaṇa lo vide arrivare. Allora egli disse: «Che il
Maestro Ānanda venga. Benvenuto al Maestro Ānanda. È da molto tempo che
il Maestro Ānanda non passa per questa strada. Che il Maestro Ānanda
sieda. C’è un posto preparato per lui».

Il venerabile Ānanda si mise a sedere nel posto preparatogli, mentre il
brāhmaṇa prese un seggio più basso e si mise a sedere da un lato. Egli
disse: «Maestro Ānanda, c’è un solo bhikkhu che possegga in tutti i modi
e in ogni modo le qualità che possedeva il Maestro Gotama?».

«Non c’è, brāhmaṇa. Perché il Beato fu colui che fece sorgere il
sentiero non sorto, colui che produsse il sentiero non prodotto, colui
che dichiarò il sentiero non dichiarato, il conoscitore del sentiero, il
veggente del sentiero, abile nel sentiero. Ora, però, quando i discepoli
dimorano in conformità con quel sentiero, lo padroneggiano, e fanno così
seguendo lui».

Nel frattempo il loro discorso non poté essere condotto a termine,
perché il brāhmaṇa Vassakāra, ministro di Magadha, che stava
ispezionando i lavori a Rājagaha, arrivò dove si trovava il venerabile
Ānanda e dove erano in corso i lavori del ministro della difesa
Moggallāna. Scambiò dei saluti e, quando questi formali doveri di
cortesia ebbero termine, si mise a sedere da un lato. Egli disse: «Per
quale discorso vi siete riuniti qui, ora? E nel frattempo quale discorso
non poté essere condotto a termine?».

Il venerabile Ānanda gli raccontò la conversazione che aveva appena
avuto luogo. Egli aggiunse: «Questo era il discorso che nel frattempo
non poté essere condotto a termine, perché tu sei arrivato».

«Maestro Ānanda, c’è un qualche bhikkhu nominato dal Maestro Gotama in
questo modo: “Costui sarà il vostro rifugio quando me ne sarò andato” e
al quale potete ora ricorrere?».

«Nessun bhikkhu fu nominato in questo modo dal Beato che conosce e vede,
realizzato e completamente illuminato».

«Allora, Maestro Ānanda, c’è un qualche bhikkhu che è stato scelto dal
Saṅgha, che è stato eletto dalla maggioranza dei bhikkhu anziani in
questo modo: “Costui sarà il nostro rifugio quando il Beato se ne sarà
andato” e al quale potete ora ricorrere?».

«Non c’è alcun bhikkhu di questo genere, brāhmaṇa. Noi abbiamo un
rifugio. Il Dhamma è il nostro rifugio».

«Maestro Ānanda, in che modo vanno comprese queste affermazioni?».

«Il Beato che conosce e vede, realizzato e completamente illuminato, ha
reso note le regole d’addestramento per i bhikkhu, e ha esposto il
_Pātimokkha_, il Codice delle Regole Monastiche. Tutti noi monaci che
viviamo nel distretto di un villaggio ci riuniamo nel giorno di
_Uposatha_ ogni luna piena e ogni luna nuova, e quando lo facciamo
scegliamo un monaco che abbia familiarità con il _Pātimokkha_. Se un
bhikkhu ha commesso un’infrazione, una trasgressione, dopo che questo
Codice delle Regole Monastiche è recitato, è in accordo con il Dhamma,
in accordo con il precetto, che è da lui agito [confessando la sua
trasgressione]: non sono certamente delle persone che ci fanno agire, ma
è il Dhamma che ci fa agire».

«C’è un qualche bhikkhu, Maestro Ānanda, che voi ora onorate,
rispettate, riverite e venerate, e dal quale dipendete, onorandolo e
rispettandolo?».

«C’è un bhikkhu di questo genere, brāhmaṇa».

«Maestro Ānanda, quando però ti è stato chiesto: “C’è un qualche bhikkhu
nominato dal Maestro Gotama in questo modo: ‘Costui sarà il vostro
rifugio quando me ne sarò andato’ e al quale potete ora ricorrere?” tu
hai risposto che non c’è. E quando ti è stato chiesto: “C’è un qualche
bhikkhu che è stato scelto dal Saṅgha, che è stato eletto dalla
maggioranza dei bhikkhu anziani in questo modo: ‘Costui sarà il nostro
rifugio quando il Beato se ne sarà andato’ e al quale potete ora
ricorrere?”, tu hai risposto che non c’è. E quando ti è stato chiesto:
“C’è un qualche bhikkhu, Maestro Ānanda, che voi ora onorate,
rispettate, riverite e venerate, e dal quale dipendete, onorandolo e
rispettandolo?” tu hai risposto che c’è. In che modo vanno comprese
queste affermazioni?».

«Brāhmaṇa, dieci cose che ispirano fede e fiducia sono state descritte
dal Beato che conosce e vede, realizzato e completamente illuminato. Noi
onoriamo, rispettiamo, riveriamo e veneriamo colui nel quale queste
dieci cose si evidenziano, e viviamo dipendendo da lui, onorandolo e
rispettandolo. Quali dieci?».

«Un bhikkhu è virtuoso, contenuto con il contenimento del _Pātimokkha_,
perfetto nella condotta e nel modo di vivere, egli teme il più piccolo
errore, si addestra portando a effetto i precetti dell’addestramento.
Egli ha imparato molto, e rammenta e ricorda quello che ha udito, gli
insegnamenti che sono salutari al principio, salutari nel mezzo e
salutari alla fine, con il significato e il senso letterale; egli spiega
la santa vita che è assolutamente perfetta e pura, gli insegnamenti che
lui ha ben imparato, li ricorda e consolida per mezzo della parola, li
esamina nella sua mente e li penetra a fondo mediante la retta visione.
Egli è contento delle sue vesti monastiche, del cibo ricevuto in
elemosina, del suo alloggio e delle medicine. Egli ottiene a suo
piacimento, senza problemi né riserve, i quattro jhāna che appartengono
alle menti più elevate e procurano un piacevole dimorare qui e ora. Egli
è dotato dei vari tipi di poteri sovrannaturali: essendo uno può
diventare molti, essendo molti può diventare uno; compare e scompare;
attraversa senza impedimenti muri, recinti, montagne, come se fossero
spazio; egli sprofonda e sorge dalla terra come se fosse acqua; seduto a
gambe incrociate viaggia nello spazio come un uccello; con la sua mano
tocca e accarezza la luna e il sole, così forte e potente; egli esercita
la padronanza del suo corpo fino al mondo di Brahmā. Con l’elemento
dell’orecchio divino, che è purificato e supera quello umano, egli sente
i quattro tipi di suoni, quelli divini e quelli umani, vicini e lontani.
Egli penetra con la sua mente nella mente degli altri esseri, delle
altre persone; egli comprende la [coscienza] affetta dalla brama come
affetta dalla brama … (si veda il cap. 12, p. 272) … e la [coscienza]
non liberata come non liberata. Egli ricorda la molteplicità delle sue
vite passate … (si veda il cap. 2, p. 27). Con l’occhio divino, che è
purificato e supera quello umano, egli vede gli esseri morire e
rinascere … (si veda il cap. 2, p. 28) … comprende come gli esseri
scompaiano in accordo con le loro azioni. Mediante la realizzazione di
se stesso con la conoscenza diretta, egli qui e ora entra e dimora nella
liberazione della mente e nella liberazione mediante comprensione
immacolata per l’esaurimento delle contaminazioni. Queste sono le dieci
cose».

Quando ciò fu detto, il brāhmaṇa Vassakāra si girò vero il generale
Upananda e gli chiese: «Che cosa pensi, generale? Se questo è il modo in
cui queste degne persone onorano chi dovrebbe essere onorato, non lo
fanno allora a ragione? Se non facessero così, chi in verità dovrebbero
onorare, rispettare, riverire e venerare, in dipendenza da chi
dovrebbero vivere, onorandolo e rispettandolo?».

Il brāhmaṇa Vassakāra chiese poi al venerabile Ānanda: «Dove vive ora il
Maestro Ānanda?».

«Ora vivo nel Boschetto di Bambù, brāhmaṇa».

«Spero, Maestro Ānanda, che il Boschetto di Bambù sia gradevole e
silenzioso, non disturbato da voci, un luogo con un’atmosfera di
separatezza, dove si può rimanere nascosti dalla gente e favorevole al
ritiro».

«In verità, brāhmaṇa, è grazie a guardiani che lo proteggono, come te,
che il Boschetto di Bambù ha tutte quelle qualità».

«In verità, Maestro Ānanda, è grazie alle brave persone che apprendono
la meditazione e la praticano, che il Boschetto di Bambù ha tutte quelle
qualità, perché queste brave persone apprendono la meditazione e la
praticano. Una volta il Maestro Gotama viveva a Vesālī, nel Salone con
il Tetto Aguzzo nella Grande Foresta. Allora mi recai là e mi avvicinai
a lui. E là il Maestro Gotama parlò della meditazione in molti modi. Il
Maestro Gotama era uno che praticava la meditazione ed era avvezzo alla
meditazione. Infatti, il Maestro Gotama raccomandava tutti i tipi di
meditazione».

«Il Beato non raccomandava tutti i tipi di meditazione, brāhmaṇa. E
nemmeno condannava tutti i tipi di meditazione. Il Beato quali tipi di
meditazione non raccomandava? Quando qualcuno dimora con il cuore
posseduto dalla brama, è una preda della brama e non comprende
rettamente l’abbandono della brama. Egli impiega ancora il desiderio per
tutto, e medita, medita troppo, non medita, e rimedita di nuovo. E allo
stesso modo è posseduto dalla malevolenza, dall’apatia e dalla
sonnolenza, dall’agitazione e dalla preoccupazione, o dal dubbio. Il
Beato non raccomandava questo tipo di meditazione».

«E quali tipi di meditazione raccomandava? Quando qualcuno, del tutto
discosto dai desideri sensoriali, discosto da stati [mentali] non
salutari, entra e dimora nel primo jhāna, che è accompagnato dal
pensiero e dall’esplorazione uniti alla felicità e al piacere nati
dall’isolamento. Ed egli entra e dimora nel secondo, nel terzo e nel
quarto jhāna. Il Beato raccomandava questo tipo di meditazione».

«Allora, Maestro Ānanda, sembra che il Maestro Gotama condannasse il
tipo di meditazione che meritava di essere condannato e raccomandava il
tipo di meditazione che meritava di essere raccomandato. E ora, Maestro
Ānanda, noi andiamo. Siamo impegnati e abbiamo molto da fare».

«È tempo ora, brāhmaṇa, di fare quel che ritieni opportuno».

Allora il brāhmaṇa Vassakāra, il ministro di Magadha, si alzò dal posto
in cui sedeva e, dopo aver approvato e manifestato accordo con le parole
del venerabile Ānanda, se ne andò per la sua strada. Subito dopo che se
ne fu andato, il ministro della difesa, il brāhmaṇa Moggallāna, disse:
«Il Maestro Ānanda non ha risposto alla nostra domanda».

«Non ti ho forse detto, brāhmaṇa, “Non c’è un solo bhikkhu che possegga
in tutti i modi e in ogni modo quelle qualità che il Beato, realizzato e
completamente illuminato, possedeva, perché il Beato fu colui che fece
sorgere il sentiero non sorto, colui che produsse il sentiero non
prodotto, colui che dichiarò il sentiero non dichiarato, il conoscitore
del sentiero, il veggente del sentiero, abile nel sentiero. Ora, però,
quando i discepoli dimorano in conformità con quel sentiero, sono
posseduti da esso, e fanno così seguendo lui”?».

[.suttaref]
_M. 108_

[.narrator]
`Secondo Narratore.` Nel frattempo il re Ajātasattu era intento alla
distruzione del suo troppo possente vicino, la confederazione Vajji con
capitale a Vesālī, a nord-est al di là del Gange. Al fine di aiutarlo a
raggiungere il suo scopo, Vassakāra finse di cospirare contro di lui, si
fece denunciare come traditore e fuggì alla volta di Vesālī per chiedere
asilo. I successivi tre anni li impiegò per disseminare con astuzia
sfiducia e sospetti reciproci tra i componenti della confederazione.
Quando giudicò che i tempi erano maturi, informò segretamente il re
Ajātasattu. I governanti di Vesālī erano allora troppo disuniti per
difendere il loro territorio, e Ajātasattu fu presto in grado di
riuscire con successo in una invasione e in un ampio massacro della
popolazione. Questa fu la fine dell’indipendenza dei Vajji. Il re
Viḍūḍabha di Kosala seguì velocemente l’esempio di suo cugino, invadendo
il territorio dei Sakya e dei Koliya posti sul suo confine
nord-orientale, trattando nello stesso modo le popolazioni che là
vivevano.

[.narrator]
`Primo Narratore.` Tutto questo chiude il primo scenario di storia
dell’India. Per il successivo secolo e mezzo, fino alla nascita
dell’Impero Maurya con la sua nuova dinastia, vengono solo menzionati i
nomi dei re di Magadha e il racconto del Secondo Concilio degli Arahant,
cento anni dopo il Parinibbāna. In quel tempo, però, il grande regno
settentrionale di Kosala era sparito (come, non lo sappiamo) e
Chandragupta (il “Sandrokottos” del viaggiatore greco Megastene), in
quanto erede dell’antico Magadha, detenne il comando di tutta la vallata
del Gange, la cui capitale era ora a Patna (Pāṭaliputta). +
   Un racconto del Secondo Concilio fu aggiunto al _Vinaya Piṭaka_ senza
dubbio al tempo dello stesso concilio. Il Canone fu nuovamente recitato,
e si può ipotizzare che in tale occasione pochi sutta riguardanti il
periodo successivo al Primo Concilio vennero incorporati nel _Sutta
Piṭaka_. In un terzo concilio, tenuto durante il regno dell’imperatore
Asoka (il nipote di Chandragupta), l’_Abhidhamma Piṭaka_ fu completato
aggiungendo un libro sulle eresie e, di fatto, il _Tipiṭaka_ venne
chiuso.

In questo tempo erano sorte diciotto differenti “scuole”. Il
_Theravāda_ (la Dottrina degli Anziani) divenne dominante sotto Asoka,
che abbracciò egli stesso il buddhismo. Suo figlio (o, secondo alcune
tradizioni, suo nipote), l’Arahant Mahinda, portò il _Tipiṭaka_ in pāli
con il suo Commentario a Ceylon,footnote:[L’attuale Sri Lanka (BB).]
mentre altri anziani
si recarono in altri territori. È questo _Tipiṭaka_ in pāli che è stato
conservato fino ad oggi a Ceylon, in Birmania, in Thailandia e in
Cambogia, dove ancora fiorisce il _Theravāda_. +
   Se si accolgono le osservazioni del viaggiatore cinese ITsing, che
arrivò in India (ma non a Ceylon) alla fine del VII secolo, il
_Theravāda_ prevaleva in tutti i territori meridionali dell’India,
mentre il _Sarvāstivāda_ (il cui Canone, in sanscrito, è ritenuto meno
antico di quello in pāli) a settentrione, benché altre scuole fossero
ampiamente diffuse in varie parti. Il Canone _Sarvāstivāda_ si diffuse a
nord e a nord-est, e il Canone in pāli a sud e a sud-est. Il _Mahāyāna_,
che I-Tsing (lui stesso era un Sarvāstivādin) pare suggerire avesse
messo radici al suo tempo in tutte o nella maggior parte delle scuole,
sembra sia sorto da una di esse, precisamente il _Mahāsanghika_. Benché
di tanto in tanto fiorente a Ceylon e in Birmania, in questi territori
esso non fu mai in grado di cancellare il suo più antico rivale. In
India, però, il buddhismo in tutte le sue forme si ritiene sia del tutto
scomparso nel XV secolo.
