[[bibliografia]]
= Bibliografia di Bhikkhu Ñāṇamoli

*Buddhist Publication Society*

_The Path of Purification (Visuddhimagga)_ di Bhadantācariya Buddhaghosa, trad. 1956, 5a ed. 1991.

_The Practice of Loving-kindness._ Texts compiled and translated from the Pāli, 1958 (Wheel, 7).

_Three Cardinal Discourses of the Buddha._ Trans. with introduction and notes, 1960 (Wheel. 17).

_Pathways of Buddhist Thought. Essays,_ 1963 (Wheel, 52-53).

_Mindfulness of Breathing (Ānāpānasati)._ Texts compiled and translated from the Pāli, 1964.

_A Thinker’s Notebook. Posthumous papers,_ 1972.

*Pāli Text Society*

_Minor Readings and The Illustrator._ Trad. del _Khuddakapāṭha_ e del _Commentario,_ 1960.

_The Guide._ Trad. del _Nettippakaraṇa,_ 1962.

_The Piṭaka Disclosure._ Trad. del _Peṭakopadesa,_ 1964.

_The Path of Discrimination._ Trad. del _Paṭisambhidāmagga,_ 1982.

_TheDispeller of Delusion._ Trad. del _Sammohavinodanī._ 2 vol., 1987, 1991.

*Wisdom Publications*

_The Middle Length Discourses of the Buddha._ Trad. del _Majjhima Nikāya._

*BPS Pariyatti Editions*

_The Path of Purification (Visuddhimagga)_ di Bhadantācariya Buddhaghosa. Trad. 1956. Prima ed. BPE: 1999.

