= Introduzione

Quanto poco alla fine del Settecento gli europei conoscessero il Buddha
e il suo insegnamento lo sottolineò il Gibbon in una nota al XIV
capitolo del suo _Decline and Fall_. Egli disse che «l’idolo
Fó»footnote:[Fó è il nome attribuito al Buddha in Cina]
è «il Fó dell’India, la cui venerazione è dominante
tra le sette dell’Hindustan, del Siam, del Tibet, della Cina e del
Giappone. Questo personaggio misterioso è, però, ancora avvolto in una
nebbia che i ricercatori della nostra Asiatic Society possono
gradualmente eliminare». Nei fatti, un gran numero di informazioni
affidabili era giunto in Europa dall’Oriente, ma esse non erano ancora
state pubblicate e restavano chiuse a chiave in forma manoscritta nelle
biblioteche. Ad esempio, il missionario gesuita Filippo Desideri portò
dal Tibet nel primo quarto del XVIII secolo un lungo e accurato
resoconto sia della vita del Buddha sia della sua dottrina: tutto ciò
rimase non pubblicato per duecento anni. Altrettanto avvenne per altri
resoconti

La “nebbia” del mistero fu dispersa dalle ricerche del XIX secolo, ma
solo per essere rimpiazzata da un pulviscolo di controversie suscitato
dalle dispute degli studiosi, nelle quali l’appena scoperta personalità
storica del Buddha parve nuovamente svanire. Non di meno, anch’esso si
disperse e, al volgere di quello stesso secolo, l’esistenza storica del
Buddha non fu più messa in dubbio, i documenti furono accertati e i
testi fissati. Tra questi documenti, il cui numero è enorme, il Canone
in lingua pāli, o _Tipiṭaka_, come esso è chiamato, era considerato sia
allora sia oggi il più antico: un po’ più antico della sua controparte
in sanscrito, benché alcuni studiosi di questa lingua ancora oppongano
resistenza a tale idea. A questo proposito, lo studioso della lingua
pāli T.W. Rhys Davids appena più di un secolo dopo Gibbon poté scrivere:
«Se si pensa che Gotama Buddha lasciò dietro di sé non un certo numero
di semplici detti dai quali i suoi seguaci in seguito costruirono un
sistema o dei sistemi, ma che fu lui stesso, quando iniziò la sua
missione, a elaborare accuratamente la sua dottrina, in parte in seguito
i dettagli, ma ancor prima i punti fondamentali. E che nel corso della
sua lunga carriera di insegnante, ebbe molto tempo per ripetere
continuamente i principi e i dettagli del sistema ai suoi discepoli e di
mettere alla prova la loro conoscenza di esso. E che, infine, i suoi
discepoli eminenti furono, come lui stesso, abituati alle più sottili
distinzioni metafisiche e addestrati in quella meravigliosa padronanza
della memoria che gli asceti dell’India di allora possedevano. Quando
questi dati di fatto vengono richiamati alla mente, si vedrà che a
ragione si può far più affidamento sugli aspetti dottrinali delle
Scritture buddhiste che non sulle altre e successive registrazioni delle
altre religioni».

La bibliografia europea sulla storia del buddhismo è ora molto ampia e,
allo stesso modo, lo è quella sulla sua letteratura e sulle sue
dottrine. L’accordo per gran parte raggiunto nell’ambito storico e
letterario, tuttavia, non si riflette su quello della dottrina. Ci sono
stati, e tuttora ci sono, numerosi e vari tentativi di dimostrare che il
buddhismo insegna il nichilismo e l’eternalismo, che è negativistico,
positivistico, ateistico, teistico, oppure che è privo di coerenza, che
è un Vedānta riformato, un umanesimo, un pessimismo, un assolutismo, un
pluralismo, un monismo, che è una filosofia, una religione, un sistema
etico, o tutto quel che vi pare opportuno. Non di meno, le parole dello
studioso russo Teodoro Stcherbatsky, scritte alla fine degli anni Venti
del XX secolo, valgono anche oggi: «Benché siano passati un centinaio
d’anni da quando gli studi scientifici sul buddhismo sono iniziati in
Europa, tuttavia brancoliamo ancora nel buio in relazione agli
insegnamenti fondamentali di questa religione e della sua filosofia.
Certo, non vi è nessun'altra religione che si sia dimostrata così
refrattaria ad essere formulata con chiarezza».

Tutti i libri che, nel Canone in lingua pāli, il _Tipiṭaka_, contengono
materiale storico e discorsi sono composti in forma antologica. Il Libro
della Disciplina, il _Vinaya Piṭaka_, consiste di raccolte di regole
monastiche con racconti di avvenimenti, talora molto lunghi, correlati
in un qualche modo al loro pronunciamento. I Discorsi nel _Sutta Piṭaka_
sono raggruppati insieme sotto numerosi e vari titoli, ma mai
organizzati storicamente. Alla storia per scopi storici non si era a
quel tempo molto interessati in India. Perciò, una narrazione
cronologica continua della vita del Buddha deve essere messa insieme da
materiale sparso ovunque nel _Vinaya Piṭaka_ e nel _Sutta Piṭaka_.
Questi libri contengono un quadro in sé completo e, nella sua
semplicità, fortemente contrastante con le adorne e floride versioni
successive, ad esempio con il _Lalitavistarā_, che ispirò Edwin Arnold
nella sua _Light of Asia_, o con la meno conosciuta introduzione alle
_Storie delle Nascite_ in lingua pāli nel Commentario ai _Jātaka_ di
Ācariya Buddhaghosa. Se confrontato con questi, il racconto offerto fino
al periodo dell’Illuminazione pare snello e lucido come una spada, come
la fiamma di una candela o una zanna d’avorio non intagliata.

Nel compilare questo racconto, è stato incluso tutto il materiale
canonico (ad eccezione del _Buddhavaṃsa_) riguardante il periodo che va
dall’Ultima Nascita fino al secondo anno successivo all’Illuminazione, e
quello relativo all’ultimo anno, un materiale che praticamente
rappresenta tutta la cronologia offerta dal Canone stesso. All’evidenza
cronologica offerta dal Canone è stato dato il primo posto. La
successiva più autorevole fonte in lingua pāli, ma quanto affidabile è
difficile dirlo, è rappresentata dai _Commentari_ di Ācariya Buddhaghosa
(V secolo d.C), che mettono in ordine molto del materiale canonico fino
al ventesimo anno successivo all’Illuminazione, aggiungendo dettagli,
come pure la storia di Devadatta. Essi aggiungono pure un certo numero
di avvenimenti non canonici, che non sono stati qui inclusi. Infine c’è
un lavoro birmano, il _Mālālankāravatthu_ (XV sec.?). È stato tradotto
in inglese dal vescovo Bigandet con il titolo _The Story of the Burmese
Buddha_ – che data qualche episodio canonico in più, ma non ha affatto,
probabilmente, autorevolezza storica ed è stato seguito solo in mancanza
di altre indicazioni. Queste sono le tre fonti utilizzate per la
sistemazione degli eventi contenuti nel _Tipiṭaka_. Altri eventi
canonici di particolare interesse, benché non databili, sono stati
comunque inclusi nel capitolo “Il periodo di mezzo”. Uno o due
avvenimenti, in particolare la morte del re Bimbisāra e quella del re
Pasenadi, che sono offerti solo nei Commentari, sono stati anch’essi
aggiunti siccome la loro fonte è chiaramente indicata e perché ben si
prestano a integrare alcuni scenari. Lo scopo principale della
compilazione è quello di includere tutti gli eventi importanti fino al
ventesimo anno successivo all’Illuminazione e l’ultimo anno. I capitoli
9° e 10° sono inevitabilmente episodici. Il capitolo 11° è dedicato a
descrivere la personalità del Buddha. La “personalità”, però, è un
argomento di centrale importanza nella dottrina buddhista e, così, il
capitolo 12°, “La dottrina”, è necessariamente coinvolto in tale
argomento. In questo stesso capitolo gli elementi principali della
dottrina sono stati grosso modo messi insieme seguendo l’ordine
suggerito dai Discorsi. Non è stata tentata alcuna interpretazione: si
veda però più avanti, il paragrafo sulla “traduzione”. Il materiale è
stato invece riunito in modo tale da aiutare il lettore a fornirne una
sua propria. Un’interpretazione stereotipata corre il rischio di
scivolare in una delle metafisiche errate visioni, che il Buddha stesso
ha descritto dettagliatamente. Se il capitolo 12° è piuttosto
difficoltoso, che le ultime parole di Anāthapiṇḍika, riportate nel
capitolo 6°, siano accolte a giustificazione per la sua inclusione, e
quanti non lo trovano di loro gusto non lo leggano, in parte o del
tutto.

La lingua pāli, la cui letteratura è molto ampia, è una lingua del tutto
riservata a un solo argomento, per la precisione all’insegnamento del
Buddha. Con questo giungiamo a una differenza rispetto al buddhismo
sanscrito o alla chiesa latina: si tratta di un fatto che gli conferisce
una particolare nettezza, senza riscontri in Europa. È una delle lingue
del gruppo indo-europeo ed è imparentata con il sanscrito, ma ha un
differente sapore. Lo stile dei sutta (Discorsi) è connotato da una
produttiva semplicità, che si accoppia a una ricchezza idiomatica che lo
rende un veicolo particolarmente raffinato al quale è difficile rendere
giustizia con una traduzione. Questo è il problema principale. Ce n’è
però un altro. La speciale caratteristica delle ripetizioni parola per
parola di passi, frasi e proposizioni che si presentano in
continuazione. Questa peculiarità è con ogni probabilità originariamente
dovuta al fatto che questi “libri” furono pensati per la recitazione. In
Europa siamo abituati a ripetizioni formali nella musica sinfonica
durante i concerti e magari alle ripetizioni in poesia, ma le troviamo
strane nella prosa. Al lettore non abituato a tali ripetizioni, nella
misura in cui esse compaiono nella lingua pāli, paiono sgradevoli su una
pagina a stampa. Perciò, esse sono state per la maggior parte eliminate
nella traduzione mediante vari stratagemmi, tuttavia sempre prestando
particolare attenzione alla conservazione dell’originaria architettura
della forma dei discorsi, che è una delle più rimarchevoli
caratteristiche espressive del Buddha. Nello stesso tempo, però, alcune
ripetizioni sono state conservate, in quanto valorizzano la preziosa
tecnica del “repetita iuvant”. Queste ripetizioni, se riscontrabili
parola per parola in lingua pāli, sono tradotte parola per parola anche
in inglese. Non è stato facile conciliare i due principali obiettivi di
questa traduzione, fedeltà letterale e corrispondenza idiomatica. Ogni
traduzione è una distorsione. Una gran cura è stata tuttavia riposta
nella coerente restituzione di termini tecnici – evitando “variazioni
eleganti” – e tali termini in lingua pāli potranno essere rinvenuti
nell’Indice, a fianco degli equivalenti in lingua
inglese.footnote:[Nell’Indice di questo volume, tali termini in lingua
pāli è possibile rinvenirli tra (), a fianco delle parole italiane.]
La scelta dei termini equivalenti in inglese
è stata effettuata con grande attenzione e assistita dall’intento di
consentire una coerente analisi delle forme inglesi per uno studio di
genere ontologico e della teoria percettiva e cognitiva insita – non a
caso, sembrerebbe – nei Discorsi.

Vi sono casi in cui la spiegazione dei Commentari in relazione al
significato delle parole è in conflitto con quella offerta dal
_Dictionary_ della Pāli Text Society. In tali casi la preferenza è stata
data ai Commentari. Dei casi più importanti si rende conto nelle
note.footnote:[Segue un paragrafo, qui omesso, relativo alla pronuncia
delle parole in lingua pāli per gli anglofoni. In relazione alla pronuncia
di tali parole per gli italiani, si veda la _Nota del traduttore_.]

Infine, qualche parola sulla forma di questa compilazione. La forma in
cui si presenta, non pensata per una divulgazione di massa, è stata
suggerita dal materiale che, come è stato detto, fu all’origine recitato
oralmente. Il Vinaya Piṭaka stesso suggerisce le “Voci” (si veda il cap.
16 e l’elenco delle voci precedenti il cap. 1) che “recitarono” il
Canone durante i Concili. I due “Narratori” sono, per così dire, due
compagni di uguale rango. In contrasto con quello che le “Voci” hanno da
dire, le parti spettanti ai “Narratori” sono per scelta caratterizzate
sia da uno stile piatto sia dalla massima brevità.

Bhikkhu Ñāṇamoli
