= L'autore

Osbert Moore, il nome con cui l’autore era conosciuto da laico, nacque
il 25 giugno 1905 in Inghilterra. Si diplomò all’Exeter College di Oxford
e durante la Seconda guerra mondiale fu ufficiale dell’esercito inglese
in Italia. Fu allora che, leggendo un libro italiano sul buddhismo,
sorse il suo interesse per quest’insegnamento. Tale testo – La dottrina
del Risveglio di J. Evola – fu in seguito tradotto da un suo amico e
compagno d’armi, Harold Musson, che, nel 1948, accompagnò Osbert Moore a
Ceylon. Entrambi ricevettero nel 1949 l’ordinazione monastica come
novizi buddhisti, nell’Island Hermitage, Dodanduwa, un monastero ubicato
su un’isola in una laguna. Nel 1950 ottennero la piena ordinazione
monastica come bhikkhu nel monastero Vajirarama di Colombo. A Osbert
Moore, il nostro autore, fu dato il nome di Ñāṇamoli e al suo amico
quello di Ñāṇavīra. Entrambi tornarono all’Island Hermitage, dove il
venerabile Ñāṇamoli trascorse quasi tutti i suoi undici anni di vita
monastica. Solo molto di rado lasciava la tranquillità dell’isola, e fu
in una di queste rare occasioni, in un giro a piedi con il monaco più
anziano dell’Island Hermitage, che egli morì all’improvviso l’8 marzo
del 1960 per un'insufficienza cardiaca. Non aveva ancora compiuto 55 anni. Il
suo trapasso avvenne in un piccolo villaggio, Veheragama, nei pressi di
Maho.

Oltre a questo volume, egli tradusse, dalla lingua pāli in un chiaro
inglese, alcuni dei più difficili testi del Buddhismo Theravādin.
L’elenco dei suoi lavori è riprodotto qui di seguito. Queste traduzioni
furono di rilievo da un punto di vista sia quantitativo sia qualitativo.
Le sue traduzioni mostrano un alto livello di competenza e di
attenzione, come pure una mente sottile e addestrata nella filosofia. Il
suo lavoro in questo campo ha rappresentato un durevole contributo agli
studi buddhisti.

