= Nota alla terza edizione

In questa terza edizione dell’ormai classica _Vita del Buddha_ del
venerabile Ñāṇamoli sono state corrette alcune minime incongruenze
presenti nella precedente edizione, nonché riviste alcune formulazioni
sintattiche. Per di più, vari termini dottrinali in lingua pāli che
l’autore aveva tradotto sono stati reintegrati nella stessa lingua pāli,
in quanto divenuti familiari ai lettori dei testi buddhisti ed entrati
nella terminologia corrente del Dhamma. Questi termini sono: “Buddha”,
per lo più tradotto dall’autore con “Illuminato”, una parola d’altro
canto mantenuta nel testo quando lo si è ritenuto opportuno; “Dhamma”,
da lui reso con “Legge”; “Saṅgha”, da lui indicato con “Comunità”;
“Nibbāna” spesso tradotto nell’edizione originale con “estinzione”.

Le note seguite da “Nyp.” tra parentesi tonde sono di Nyanaponika Thera,
quelle seguite da “BB” sono mie. Tutte le altre sono dell’autore.

In questa nuova edizione è presente __l'Elenco delle fonti__, che
consente agli studiosi dei sutta in lingua pāli di rintracciare
facilmente i testi. Il nucleo originario di questa sezione è stato
compilato da bhikkhu Ñāṇajivako, ma è stato implementato per renderlo il
più completo possibile.

Bhikkhu Bodhi
