[[editors-preface]]
= Prefazione dell’editore

Questo volume è stato pubblicato dalle carte postume del defunto
venerabile bhikkhu Ñāṇamoli, la cui biografia è collocata alla fine di
questo volume. La maggior parte del libro ha ricevuto la sua forma
finale dall’autore stesso e il dattiloscritto fu preparato da lui con
accuratezza e ordine. L’introduzione era però una bozza e le appendici
menzionate nel manoscritto non furono ritrovate tra le carte
dell’autore. Più della metà del testo di questo volume era stato
pubblicato in precedenza, a puntate, in una rivista buddhista
quindicinale, _Buddha Jayanti_ (Colombo, 1954-1956), benché con alcuni
passi differenti. Per questa versione, verso gli ultimi suoi anni,
l’autore rivide e aumentò considerevolmente la sua traduzione dei testi
canonici e integrò la struttura dell’opera, ingegnosamente ideata,
incorporando ampio materiale dalle fonti non canoniche. Tale struttura è
spiegata nella sezione che s’intitola “Voci”.

Egli inoltre offrì nuove interpretazioni di un certo numero di parole e
termini dottrinali. In relazione a cinque di essi, l’editore ha ritenuto
opportuno tornare alle interpretazioni precedenti, apparse nella sua
traduzione pubblicata in __Buddha Jayanthi__ nella sua traduzione del
_Visuddhimagga._ Rinvii ad alcune di queste poche alterazioni sono
contenuti nelle note dell’editore presenti a piè di pagina. Come
indicano alcune correzioni autografe presenti nel manoscritto, l’autore
ritenne che alcune di queste sue interpretazioni non potessero essere
coerentemente applicate a tutti i contesti, un fatto che ha contribuito
a far sì che l’editore abbia proceduto nel modo suddetto.

Nyanaponika Thera +
Forest Hermitage +
Kandy, Ceylon +
Settembre 1971
