= Voci

[.narrator]
`PRIMO NARRATORE.` È un commentatore del nostro tempo che offre cognizioni
introduttive, un osservatore imparziale con una generale conoscenza
degli eventi.

[.narrator]
`SECONDO NARRATORE.` È un commentatore che propone informazioni storiche e
culturali presenti solo nei Commentari in lingua pāli, soprattutto in
quelli di Buddhaghosa, che risalgono al V secolo d.C. Ha la funzione di
offrire il materiale strettamente indispensabile per una
contestualizzazione storica e, occasionalmente, sintetizza parti del
Canone stesso.

[.voice]
`PRIMA VOCE.` È la voce di Ānanda, discepolo e assistente personale del
Buddha, che recitò i Discorsi (o sutta) durante il Primo Concilio,
tenutosi a Rājagaha tre mesi dopo la morte e il _Parinibbāna_ del
Buddha.

[.voice]
`SECONDA VOCE.` È la voce di Upāli, discepolo del Buddha, che durante il
Primo Concilio recitò la Disciplina (o Vinaya).

[.voice]
`TERZA VOCE.` È un partecipante al Secondo Concilio, tenutosi cento anni
dopo il _Parinibbāna_ del Buddha, che nel XVI capitolo narra gli eventi
verificatisi prima e dopo il Primo Concilio.

[verse, role=cantor]
____
CANTORE

Questa voce recita alcuni versi +
in forma di brevi poemi o inni +
che nel Canone in lingua pāli +
non sono introdotti +
dalle tradizionali parole +
pronunciate da Ānanda, «Così ho udito», +
né sono presenti nella Disciplina.
____
